### ISSUE TITLE
Text-Informationen bei Kursempfehlungen löschen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1060]
### Hintergrund
Abhängig von der Konfiguration eines Kurses, wird für potentielle Kursteilnehmende eine Empfehlung der Abteilung, Region & des Kantons abgeholt. Wenn eine Person für einen Kurs empfohlen wird, können verschiedene Bewertungen mitgegeben werden. Typischerweise sind das persönliche Einschätzungen, die direkt und ehrlich (als Text) formuliert werden.
 
Diese Einschätzungen sind zwar ein wichtiger Teil des Kurswesens, allerdings werden sie nach dem Abschluss des Kurses nicht mehr verwendet. Weil es sich hierbei um sensible Daten zur Person handelt, wünschen wir uns, dass diese Informationen nur noch solange nötig im System gespeichert werden. Da es nach dem Kurs jeweils eine Rekursdauer von 3 Monaten gibt, wäre es am besten, nach Ablauf dieser Dauer die Daten zu löschen.
 
### Ist-Zustand
Schriftliche Kommentare zu den Empfehlungen bleiben uneingeschränkt im System gespeichert.
 
### Soll-Zustand
Schriftliche Kommentare zu den Empfehlungen werden 3 Monate nach Kursende gelöscht. Eine Archivierung ist nicht nötig, die Daten sollen ganz gelöscht werden.
 
### Abnahmekriterien
- 3 Monate nach Kursende werden alle Textangaben zu den Empfehlungen gelöscht:
  - Tätigkeit
  - Stufe
  - Bewertung
  - Stärken
  - Förderpunkte
  - Kommentar

### Tech-Spec

- Ziel: es sollen keine unnötigen Daten gespeichert
- die (strukturierten) Kommentare an den Empfehlungen sollen 3 Monaten nach Kursende gelöscht werden
- Umsetzung im Wagon
- Die Empfehlungen sind in `Event::Approval`/`event_approvals` hinterlegt

### ToDo

- [x] "ApprovalCleanerJob" anlegen, der täglich läuft
- [x] ApprovalCleanerJob sucht Approvals zu Kursen, die vor 3 Monaten beendet wurden
- [x] ApprovalCleaner löscht/leert die folgenden Spalten:
  - [x] current_occupation
  - [x] current_level
  - [x] occupation_assessment
  - [x] strong_points
  - [x] weak_points
  - [x] comment
- [x] Specs schreiben
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by daniel-illi** [comment]
Siehe auch Implementierung zum automatischen Löschen von Kursteilnahmen Bemerkungen:
https://github.com/hitobito/hitobito/pull/2284
