### ISSUE TITLE
Mailtrap Accounts zusammenführen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1078]
**Ausgangslage:**
Aktuell haben wir pro Instanz einen eigenen Mailtrap Account. Mit den jeweiligen Plans von Mailrtrap.io können wir 10 emails / 10 sec empfangen. Je nach Situation und für Fehleranalyse ist dies ein Problem

**Ziel:**
Wir haben ein Team-Plan. Dieser ermöglicht es 15 Inboxes zu haben. Empfang ist bei 25 emails / 10 sec. Pro Instanz kann eine Inbox angelegt und entsprechend Kunden eingeladen werden. Der Admin Account hat auf alle Mailbox zugriff.

**Tasks:**
- [x] Mailboxen anlegen im Team-Account anlegen. Naming analog der Integrationsumgebung.
- [x] Bestehender User auf der neuen Mailbox berechtigen
- [x] Integrationsumgebungen auf die neuen Mailboxen anpassen

Aufräumen
- [x] Cryptopus aktualisieren
- [x] Alte Mailboxen in den Accounts abräumen
- [x] Dokumentation im Wiki aktualisieren
- [x] Team informieren
   * Neue Admin Mailbox, bestehende Kundenaccounts bleiben bestehend, Pro Account
   * Port 2525

Für die Kunden ändert sich nichts, da die gleichen User für die Shared Inboxes verwendet werden können. Zusätzliche User können direkt via _Inbox Team Members_ eingeladen werden.

**Comment by olibrian** [comment]
Offene Tasks

- [ ] Integrations Build von Mulittenant schlägt zur Zeit fehl (Assemble failed) - daher keine Umstellung
- [ ] CVP Prod schickt noch an Mailtrap - alte Mailbox noch belassen
