### ISSUE TITLE
RECHNUNGEN: Zahlungen direkt von Finanzinstitut beziehen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1131]
**Ausgangslage:**
Aktuell können wir camt054 xml von einem Finanzinstitut (z.b. Postfinance) importieren. Anschliessend werden die entsprechende Rechnungen als bezahlt markiert.

**Ziel:**
Um diesen manuellen Schritt zu automatisieren werden camt054 Dateien via Schnittstelle von den Finanzinstituten bezogen.

Die Postfinance bietet verschiedene [Schnittstellen](https://www.postfinance.ch/de/unternehmen/beduerfnisse/unternehmen/filetransfer.html).

In einer ersten groben Sichtung würde sich der [EBICS](https://de.wikipedia.org/wiki/Electronic_Banking_Internet_Communication_Standard) Standard gut eignen, da dieser unabhängig von dem Finanzinstitut ist. Offizielle Seite EBICS: https://www.ebics.de

**Umsetzung**

Konfigurierbar auf den Rechnungseinstellungen (https://puzzle.hitobito.com/de/groups/1/invoice_config) pro Layer. Credentials mittels Encryptionservice verschlüsselt in der DB ablegen.

- Zahlungsprovider sind in Hitobito vorkonfiguriert (vorerst mal Postfinance)
- Die Schnittstelle wird täglich automatisch für alle Layer mit entsprechender Rechnungseinstellungen abgefragt
- Es ist nicht vorgesehen das die Abfrage manuell gestartet werden kann
- Beim Einrichten der Schnittstelle wird ein HTML File generiert das ausgedruckt und per Post an die Bank gesendet wird. Dieses Dokument soll gleich vom Webserver nach dem Einrichten im Browser angezeigt werden. [Beispielbrief](http://www.swiss-qr-invoice.org/downloads/EBICS-INI-Letter_Example_V0_1.pdf)
- Die Hashwerte der Postfinance sind hier beschrieben: https://www.postfinance.ch/content/dam/pfch/doc/prod/pay/FS_EBICS_Parameterblatt_Software_479.07_de.pdf
- Rechnung wird z.B. über Referenznr identifiziert und eine entsprechende Zahlung wird in Hitobito angelegt, aber nur wenn das Layer der Rechnung mit dem Layer der PaymentProviderConfig übereinstimmt
- Zahlungen die keiner Rechnung zugewiesen werden können, werden ignoriert
- Die Zahlung / Transaktions-ID soll der Zahlung in Hitobito zugewiesen werden. Es muss verhindert werden das die gleiche Zahlung mehrfach importiert wird
- Der Status der Rechnung einer zugehörigen Zahlung wird entsprechend aktualisiert
- Ist eine automatische Schnittstelle für einen Layer konfiguriert, ist der manuelle Import via camt054 deaktiviert

# Techspec

- [x] Gem für EBICS https://github.com/railslove/epics
- [x] Neues Model: PaymentProviderConfig, payment_provider, keys (mit Encryptionservice verschlüsseln), status: :new, :pending, :registered, last_sync_at
- [x] Error Handling der Kommunikation zur Bank
- [x] invoice_config: has_many :payment_provider_configs
- [x] In "Rechnungseinstellungen > Edit" neues Tab "Zahlungsschnittstellen"
- [x] Neuer Zahlungsprovider: Form für Registrierung, nach Absenden wird HTML zum Ausdruck angezeigt -> Button in InvoiceConfig#show
- [x] Zahlungsprovider edit: hier können die von der Bank zur Verfügung gestellten Keys gespeichert werden. ~Werte die nicht mehr geändert werden dürfen sind read-only~ Warnhinweis, nach erster Initialisierung
- [x] Neuer DelayedJob der täglich die konfigurierten Schnittstellen synced

Schätzung Aufwand: 8-10PT

**Comment by kronn** [comment]
Ich habe das Ticket aufgesplittet und daher die Aufwandsschätzung hier um die Schätzungen der Teiltickets reduziert. Es bleibt noch 1 Punkt übrig, was dann vllt die finale Verifikation sein könnte.

**Comment by olibrian** [comment]
Wurde umgesetzt. Welcome Back @psunix . Willst du die Umsetzung noch anschauen?

**Comment by mtnstar** [comment]
https://github.com/hitobito/hitobito/blob/master/app/domain/payment_provider.rb#L44
use update! ?

https://github.com/hitobito/hitobito/blob/master/app/domain/payment_provider.rb#L97
add comment? extract decoding to own method? split into multiple lines to make it more readable?

https://github.com/hitobito/hitobito/blob/master/app/jobs/payments/ebics_import_job.rb#L9
this runs the job on a random time daily. should this not be at a specific time during the night? not so sure if it's possible with our job setup.

https://github.com/hitobito/hitobito/blob/master/doc/features/ebics-connection.md
* instead of: invoice data, invoice payment data?

https://github.com/hitobito/hitobito/blob/master/config/settings.yml
is getting bigger and bigger ... maybe extract this to config/payment_providers.yml? include it from settings.yml or access it differently

**Comment by TheWalkingLeek** [comment]
Feedback eingebaut in https://github.com/hitobito/hitobito/commit/fe7f946faa8369526b31d852406a0e86aec588b8

**Comment by kronn** [comment]
Nach meiner Kenntnis kann man die allgemeinen Settings nicht weiter aufteilen. Man könnte überlegen, ob man mehr Daten aus den Settings in die DB verschiebt und dann als seeds lädt und verwaltet.
