### ISSUE TITLE
TECH: Von Travis auf GitHub Actions migrieren

### ISSUE THREAD

**Issue by BacLuc** [hitobito/hitobito#1190]
Follow up to #1088
To do / Tech spec:

- [x] create hitobito Github Action (done #1191)
- [x] create hitobito_youth Github Action (done hitobito/hitobito_youth#14)
- [x] create hitobito_pbs Github Action (done in hitobito/hitobito_pbs#190)
- [x] cache the dependencies in vendor/bundle (done in the above PRs)
- [x] create Github Action for other Wagons
- [x] delete travis.yml from the repos

Possible further improvements

- [ ] Set Github Action checks as required
- [ ] Gemfile.lock should match the Gemfile
- [ ] add dependency to rake to Gemfile
- [ ] Pin version of node and yarn
- [ ] Update batch in readme.md
