### ISSUE TITLE
SETUP: Basis-Setup

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1238]
Basis Setup 

Vorgehen gemäss Anleitung: https://wiki.puzzle.ch/Hitobito/ProjektSetup
TODO: Titel übernehmen
- [ ] Projekt Setup für Kunden Demo
- [ ] Resourcen bestellen bei /sys
- [ ] Hitobito Setup
- [ ] Openshift Setup
- [ ] Nach dem Setup
- [ ] DNS Einstellungen Kundenseite
- [ ] Wartung und Support
- [ ] Neuen Wagon erstellen
- [ ] Entsprechende Travis Build Jobs einrichten (.travis.yml im Wagon und auf travis integration auf github aktivieren) 

# Grundstruktur
- [ ] Verwendete Sprachen
  - [ ] Deutsch
  - [ ] Französisch
- [ ] Logo -> Siehe Nextcloud
- [ ] Design -> Hauptfarben Rot/Weiss (siehe Webseite http://www.svse.ch)

# Rollen, Berechtigungen
Dachverband
  - Geschäftsleitung (Alle Mitglieder der Geschäftsleitung haben dieselben Rechte)
      - Mitglied: [:group_and_below_full]
      - Kassier: 
  - Ressortmitarbeitende:
      - Mitglied: []
  - TK (Technische Komission) (1 Leiter Pro Sportart)
      - Mitglied: [:group_and_below_full]
  - Ehrenmitglieder (aktuell kein Login, in Zukunft gerne)
      - Mitglied: []
  - Externe Kontakte / Sponsoren
      - Kontakt: []
  - Sektion
      - Mutationsführer [:group_and_below_full]
      - Mitglied: []
      - NichtMitglied: []
      - ReadOnly: [:group_read]
      - Kassier: [:group_and_below_full]
         -> Sportart als Bezeichnung auf der Rolle abgebildet als Gruppe
      - NichtMitglied []
      - Eherenmitglied []
      - Sportart Gruppe:
          - Ombutsmann/Frau: [:group_full]
          - Mitglied: []
      - Externe Kontakte / Sponsoren
          - Kontakt: []

Aus der Doku: https://github.com/hitobito/hitobito/blob/master/doc/architecture/08_konzepte.md
`

> A Roletype can additional be of a specific kind self.kind = :external which is used in certain views to differentiate between different kinds of role. The core defines the following kinds: [:member, :passive, :external]. But this has no influence on permissions.

`

[Kickoff-Meeting](https://codimd.puzzle.ch/J96ECYnQRTuQyFLU_1c4Ng?edit)
