### ISSUE TITLE
PEOPLE: 2FA pro Rolle

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1300]
Eine Zweifaktor-Authentifizierung (2FA) soll für Benutzer mit erhöhten Zugriffsrechten erzwungen werden.

Bei der PBS soll für folgende Rollen 2FA obligatorisch sein:
 - Region: alle mit layer_and_below / layer_and_below_full
 - Kanton: alle mit layer_and_below / layer_and_below_full
 - Kanton: Verwantwortlicher_Krisenteam
 - Kanton: Mitglied_Krisenteam
 - Bund: alle mit layer_and_below / layer_and_below_full
 - Bund: Mitglied_Krisenteam

# Tech-Spec

* Anpassungen im pbs wagon
* 2FA ist im core aktiv (totp), konfiguration 2FA enforce auf Rollen

# Todo

- [ ] `app:hitobito:roles` so anpassen das bei der Ausgabe angezeigt wird bei welchen Rollen 2FA enforced ist (core)
- [x] `self.two_factor_authentication_enforced = true` setzen auf Rollen gemäss der Liste oben
- [ ] Neuer Output von `app:hitobito:roles` nach README.md im wagon kopieren
