### ISSUE TITLE
2.0 - MESSAGES

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1320]
Rund um Abos und Nachrichten gibt es immer mehr Features und es sollen einige Optimierungen in diesem Bereich vorgenommen werden:

# 1. Mail Client Web UI

- [x] Fertigstellen und Mergen von https://github.com/hitobito/hitobito/pull/1268
- [ ] Test auf Integration, Info an Admin Benutzer
- [ ] SPAM Mails werden künftig direkt von Admin Benutzer managed

# 2. Neuer Bulk Mail Stack
Der Empfang und Versand von Abo Mails soll robuster und weniger Wartungsintensiv werden:

- [x] Analyse von https://github.com/puzzle-bbt/bbt/issues/26
      - Übersicht verschaffen was alles bereits konzipiert und umgesetzt wurde
      - Issues nach hitobito projekt moven (epic 26 und dazugehörige issues)
- [x] Sammelticket Abschluss BulkMail Stack: https://github.com/hitobito/hitobito/issues/1621

*Der dev branch des Features ist `feature/bulk-mail`. Die weiteren branches der Subsysteme werden nach `feature/mail-retreiver/____` respektive nach `feature/dispatch/____` benannt.*

## Umsetzung des BulkMail Retrievers
- [x] https://github.com/hitobito/hitobito/issues/1480 (PR *MERGED*: https://github.com/hitobito/hitobito/pull/1492)
- [x] https://github.com/hitobito/hitobito/issues/1493 (PR *MERGED*: https://github.com/hitobito/hitobito/pull/1539)
~- [ ] https://github.com/hitobito/hitobito/issues/1526 (Neue Lösung mittels `Return-Path` sowie `Reply-To` Headers welche vom Dispatch gesetzt werden müssen.)~ Falls es mit dem setzen des Return-Path funktioniert, benötigen wir das Bounce Address Feature nicht mehr. Nach Implementation testen und ggf. Bounce Mail Handling später implementieren wenn das so nicht funktioniert.
- [x] https://github.com/hitobito/hitobito/issues/1481

## Umsetzung des BulkMail Dispatch
- [x]  https://github.com/hitobito/hitobito/issues/1546 (PR: https://github.com/hitobito/hitobito/pull/1555)
- [x] https://github.com/hitobito/hitobito/issues/1556 (**In progress** -> `feature/dispatch/delivery`)
- [x] https://github.com/hitobito/hitobito/issues/1557

**Comment by chrusu** [comment]
im august-sprint: tickets aus bbt-repo ins hitobito-repo verschieben

**Comment by chrusu** [comment]
@carlobeltrame @kronn @luca-bruegger @TheWalkingLeek Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito/1320?planning-poker)
