### ISSUE TITLE
INVOICES: Löschen von Sammelrechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1387]
Sammelrechnungen können zur Zeit nicht gelöscht werden. Bei einer fehlerhaften Erstellung einer Sammelrechnung muss diese direkt in der Datenbank gelöscht werden.
Ziel ist es via GUI die Sammelrechnungen zu löschen. Dabei werden auch sämtliche Rechnungen, welche zu der entsprechenden Sammelrechung gehört, gelöscht.

Sammelrechnungen können nur gelöscht werden, solange noch alle dazugehörigen Rechnungen den Status "Entwurf" haben. Sobald eine Rechnung verschickt, gemahnt, oder bezahlt wurde kann die Sammelrechnung nicht mehr gelöscht werden. in diesen Fällen müssen die Rechnungen einzeln gelöscht werden.

Vor dem Löschen soll eine Sicherheitsabfrage erscheinen welche der User bestätigen muss.

Berechtigung wie beim Anzeigen der Sammelrechnungen.

Umsetzung im Core prüfen.

# Mockup

Ergänzen der Ansicht Sammelrechnung `invoice_lists` durch Löschfunktion
![sammelrechnungen](https://user-images.githubusercontent.com/9592347/133037458-c2a21996-0e57-4d2a-9b06-595e8ace1ae4.png)

# Workflow

1. User klickt auf das Lösch-Icon einer Sammelrechnung
2. Es wird ein Modal-Fenster angezeigt mit den Detail-Infos zur gewählten Sammelrechnung. (Name, evtl. noch Anzahl Rechnungen). Dieses Modal-Fenster hat zwei Action Buttons: Löschen, Abbrechen
  - Falls die Rechnung nicht gelöscht werden kann da bereits Rechnungen mit Status höher Entwurf vorhanden sind, wird ein entsprechender Hinweis angezeigt und der Löschen-Button ist disabled
  - Neben dem Löschen-Button (Secondary) ist ebenfalls ein Abbrechen-Button/Link vorhanden (Primary)
 3. Mit klick auf einen aktiven Lösch-Button wird der Dialog geschlossen und die Sammelrechnung inkl. Rechnungen gelöscht und der User befindet sich wieder auf der Liste der Sammelrechnungen. Die gelöschte Sammelrechnung ist natürlich nicht mehr in der Liste vorhanden

# Tech-Spec

Umsetzung im Core

- https://github.com/hitobito/hitobito/blob/master/app/models/invoice_list.rb
- https://github.com/hitobito/hitobito/blob/master/app/views/invoice_lists/_list.html.haml
- https://github.com/hitobito/hitobito/blob/master/app/controllers/invoice_lists_controller.rb
- https://github.com/hitobito/hitobito/blob/master/app/abilities/invoice_ability.rb#L16C53-L16C53
  - Interessanterweise ist hier bereits eine Permission für Destroy vorhanden -> prüfen ob das so korrekt ist

Aus Performance-Gründen wird das Lösch-Icon auf der Liste immer angezeigt. Ob eine Sammelrechnung tatsächlich gelöscht werden kann wird vor dem Rendern des Löschdialogs geprüft und eine Meldung dort angezeigt falls der Eintrag nicht gelöscht werden kann.

Zusätzlich soll auch geprüft werden ob Sammelrechnung noch mit einem Rechnungsbrief verbunden ist. Falls ja sollte dies im Modal so erwähnt werden und dann mitgelöscht werden.

# ToDo

- [x] InvoiceList model validierungen um das Löschen zu verhindern falls Rechnungen mit anderem Status als Entwurf vorhanden sind
- [x] Dazugehörige Message korrekt mitlöschen (erst noch message_recipients)
- [x] In list view action button für Löschen (Ghüder/Güsel) hinzufügen und mit async #destroy verlinken
- [x] Neues Modal-Fenster bzw. Action erstellen mit Infos und Buttons
- [x] System Spec erstellen
