### ISSUE TITLE
GROUPS: Filter haben Probleme mit archivierten Rollen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1440]
## Aktuelles Verhalten

Seit #1275 können Gruppen archiviert werden. Wenn eine Gruppe archiviert wird, werden auch die zugehörigen Rollen archiviert.

In der Filter-Liste werden nun Treffer ganz ohne Rollen angezeigt.

## Gewünschtes Verhalten

Die Filter zeigen nur Personen mit aktiven Rollen, sofern nicht explizit nach gelöschten gesucht wird. Bei einem Filter nach gelöschten/beendeten Rollen können sowohl gelöschte wie auch archivierte Rollen einbezogen werden.

## Schritte zum reproduzieren

Folgender Filter ist auf cevi.puzzle.ch definiert:

```
#<PeopleFilter:0x00005601c3f18900
 id: 2,
 name: "Teamleiter",
 group_id: 76,
 group_type: nil,
 filter_chain:
  #<Person::Filter::Chain:0x00005601c4088f38
   @filters=
    [#<Person::Filter::Role:0x00005601c4088c90
      @args={"role_types"=>["Group::MitgliederorganisationGremium::Leitung"], "role_type_ids"=>[25]},
      @attr="role">]>,
 range: "deep",
 created_at: nil,
 updated_at: Tue, 28 Nov 2017 15:03:46 CET +01:00>
 ```

Die Gruppenhierarchie enthält auch zwei archivierte Gruppen mit Personen, die nur dort Rollen hatten. 

https://user-images.githubusercontent.com/1123483/138044274-7e1efdd1-7eab-4b3a-9b22-b879aa04c180.png

Die Personen sollten gar nicht mehr angezeigt werden wenn keine aktiven Rollen mehr vorhanden sind.

Link: https://cevi.puzzle.ch/groups/76/people?filter_id=2

# technical breadcrumbs

- https://cevi.puzzle.ch/groups/76/people?filter_id=2
- Der Filter wird in `app/domain/person/filter/role.rb` ausgewertet.
- Ein erster, inzwischen wieder veralteter Versuch ist im Branch [repair-group-archival](https://github.com/hitobito/hitobito/tree/repair-group-archival) (veraltet ist, dass Role.deleted_at inzwischen auch zukünftige Daten enthalten kann und die Rolle dann noch nicht als gelöscht gilt. Plus der Branch enthält erst einen Ansatz für den Fix bei Personenfiltern, Abos sind noch nicht angegangen, genausowenig wie der Fall wenn eine archivierte Gruppe angezeigt wird)

## TODO
- [x] Global im Core nach `GROUP_ARCHIVE_DISABLED` suchen, und die Deaktivierung von Gruppen-Archivierung rückgängig machen
- [ ] [Personenfilter]() anpassen
  - [x] In [Person::Filter::List#filter](https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/list.rb#L47) im Fall dass keine Filter-Parameter präsent sind (`chain.present? == false`) nicht nur nach `members` filtern, sondern nach Members in nicht archivierten Gruppen.
  - [x] Der Filter [`Person::Filter::Role`](https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/role.rb) soll eine neue Boolean Option `include_archived` erhalten
    - [x] Default: `false`.
    - [x] Wenn diese Option `false` ist, sollen Rollen in archivierten Gruppen als gelöscht zählen. Also überall wo anhand von `roles.deleted_at` ausgewertet wird ob eine Rolle noch aktiv ist, den Archivierungsstatus der Gruppe miteinbeziehen: Falls Gruppe archiviert, gilt auch die Rolle als "gelöscht".
    - [x] Wenn diese Option `true` ist, sollen Rollen in archivierten Gruppen als aktiv zählen (ausser natürlich sie haben ein Enddatum in der Vergangenheit). Also überall wo anhand von `roles.deleted_at` ausgewertet wird ob eine Rolle noch aktiv ist, den Archivierungsstatus der Gruppe miteinbeziehen: Falls Gruppe archiviert und Löschdatum leer oder in der Zukunft, gilt die Rolle als "aktiv".
    - [x] Diese neue Option soll als Checkbox im [Filter-UI](https://github.com/hitobito/hitobito/blob/master/app/views/people_filters/_role.html.haml) angeboten werden
  - [x] Beim Anzeigen von einer archivierten Gruppe soll statt der Filter-Ansicht "Mitglieder" ein Filter names "Archivierte Mitglieder" angezeigt werden, der `include_archived == true` gesetzt hat. So etwas ähnliches ist bereits bei der Mitte aktiv, aber nicht für archivierte Gruppen sondern für Layers: https://github.com/hitobito/hitobito_die_mitte/blob/master/app/helpers/die_mitte/filter_navigation/people.rb
- [x] Abos anpassen
  - [x] Archivierte Gruppen bei der Berechnung der [Abo Subscribers](https://github.com/hitobito/hitobito/blob/master/app/domain/mailing_lists/subscribers.rb#L87..L102) komplett ausschliessen (archivierte Rollen gelten in Abos als "gelöscht")
  - [x] Beim Auswählen von neuen Gruppen / Rollen in einem Abo archivierte Gruppen nicht mehr anbieten
  - [x] Auf archivierten Gruppen keine neuen Abos mehr erstellen können bzw. gleich das ganze Abos-Tab ausblenden
  - [x] Beim Archivieren von einer Gruppe die bestehenden Abos dieser Gruppe löschen
  - [x] Beim Archivieren von einer Gruppe die bestehenden Subscriptions (Gruppen/Rollen) dieser Gruppe in sämtlichen Abos löschen
- [ ] Specs schreiben und bestehende Specs anpassen
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Da mir nicht klar ist, was "Filter" alles enthält: Betroffen sind sowohl die Filter im Personen-Tab wie auch die Auswahl von Personen für Abos. An beiden Orten sollten archivierte Rollen gleich wie gelöschte behandelt werden.

(einzige Ausnahme: Wenn ich direkt eine archivierte Gruppe öffne, sollen einfach die archivierten Rollen angezeigt werden.)

### Story
Wir eröffnen am 1.1. eine Projektgruppe Ausbildung > Projekt mit [Alice, Bob, Celine] die während einem Jahr an einem Projekt arbeitet. Am 1.7. verlässt Bob die Gruppe (Rolle wird gelöscht) und am 1.8. David kommt hinzu. am 1.12 ist das Projekt abgeschlossen und die Gruppe wird archiviert.

##### Resultate:
Annahme: Niemand hat sonst eine Rolle in der Ausbildung
  * Filter nach Mitgliedern in Ausbildung (In der aktuellen Gruppe und allen darunter liegenden Gruppen) oder Abo an die Mitglieder der Untergruppen von Ausbildung: niemand der vier wird berücksichtigt
  * Filter nach Mitgliedern in Ausbildung (In der aktuellen Gruppe und allen darunter liegenden Gruppen) mit Zeitraum: archiviert wird wie gelöscht behandelt.
    *  1.1 - 31.7. war aktiv: [Alice, Bob, Celine]
    * 1.1. - 31.12. war aktiv: [Alice, Bob, Celine, David]
    * 1.1. - 31.7. wurde gelöscht: [Bob]
    * 1.8. - 31.12. wurde gelöscht: [Alice, Celine, David]
  * Beim direkten Öffnen der archivierten Gruppe im folge Jahr sehe ich [Alice, Celine, David] 
  * Filter auf Projekt funktionieren wie Filter auf Ausbildung 

(Beim öffnen einer Archiverten Gruppe sehe ich also den zustand im Moment des Archivierens. Falls Bob am 1.12 vor dem Archivieren gelöscht worden wäre, dürfte er aber auch erscheinen. d.h. das sollte sich damit lösen lassen, dass beim öffnen archivierter Gruppen standardmässig einfach ein Filter auf "gelöscht am archivierungdatum" gesetzt ist)

**Comment by carlobeltrame** [comment]
@nchiapol Mir ist noch nicht ganz klar wie das bei Abos im Detail funktionieren soll. Wenn ich ein bestehendes Abo habe in dem alle Mitglieder der Projektgruppe (und vielleicht noch weitere, nicht archivierte Gruppen) eingeschlossen sind, und dann die Projektgruppe archiviert wird, was soll dann passieren?

Sollen die archivierten Mitglieder weiterhin im Abo auftauchen? Sollen sie gar nicht mehr sichtbar sein? Brauchts eine Einstellung auf jedem Abo ob archivierte Gruppen miteinbezogen werden (so wie es bei den Personenfiltern schon nötig wird)? Braucht es eine solche Einstellung für jede Gruppe die im Abo miteinbezogen wird (sodass ich in demselben Abo sagen kann, "alle Mitglieder inklusive archivierte von Region A, aber nur nicht-archivierte Mitglieder von Region B)?

Dürfen archivierte Gruppen überhaupt bei neuen Abos hinzugefügt werden?

**Comment by nchiapol** [comment]
Vielen Dank für die Dokumentation der Anliegen und die Rückfrage betreffend Abos. 

Ich denke die für alle einfachste Lösung ist, wenn archivierte Gruppen in den Abos nicht berücksichtigt werden. 
Der Normalfall wird ein Abo mit allen aktiven Gremienmitarbeier sein. Wenn dort ein Gremium archiviert wird, sollten dessen Mitglieder nicht mehr auftauchen. (vgl. auch https://github.com/hitobito/hitobito/issues/1275#issuecomment-914652328)

Wenn wir beginnen archivierte Gremien zu berücksichtigen, öffnen wir  Pandoras-Box. Früher oder später hätten wir sicher wünsche nach einer Einstellung pro Gruppe die im Abo miteinbezogen ist. Zudem wäre unklar wieso Personen aus archivierten Gremien berücksichtigt werden, nicht aber Personen mit normal gelöschten Rollen...

Den einzigen Usecase, den ich für Abos mit archivierte Rollen sehe ist, den Kontakt zu Ehemaligen zu pflegen. Für einzelne Versande kann das auch manuell über den Filter im Personen-Tab (`include_archived == true` oder "Rolle war von ... bis ... aktiv") sowie den Export dort geschehen. Für regelmässige Versande sollten die Personen wohl eine aktive Rolle in einer "ehemaligen Gruppe" bekommen. So könnten sie sich dann auch wieder vom Versand ausschliessen lassen. (noch besser wäre natürlich eine echte Ehemaligen-Verwaltung gemäss https://github.com/hitobito/hitobito/issues/1299)

**Comment by nchiapol** [comment]
@ThomasEllenberger Nachdem #1932 nun gelöst ist, habe ich hier eben auch die Abos getestet. Dort erscheinen archivierte Rollen aber immer noch in den Exporten (und die entsprechenden Abos erscheinen auch noch auf dem Abo-Tab der archivierten Person) 

Fürs Nachstellen:
https://cevi.puzzle.ch/groups/137/people/1596 (archiviert in https://cevi.puzzle.ch/groups/137/)
https://cevi.puzzle.ch/groups/85/people/897 (archiviert in https://cevi.puzzle.ch/groups/80)

**Comment by carlobeltrame** [comment]
@nchiapol wir haben das heute gelöst. Könntest du ab morgen nochmals auf der Integrationsumgebug testen? Merci!

**Comment by ThomasEllenberger** [comment]
@nchiapol habe heute kurz versucht dies nachzustellen. Auf den archivierten Personen selbst sind die Abos noch ersichtlich, doch für mich kamen sie im Exportierten File vom Abo nicht mehr.
Kannst du das bestätigen?

**Comment by nchiapol** [comment]
@carlobeltrame Ich kann die Beobachtung von @ThomasEllenberger bestätigen. Der Export scheint soweit ok. Die Anzeige auf der archivierten Person ist noch falsch - das ist unschön aber aus meiner Sicht kein dringender Bug. (Also bitte entweder gleich auch noch fixen oder als neuen Bug erfassen ;-)

Ich habe folgendes getestet:
  * Export PDF-Liste
  * Export Etiketten
  * Export E-Mail-Adressen

Den Versand an die Abo-Mail-Adresse (testabo@cevi.puzzle.ch) wollte ich auch testen, in der Mailtrap sind dann aber nur 2 Mails angekommen. Ich nehme an, da hat irgend ein Tool bemerkt, dass das identische Mail N-mal an die gleiche Adresse gesendet worden wäre.
Ich gehe aber davon aus, dass das korrekt funktioniert, wenn der Export die Mail-Adressen korrekt anzeigt.

**Comment by carlobeltrame** [comment]
Merci euch fürs Testen. Ich habe das gleich noch kurz gefixt und lokal getestet. Ab morgen ists dann wieder auf Integration.

**Comment by nchiapol** [comment]
Habs eben auf der Integration angeschaut, die beiden Beispiele oben zeigen die Abos immer noch an. Gemäss Git log ist der Commit aber auch noch nicht in der History des aktuellen Commits unserer Integration.
