### ISSUE TITLE
Notizen sollen auch auf Gruppenebene möglich sein 8h

### ISSUE THREAD

**Issue by jharari** [hitobito/hitobito#147]
## Akzeptanzkriterien

* [x] Zu einer Gruppe können auf der Info-Seite auf der Linken Spalte unten Notizen angelegt werden (Analog zu Personen).
* [x] Die letzten Notizen werden auf der Info Seite angezeigt (analog zu Personen)
* [x] Ich kann Notizen wieder löschen
* [x] Auf Layer und Gruppen-Tab Notizen werden die Notizen gemeinsam mit den Personennotizen in einer Liste angezeigt. (angezeigt werden alle Notizen der Untergruppen einer Gruppe, aber nicht Unterebenen)
* [x] Ich bin nur berechtigt Notizen anzulegen, wenn ich diese Gruppe editieren kann.

## Todo

* [x] Darstellung von Gruppennotizen in Notizentab definieren. -> as discussed mit Gruppensymbol

https://redmine.puzzle.ch/issues/20634

**Comment by RolandStuder** [comment]
Noch unklar ob im Wagon oder Core. Abklären mit anderen Organisationen.

**Comment by RolandStuder** [comment]
Issues zu Sichtbarkeit von Notizen: https://github.com/hitobito/hitobito/issues/136

**Comment by codez** [comment]
Person::Note Model in Note Model mit polymorpher Beziehung refactorn.

**Comment by RolandStuder** [comment]
@jharari bitte Abnehmen, du kannst es ausprobieren auf: http://dsj.puzzle.ch

Wenn alles OK ist: Bemerkung "OK, abgenommen" hinterlegen.
Wenn nicht OK, Bemerkung "Nicht OK: " und was inkorrekt ist.

Als Erinnerung den Integrationsumgebungen werden keine echten Mails verschickt, diese werden an https://mailtrap.io verschickt und können dort überprüft werden.

**Comment by jharari** [comment]
Ok, abgenommen.
