### ISSUE TITLE
CHANGELOG: Links zu Issues einführen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1484]
Im aktuellen Changelog werden Issues referenziert. Aktuell ist dies nur ein Text. 

Ziel: Anstelle nur ein Text sollte ein Link hinterlegt werden können. Dies
ermöglicht es, auch weniger versierten User, das Changelog besser
nachvollziehen zu können.

# ToDo

- [x] `ChangelogReader` erweitern, um Formatierung der Einträge zu unterstützen
	- [x] ggf. `ChangelogEntry`-Klasse als Wrapper hinzufügen
- Formatierungen
	- [x] Hashtag+Nummer zu Link zum Issue umwandeln
	- [x] Repo+Hashtag+Nummmer zu Link in anderem Repo unwandeln
	- [x] AtZeichen+Name zu Link zu Github-User umwandeln
	- [x] URLs zu Link umwandeln
		- [ ] ggf. Link-Text kürzen
	- [x] Text in Backticks passend umwandeln (`<tt>` o. ä.)

**Comment by carlobeltrame** [comment]
Als Alternative zu bedenken, statt von Hand viele später unleserliche Regexes zu schreiben:
https://github.com/github/markup
Ein Gem das GitHub flavored Markdown liest und HTML ausspuckt.
