### ISSUE TITLE
EBICS: EBICS 3.0 unterstützten

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1516]
# Ausgangslage

Hitobito kann Zahlungsdaten von Banken abholen über eine Schnittstelle nach dem Standard EBICS 2.5.

Der Nachfolge-Standard EBICS 3.0 wird von den Schweizer Finanzinstituten seit November 2021 unterstützt und ist seit November 2022 Voraussetzung für die neuen ISO-20022-Meldungsversionen (v2019, SPS 2022). Diese sind nicht rückwärtskompatibel zu älteren EBICS-Versionen.

Die Schweizer Banken stellen EBICS 2.5 per **13.11.2026** ab. Dieses Datum kommunizieren u.a. Raiffeisen und PostFinance. Danach wird nur noch EBICS 3.0 unterstützt.

> [!WARNING]
> Die Deadline für die Migration auf EBICS 3.0 ist **13.11.2026**.

# Anforderungen

Hitobito muss für die Bankenanbindung den EBICS 3.0 Standard unterstützen. 

Während einer Übergangsfrist sollen die EBICS 3.0 Anbindungen parallel neben bereits konfigurierten EBICS 2.5 Anbindungen eingerichtet werden können.
Wenn eine aktivierte EBICS 3.0 Anbindung vorhanden ist, wird diese verwendet. Andernfalls wird eine allenfalls vorhandene aktiviere EBICS 2.5 Anbindung benutzt.

# Offene Fragen

* [ ] Das verwendete ruby gem [epics](https://github.com/railslove/epics) unterstützt EBICS 3.0 seit Version `3.0.0.rc1`. Dies ist ein Release Candidate, wann ein reguläres Release erscheinen wird ist nicht bekannt. Es ist auch möglich, dass es in der EBICS 3.0 Unterstützung noch bugs oder unvollständige Funktionen gibt. Wie gehen wir damit um?
* [ ] Signaturprüfung (HPB-Hash-Check) auf EBICS 3.0: hitobito hasht den RSA-Key (`public_digest`), PostFinance publiziert für "3.0 mit Zertifikaten" aber Cert-Fingerprints. Matchen die bestehenden `encryption_hash`/`authentication_hash` weiter (Cert wrappt denselben Key), oder braucht es einen Cert-Fingerprint-Check + neue Settings-Keys? → Auf PostFinance-Testplattform verifizieren.

# Tech-Spec

Implementierung im Core

Die EBICS 3.0 Anbindung soll parallel zu allenfalls konfigurierten EBICS 2.5 Anbindungen eingerichtet werden können.

Solange die EBICS 3.0 Anbindung durch die Bank noch nicht aktiviert ist, werden die Transaktionsdaten weiterhin über die EBICS 2.5 Anbindung abgeholt.
Nach der Aktivierung der EBICS 3.0 Anbindung wird die neue Schnittstelle verwendet.

### Änderungen von EBICS 2.5 (H004) zu 3.0 (H005)

Relevante Unterschiede für die hitobito-Integration:

* **OrderTypes → BTF-Services**: H004 identifiziert Geschäftsvorfälle via
  `OrderType` + `OrderAttribute` (z.B. `Z54`/`DZHNN`). H005 ersetzt dies durch ein
  `<Service>`-Element (`ServiceName`/`Scope`/`ServiceOption`/`MsgName`/`Container`);
  Downloads sind BTD-, Uploads BTU-Requests.
* **`Scope` obligatorisch**: CH-Banken lehnen Requests ohne `Scope: CH` ab
  (`091005 EBICS_INVALID_ORDER_IDENTIFIER`) — der Scope wählt die
  Markt-Variante des Services (CH/DE/BIL).
* **Signatur A005 → A006**: RSASSA-PSS statt RSA-PKCS1. Achtung: `Client.setup`
  des Gems defaulted auf A006 auch für H004 → für 2.5 explizit
  `signature_version: A005` setzen.
* **X.509-Zertifikate obligatorisch**: INI/HIA senden `ds:X509Data` statt
  `PubKeyValue`; `Client.setup` generiert auf H005 automatisch self-signed Certs.
  INI-Brief zeigt Cert-Fingerprints, HPB liefert Bank-Certs statt RSA-Keys.
* **Schlüssellänge ≥ 2048 Bit** (Gem-Default neu 4096).
* **`order_types`/`HAA`/`HTD`** liefern auf H005 Service-Hashes statt Strings.
* **XTC entfällt**: kein H005-Äquivalent, Uploads via BTU (`CCT`/pain.001).
* **Endpoints unverändert**: URL, `host_id`, `user_id`, `partner_id` sind bei den
  geprüften CH-Banken (LUKB, PostFinance, Raiffeisen) für beide Versionen
  identisch, ein Provider-Eintrag in `payment_providers.yml` genügt.
* **Namespace**: `urn:org:ebics:H005` statt `H004`.

→ das `epics` Gem kapselt die Unterschiede, für Hitobito ist die Umstellung mehrheitlich transparent bis 
auf den neu nötigen Parameter `scope` (für EBICS 3.0) und `signature_version` (für EBICS 2.5).

### Testing

Um die EBICS Anbindung zu testen kann die [Testplatform von postfinance](https://isotest.postfinance.ch/) verwendet werden.
Die credentials fürs Login sind im Bitwarden abgelegt.

>[!WARNING]
> Unter [Produktnutzung](https://isotest.postfinance.ch/corporates/user/productVersion) muss Produktangebot 2 angewählt sein  
> (Produktangebot 1 bietet die "neuen" Payload-Formate nicht, welche für EBICS 3.0 verwendet werden)

In den development env settings ist dazu der payment provider `postfinance-test` hinterlegt. Falls die Authentifizierung 
fehlschlägt, muss auf https://isotest.postfinance.ch/corporates/user/settings/ebics geprüft werden, ob die Verschlüsselungs- 
und Authentifizierungshashes noch korrekt sind in den settings.

Auf https://isotest.postfinance.ch/corporates/user/files können Zahlungsdateien hochgeladen werden, welche dann über
die EBICS Schnittstelle der Testplatform abgerufen werden.

### 1. Gem `epics` aktualisieren

auf eine Version mit EBICS 3.0 Unterstützung (`>= 3.0.0.rc1`) heben.

### 2. Feature Gate

Neues feature gate `invoice_config.legacy_ebics_25.enabled: true` in `settings.yml` 

### 3. `PaymentProviderConfig` erweitern

Flag `legacy_25_ebics` (boolean, default `true`) markiert bestehende 2.5-Konfigurationen; neue Konfigurationen mit `legacy_25_ebics = false` sind EBICS 3.0.

* Migration schreiben um Flag in Tabelle `payment_provider_configs` hinzuzufügen sowie einen unique index auf `(invoice_config_id, payment_provider, legacy_25_ebics)`
* `PaymentProviderConfig#ebics_version` Helper Methode implementieren:  
  ```ruby
  def ebics_version = legacy_25_ebics ? Epics::Keyring::VERSION_25 : Epics::Keyring::VERSION_30
  ```
* `#clear_scheduled_ebics_import_jobs` entfernen, der Job wird neu die Config zur Laufzeit laden und damit umgehen wissen wenn es keine Config mehr gibt.
* `list` scope implementieren der die configs nach `provider` und `legacy_25_ebics` sortiert zurückgibt.

### 4. `InvoiceConfigsController` anpassen

* `legacy_25_ebics` in `permitted_attrs` aufnehmen
* `#missing_payment_providers` und `#build_payment_provider_configs` erweitern:
  * wenn das feature gate aktiviert ist, Provider zwei Konfigurationen bauen (für `legacy_25_ebics` flag `true` und `false`).
  * wenn das feature gate deaktiviert ist, Provider nur eine Konfiguration bauen (mit `legacy_25_ebics = false`).
  
### 5. View partials anpassen

* `app/views/invoice_configs/_form.html.haml`: auf `payment_provider_configs` den `list` scope aufrufen
* `invoice_configs/_provider_fields` form erweitern:
  * Im Titel EBICS Version anzeigen
  * Verstecktes Feld für `legacy_25_ebics` flag
  * fields für `legacy_25_ebics = true` nur anzeigen wenn das feature gate aktiviert ist
* `app/views/invoice_configs/_attrs.html.haml`: auf `payment_provider_configs` den `list` scope verwenden

### 6. `Payments::EbicsImportJob` und `Payments::EbicsImport` anpassen

* für `parameters` neu `invoice_config_id` und `payment_provider` verwenden, `#initialize` entsprechend anpassen
* configs abrufen, abhängig vom feature gate nur 3.0 oder auch 2.5 
* payments importieren: Import versucht zuerst die 3.0 Anbindung. Nur wenn die Bank den Zugang noch nicht aktiviert hat, wird automatisch auf die 2.5 Anbindung zurückgefallen, andere Fehler werden wie bisher gemeldet.

### 7. `Payments::EbicsImportScheduleJob` anpassen

ein Job pro `(invoice_config_id, payment_provider)`-Paar schedulen

### 8. `PaymentProvider` anpassen

* `#initial_setup` sowie `#client`: beim Aufruf von `Epics::Client.setup` resp. `#new` version als param übergeben: `version: config.ebics_version` 
* `#initial_setup`: falls `config.legacy_25_ebics` → als param übergeben: `signature_version: Epics::Signature::A_VERSION_5`
* `#ebics_scope` Hilfsmethode: `payment_provider_setting.scope.presence || "CH"`
* `#Z54` (Download camt.054):   
  Nach Version dispatchen:

  * **2.5**: unverändert `client.send(:download_and_unzip, PaymentProviders::Z54, from, to)`.
    Die eigene Klasse `PaymentProviders::Z54` baut den Request von Hand:
    `OrderType "Z54"`, `OrderAttribute "DZHNN"`, `StandardOrderParams/DateRange`.
    Bleibt bis zum 2.5-Removal bestehen. 
  * **3.0**: `client.Z54(from, to, scope: ebics_scope)`.
    H005 kennt keine OrderTypes mehr, Downloads sind BTD-Requests mit einem
    `<Service>`-Element (`ServiceName`/`Scope`/`ServiceOption`/`MsgName`/`Container`).
    Das Gem liefert via `create_z54` die Defaults `service_name: 'EOP'`,
    `msg_name: 'camt.054'`, `service_option: 'XQRR'`, `container_type: 'ZIP'`;
    einzig `scope` muss übergeben werden (`ebics_scope`, Default `'CH'`,
    per `payment_providers.yml` übersteuerbar).
  * Rückgabe identisch: `download_and_unzip` liefert ein Array von XML-Strings,
    das `xml_from_order_data`-Cleanup bleibt unverändert. Fehlerbehandlung
    (`090005` = keine Daten) bleibt in `Payments::EbicsImport`.

### 9. Ticket erstellen für Rückbau von EBICS 2.5 Support

Folgeticket für das nächste Release erstellen. Beim Rückbau muss entfernt werden:

* **Feature-Gate**: `invoice_config.legacy_ebics_25` aus `settings.yml` sowie alle
  `FeatureGate.enabled?('invoice_config.legacy_ebics_25')`-Checks
  (View `_provider_fields`, `EbicsImportJob`, `InvoiceConfigsController`)
* **Datenbank**: Spalte `legacy_25_ebics` per Migration droppen; Unique-Index
  zurück auf `(invoice_config_id, payment_provider)`; bestehende
  `legacy_25_ebics: true` Records per Daten-Migration löschen
* **`PaymentProviderConfig`**: `#ebics_version` Helper entfernen
  (`Epics::Keyring::VERSION_30` direkt verwenden); `list`-Scope ggf. auf
  Provider-Sortierung vereinfachen
* **`PaymentProvider`**: `#Z54`-Dispatch entfernen → nur noch
  `client.Z54(from, to, scope: ebics_scope)`; `signature_version: A_VERSION_5`
  aus `#initial_setup` entfernen; `#XTC` + `PaymentProviders::Xtc` löschen
  (falls nicht schon jetzt geschehen)
* **`PaymentProviders::Z54`**: eigene Request-Klasse löschen
* **`InvoiceConfigsController`**: `missing_payment_providers` /
  `build_payment_provider_configs` zurück auf eine Config pro Provider
* **View**: 2.5-Fieldsets und Gate-Check aus `_provider_fields` entfernen
* **`Payments::EbicsImportJob`**: 2.5-Fallback entfernen — nur noch die
  3.0-Config auflösen (inkl. pending → HPB-Check)
* **Locales**: 2.5-spezifische de-Texte entfernen (Versions-Labels, Fieldset-Titel)
* **Specs/Fixtures**: alle 2.5-Fälle und Gate-off-Szenarien entfernen

# ToDo

- [ ] Gem aktualisieren
- [ ] Model anpassen, Migration schreiben
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] `EbicsImportJob`, `EbicsImportScheduleJob` anpassen
- [ ] `Payments::EbicsImport` anpassen
- [ ] `PaymentProvider` anpassen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] bei Core-Änderungen alle Wagons durchtesten
- [ ] [DoD](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) geprüft und erfüllt?
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
- [ ] bei Core-Features: https://hitobito.readthedocs.io anpassen
- [ ] Folgeticket für EBICS 2.5 Rückbau erstellen

**Comment by ODI-Navil** [comment]
Schweizer Stichtag: Am 13. / 14. November 2026 stellen SIX Interbank Clearing und die Schweizer Finanzinstitute (PostFinance, UBS, Kantonalbanken etc.) den Support für EBICS 2.5 (H004) für den aktiven Zahlungsverkehr ein.

**Comment by daniel-illi** [comment]
## BTF-Mapping Z54 → EBICS 3.0 (SIX-Standard, verifiziert)

Quelle: [SIX Mapping EBICS 2.x CH → 3.x BTF (Q4/2022)](https://www.six-group.com/dam/download/banking-services/interbank-clearing/en/standardization/ebics/mapping-table.pdf) — nationaler Standard, den alle CH-Banken implementieren.

* **Z54** camt.054 → `REP` / `CH` / keine Option / `BTD` / `ZIP` («Additional Aggregate Booking Information Report»)
* **ZQR** camt.054 → `EOP` / `CH` / `XQRR` — nur QRR-Transaktionen; **das entspricht dem Gem-Default von `create_z54`** (`EOP`/`XQRR`) — das Gem mappt faktisch ZQR, nicht Z54
* **ZS2** camt.054 → `REP` / `CH` / `XDCI` (Gut-/Lastschriftsanzeigen)

Banken-Evidenz (alle identisch zum SIX-Standard):

| Bank | Z54 → 3.0 | Quelle |
|---|---|---|
| PostFinance | `REP`/`CH`/—/`camt.054`/`ZIP`, MsgVersion 04/08 | [Testplattform-Doku](https://isotest.postfinance.ch/) |
| UBS | `REP`/`CH`/—/`camt.054`/`ZIP` V04 | [ubs.com EBICS-3.0-Seite](https://www.ubs.com/ch/en/services/payments/connection-ubs/ebics.html) |
| ZugerKB (Swisscom-Plattform) | `REP`/`CH`/`ZIP`/`camt.054` 04/08 | [Parameterdatenblatt (PDF)](https://www.zugerkb.ch/docs/default-source/firmen/ebics-verbindungsparameter.pdf?sfvrsn=f396e68c_8) |
| BEKB | `REP`/`CH`/`ZIP`/`camt.054` 04/08 («Reporting QRR/LSV») | [Informationsblatt EBICS 3.0 (PDF)](https://www.bekb.ch/-/media/bekb/portal/documents/firmenkunden/ebics/informationsblatt-ebics-3-0.pdf) |
| LUKB | verweist auf BPD-Blatt, folgt CH-Standard | [Umstellungsseite](https://www.lukb.ch/unternehmen/zahlen/zahlungsverkehr/ebics/umstellung) |

Swisscom-gehostete Banken (tkb, valiant, zugerkb, ukb, bcn, bcvs) teilen dieselbe Plattform → gleiches Mapping (ZugerKB bestätigt). Abweichungen existieren nur länderübergreifend (DE: `STM`/`DE`, AT: `STM`/`AT`) — für die CH-Providerliste irrelevant.

→ **`client.C54(scope: 'CH', msg_name_version: '08')` ist für alle gelisteten CH-Banken korrekt.**
