### ISSUE TITLE
INVOICES: Konzeption - Rechnung an Gruppe stellen

### ISSUE THREAD

**Issue by betsim** [hitobito/hitobito#1518]
Bisher ist es nur möglich, Rechnungen an Personen zu stellen. Zusätzlich soll es möglich sein, auch einer Gruppe eine Rechnung zu stellen. Szenario: Mitgliederbeitrags-Rechnung vom Kantonalverband an seine Vereine aufgrund der in hitobito eingetragenen Mitglieder.

- [ ] Die Rechnungsstellung soll wie bis anhin erfolgen durch Auswahl eines Rechnungsartikels. Beim Erstellen des entsprechenden Rechnungsartikels soll zusätzlich eine Checkbox "Abhängig gem. Anzahl Aktivmitglieder" (über genaue Bezeichnung kann man sich noch streiten) verfügbar sein. Wenn diese Option aktiv ist, soll beim Hinzufügen dieses Rechnungsartikels anstatt des Feldes "Anzahl" ein nicht editierbares Feld mit der Anzahl der Aktivmitglieder erscheinen.
- [ ] Dieser Rechnungsartikel steht nur beim Erstellen von Rechnungen an Gruppen im Dropdownmenü zur Verfügung (nicht bei Rechnungen an Personen)
- [ ] Noch zu diskutieren: Wie erstellt man eine Rechnung für alle seine Gruppen? Bei den Personen können alle gewünschten Personen in den Personenlisten selektiert werden. Eine solche selektierbare Liste fehlt für die Gruppen. Einfachste Lösung: im Info-Tab einen neuen Button "+Vereinsrechnung" (hinter Export UV Lohnsumme) hinzufügen; dann geht die Rechnung an alle Vereine.

# ToDo
- [ ] Issue für Umsetzung erstellen
- [ ] Workflow Rechnung an Gruppe beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by severinraez** [comment]
Erste Gedanken zu Lösungsoptionen, nächster Schritt intern diskutieren und "ToDo" angehen:

# Versand

Option 1:

* Rolle "Rechnungskontakt" hinzufügen
* Gruppe mit allen Rechnungskontakten machen (RK)
* Rechnungen an Rechnungskontakte versenden
* ! Wie verhindern, dass Gruppen ohne Rechnungskontakte keine Rechnung kriegen, weil keine Rechnungskontakte in RK sind?

Option 2 (Favorit):

* Rolle "Rechnungskontakt" hinzufügen
* a) Button auf Gruppe im Info-Tab: "Rechnung an Rechnungskontakte erstellen"
* b) Button, welcher einen Job zum Versand an alle relevanten Gruppen triggert
* Abbrechen oder warnen, wenn Gruppen ohne Rechnungskontakte abgerechnet werden sollen

# Rechnungserstellung

* Rechnungsartikel, welcher seine Anzahl gemäss der Gruppenmitglieder gesetzt bekommt, erstellen
  * Ist nur verfügbar, wenn eine Gruppenrechnung erstellt wird
  * ? Gibt es Fälle, in denen nicht alle Mitglieder der Gruppe gezählt weden sollen? Wenn ja:
    * Option a: Anzahl manuell editierbar machen
    * Option b: Einen Filder der für die Berechnung relevanten Personen angeben

**Comment by carlobeltrame** [comment]
Wir haben dafür das Umsetzungs-Ticket #1610 erstellt, welches aber noch blockiert ist durch eine ausstehende technische Konzeption von Rechnungsartikeln die ihren Betrag dynamisch berechnen (das ist die Gemeinsamkeit von diesem Ticket, #1605 und dem variablen Spendenaufruf der Mitte).
Bevor solche Rechnungsartikel mit dynamischem Preis verfügbar sind kann dieses Ticket denke ich nicht sinnvoll umgesetzt werden.

Ich schliesse dieses Ticket hier aus internen technischen Gründen, damit wir unseren Sprint abschliessen können.
