### ISSUE TITLE
TECH: Wechsel auf S3

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1568]
Im Rahmen zum Wechsel auf OpenShift 4 muss auf S3 gewechselt werden.

In dem Rahmen sollen folgende Fragen geklärt werden:

    * Kosten S3-Versionierung (versionierung aller files und db-files während 90 Tagen)?
    * Müssen wir?
    * Wollen wir?
    * Tasks Engineering
    * Tasks Migration

Siehe doc/architecture/09_entwurfsentscheidungen.md

- Die Kosten sind geringer und vor allem dem tatsächlichen Verbrauch angepasst.
- Aktuell scheint es zwingend notwendig, auf S3 oder vergleichbare Technologien zu wechseln
- Andere Projekte haben damit Erfolg oder erfolgversprechende Ansätze -> ja, wir wollen

# Hinweise

Die Migration führt zu einer kurzen Zeit von broken links. Die konkrete Dauer
muss vorher getestet werden.

Wenn man mehrere ActiveStorage-Stores definiert, kann man den Wechsel per ENV
steuern. Solange der Wechsel nicht komplett abgeschlossen ist, muss man das gem
"nochmal" im Gemfile behalten und auch produktiv deployen.

# ToDos

- [x] Uploads vom `nochmal`-gem lesbar machen
	- nochmal erweitern, um Uploads von Carrierwave zu lesen
	- jeder Carrierwave-Uploader hat `store_dir`, in welchem sich die Dateien befinden
- [ ] zwei ActiveStorage-Backends hinterlegen, die via ENV-Variable gewählt werden
- [x] nochmal dem Projekt hinzufügen
- [ ] Migrationsanweisung in RELEASENOTES hinterlegen
- [ ] ENV-Var umstellen
- [ ] Datenmigration mit `nochmal` durchführen
- [ ] CHANGELOG-Eintrag
