### ISSUE TITLE
TECH: Openshift 4 Migration Konzipieren

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1569]
Im Rahmen des Wechsels auf OpenShift 4 stellt sich die Frage, ob wir in dem Zuge gleich noch weitere Architekturthemen angehen wollen.

    * DB-Technik?
    * MySQL+Sphinx vs Postgresql
        * Tasks Engineering / Tasks Migration
    * DB-Location (DB as a Service?)
    * Backupstrategie
    * S3

Wären ADRs eine passende Form um Architekturentscheide zu dokumentieren, wer will, kanns ja gleich mal ausprobieren: 
https://martinfowler.com/articles/scaling-architecture-conversationally.html#1.AThinkingAndRecordingToolDecisionRecords

# ToDo

- [x] Offene Punkte klären, festlegen und eine grobe Planung erstellen
- [x] Erkentnisse in https://github.com/hitobito/hitobito/issues/1537 ablegen
- [x] Termine und Deadlines abklären
