### ISSUE TITLE
PERSON: Mitgliederausweis & Paddlepass verlinken.

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1576]
![image](https://user-images.githubusercontent.com/17568539/148069049-99966738-f7ab-476b-9081-5bda089ab804.png)

# Tech-Spec
- https://github.com/hitobito/hitobito/tree/master/app/views/people

# ToDo
- [ ] Neue Sektion Dokumente erstellen in SKV Wagon
- [ ] Link aus Export Dropdown entfernen
- [ ] Link für Download Mitgliederausweis #xx
- [ ] Link für Download Paddle Ausweis #xx

**Comment by chrusu** [comment]
@chrusu Mockup anpassen

**Comment by chrusu** [comment]
Issue moved to [hitobito/hitobito_skv #26](https://github.com/hitobito/hitobito_skv/issues/26) via [**ZenHub**](https://www.zenhub.com/)
