### ISSUE TITLE
TECH/SECURITY: CookieSerializer auf :json umstellen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1588]
Sobald alle Umgebungen mit dem Commit https://github.com/hitobito/hitobito/commit/97009531bc154fb899b72b27517ca670a7d112aa produktiv für mindestens 2 Wochen gelaufen sind, sollten wir den CookieSerializer auf den sichereren Wert `:json` umstellen.

# Tech-Spec

Brakeman reklamiert weil `:hybrid` theoretisch unsafe ist. Jedoch braucht es eine Übergangsphase bis alle remember-me-Cookies abgelaufen sind, in der noch `:hybrid` eingesetzt werden muss. Die remember-me-Cookies sind in Devise standardmässig für 2 Wochen gültig, und wir haben dies nicht abgeändert.

# ToDo

- [x] Warten bis Version 1.26.52 (oder neuer) überall für 2 Wochen aktiv war.
- [x] Änderung von https://github.com/hitobito/hitobito/commit/97009531bc154fb899b72b27517ca670a7d112aa rückgängig machen
- [x] Ausnahme aus der [brakeman.ignore](https://github.com/hitobito/hitobito/blob/master/config/brakeman.ignore) Datei entfernen
