### ISSUE TITLE
ABOS: Grosse Etiketten-Exporte laufen in 504 Gateway Timeout

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1592]
## Aktuelles Verhalten

Bei grossen Abos (>2000 Personen) resultiert der Haushalts-Etiketten-Export in einem 504 Gateway Timeout. 

## Gewünschtes Verhalten

Der Export kann ohne Fehler durchgeführt werden.

## Schritte zum reproduzieren

1. https://db.scout.ch/de/groups/1580/mailing_lists/1147/subscriptions
2. Export -> Etiketten -> "Haushalte zusammenfassen" aktivieren -> irgendein Etikettenformat wählen
3. Neues Tab geht auf, welches schliesslich in 504 Gateway Timeout resultiert

# Tech-Spec

Umsetzen im Core

In `SubscriptionsController#index` `format.pdf { }` in Backgroundjob verschieben.
Achtung, dieselbe Action mit demselben Format gibt auch die PDF-Adressliste aus, wenn kein `label_format_id` Parameter gesetzt ist. Zu klären: Soll dieses PDF auch gleich in einem Backgroundjob erstellt werden? Das Problem tritt bisher nur bei Haushalts-Exporten auf, und das Adresslisten-PDF fasst keine Haushalte zusammen. Aber wenn wir gerade dabei, sind könnte es sich lohnen.

Möglicher Zusammenhang mit einem Bug in der Haushalts-Berechnung, siehe #1553. Vielleicht wird dort ein Bug aufgedeckt der die Haushalts-Zusammenfassung wieder schneller macht. Aber garantiert ist es nicht und die Etiketten in einem Backgroundjob zu verlagern, macht wohl trotzdem Sinn.

# ToDo

- [ ] `render_pdf_in_background` bzw. `render_labels_in_background` implementieren, welches einen Backgroundjob triggert
- [ ] Backgroundjob implementieren, welcher die bisherige Label-PDF-Export-Logik (`RenderPeopleExports#generate_pdf`) enthält
- [ ] Testen in pbs-Wagon
- [ ] Testen in die-mitte-Wagon
