### ISSUE TITLE
MESSAGES: BulkMail: Mail Retriever Config

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1609]
Timebox: 4h

# Bestehend

Heute werden die Zugangsdaten für den Mail Retriever (Abos, Catch All) in einer Umgebungsvariable in folgendem Format gespeichert:

`address: mailhost.local, port: 995, enable_ssl: true`

env name: RAILS_MAIL_RETRIEVER_CONFIG

Zusätzlich wird über RAILS_MAIL_RETRIEVER_TYPE der Mailservertyp definiert (pop, imap)

Dies ist nicht besonders leserlich und verhindert das gewisse Sonderzeichen im Passwort vorkommen können.

# Config via Yaml File

Rails.root/config/mail/retriever.yml

```
imap: 
  address: mail.example.com
  username: mr-fetcher
  password: cGFzc3dvcmQ= # base64 encoded # echo -n 'password' | base64
  ssl: true
  port: 995
  ... weitere config optionen ?
```

Dieses neue Configformat wird mit dem neuen BulkMail Stack eingeführt. 

Ist die Config vorhanden, wird der bestehende Retriever Job deaktiviert und die neue Bulk Mail Implementation aktiviert. So kann der neue Retriever erst in einer Umgebung getestet und später alle anderen Umgebungen umgestellt werden. 

Später wird dann RAILS_MAIL_RETRIEVER_CONFIG sowie RAILS_MAIL_RETRIEVER_TYPE zusammen mit der alten Mail Retriever Logik komplett entfernt.

# Tech-Spec
- New mail retriever job: https://github.com/hitobito/hitobito/blob/feature/bulk-mail/app/jobs/mailing_lists/mail_retriever_job.rb
- Existing job: https://github.com/hitobito/hitobito/blob/feature/bulk-mail/app/jobs/mail_relay_job.rb
- https://github.com/hitobito/hitobito/blob/feature/bulk-mail/app/utils/imap/connector.rb
- Config Reader Cryptopus: https://github.com/puzzle/cryptopus/blob/master/lib/auth_config.rb

# ToDo

- [ ] Example Config config/mail/retriever.yml erstellen
- [ ] Falls neue retriever config vorhanden
  - [ ] wird neuer Retriever Job aktiviert
  - [ ] wird der alte Retriever Job deaktiviert
- [ ] Neuer Retriever liest Zugangsdaten nur noch aus yml
- [ ] Mail Client (UI) verwendet die yml config falls vorhanden, sonst die best. env vars. check IMAP::Connector
