### ISSUE TITLE
MESSAGES: New BulkMail stack finish

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1621]
Restliche Aufgaben für die Fertigstellung des neuen BulkMail Stacks

# Tech-Spec

# ToDo

- [x] Delivery Report implementieren
- [x] Neuer BulkMail Stack/Branch in Master mergen (feature wird nur aktiv wenn config/mail.yml vorhanden)
- [x] Auf einer Integrationsumgebung Testen mit neuer config/mail.yml
- [x] Prüfen wie sich die neuen Mailheaders verhalten (in Mailclients wie z.B. M$ Outlook, Thunderbird)
- [x] ggf. kleinere Changes/Fixes
- [x] Changelog Entry
- [ ] Docu updaten:
  - https://github.com/hitobito/hitobito/blob/master/doc/architecture/modules/01_messages.md
  - https://github.com/hitobito/hitobito/tree/feature/bulk-mail/app/domain/mailing_lists/bulk_mail
  - ggf. aus Messages Modul Doku einfach verlinken damit Module Doku nicht zu gross wird
- [x] Ticket erstellen für Umstellung erste Produktion
- [x] Migrationsanleitung erstellen
- [ ] Docu neue Umgebung Konfiguration Mailserver config/mail.yml
