### ISSUE TITLE
FRONTEND: Bootstrap aktualisieren

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1635]
Als Webentwickler von hitobito
möchte ich ein aktuelles Bootstrap verwenden,
um neue Features und Sicherheitsupdates zu haben

Der Upgradeprozess ist gut beschrieben, pro Major-Version ist ein separater Migrationguide vorhanden.

# ToDo

Was ist sinnvoller?
Entweder:
- [x] Upgrade to Bootstrap 3 (https://getbootstrap.com/docs/3.4/migration/ im Core und allen Wagons)
- [x] Upgrade to Bootstrap 4 (https://getbootstrap.com/docs/4.6/migration/ im Core und allen Wagons)
- [x] Upgrade to Bootstrap 5 (https://getbootstrap.com/docs/5.0/migration/ im Core und allen Wagons)

Oder:
- [x] Bootstrap 2 deinstallieren
- [x] Bootstrap 5 installieren
- [x] UI wiederherstellen, in Core und allen Wagons

Besser Variante 2

- [x] Docu erstellt/aktualisiert: https://github.com/hitobito/hitobito/blob/master/doc/development/09_frontend.md
- [x] Umsetzungsticket erstellt https://github.com/hitobito/hitobito/issues/1754
