### ISSUE TITLE
KURSE: J+S Reaktivierung von Qualifikationen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1640]
Hierbei geht es um die Umsetzung einer J+S-Anpassung zusammen mit der Youth-Community. Eine schriftliche Absprache mit Jubla und Cevi hat stattgefunden. In diesem Ticket soll eine mögliche Anpassung diskutiert werden.

## Hintergrund
Der J+S hat im Infomailing vom 4/2021 (Punkt 2.6) informiert, dass es eine Änderung an der Reaktivierung der Qualifikationen gibt:
https://www.jugendundsport.ch/de/infos-fuer/infomailings-partner.html

> Daher wurde beschlossen [...] den Status «weggefallen archiviert» per 1.1.2022 zu eliminieren (es bleiben die Status «gültig» und «weggefallen»). Die Bedingungen um eine oder mehrere Anerkennungen «weggefallen» zu erneuern, sind nun dieselben wie für die Verlängerung einer «gültigen» Anerkennung.

Durch diese Änderung gibt es nun mehr Fälle, bei denen der Status "weggefallen" in der Überprüfung der Anerkennung relevant wird. Wir würden deshalb gerne die beiden Stati «gültig» und «weggefallen» sauber in der MiData abbilden.

##### Zusatz / Abgrenzung
Zumindest die PBS hat unter https://db.scout.ch/de/qualification_kinds bereits die Reaktivierbarkeit von einzelnen Qualifikationsarten auf 1000 Jahre gestellt. Damit ist keine Anpassung nötig, um die Reaktivierbarkeit grundsätzlich auszuweiten.

### Administration
In der Administration der Kurse soll jede Vorbedingung mit einem Zusatz «gültig» oder «gültig oder weggefallen» ergänzt werden. Beispiel: https://db.scout.ch/de/event_kinds/22/edit

![Vorbedingungen](https://user-images.githubusercontent.com/1799621/154090065-83802176-a47d-41c2-81d7-923d3762cfca.png)

Standard-Wert müsste "gültig oder weggefallen" sein.

### Kursanmeldung
Bei der Prüfung der Vorbedingungen für Kurse sollen die beiden Fälle unterschieden werden: Wenn «Muss gültig sein» aktiviert ist, soll bei den Anmeldungen eines Kurses die Gültigkeit der Qualifikation beachtet werden. Wenn hingegen «Muss gültig oder weggefallen sein» aktiviert ist, soll nur überprüft werden, ob eine Qualifikation jemals zugewiesen wurde oder nicht.

Bei einer Vorbedingung mit "Muss gültig oder weggefallen sein" sollen auch die Hinweise (orange Ausrufezeichen) bei angemeldeten Personen entsprechend angepasst werden.

![image](https://user-images.githubusercontent.com/1799621/154090149-ebe1aef1-d825-42b0-a815-9f21a5c8d328.png)

### Personenfilter
Bei den Filtern sollen bei «reaktivierbare» dann auch alle miteinbezogen werden.

<img width="376" alt="filter" src="https://user-images.githubusercontent.com/1799621/154090190-9a8efc3d-4b06-4846-9ae8-9b7a27c6c33d.png">

# ToDo

- [ ] Administration anpassen
	- [ ] Vorbedingungen ähnlich wie neue Kontaktmöglichkeit hinzufügen
	- [ ] Tabelle `event_kind_qualification_kinds` um Spalte `validity` ergänzen
	- [ ] JS-Modul `EventKindPreconditions` erweitern
	- [ ] Controller anpassen, um `Event::KindQualificationKind`-Daten richtig für die DB aufzubereiten
	- [ ] Specs anpassen, um längere Reaktivierbarkeit zu berücksichtigen
	- [ ] Specs schreiben
- [ ] Kursanmeldung spezifizieren und anpassen (ggf. in eigenem Ticket)
- [ ] Personenfilter spezifizieren und anpassen (ggf. in eigenem Ticket)
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag hinzufügen

**Comment by richardjubla** [comment]
Hallo 👋

Jubla ist hiermit mit mir "mit von der Partie".

**Comment by kronn** [comment]
Zwischenstand/Frage: Die Einstellung der Gültigkeitsanforderung könnte unterhalb der Wahl der Vorbedingungsqualifikationen stehen. Bearbeiten wäre wie bisher ein Löschen und Neuanlegen. Damit muss man sich wenig umgewöhnen. Die Anforderung an die Gültigkeit wäre dann gleich für alle Qualifikationen, die man gleichzeitig auswählt. Da mehrere Vorbedingungen gewählt werden können, lassen sich hiermit sicherlich 99% der tatsächlichen Fälle abdecken.

Nicht abdeckbar, aber deutlich komplexer in der Umsetzung wäre, wenn man in einer gruppierten Anforderung nur einige Qualifikationen verlängerbar erlaubt, andere aber aktuell gültig sein müssen. 

DB-seitig würde die Gültigkeitsanforderung dennoch ggf. mehrfach gespeichert, um hier gleichermassen flexibel wie genau zu bleiben. Damit verbaut man sich dann auch nicht eventuelle komplexere Interfaces, um das zu definieren. Vorerst wird es aber das eingangs skizzierte bisherige Interface beibehalten und nur minimal erweitert.

**Comment by richardjubla** [comment]
Antwort aus Sicht Jubla: Unterschiedliche Gültigkeitsanforderung für unterschiedliche Qualifikationen sind nur beim Coach-Expert*innenkurs der Fall (Coach müss gültig sein, Expert muss gültig oder weggefallen sein). Weil dies ca. 2-5 Anmeldungen pro Jahr sind, kann dies vernachlässigt und manuell geprüft werden. Die andere Situation tritt beim Sicherheitsmodul Wasser ein, die SLRG-Anerkennungen müssen aber so oder so manuell via Brevet-Check geprüft werden.

**Comment by richardjubla** [comment]
Leiber @nchiapol und @Michael-Schaer 
Dieser Task ist aktuell in der Umsetzung: [JUBL-HIT22](https://github.com/hitobito/hitobito/milestone/50) 
Bitte um Rückmeldung falls es Konflikte mit der Youth-Community geben sollte.

**Comment by Michael-Schaer** [comment]
Für uns in Ordnung, wir haben kaum Fälle, in denen zwei mit einer Gültigkeit versehenen Vorbedingungen erfüllt sein müssen

**Comment by richardjubla** [comment]
Bug, gemeldet durch das Kursadmin-Team: 

In der Testumgebung der jubla.db erscheint keine Fehlermeldung/Hinweis, wenn sich eine Person mit weggefallener Anerkennung für einen Kurs mit Anerkennungs-Bedingung "gültig" anmeldet.
Beispielkurs: https://jubla.puzzle.ch/groups/1/events/623
Kursart SLK hat Quali Jugendsport als Vorbedingung "muss gültig sein".
Bei Lucia (https://jubla.puzzle.ch/groups/2/people/1056.html) erscheint korrekt die Fehlermeldung, dass die Qualifikation fehlt.
Bei Petra (https://jubla.puzzle.ch/groups/1/events/623/participations/3940) erscheint keine Fehlermeldung, es müsste aber anmerken "Folgende Qualifikationen sind nicht gültig: Leiter*in LS/T Jugendsport"

<img width="1822" alt="image" src="https://user-images.githubusercontent.com/95908537/191925365-4263646c-1dd8-4f91-82b1-3978b65576be.png">

**Comment by mtnstar** [comment]
> Bug, gemeldet durch das Kursadmin-Team:
> 
> In der Testumgebung der jubla.db erscheint keine Fehlermeldung/Hinweis, wenn sich eine Person mit weggefallener Anerkennung für einen Kurs mit Anerkennungs-Bedingung "gültig" anmeldet. Beispielkurs: https://jubla.puzzle.ch/groups/1/events/623 Kursart SLK hat Quali Jugendsport als Vorbedingung "muss gültig sein". Bei Lucia (https://jubla.puzzle.ch/groups/2/people/1056.html) erscheint korrekt die Fehlermeldung, dass die Qualifikation fehlt. Bei Petra (https://jubla.puzzle.ch/groups/1/events/623/participations/3940) erscheint keine Fehlermeldung, es müsste aber anmerken "Folgende Qualifikationen sind nicht gültig: Leiter*in LS/T Jugendsport"
> 
> <img alt="image" width="1822" src="https://user-images.githubusercontent.com/95908537/191925365-4263646c-1dd8-4f91-82b1-3978b65576be.png">

habe dazu ein neues Bug Issue erstellt: #1870

**Comment by richardjubla** [comment]
@ThomasEllenberger 
Wir sind mit Testen durch. Es gab keine zusätzlichen Rückmeldungen.
Offen ist noch https://github.com/hitobito/hitobito/issues/1870
Ich werde schauen, dass wir hier mitlesen und bei Bedarf helfen/ergänzen können.
