### ISSUE TITLE
KONFIG: Anfragen bei Gruppen für alle aktivieren

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1653]
Um zu verhindern, dass man beliebigen Personen aus der Datenbank eine Rolle vergeben kann, wurden die Gruppen-Anfragen eingeführt. Aktiviert eine Gruppe diese Funktion, so erhalten die zuständigen Personen eine Anfrage, sobald ein Mitglied einer anderen Gruppe hinzugefügt werden soll. Diese Anfrage kann dann Angenommen oder Abgelehnt werden.

![image](https://user-images.githubusercontent.com/1799621/155495458-66330876-e782-4c9f-bf52-8bf07ad8d7a4.png)

Leider ist diese Funktion bei der PBS nicht flächendeckend aktiviert. Als Quick-Fix möchten wir diese Funktion per Datenbank-Migration für alle Abteilungen (oder wenn einfacher: alle Gruppen) aktivieren.

Programmatisch soll nichts angepasst werden. Die Freigabe soll lediglich einmalig für alle aktiviert werden.

# ToDo

- [ ] Daten-Migration im Wagon erstellen
	- [ ] Möglichst nah an der DB bleiben, nicht Model-Code verwenden!
	- [ ] eine "leere" Down-Migration hinzufügen, es ist nicht sinnvoll umkehrbar
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unterhalb hinzufügen
