### ISSUE TITLE
TECH: S3-Migration aufräumen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1658]
Als Wartungsverantwortlicher
möchte ich den für die S3-Migration übergangsweise hinzugefügten Code entfernen,
um weniger Abhängigkeiten zu haben.

Siehe #1568 

# Tech-Spec

- weniger Dependencies
- weniger ungenutzte Config
- ungenutzten Speicherplatz freigeben

# ToDo

- [x] `gem "nochmal"` aus Gemfile entfernen
- [x] eventuell ungenutzte ActiveStorage-Configuration entfernen
- [x] ungenutzte Carrierwave-Uploader entfernen
- [x] ggf. PVC "files-store" entfernen
- [x] ggf. PVC "useruploads" entfernen
- [x] ggf. PVC "mysql-backup" entfernen
- [x] Configmanagement entsprechend anpassen
- [x] `UploadDisplayHelper` ausdünnen
- [ ] `Event::Attachment` vielleicht gegen `Event.has_many_attached` tauschen (nur timeboxed angehen)
