### ISSUE TITLE
PEOPLE: Sprache/Korrespondenzsprache als Core Feature

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1663]
wie aus https://github.com/hitobito/hitobito/issues/1451 ersichtlich, verwenden diverse Wagons das Attribut **correspondence_language**. 
Um einen ersten Schritt in Vereinheitlichung zu gehen und das Feature für alle Wagons zur Verfügung zu stellen, soll im core das Attribut **language** auf der Person eingeführt werden.
Das Feature wird aber nur aktiv falls auf der Person **correspondence_language** nicht vorhanden ist. Feature toggle erfolgt also über das Vorhandensein dieses Attributs. 
So können wir das Feature im Core einführen ohne das wir die Wagons sofort alle Updaten/Anpassen müssen.

- Standardmässig werden alle Sprachen die im System (UI Sprache) ausgewählt werden können verwendet
- In den einzelnen Wagons soll es dann möglich sein weitere Sprachen zu adden (auch solche, für die wir keine Transifex-Übersetzungen haben)
- Das Feld ist ein Muss-Feld, bei Personen ohne Sprache wird die Standardsprache assigned

# Tech-Spec
- [x] Person Attribut `language` via Migration im Core hinzufügen
	- varchar
	- NOT NULL
	- Standardsprache als default value
- [x] Standardsprache ist die erste definierte Sprache. Hier ggf. noch einen Kommentar in der `settings.yml` einfügen.
- [x] Sprachen aus `Settings.application.languages`
- [x] In den Wagons sollen weitere Sprachen hinzugefügt werden können (z.B. Rätoromanisch/rm): `Settings.application.additional_languages`
- [x] Changelog-Eintrag

# ToDo

- [x] Neue DB Migration für language attribut, :string, null: false, default: Standardsprache Wagon
- [x] Feature Toggle implementieren: Nur aktiv falls Attribut **correspondence_language** auf Person nicht vorhanden
- [x] Auf Model Werte validieren
- [x] Settting um im Wagon die verfügbaren Sprachen zu ergänzen/überschreiben
- [x] Radio Buttons auf Person#edit für Auswahl Sprache
- [x] Anzeige Sprache auf Person#show
