### ISSUE TITLE
SUCHE: Suche nach Rechnungen aufgrund von Referenz/Rechungs Nummer

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1672]
Als Benutzer und Finanzverantworlicher,
möchte ich eine Rechnung aufgrund der Nummer suchen,
um Rückmeldungen zu Rechnungen schnell bearbeiten zu können

Neu soll neben Personen, Anlässe, Gruppen auch Rechnungen gefunden werden. Suchkriterium sind:
* Titel
* Rechnungsnummer
* Referenznummer

Dies soll, falls die erforderlichen Berechtigungen vorhanden sind, über die Suche erfolgen. 

# Mockup

Eigenes Icon im Dropdown der Suche und neues Tab im Suchresultat:

![image](https://user-images.githubusercontent.com/9592347/158389354-ca2e0c47-d398-42b1-8540-84d74f2dee6d.png)

# Tech-Spec

- Die Suche soll eine weitere Facette bekommen
- Wenn man keine `:finance`-Berechtigung hat, sollen keine Rechnungen in den Ergebnissen auftauchen
- Benutzer können die an sie gerichteten Rechnungen nicht über die Suche finden

# ToDo

- [x] Neuen "Partial-Index" für Rechnungen erstellen (`app/indices/`)
	- [x] titel
	- [x] reference
	- [x] sequence_number
	- [x] ggf. group_id zum filtern
	- [ ] Index in hitobito/development Repo ergänzen: https://github.com/hitobito/development/blob/d6bc10d36b2118e32de4c45b7731a9b3b54bcdf5/docker/sphinx.conf
- [x] `SearchStrategies` erweitern, um Daten zu holen
- [x] `FullTextController` erweitern
	- [x] `index` grosse Ergebnissseite
	- [x] `query` Vorschau
	- [x] nur "sichtbare" Rechnungen weitergeben
- [x] Views in `full_text/index` anpassen, um ggf. weiteres Tab anzuzeigen (siehe Mockup)
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
	- [x] mit :finance-Berechtigung
	- [x] ohne :finance-Berechtigung
- [x] CHANGELOG-Eintrag hinzufügen

**Comment by TheWalkingLeek** [comment]
Volltextsuche ist broken auf Integration: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/51783/?query=is%3Aunresolved
