### ISSUE TITLE
SUCHE: Nach Gruppe suchen in "Person hinzufügen"-Dialog

### ISSUE THREAD

**Issue by Joelius300** [hitobito/hitobito#1675]
Bisher kann in dem "Person hinzufügen"-Dialog (für Kurse oder Lager) nach Vorname, Nachname, Übername, Firma und Adresse (bzw. Ort) gesucht werden.

Neu soll zusätzlich nach Gruppen gesucht werden können sofern zwei Suchbegriffe in die Suchleiste eingegeben wurde.  
Dies vereinfacht die Suche nach Personen von welchen man den legalen Namen und den Wohnort nicht kennt (häufig kennt man den Pfadinamen und die Abteilung).

Dabei werden alle Ebenen (nicht nur die Hauptebene) miteinbezogen.  
Falls ein Suchterm die Gruppe matcht, wird diese im Dropdown-Element auch angezeigt und der entsprechende Part hervorgehoben wie bei den anderen Feldern. Wenn die Suche nicht auf die Gruppe geht (sondern auf den Vornamen oder so) dann wird keine Gruppe im Dropdown-Element angezeigt, um den Datenschutz zu wahren; die Suche nach einer Gruppe sollte nur möglich sein wenn die Gruppe bekannt ist. Die Idee, dass die Gruppen nur in die Suche miteinbezogen werden, wenn mehr als ein Suchbegriff eingegeben wurde, ist um zu verhindern, dass Personen einfach nach der Pfadiabteilung (Gruppe) "Nünenen" suchen und Personen von dieser Abteilung sehen, auch wenn sie dies mit ihren Berechtigungen sonst nicht würden. Natürlich kann man immer noch "Nün enen" suchen, um es zu umgehen, aber es stellt eine erste Barriere in den Weg.

Damit die Benutzer realisieren, dass sie nach Gruppen suchen können, könnte ein kleiner Info button gemacht werden. Dies wird benötigt, da man in der Auflistung die Gruppe nicht sieht ausser sie wird gematcht.

## Andere Möglichkeiten
Diese Möglichkeiten wurden am 12.03 besprochen aber wurden nicht weiter in Betracht gezogen.

- Zweites Suchfeld für Abteilung
  - Direkt dabei
  - Hinter einem Dropdown
  - Auswahlfeld / Dropdown-select
  - Defaultwert der eigenen Abteilung
- Sortierung nach "Nähe" -> könnte ein Feature für die globale Suche werden
- Suche bei Lager nur innerhalb der Veranstalter

## ToDo

- [ ] Datenschutzimplikationen überlegen
- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren
