### ISSUE TITLE
Website: Automate process to generat new SaaS environments

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1689]
## Bisher:
Will jemand SaaS 30Tage kostenlos testen, generiert dies ein Email an info@hitobito.com.
Die SaaS Umgebung wird anschliessend von einem PL manuell erstellt.

Da dies ein manueller Schritt ist, passiert dies immer erst am nächsten Arbeitstag. Möchte jemand sich am Samstag einloggen und gleich loslegen geht dies nicht. Der User erhällt auch keine Info und weis evtl. nicht genau warum es noch nicht geht. Bis wir am nächsten Montag Kontakt aufnehmen, könnte der User längst eine andere Lösung gefunden haben.

## Gewünschte Lösung:
Neu soll die neue SaaS Umgebung nach dem Eintragen sämtlicher Userdaten automatisch generiert werden.
Dadurch kann der User sofort loslegen und für den PL entfällt die manuelle Eingabe

## Zu definieren:
- Sollen die PL's dennoch weiterhin ein Email erhalten, damit diese wissen wenn sich jemand Neues angemeldet hat.
Damit können sie nach wie vor mit dem potentiellen Kunden Kontakt aufnehmen und Bedürfnisse abklären.

- Persönlich finde ich es etwas verwirrend, dass wir sowohl ein "kostenlos testen" sowie eine "kostenlose Demoversion" haben. 
Evtl. könnte man dies auf der Website anders benennen / die Demoversion prominenter darstellen. Dadurch könnten User welche das Produkt lediglich einmal etwas anschauen wollen auf die Demoversion geleitet werden und würden keine neue SaaS Version anlegen.

## Inputs:
- Gemäss obr gab es bereits einmal ein Plugin welches hier einen Workaround geschaffen hat. Kann man von diesem evtl. etwas weiterverwenden?
- Gemäss mvi war dies bereits einmal angedacht wurde jedoch aufgrund des grossen Aufwands verworfen. Existiert von damals noch ein Issue o.ä.?

## ToDo:

- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] Aufwand schätzen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by ThomasEllenberger** [comment]
Wird aktuell nicht weiterverfolgt
