### ISSUE TITLE
EVENTS: Event::ParticipationConfirmationJob aufsplitten

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1702]
### Aktuelles Verhalten

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/51510
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/48372

Bei der Multitenancy ist das Attribut `events.notify_contact_on_participations` nicht vorhanden. Dadurch failed der `Event::ParticipationConfirmationJob`, startet neu und sendet die `Event::ParticipationMailer.confirmation` Mail mehrmals. 

### Gewünschtes Verhalten

Das Attribut `events.notify_contact_on_participations` ist vorhanden.

### Schritte zu reproduzieren

1. Anlass in Tenant erfassen:
2. Kontaktperson hinterlegen
3. "Kontaktperson über neue Anmeldung per Mail benachrichtigen" aktivieren
4. Teilnahme erfassen

### Wann ist der Fehler aufgetreten?

Siehe Sentry

### hitobito version

1.27.11

### Organisation

Tenants

### Screenshots, weiterer Kontext

PR zu Benachrichtigungsfeature: https://github.com/hitobito/hitobito/pull/1570

Es soll mit Version 1.27.13 behoben sein?

## ToDo

- [x] Event::ParticipationConfirmationJob aufsplitten
  - [x] eigener Job für `Event::ParticipationConfirmationJob#send_confirmation`
  - [x] eigener Job für `Event::ParticipationConfirmationJob#send_notification`
    - [x] Logging an der Stelle präzisieren
- [x] Ticket fürs Debugging vom eigentlichen Error
