### ISSUE TITLE
API: Upgrade JSON API

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1708]
#207

Aktuell ist die JSON API mit einem veralteten Standard, basierend auf einem Gem welches nicht mehr maintained wird, umgesetzt.

Neu soll zusätzlich eine JSON API Schnittstelle mit aktuellem Standard und Gem angeboten werden. Dafür existiert bereits ein Branch welcher den `/events`, `events/:id`, `/groups` auf neuem Standard implementiert hat: https://github.com/hitobito/hitobito/commits/update_json_api

Wichtig ist, die neue Version soll mittels Parameter bei der Anfrage abgefragt werden. Auf dem Branch wurde dies mittels query parameter `api_version` gelöst. Standardmässig alte Version anbieten, in Dokumentation aber auf neue Version verweisen und empfehlen.

# ToDo
- [ ] Issue(s) (Epic?)  für:
  - [ ] Review des `update_json_api` Branch & Bereits vorhandenes mergen
  - [ ] noch zu erledigende Endpunkte 
  - [ ] Doku 
  - [ ] Discussion zur Deprecation der alten Endpunkte
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by mtnstar** [comment]
neue JSON:API wurde mit #1920 eingeführt.
