### ISSUE TITLE
TECH: Grosse Im- und Exporte ermöglichen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1712]
Aktuell kommen grosse Im- und Exporte öfter an RAM-Grenzen oder laufen in Timeouts. Der Speicher kann einerseits nicht unendlich erhöht werden kann, gleichzeitig behindern diese Exporte die Bearbeitung anderer Jobs.

Im Ergebnis wirkt hitobito damit defekt.

Wir haben bereits ein paar Issues hierzu:
- #1361
- #1700 

Neu sollen Möglichkeiten gefunden werden, grosse Exporte aufzuteilen oder zu beschleunigen. Wenn die Exporte aufgeteilt werden, müsste man das Zusammenführen der Teilexporte lösen können. Für die Beschleunigung der Exporte könnte Vorberechnung und Caching helfen oder auch die Zusammenfassung der Rechteprüfungen.

Umfangreiche Exporte sind:
- CSV-Export "SARASANI" der PBS
- PDF-Erstellung via Rechnungsbrief "Spendenbestätigung" der Partei Die Mitte

Importe haben teilweise das Problem, dass zu grosse Dateien zu lange brauchen, um analysiert zu werden. Hier könnte man mit einem Upload und dann verzögertem Preview arbeiten. Die Umsetzung wäre vermutlich analog zu Asynchronen Download. Hier ist aber auch noch zu prüfen, ob weitere Möglichkeiten bestehen. 

# ToDo

- [ ] Issues für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by kronn** [comment]
Siehe auch https://codimd.puzzle.ch/uZ6AljA6Qi-UBDj0xBM-cA#Ressourcenintensive-Delayed-Jobs
