### ISSUE TITLE
PERSON: Setzen von einem Bis Datum auf der Rolle

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1714]
### Aktuelles Verhalten

Wird auf einer Person, welche nur eine Rolle hat, das Bis Datum in der Vergangenheit gesetzt, landet der Benutzer auf einer 404 Seite. Dies ist wohl so, weil die Person keine aktive Rolle mehr hat.

### Gewünschtes Verhalten

Falls die Person keine Rolle mehr hat, soll der Benutzer auf der Gruppe landen.
Bis Datum kann nur in der Vergangenheit gesetzt werden. Zukünftiges Feature ermöglicht es dann das Bis Datum in Zukunft zu setzten.
Acts As Paranoid macht das nicht: https://github.com/rubysherpas/paranoia/issues/480

### Schritte zu reproduzieren

1. Person mit einer Rolle erstellen
2. Rolle bearbeiten
3. Rolle Bis auf ein Datum in der Vergangenheit setzten

### Wann ist der Fehler aufgetreten?

12.04.2022 - 0945

### hitobito version

1.27.17

### Organisation

SWW

### ToDos

- [x] Issue aufbereiten
- [x] ggf. Sentry-Issues dazu heraussuchen
- [x] Labels für `interest-xyz` setzen
- [x] Schritte für Fehlerbehebung erfassen
- [x] Team informieren, um es einzuplanen

### Fehlerbehebung

- [x] bis-Datum als Feld hinzufügen
- [x] bis-Datum so validieren, dass es in der Vergangenheit liegen muss
- [x] alle Wagons durchsehen, wo was bis-Feld schon verwendet wird
  - PBS
  - SBV
  - SWW
  - ...?

### Stretch-Goal

Wenn es leicht möglich ist:

- [x] Eventuell Paranoia-Scope anpassen, sodass das Datum korrekt berücksichtigt wird.

Dies könnte auch ein neues Feature werden
