### ISSUE TITLE
PERSON: Exporte für neue NDS

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1733]
Liebe Youth-Community

Gemäss Kommunikation des BASPO wird die neue NDS im Herbst 2022 live gehen. [Mehr infos](https://www.jugendundsport.ch/de/themen/neue-nds.html). Die PBS möchte pünktlich zum Go-Live der neuen NDS auch die Exports angepasst haben. Wir haben uns dazu folgende Gedanken gemacht.

@nchiapol @richardjubla Seid ihr auch im Boot? Machen wir das zusammen? Und habt ihr die gleichen Anforderungen wie wir?

Unter den [J+S Anleitungen](https://www.jugendundsport.ch/de/themen/neue-nds/anleitungen.html) sind die Musterdateien für den Import in der NDS zu finden. Dabei interessiert uns «Import von Personen in der Jugendausbildung» und «Import von Personen in der Kaderbildung».

Anzupassende Exports:
Lager/Kurs/Anlass -> Teilnehmende -> Export -> CSV/Excel -> NDS
- umbauen gemäss «Musterdatei für den Import von Personen in der Kaderbildung»
- umbenennen zu «NDS: Kurs» (fr. BDNS: Cours / it: BDNS: Corso)

Lager/Kurs/Anlass -> Teilnehmende -> Export -> CSV/Excel -> SPORTdb
- umbauen gemäss «Musterdatei für den Import von Personen in der Jugendausbildung»
- umbenennen zu «NDS: Lager» (fr: BDNS: Camp / it: BDNS: Campo)

Optional: 
- ~~"NDS: Kurs" nur bei Kursen anzeigen, "NDS: Lager" nur bei Lager anzeigen~~
- ~~Es wäre nützlich, wenn die MiData warnen könnte, bei welchen Personen welche Pflichtfelder nicht ausgefüllt sind.~~

---

# Tech-Spec

- Umsetzung im Youth Wagon
- Es ist wohl am einfachsten wenn wir zwei neue CSV-Exporte (NDS-Kurs und NDS-Lager) machen, die alten werden dann entfernt
  - NDS-Lager-Export ist dokumentiert unter https://www.jugendundsport.ch/de/themen/neue-nds/anleitungen.html#datenimporte-in-die-neue-nds "Musterdatei für den Import von Personen in der **Jugendausbildung**" sowie "Import von Personen in der **Jugendausbildung**"
  - NDS-Kurs-Export ist dokumentiert unter https://www.jugendundsport.ch/de/themen/neue-nds/anleitungen.html#datenimporte-in-die-neue-nds "Musterdatei für den Import von Personen in der **Kaderbildung**" sowie "Import von Personen in der **Kaderbildung**"

# ToDo
- [ ] Neuer CSV-Export "nds_course"
  - [ ] Wird nur auf der Teilnehmendenliste von Kursen angeboten
  - [ ] Nach Vorbild des alten CSV-Exports "NDS" bzw. "NDBJS"
  - [ ] Format der CSV-Spalten anhand Vorlage "Musterdatei für den Import von Personen in der **Kaderbildung**" von der [J+S-Seite](https://www.jugendundsport.ch/de/themen/neue-nds/anleitungen.html#datenimporte-in-die-neue-nds)
- [ ] Neuer CSV-Export "nds_camp"
  - [ ] Wird nur auf der Teilnehmendenliste von Lagern (und bei der PBS auf campy_courses) angeboten
  - [ ] Nach Vorbild des alten CSV-Exports "SPORTDB"
  - [ ] Format der CSV-Spalten anhand Vorlage "Musterdatei für den Import von Personen in der **Jugendausbildung**" von der [J+S-Seite](https://www.jugendundsport.ch/de/themen/neue-nds/anleitungen.html#datenimporte-in-die-neue-nds)
- [ ] Alte CSV-Exporte "SPORTDB" und "NDS" entfernen, diese sind nicht mehr nützlich weil die alte NDBJS abgeschaltet wurde
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Der Cevi ist da auch interessiert und möchte das auch möglichst gemeinsam lösen. Anforderungen scheinen die gleichen.

**Comment by richardjubla** [comment]
> Wichtige Infos aus dem Infomail von J+S:
> 
> Inbetriebnahme NDS
> In der letzten Oktober-Woche 2022 (zwischen 24. und 28.10.2022) soll neue NDS freischalten. Die aktuelle NDS wird vorher für ca. 5 Arbeitstage abgestellt, damit die Datenmigration auf das neue System erfolgen kann. In dieser Zeit werden keine Daten in der NDS verarbeitet werden können. 
> 
> Der Release der neuen NDS sollte also Ende Oktober erfolgen. Auf jeden Fall scheint also die DB 1 Monat vor Inkrafttreten der Verordnungsrevision 2022 kommen. Das müssen wir sicher bei der Anpassung, z.B. auch der jubla.db mitdenken. 

Die Jubla möchte/sollte demzufolge diesen Task in den Sprint (Q3/Jul-Sep) aufnehmen.

**Comment by richardjubla** [comment]
Dieser Task wurde nicht in der jubla Offerte/Sprint Q3/Juli-Sept aufgenommen.

**Comment by richardjubla** [comment]
Infos zur NDS aus dem J+S Infomail:

> In der letzten Oktober-Woche 2022 (zwischen 24. und 28.10.2022) werden wir die neue NDS freischalten. Die aktuelle NDS wird vorher für ca. 5 Arbeitstage abgestellt, damit die Datenmigration auf das neue System erfolgen kann. In dieser Zeit werden keine Daten in der NDS verarbeitet werden können. 

Verbände welche eine nahtlosen Übergang der Daten sicherstellen möchten, müssten ihre Systeme auf diesen Zeitpunkt hin aktualisieren.

**Comment by richardjubla** [comment]
Ergänzung: "Harmonisierung" der Namen SPORTdb und NDS. -> Sicherstellen, dass Name korrekt unterschieden werden kann und korrekt funktioniert. (SPORTdb gibt es zukünftig nicht mehr, NDS eigentlich auch, wobei die Abkürzung die gleiche ist?)


Eigentlich müsst der Export für SPORTdb und NDS identisch sein. Ich gehe davon aus, dass der NDS Export der "neue" Export wird oder ein komplett neuer Export erstellt wird.
![image](https://user-images.githubusercontent.com/95908537/192739592-fa5cd9dc-788f-4d2a-acb5-4345ca8b72c4.png)


**Berechtigungen**: Coaches können gemäss #1756 SPORTdb Exporte machen. Mit der Aktualisierung der Exporte müsste weiterhin sichergestellt werden, dass alle Berechtigungen weiterhin korrekt sind.

**Pflichtfelder** Jubla kennt keine PEID (Lichtenstein). Was muss gemacht werden, damit der Export für die youth community generell alle Pflichtfelder exportieren kann.  

**Termine:** Genauer Zeitpunkt wird wohl verschoben und in verschiedenen Phasen stattfinden.

**Comment by Michael-Schaer** [comment]
@richardjubla Siehe mein erster Beitrag: Für uns sollte es zwei Exports NDS-Kurs und NDS-Lager geben.

Zu den Terminen: Merci fürs Tracken. Ich bin froh, wenn wir die Exports rechtzeitig drin haben, bin aber auch nicht immer ajour, wie es mit dem Release-Zeitpunkt der NDS aussieht...

**Comment by richardjubla** [comment]
Korrekt: die initiale Aussage zu Export Kurs und Lager (2 Exports) stimmt.


Kommunizierter Terminplan auf Seiten BASPO:
![image](https://user-images.githubusercontent.com/95908537/197757452-30b65cca-ff0b-4555-a1b8-c7a2fb275977.png)

(erneuter Hinweis zur Offerte ist erfolgt)

**Comment by richardjubla** [comment]
Jubla hat Freigabe für Offerte gegeben (ohne Optionen)

**Comment by TheWalkingLeek** [comment]
Hallo zeme
Ich habe jetzt mit der Umsetzung begonnen. Dabei sind mir folgende Punkte beim "Import von Personen in der Kaderbildung" (Export Kurse) aufgefallen die ich nachfragen möchte:
- PEID: Die PEID ist ein Pflichtfeld laut der Doku vom J+S, im Hitobito führen wir diese aber so nicht. Die Doku erlaubt aber auch dass jeweils entweder AHV-Nummer oder PEID leer sein darf. Daher meine Frage, sollen wir die PEID einfach leer lassen oder habt ihr eine Idee wie/woher wir das befüllen können?
- EMAIL (PRIVAT): Ist das einzige Pflicht E-Mail Feld, daher würden wir es einfach mit der Hitobito "Haupt E-Mail" befüllen. Ich hoffe das passt so
- EMAIL/TELEFON (AMTLICH): Führen wir in Hitobito gar nicht und ist daher dann einfach leer. Hoffe das passt auch :)

**Comment by ThomasEllenberger** [comment]
@richardjubla, @nchiapol, @Michael-Schaer Was meint ihr hierzu?
Hat jemand von euch Mitglieder aus Lichtenstein mit einer PEID Nummer? Und wo füllt ihr diese ab?
(Im AHV Feld kann diese ja nicht führen, da dort das Dateformat nur 13 stellige Nummern zulässt)

**Comment by Michael-Schaer** [comment]
> PEID

Ja, leer passt für mich.

> EMAIL (PRIVAT)

Ja, Haupt-E-Mail sollte passen. Oder wie ist es denn beim jetzigen NDS-Export?

> EMAIL/TELEFON (AMTLICH)

Passt für mich.

**Comment by TheWalkingLeek** [comment]
Beim bisherigen NDS-Export gibt es nur ein E-Mail Feld "EMAIL", welches von der Haupt E-Mail befüllt wurde

**Comment by nchiapol** [comment]
Für mich passen die Vorschläge ebenfalls.

**Comment by richardjubla** [comment]
Ich habe auf unserer Testdb den Export getestet und mit den Test-Dateien (Musterdatei für den Import von Personen in der Jugendausbildung / Lager & Musterdatei für den Import von Personen in der Kaderbildung / Kurse) verglichen. Aus meiner Sicht ist der gewünschte Teil (Offerte Jubla ohne Optionen) umgesetzt. 

@nchiapol @Michael-Schaer 
Wir würden mit einem Release (Produktivem Test) auf euer Feedback warten und bei Bedarf auch auf die Optionen.

**Comment by nchiapol** [comment]
@richardjubla Ich habe eben versucht das ebenfalls zu testen aber keine entsprechende Musterdatei gefunden. In der NDS finde ich in  
`Dokumentenbibliothek / Jugendausbildung / Importvorlagen`
Vorlagen für Aktivitäten und Anwesenheiten - beide sehen aber ziemlich anders aus als die Exporte in unserem Integrationssystem. (Und aktuell habe ich keinen Zugang zu einem laufenden Angebot um dort die Uploads anzuschauen)

**Comment by carlobeltrame** [comment]
Die Musterdatei welche imVorfeld vor dem Release bereits veröffentlicht wurde ist in der Beschreibung dieses Issues verlinkt

**Comment by nchiapol** [comment]
Danke! In dem Fall sieht das für mich auch korrekt aus. 

Ich denke, die Optionen können wir noch einmal anschauen, wenn wir erste Erfahrungen gemacht haben.

**Comment by richardjubla** [comment]
Ich habe nach Hinweisen (auch aus #1960 und #1961) den Export aus Hitobito und der Musterdatei verglichen. 
Während Hitobito "ANSI" exportiert, ist die Musterdatei in "UTF-8 mit BOM".

**Comment by carlobeltrame** [comment]
@richardjubla danke Richard fürs auch hier festhalten. Siehe auch https://github.com/hitobito/hitobito_pbs/pull/250 und https://github.com/hitobito/hitobito/pull/1993, wo die Diskussion bereits weitergeht.

**Comment by richardjubla** [comment]
> @richardjubla danke Richard fürs auch hier festhalten. Siehe auch [hitobito/hitobito_pbs#250](https://github.com/hitobito/hitobito_pbs/pull/250) und #1993, wo die Diskussion bereits weitergeht.

Danke für die Info. Ich bitte aber die Erkenntnisse und Auswirkungen wieder zurück hierhin zu tragen. Dies weil die "Lösung" an dieses Ticket und eine Offerte/Auftrag gebunden ist. 
Mit @ThomasEllenberger ist vereinbart, dass wir mit Verfügbarkeit der NDS Testen.
