### ISSUE TITLE
INVOICE: Transaction identifier uniqueness überarbeiten

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1753]
### Aktuelles Verhalten

Wenn eine Zahlung importiert wird (egal ob EBICS oder manuell) und der `transaction_identifier` schon vergeben war, wird die Zahlung nicht gespeichert.

Das dazu bezogene Feld im XML ist `Refs.AcctSvcrRef`oder `Refs.Prtry.Ref`: https://github.com/hitobito/hitobito/blob/master/app/domain/invoice/payment_processor.rb#L144

### Gewünschtes Verhalten

Der Uniqueness Constraint soll bleiben. Nur soll das Feld neu abgefüllt werden.

Da es keinen eindeutigen Identifier für einzelne Zahlungen gibt (am nächsten kommt AcctSvcrRef, aber das ist nur unique für einen Batch von Zahlungen), kombinieren wir die Felder AcctSvcrRef, QR-Referenz (ist optional), Betrag, Eingangsdatum und Debitor IBAN in einen Bandwurm-Identifier.

### Schritte zu reproduzieren

https://help.puzzle.ch/#ticket/zoom/4103
https://help.puzzle.ch/#ticket/zoom/3157

In diesen Tickets sind jeweils XML Dateien angehängt welche den Fehler provozieren.

### hitobito version

1.27.19

### Organisation

Die Mitte

### ToDos

ToDo

- [ ] PaymentProcessor anpassen
  - [ ] neuer "Bandwurm-Identifier" auslesen und einspeichern
- [ ] Specs schreiben & anpassen
- [ ] Bestenfalls mit den XMLs aus den Tickets durchtesten

**Comment by ThomasEllenberger** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito/1753?planning-poker) with ZenHub @kronn @mtnstar @TheWalkingLeek
