### ISSUE TITLE
Berechtigung anpassen: Coaches sollen Exporte für die Sport DB machen können

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1756]
Die ~~Cevi~~ Jubla möchte die Berechtigungen der Rolle "Coach" so anpassen, dass diese die Exporte für die Sport Datenbank selbst durchführen können.

Neu sollen Personen welche die Rolle "Coach" haben, die Rechte haben um die Exporte für die Sport Datenbank zu generieren. Dabei soll jede Person lediglich Daten exportieren können welche sie mit ihren Berechtigungen auch sehen kann.

# Tech-Spec

- Coach ist eine Rolle auf einem (Lager) Event
- im [Jubla-Wagon](https://github.com/hitobito/hitobito_jubla) lösen

# ToDo

- [x] In https://github.com/hitobito/hitobito_jubla/blob/master/app/models/event/camp/role/coach.rb#L11 `:participations_read` in `:participations_full` ändern
- [x] Allenfalls Specs anpassen
- [x] Mit angemessener Rolle "durchklicken"
  - Lager edit form, Person als Coach setzen, als diese Person einloggen oder immitieren
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Betrifft die Jubla, nicht den Cevi. Beim Cevi haben die Coaches die nötigen Rechte bereits.

**Comment by richardjubla** [comment]
**User-Story**
>Als Coach muss ich in der Datenbank Lager-Teilnehmer exportieren können um diese dann in der SportDb einreichen zu können (CSV Datei Sportdb).


**Aspekte**
- Wir gehen davon aus, dass bereits eine Anpassung der Export-Berechtigungen ausreicht, um dem Coach die Möglichkeit zum Export zu geben.
- Der Coach muss nur "seine" Lager exportieren können. 


Die Rolle **Coach** in der Gruppe {} hat folgende Berechtigungen:
- Lesen der Kontaktdaten aller anderen Personen mit Kontaktdatenberechtigung.
- Lesen auf der Gruppe.



**Definition of Done** 
- User mit der Rolle Coach kann einen Lager-Teilnehmende-Liste exportieren (CSV Datei Sportdb) und gemäss seinen Vorgaben verwenden
- Dokumentieren, welche Rollen den Export in dieser Form machen können

![image](https://user-images.githubusercontent.com/95908537/175994269-02406b7b-c73f-4ad5-a0c7-16d22d5f50d7.png)

**Comment by richardjubla** [comment]
Lieber @fossil12 gibt es relevante Punkte, welche von https://github.com/hitobito/hitobito/issues/471 übernommen werden müssten?

**Comment by carlobeltrame** [comment]
@richardjubla Bisher haben bei der Jubla Hauptleitung und Hilfsleitende diese Möglichkeit, und neu dann auch Coaches.

**Comment by richardjubla** [comment]
@ThomasEllenberger 
**Wir sind mit Testen durch. Es gab keine zusätzlichen Rückmeldungen.**

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Bitte dieses Issue wieder öffnen. Die Rolle Coach kann gemäss unseren Test **keine** Exporte mehr für die NDS/Sport DB mehr machen. Dies müsste mit dem Release [Version 2.9.15](https://db.jubla.ch/changelog) zusammenhängen. 
Vermutung: Die Fähigkeit wurde nicht angepasst oder zurück gebaut, sondern ist ein "Opfer" der Umstellung der Berechtigungsstruktur: Exporte hängen jetzt an Gruppenrechten – das ist die eigentliche Ursache, warum der Coach keine Exporte mehr machen kann.

Ich gehe davon aus, dass die Jugendverbände dies weiterhin benötigen und vermissen werden. Nach den Lagern ist jeweils der Coach dafür zuständig, das durchgeführte Lager in der NDS zu importieren. Wir sollten verhindern, dass diese Listen über andere Wege von der Schar zum Coach kommen muss. 





Development 2.8.15 : Ayleen Welz / Voluptatem / Coach in Gruppe und Event fehlt NDS Export:
<img width="1979" height="1281" alt="Image" src="https://github.com/user-attachments/assets/7b93778d-adbf-4a7a-97b8-0ee03cdd2da6" />

<img width="2007" height="1233" alt="Image" src="https://github.com/user-attachments/assets/817eb2d3-6f8a-4606-9870-f66c29806b43" />


Integration Version 2.9.4 : Sinjoa Torlocki / Dulur Coach in Gruppe und Event fehlt NDS Export:

<img width="2136" height="698" alt="Image" src="https://github.com/user-attachments/assets/306e7b4b-17eb-4894-843b-524a568e9e42" />

<img width="2168" height="1050" alt="Image" src="https://github.com/user-attachments/assets/e2e6afda-6cde-41d8-8313-a80272b42460" />


Beispiel wie der NDS-Kurs oder NDS-Lager exportiert werden kann:
<img width="2020" height="580" alt="Image" src="https://github.com/user-attachments/assets/b23ac258-58be-42d5-8345-9a58ac541c34" />

**Comment by carlobeltrame** [comment]
Ich habe den [vorgeschlagenen Fix](https://github.com/hitobito/hitobito_jubla/pull/227#issuecomment-4517611035) von Richi feat. KI umgesetzt und einen Test dafür gemacht. Es scheint zu funktionieren (in der lokalen Umgebung ist es etwas mühsam / knowhow-intensiv zu testen, weil dort keine Coaches in den Lagern geseedet werden).

Mir ist aber nicht ganz klar, wie das vor hitobito/hitobito_jubla#227 hätte funktionieren können. Zudem ist mir unklar, wieso Kursbetreuungspersonen die Exporte nach wie vor machen können, obwohl sie nur `:participations_read` Berechtigung haben.

@richardjubla merci für die Meldung, den Fix-Vorschlag, und merci falls du das nochmals auf eurer Integration testen kannst, ob jetzt alles stimmt. Die anderen Jugendverbände waren davon nicht betroffen.

**Comment by richardjubla** [comment]
> Ich habe den [vorgeschlagenen Fix](https://github.com/hitobito/hitobito_jubla/pull/227#issuecomment-4517611035) von Richi feat. KI umgesetzt und einen Test dafür gemacht. Es scheint zu funktionieren (in der lokalen Umgebung ist es etwas mühsam / knowhow-intensiv zu testen, weil dort keine Coaches in den Lagern geseedet werden).

**Danke!** (Werde mir merken expliziter von vermuteter Lösung/Bug zu sprechen, schliesslich überlasse ich die Prüfung/Verantwortung euch)
Ich habe ebenfalls getestet und aus meiner Sicht können Coaches wieder NDS-Exporte machen. 


> Mir ist aber nicht ganz klar, wie das vor [hitobito/hitobito_jubla#227](https://github.com/hitobito/hitobito_jubla/pull/227) hätte funktionieren können. Zudem ist mir unklar, wieso Kursbetreuungspersonen die Exporte nach wie vor machen können, obwohl sie nur `:participations_read` Berechtigung haben.

Mir auch nicht. 
Kursbetreuungspersonen können keine NDS-Exporte machen, bisher und auch jetzt nicht.


> [@richardjubla](https://github.com/richardjubla) merci für die Meldung, den Fix-Vorschlag, und merci falls du das nochmals auf eurer Integration testen kannst, ob jetzt alles stimmt. Die anderen Jugendverbände waren davon nicht betroffen.

Ich gehe hier von technischer Schuld aus, wäre gut wenn das Verhalten gleich oder mindestens nachvollziehbar und stabil ist.

**Comment by carlobeltrame** [comment]
> Ich gehe hier von technischer Schuld aus, wäre gut wenn das Verhalten gleich oder mindestens nachvollziehbar und stabil ist. 

Der Unterschied und auch der Bug selber kam von einer Jubla Customization. Der Fix war, diese Customization abzuschaffen, da sie nicht mehr nötig war. Trotzdem unterscheiden sich die Events unter den Jugendverbänden noch erheblich, da z.B. beim Cevi gar keine Lager im UI existieren, und auch das Handling der Coaches teils wegen Prozessunterschieden abweicht.
