### ISSUE TITLE
Übersicht: Wer ist wo im Lager

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1758]
Die Jubla hätte gerne eine Übersicht aller anstehender Lager und die Möglichkeit auszuwerten welcher User wann wo im Lager ist.

Bei der PBS gibt es das Lagertab links in der Übersicht bereits. Diese sollen für die Jubla ebenfalls ähnlich ~~aktiviert~~ implementiert werden.
Der Export der bevorstehenden Lager bei der PBS zeigt jedoch nur das Lager selbst und sämtliche Attribute dieses Lagers, wie etwa auch Teilnehmeranzahl. Allerdings ist es damit noch nicht möglich die genauen Teilnehmenden dieser Lager zu sehen.

# Mockup

![Screenshot 2022-09-05 at 09-53-13 jubla.db - Kanton Aargau.png](https://images.zenhubusercontent.com/6024f53010a3a03f4448add2/7afa9a2c-1448-4e23-b352-2cad89d8f202)

![Screenshot 2022-09-05 at 10-03-40 MiData PBS_MSdS_MSS - Alle Lager im Ausland](https://user-images.githubusercontent.com/7566995/188399627-02726b92-e183-4561-8889-8dcf9467494e.png)

# Tech-Spec

- Umsetzung im Jubla Wagon, da sich das Feature in den Details zu fest von der Version der PBS unterscheidet

Der Export der zuvor in Ticket #364212 erstellt wurde hatte folgende Daten geliefert (keine Teilnehmendendaten):
```ruby
timespan = Time.zone.now.midnight + 4.weeks
camps = Event::Camp.includes(:groups).list.upcoming.where('event_dates.start_at <= ? OR event_dates.finish_at <= ?', timespan, timespan)
data = Export::Tabular::Events::List.csv(camps)
File.open(Rails.root.join('camps.csv'), 'w') { |file| file.write(data) }
```

# ToDo

- [x] Neuer Menüpunkt "Lager" im linken Hauptmenü (analog PBS)
  - [x] Wenn draufgeklickt, führt dieses Menü zum ersten für den User verfügbaren Unter-Menüpunkt
  - [x] Wenn keiner der Unter-Menüpunkte verfügbar ist wird auch der "Lager" Menüpunkt nicht angezeigt
- [x] Unter-Menüpunkt "Lager in der ganzen Schweiz" (analog PBS)
  - [x] Zugänglich / sichtbar für Rolle IT-Support in Gruppentyp Group::Federation
  - [x] Zugänglich / sichtbar für Rolle Mitglied in Gruppentyp Group::FederalBoard
  - [x] Zeigt eine Liste von sämtlichen Lagern die zwischen heute und heute in 4 Wochen stattfinden (mind. 1 event_date muss überschneiden mit diesem Zeitraum). Beispiel für Query siehe TechSpec
  - [x] CSV Export der angezeigten Daten, Button sollte so aussehen wie bei der PBS. Export::Tabular::Events::List dafür verwenden, dann kommen die gewünschten Felder raus.
- [x] Pro Kanton (Group::State) ein Unter-Menüpunkt "Lager aus xy"
  - [x] Zugänglich / sichtbar für die Rollen Coach und GroupAdmin in Gruppentyp Group::State
  - [x] Zugänglich / sichtbar für die Rollen Leader und GroupAdmin in Gruppentyp Group::StateAgency
  - [x] Natürlich soll z.B. eine Rolle im Kanton Luzern nur Zugriff auf "Lager aus Luzern" geben
  - [x] Zeigt eine Liste von allen Lagern von Gruppen des Kantons, welche im aktuellen Kalenderjahr stattfinden (mind. 1 event_date muss überschneiden mit diesem Zeitraum). Ungefähres Beispiel für Query siehe TechSpec
  - [x] Lager die das Flag "Sichtbar für die ganze Datenbank" gesetzt haben, sollen zusätzlich auch sichtbar sein
  - [x] CSV Export der angezeigten Daten, Button sollte so aussehen wie bei der PBS. Export::Tabular::Events::List dafür verwenden, dann kommen die gewünschten Felder raus.

**Comment by richardjubla** [comment]
**User-Story**
>Als Bulei Mensch (Aufgabe Kommunikation, Krisentelefon, etc.) möchte ich in der Datenbank eine Übersicht aller aktiven oder geplanten Lager haben. 
Kantonsleitungen oder Coaches sollten die Lager ihrer Kantone (Ebenen) einsehen können. 


**Aspekte**
- Ansicht "Lager" -> Weshalb ist diese Ansicht in der PBS Datenbank sichtbar und nicht bei der Jubla Datenbank? (Die Idee ist, diese Ansicht/Modul für Benutzer der Ebene Verband (und Kantone) zu aktivieren. 
- Bitte die Sichtbarkeit der Lager abhängig der Option "Anlass ist für die ganze Datenbank sichtbar" (er)klären. Ich denke, dass die Ansicht Lager diese Option ignorieren darf. In der MiData  wird die Sichtbarkeit wie folgt beschrieben: _"Dabei werden nur Lager berücksichtigt, welche eingereicht wurden und die nicht abgesagt sind._
- Bitte den Filter-Zeitraum (er)klären. Ganze Schweiz (drei Wochen), einzelne Kantone (ganzes Jahr). Wenn der Export (..de/list_all_camps.csv) alle Daten beinhaltet, ist der Filter-Zeitraum OK


Definition of Done 
- Übersicht aller Lager für den Sommer 2022
- Ansicht/Modul "Lager" in der Datenbank für bestimmte Rollen/Ebenen sichtbar

![image](https://user-images.githubusercontent.com/95908537/176895537-a0dc7548-b33a-4051-977c-931bbb1389a9.png)

**Comment by richardjubla** [comment]
**Präzisierungen der Tech-Spec**

> Lagerübersicht links in der Übersicht soll für alle Benutzer der Ebene Verband und Kantone aktiviert sein implementiert werden.

Nein, wir wollen hier eher restriktiv unterwegs sein. 
Lager ganze Schweiz:  Ebene: Jungwacht Blauring Schweiz (ohne Unterebenen)
Kanton: Ebene Kanton + Arbeitsstellen
_Hier haben wir wohl das Problem, dass wir nicht generelle Regeln definieren können? Nur die oberste Ebene zu berechtigen genügt nicht da wir hier "nur" die Coaches verwalten. In jedem Kanton hat es eine individuelle Arbeitsstellen mit dem Gruppentyp "Arbeitsstelle". Die Leitung der Arbeitsstelle soll alle Lager in ihrem Kanton sehen können._


> Spezifizieren welche Rollen die Übersicht aktiviert hat und die Auswertung vornehmen kann.

Rolle: _IT Support_ auf Ebene Verband soll zugriff auf alle Lager haben + Rolle "Mitglied" auf Ebene Verband in Gruppentyp
Bundesleitung
Rolle _Leitung_ auf der Ebene Kanton in Gruppentyp "Arbeitsstelle"

Export nach Möglichkeit nur für  Rolle: _IT Support_ auf Ebene Verband

_Ziel: Alle Lager in der ganzen Schweiz sollen nur wenige, ausgewählte Personen sehen. Auf Kantonaler Ebene sollen sicher die Arbeitsstellen und evtl. Coaches ihren eigenen Kanton sehen können. Bitte nach möglichst einfachen, strikten Regeln für die Berechtigungen suchen. Bei bedarf weiter von uns präzisieren lassen._ 


> Spezifizieren: Dürfen die Kantonsleitenden ebenfalls schweizweit sämtliche Lager auflisten, oder nur die aus ihrem Kanton? Falls nur aus ihrem Kanton, ist für euch relevant ob ein Lager in meinem Kanton organisiert wird, oder ob ein Lager in meinem Kanton stattfindet?

"Kantonsleitende" sollen höchstens ihren eigenen Kanton sehen. Es spielt keine Rolle, wo das Lager stattfindet. Lager aus anderen Kantonen im eigenen Kanton müssen NICHT sichtbar sein.

> Spezifizieren: Sind für diese Personen sämtliche Lager sichtbar, unabhängig der Option "Anlass ist für die ganze Datenbank sichtbar"?
Nein, die Option soll respektiert werden. 
Die Ebene "Jungwacht Blauring Schweiz" sieht onehin alles. Die jeweiligen Kantone (Kantons-Ebenen) die Lager in ihren Kantonen ebenfalls. 

_Ich denke diese Frage ist obsolet, da es onehin keine übergreifende Sichtbarkeit geben wird. Selbst ein Lager welches in der ganzen Datenbank sichtbar geschaltet wird, wird lediglich vom eigenen Kanton oder der Verbandsleitung gesehen._

Wunsch: Die Option "Anlass ist für die ganze Datenbank sichtbar" bei einem neuen Datensatz (neues Lager erstellen) per Standard abwählen. (Aktuell ist es per Standard aktiv)

> Spezifizieren: Die Jubla hat aktuell keinen Lagerstatus. Implementieren? Welche Stati sollen ersichtlich sein / ausgewertet werden?
Nein, kein Lagerstatus implementieren.


> Spezifizieren: Filterzeitraum: Muss dieser frei gewählt werden können? Müssen vergangene Lager angezeigt werden können? Fixer Zeitraum?

Zeitraum ganze Schweiz: 4 Wochen (fix)
Zeitraum Kantone: ganzes Jahr
(vergangene Lager anzeigen, Verhalten weitgehend analog von PBS)


> Spezifizieren: Welche Daten müssten alle ausgewertet werden? Analog Export der PBS? Müssen die genauen Teilnehmenden der Lager ersichtlich sein, oder nur die Gesamtanzahl der Teilnehmenden? Analog Ticket #364212?
Ja, Analog Ticket #364212?
Im Export dürfen lediglich die Gesamtanzahl der Teilnehmenden ersichtlich sein. Der Export darf lediglich "öffentliche", der Rolle/Berechtigung ohnehin zugängliche Daten enthalten.

**Comment by carlobeltrame** [comment]
Hallo @richardjubla, bei der Formatierung deiner Antwort zu den Rollen die das dürfen ist dir wohl etwas durcheinander geraten. Könntest du diese Antwort nochmals neu formatieren? Zum Beispiel macht *"Mitglied" auf Ebene Verband in Gruppentyp
Bundesleitung"* keinen Sinn oder? Auf der Ebene Verband gibts keinen Gruppentyp Bundesleitung.

**Comment by richardjubla** [comment]
> Hallo @richardjubla, bei der Formatierung deiner Antwort zu den Rollen die das dürfen ist dir wohl etwas durcheinander geraten. Könntest du diese Antwort nochmals neu formatieren? Zum Beispiel macht _"Mitglied" auf Ebene Verband in Gruppentyp Bundesleitung_ keinen Sinn oder? Auf der Ebene Verband gibts keinen Gruppentyp Bundesleitung.


Gruppentyp: Bundesleitung
![image](https://user-images.githubusercontent.com/95908537/188183135-15701d13-5eb2-41b1-9c27-063d6a06227e.png)

Ich möchte allen Mitarbeitenden der Bundesleitung (Bulei) (Geschäftsstelle von Jungwacht Blauring Schweiz) die Berechtigung geben. Diese sind in der Gruppe https://db.jubla.ch/groups/2/

**Comment by carlobeltrame** [comment]
Aha, sorry, mein Fehler. Verband ist natürlich der Dachverband, da gibts logischerweise diesen Gruppentyp. Ich hatte unter Verband "Kantonalverband" verstanden, aber die heissen ja bei euch nicht so. Jetzt ist alles klar, merci.

**Comment by richardjubla** [comment]
Fehler: Person hat das Modul "Lager" sichtbar, kann es aber nicht aufrufen. 
![weristwoimlager](https://user-images.githubusercontent.com/95908537/189895243-5ec1eefb-99fe-4e6e-a069-98b425677614.gif)

**Comment by TheWalkingLeek** [comment]
Hoi @richardjubla 
Merci fürs Testen und melden, habs mitlerweile gefixt. Ist auch bereits auf Integration

**Comment by richardjubla** [comment]
Als  Rolle "Mitglied" auf Ebene Verband in Gruppentyp Bundesleitung sollte ich "Alle Lager" sehen können. Dies ist aber nicht der Fall
![image](https://user-images.githubusercontent.com/95908537/190086106-416a5091-3d1e-4bd7-bea9-3345b1844444.png)
![image](https://user-images.githubusercontent.com/95908537/190085225-eb08fced-726a-4e8b-9f90-b10f082ce1b8.png)


Als Coach kann ich Lager im eigenen Kanton sehen:
![image](https://user-images.githubusercontent.com/95908537/190085513-f2b3fc52-da5c-4588-9307-9597f9554aab.png)

Die Zeiträume und zusätzlichen Filter-Möglichkeiten sehe ich nicht. Wie genau wurde die genannten Funktionen umgesetzt?
Konkret: _vergangene Lager anzeigen, Verhalten weitgehend analog von PBS_

**Comment by ThomasEllenberger** [comment]
Hey @richardjubla .
Ich habe mir das soeben nochmals angeschaut und meines Erachtens funktioniert der Filter wie oben spezifiziert.

> 
> > Spezifizieren: Filterzeitraum: Muss dieser frei gewählt werden können? Müssen vergangene Lager angezeigt werden können? Fixer Zeitraum?
> 
> Zeitraum ganze Schweiz: 4 Wochen (fix) Zeitraum Kantone: ganzes Jahr (vergangene Lager anzeigen, Verhalten weitgehend analog von PBS)
> 
Personen welche eine Rolle auf der Jubla Schweiz Ebene haben sehen alle Lager in den nächsten 4 Wochen (28 Tage) von der ganzen Schweiz.
Personen welche nur eine Rolle in einem Kantonalverband haben sehen sämtliche Lager ihres Kantons vom aktuellen Kallenderjahr. Vergangene und auch solche welche mehr als 4 Wochen in der Zukunft liegen.

Wäre das Bedürfniss hier ein anderes?

**Comment by richardjubla** [comment]
> Wäre das Bedürfniss hier ein anderes?
(evtl. sind Aussagen Verwirrend oder Unpräzise, ich muss noch genauer Herausfinden was genau umgesetzt weurde)


- Aktuell kann ich auf der test.db nicht alle Lager sehen, wenn ich eine Rolle in einem Kantonalverband habe
- Auf Ebene Kantonalverband wäre es (analog PBS) gut, auch die  "Lager Kanton xy" zu haben
- Die Zeitachse und [Hilfstext ](https://github.com/hitobito/hitobito_pbs/blob/e48e8ceaddc348dcacde0805eb9bc6d75e493546/config/locales/views.pbs.de.yml) wurde nicht übernommen (ist für das gesteckte Ziel ok, wurde aber von uns im Bereich Zeitraum Kantone anders formuliert)

**Comment by ThomasEllenberger** [comment]
Als erklärung für die User soll bei der Ansicht der Lager ein Text hardcodiert werden.
Siehe vergleichbarer Text bei der PBS:
![image](https://user-images.githubusercontent.com/100761305/190609701-2c11ebf2-f9ca-4f6a-8eda-eed9f5527e0b.png)


Text bei Ansicht Lager der ganzen Schweiz:
"Alle Lager, welche aktuell oder in den nächsten vier Wochen durchgeführt werden."

Text bei Ansicht der Lager eines einzelnen Kantons:
"Alle Lager, welche innerhalb des Kantonalverbands in diesem Kalenderjahr durchgeführt werden."

**Comment by richardjubla** [comment]
@ThomasEllenberger
Wir sind mit Testen durch. Es gab keine zusätzlichen Rückmeldungen.
Offen: https://github.com/hitobito/hitobito/issues/1758#issuecomment-1247951790

**Comment by richardjubla** [comment]
@ThomasEllenberger 
Wir haben besprochen, dass der Hilfstext noch korrigiert wird (oder von dir noch eine Rückmeldung dazu kommt). Ist das korrekt? Soll ich jeweils ein neues (Sub-)Isuue erstellen, damit offene/geschlossene issues nicht verwirren?
