### ISSUE TITLE
EVENTS: Fehlende Sprache

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#1761]
### Aktuelles Verhalten

Als Person, die sich über einen externen Link für einen Event anmelden möchte, erhalte ich die Fehlermeldung "Sprache nicht ausgefüllt".
Das Problem tritt bei allen Kunden auf, welche die Korrespondenzsprachen bereits vor der Umsetzung im Core verwendet  haben.
Der DSJ hat noch das `correspondence_language` Feld auf der Person, und daher nicht das geteilte `language` Feld das wir inzwischen im Core haben. Es ist dieses Feld das auf dem Formular für externe Registrierung fehlt (wenn ich angebe dass ich noch keinen Account habe)

### Gewünschtes Verhalten

Das Anmelden für Events über einen externen Link soll wieder möglich sein.
Bei der Anmeldung wird nach der Korrespondenzsprache gefragt.

### Schritte zu reproduzieren

- Event erstellen und für externe Anmeldungen zulassen.
- Vie externem Link anmelden und "Du hast noch kein Login?" wählen (BSP: https://dsj.puzzle.ch/de/groups/54/public_events/992)
- Formular ausfüllen, "Speichern" anklicken -> Fehlermeldung erscheint.
![image](https://user-images.githubusercontent.com/100761305/173004562-18731de5-cdfb-42e8-a288-6bceba6b6059.png)

### Wann ist der Fehler aufgetreten?

01.04.2022

### hitobito version

1.26.45

### Organisation

DSJ

### Screenshots, weiterer Kontext

![image](https://user-images.githubusercontent.com/69250571/172873350-46a3afb1-405e-48e7-b422-420e4e3efdf3.png)
![image](https://user-images.githubusercontent.com/69250571/172873429-1503c361-74a8-4a64-97e3-41518daeb64e.png)

# ToDo

- [ ] Problem reproduzieren mit DSJ wagon
- [ ] `correspondence_language` Feld durch `language` Feld ersetzen
  - neue db migration im DSJ wagon
- [ ] externen Login-Link testen

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/683d15499544c9793b2790fcea70b0b793f0b633/app/controllers/people_controller.rb#L24
- https://github.com/hitobito/hitobito/blob/bc5146690819941d84c5c5f41a914f83acf0c283/config/initializers/person_language.rb

**Comment by TheWalkingLeek** [comment]
Fehler wurde behoben indem DSJ auf das Core Korrespondenzsprachen Feature umgestellt wurde: https://github.com/hitobito/hitobito_dsj/pull/16
Zusätzlich wurde die Sprache ins Event Anmeldungsformular aufgenommen: https://github.com/hitobito/hitobito/commit/21d875327c71974f046801dea08a0c87b22b5e1f
