### ISSUE TITLE
Security Overview - Abschliessen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1762]
PR #1688  wurde von @Michael-Schaer eröffnet und bereits von @TheWalkingLeek reviewed.
Noch offen ist das Erstellen neuer Specs.

# ToDo

- [x] Testen, dass das Passwort-Reset Mail an alle Adressen der betroffenen Person geht
- [x] Testen dass der Tab nur mit Update-Berechtigung sichtbar ist
- [x] Specs hinzufügen
- [x] ggf. CHANGELOG-Eintrag erstellen

**Comment by ThomasEllenberger** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito/1762?planning-poker) with ZenHub @kronn @TheWalkingLeek
