### ISSUE TITLE
INVOICE: Suche nach Firma in Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1773]
Als Rechnungssteller
möchte ich eine Rechnung finden, welche an einer Firma geschickt wurde.

Die Suchfunktion innerhalb der Rechnungen gibt keine Resultate für Firmen zurück. Personen werden gefunden.

# Mockup

**Rechnungen:**
![image](https://user-images.githubusercontent.com/9592347/177317980-6c511fc7-110a-4db2-949e-5a5691b31867.png)

---
**Suche nach Firma "BLS AG"**

![image](https://user-images.githubusercontent.com/9592347/177318003-9489075f-7428-4cb4-9218-f2c950706613.png)

---

# Tech-Spec

- Gemeint ist das Textfeld "Firmenname" (company_name) auf Person, welches auch durchsuchbar sein soll
- Vorerst ignorieren wir die Checkbox "company". Das bedeutet, wenn jemand die Checkbox nicht aktiviert hat, aber sowohl einen normalen Namen wie auch einen Firmennamen eingetragen hat, dann wird in der Tabelle der normale Name angezeigt, aber der Firmenname ist trotzdem noch durchsuchbar. Also dann könnte man Rechnungen mit Empfänger "Carlo Beltrame" auch mit einer Suche nach "Puzzle" finden. Wir gehen im Moment mal davon aus dass das okay ist, bis sich jemand darüber beklagt.

# ToDo

- [x] In [InvoicesController#search_columns](https://github.com/hitobito/hitobito/blob/master/app/controllers/invoices_controller.rb#L23..L24) die Spalte `people.company_name` einfügen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
