### ISSUE TITLE
EVENTS: Verbesserungen Externe Anmeldungen

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito#1775]
Als Eventverantwortliche*r
möchte ich den Anmeldungsprozess bei externen Anmeldungen für Events vereinfachen
um die Absprungsrate zu minimieren.

Neu soll:
* Optimierung Übersichtsseite
    * alles auf einer Seite und untereinander
    * Kursinfo (Allgemein) und Anmeldedaten (optisch) zusammenführen.
      * alles im grauen Block
      * "Anmeldung" vor das Login verschieben
    * leere felder ausblenden
    * anzahl anmeldungen
        * ausblenden wenn keine maximalteilnehmer festgelegt
        * anzahl freie Plätze anzeigen (statt anzahl anmeldungen) (OPTIONAL)
    * externer link ausblenden

# Mockup

### Ist:
![image](https://user-images.githubusercontent.com/100761305/178276697-84a3e94b-b92f-46fc-8b10-f3a7c3439d4d.png)
![image](https://user-images.githubusercontent.com/100761305/178701950-0eff47ca-8d25-4b0e-a717-7cf9df9bff29.png)

### Soll:
Ansicht eines Loginscreens von einem Kurs bei welchem nur die notwendigsten Daten ausgefüllt wurden. Alle leeren Felder wurden ausgeblendet.
![image](https://user-images.githubusercontent.com/17568539/177544158-a12a1bd7-6a4b-4945-a2c4-e2509f677f28.png)

Ansicht eines Loginscreens von einem Kurs bei welchem nur die notwendigsten Daten ausgefüllt wurden. Alle leeren Felder wurden ausgeblendet.

# Tech-Spec

- Der Abschnitt «Ohne Login» in der neuen Maske erscheint nur, wenn auf diesem Event das Flag
«Externe Anmeldungen» gesetzt ist.
- Die gleiche maske wird auch für interne Anlässe umgesetzt.
- API welche für die Anzeige von Anlässen auf Websiten verwendet werden sollen nicht verändert werden.

# ToDo

- [x] View/Controller anpassen
- [x] ggf. Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Auch von Seite des Cevi sieht das vielversprechend aus. Uns sind im Aktuellen Ablauf noch unnötige Klicks/Schritte aufgefallen, ich nehme an ihr achtet bei der Umsetzung darauf diese zu vermeiden.

Ausserdem ist nicht eindeutig, wie in der Anzeige der Plätze die noch nicht zugewiesenen Anmeldungen behandelt werden sollten. Spontan würde ich die als "Angemeldet" zählen.

**Comment by ThomasEllenberger** [comment]
Inputs vom Efficency CLub:
- Der Abschnitt «Ohne Login» in der neuen Maske erscheint nur, wenn auf diesem Event das Flag
«Externe Anmeldungen» gesetzt ist (ist implizit schon klar, aber ich wollte das erwähnen)
- Die gleiche Maske könnte somit auch für interne Anmeldungen verwendet werden. Hinweis: dies ist so oder so bei uns auf der Homepage ersichtlich, weil wir das publishen. Erst beim Anmelden weiss man, ob es intern oder extern ist (Anzeige mit Login/ohne Login)
- Die Anzeige der Anzahl Anmeldungen und optional Max-Teilnehmer haben wir auf der Webseite auch. Anzahl freie Plätze macht dann nur Sinn, wenn es ein Kontigent hat. Ich möchte noch darauf hinweisen, dass wir[ https://github.com/hitobito/hitobito/issues/1623](https://github.com/hitobito/hitobito/issues/1623) erfasst haben, was Impact auf der Anzeige von freien Plätzen hat.
- Beachten, dass das API, dass wir für die Webseite verwenden, nicht tangiert wird. Wenn doch, müsste wir das mit Comvation abgleichen

**Comment by betsim** [comment]
Der SBV unterstützt dies auch! Insbesondere das Ausblenden der leeren Felder ist uns wichtig 👍 

Wir möchten dieses Feature auch für Konzerte nutzen, d.h. für Anlässe, für welche man sich weder anmelden kann noch muss --> es sollte möglich sein, Events zu erfassen, zu denen man sich auch nicht anmelden kann (Anmeldefrist-Datum in der Vergangenheit erfassen ist kein adäquater Workaround, weil dieses Datum dann angezeigt wird, was wir nicht wollen).

**Comment by richardjubla** [comment]
**User-Management für Event-Teilnehmende**
Wo landen neue User, die sich für einen Event angemeldet haben? In der Gruppe "ohne Rollen" auf der Ebene, in welcher der Anlass angelegt wurde? Von wem und wie können die User verwaltet werden?


_Ich frage aus dem Grund, um herauszufinden wie solche User danach verwaltet werden können. Bei einem Grossanlass (Konzert) oder einer Werbeveranstaltung sollten/könnten die User danach auch in gewissen Gruppen zugeordnet werden können. (Evtl. sind auch Rechnungen etc. interessant, den Use-Case kenne ich aber nicht)
Events und externe Anmeldungen können zu Doubletten und/oder unverwalteten Datensätzen führen weil die Sicht/Rollen nicht im Einklang sind._

**Comment by ThomasEllenberger** [comment]
> Der SBV unterstützt dies auch! Insbesondere das Ausblenden der leeren Felder ist uns wichtig +1
> 
> Wir möchten dieses Feature auch für Konzerte nutzen, d.h. für Anlässe, für welche man sich weder anmelden kann noch muss --> es sollte möglich sein, Events zu erfassen, zu denen man sich auch nicht anmelden kann (Anmeldefrist-Datum in der Vergangenheit erfassen ist kein adäquater Workaround, weil dieses Datum dann angezeigt wird, was wir nicht wollen).

Anlässe mit einem öffentlichen Link, kommen meines Wissens immer mit einem Anmelden Button. Dies scheint eine ziemlich spezifische Anforderung vom SBV zu sein. Sollte dies etwas sein was ihr umsetzen möchtet, würden wir hierzu ein neues Issue eröffnen.

**Comment by betsim** [comment]
> > Der SBV unterstützt dies auch! Insbesondere das Ausblenden der leeren Felder ist uns wichtig +1
> > Wir möchten dieses Feature auch für Konzerte nutzen, d.h. für Anlässe, für welche man sich weder anmelden kann noch muss --> es sollte möglich sein, Events zu erfassen, zu denen man sich auch nicht anmelden kann (Anmeldefrist-Datum in der Vergangenheit erfassen ist kein adäquater Workaround, weil dieses Datum dann angezeigt wird, was wir nicht wollen).
> 
> Anlässe mit einem öffentlichen Link, kommen meines Wissens immer mit einem Anmelden Button. Dies scheint eine ziemlich spezifische Anforderung vom SBV zu sein. Sollte dies etwas sein was ihr umsetzen möchtet, würden wir hierzu ein neues Issue eröffnen.

Events, für welche keine Anmeldung möglich sein sollen, werden auch keinen öffentlichen Link haben. Die öffentliche Publikation der Veranstaltungen wird eher über die API gelöst werden.

**Comment by ThomasEllenberger** [comment]
> 



> 

fg

> **User-Management für Event-Teilnehmende** Wo landen neue User, die sich für einen Event angemeldet haben? In der Gruppe "ohne Rollen" auf der Ebene, in welcher der Anlass angelegt wurde? Von wem und wie können die User verwaltet werden?
> 
> _Ich frage aus dem Grund, um herauszufinden wie solche User danach verwaltet werden können. Bei einem Grossanlass (Konzert) oder einer Werbeveranstaltung sollten/könnten die User danach auch in gewissen Gruppen zugeordnet werden können. (Evtl. sind auch Rechnungen etc. interessant, den Use-Case kenne ich aber nicht) Events und externe Anmeldungen können zu Doubletten und/oder unverwalteten Datensätzen führen weil die Sicht/Rollen nicht im Einklang sind._

Neue User welche sich über einen externen Link auf den Anlass anmelden erhalten nur eine Rolle auf dem Anlass selbst, als "Teilnehmer/in". Diese können anschliessend weiterverwendet und in anderen Gruppen hinzugefügt werden.

**Comment by richardjubla** [comment]
@ThomasEllenberger 
> Neue User welche sich über einen externen Link auf den Anlass anmelden erhalten nur eine Rolle auf dem Anlass selbst, als "Teilnehmer/in". Diese können anschliessend weiterverwendet und in anderen Gruppen hinzugefügt werden.

Diese Aussage ist für die ([Version 1.30.20](https://jubla.puzzle.ch/changelog)) nicht korrekt. Ein User welcher sich über einen externen Link auf einen Anlass anmeldet, erstellt ein Profil (mit aktivem Login, aber ohne gesetztes Passwort) und einer Rolle (Extern) auf der Ebene/Gruppe des Event. Die Option "Externe Registrierung" kann dabei aktiv oder auch deaktiviert sein. 

![image](https://github.com/hitobito/hitobito/assets/95908537/f55a50c8-d81d-4343-8a5b-f8db5e73ae09)
![image](https://github.com/hitobito/hitobito/assets/95908537/936e9880-d9fd-4238-af98-257924316d7a)
![image](https://github.com/hitobito/hitobito/assets/95908537/59248c29-c15e-47b0-b018-1a2efbd531b5)
![image](https://github.com/hitobito/hitobito/assets/95908537/fede0ee1-c72c-43f1-b467-442403931fc5)

Die Profile sind demnach direkt in der Ebene/Gruppe und können/müssen dort bewirtschaftet werden. Das ist für mich "soweit ok", führt aber zu folgenden Herausforderungen:
- Das Profil ist aktiv, der User hat aber kein Login (nach Timeout muss er sich Anmelden und kann dies nur über PW vergessen tun)
- Das Profil hat zugriff auf die Suchfunktion für andere Profile

**Comment by carlobeltrame** [comment]
> Diese Aussage ist für die ([Version 1.30.20](https://jubla.puzzle.ch/changelog)) nicht korrekt. Ein User welcher sich über einen externen Link auf einen Anlass anmeldet, erstellt ein Profil (mit aktivem Login, aber ohne gesetztes Passwort) und einer Rolle (Extern) auf der Ebene/Gruppe des Event. Die Option "Externe Registrierung" kann dabei aktiv oder auch deaktiviert sein.

Disclaimer: Dass die Rolle "Extern" automatisch angelegt wird, ist ein Jubla-spezifisches Feature, und gilt nicht für den SBV, efficiency club, etc.

Dass diese Personen die Suche benutzen können gilt somit ebenfalls nur für die Jubla (könnten wir seit neuem bei Bedarf ausschalten). Sich selber ein Passwort setzen können aber extern registrierte Personen bei allen Wagons, auch ohne Rolle.
