### ISSUE TITLE
INVOICE: Export nicht zugewiesene Zahlungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1789]
Als Kassier
möchte ich wissen, welche Zahlungen (via EBICS) nicht einer Rechnung zugeordnet werden könne 
um die manuelle Nacharbeit zu erledigen.

Ziel ist es eine Liste der über die Schnittstelle EBICS nicht zugeordneten Zahlungseingänge im Hitobito über einen definierten Zeitraum zu haben. Diese Liste soll regelmässig (ca Monatlich) erstellt werden können. Daher im ersten Schritt würde ein entsprechendes Script ausreichen.

Beim manuellen Import von camt054 sieht der Kunde, welche Zahlungen nicht zugewiesen werden konnten.

In diesem Zusammenhang #1472 und #1494 beachten.

Bezieht sich auf Kundenanfrage: https://help.puzzle.ch/#ticket/zoom/4259

# Tech-Spec

- Es soll nachvollziehbar sein, welche Zahlungen übertragen wurden
- nicht zugeordnete Zahlungen sollen in Hitobito bekannt bleiben.
- EBICS liefert Daten standardmässig nur einmal
- Wir müssen neu alle Payments (Zahlungen von EBICS) persistieren, ggf. keine Rechnung verlinken. Status hinterlegen, bisher werden nur erfolgreich zugeordnete Zahlungen persistiert.
- Export sollte eine CSV-Datei werden

# ToDo

- [x] Migration erstellen
    - [x] `payments status enum`
- [x] EBICS-Import anpassen
- [x] Rake-Task für Export erstellen
- [x] Specs schreiben
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
