### ISSUE TITLE
EVENTS: Beschreibungsfeld als Richtext

### ISSUE THREAD

**Issue by binggelivo** [hitobito/hitobito#1791]
# Ausgangslage

Heute ist `Event#description` ein einfaches `text`-Feld. Zeilenumbrüche und einfache Formatierungen werden nicht sauber gerendert. User möchten Anlässe, Lager und Kurse mit formatiertem Text (mindestens einfaches Markdown/Rich Text) beschreiben können.

# Anforderungen

- `Event#description` soll als Rich-Text-Feld (ActionText/Trix) verwaltet werden können.
- Mehrsprachigkeit (Globalize) soll wie bei `CustomContent#body` mit `translates_rich_text :description` umgesetzt werden.
- Das Feature "Inline Attachments" von ActionText soll deaktiviert werden.
- Das Formular für Events soll ein `rich_text_area` für `description` verwenden und Mehrsprachigkeit unterstützen.
- In der JSON-API (`EventResource`) soll `description` weiterhin den Plain-Text liefern ohne die Rich-Text Formatierung. Ein neues `description_html` soll das originale HTML zurückgeben.
- Bestehende Daten in `event_translations.description` müssen in `action_text_rich_texts` migriert und die alte Spalte entfernt werden.

# Offene Fragen

- Welche Stellen rendern `description` heute und müssen auf `to_s` bzw. `to_plain_text` umgestellt werden (PDF, Mails, Anzeige)?

# Tech-Spec

- Implementierung im `Core`
- `Event` Model anpassen:
  - `translates_rich_text :description` ergänzen (statt `translates :description`)
  - Validierung ergänzen analog `CustomContent`: `no_attachments: true`
- Formularfeld in `app/views/events/_general_fields.html.haml` anpassen: `description` mit `labeled_rich_text_area` rendern
- JSON:Api Anpassung in `EventResource`
  - für `attribute :description` das Attribut als plain text formattieren: `@object.description.to_plain_text`
  - neues `attribute :description_html` mit dem Attribut als HTML: `@object.description.to_s`
- Migration: 
  - bestehende `event_translations.description` in `action_text_rich_texts` (Record `Event::Translation`, Name `description`) überführen
  - obsolete Spalte `description` aus `event_translations` entfernen.
- Prüfen, ob Event-Beschreibung in PDFs, Mailing-Listen oder sonstigen Exports genutzt wird.

# ToDo

- [ ] `Event` Model anpassen
- [ ] Formular View anpassen
- [ ] `EventResource` anpassen
- [ ] Migration erstellen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] bei Core-Änderungen alle Wagons durchtesten
- [ ] [DoD](https://github.com/hitobito/hitobito/blob/master/doc/developer/process/definition_of_done.md) geprüft und erfüllt?
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
Von welcher Beschreibung sprichst du? Und von welcher Organisation / welchem Dachverband bist du?

**Comment by binggelivo** [comment]
Hauptsächlich vom Beschreibungsfeld, bei den Anlässen, Lager, Kurse uws.

Der Dachverband wäre die Pfadi

**Comment by Michael-Schaer** [comment]
Hallo Binggelivo und merci für deine Rückmeldung. 

Bei den Anlässen haben wir einen Fehler, wobei die Zeilenumbrüche aktuell nicht gerendert werden. Du kannst den Status dieses Issues unter https://midata.statuspal.io/ prüfen. 

Für weitere Fragen, melde dich am besten bei dem*der PowerUser deines KVs. Falls du selber ein solcher bist, kannst du deine Anliegen auch gerne an die PBS melden. Ideen und Wünsche nehmen wir (das Team MiData und ich) gerne entgegen. Diese werden dann zusammen mit den PowerUser priorisiert und von uns beauftragt.

Der Weg über GitHub ist natürlich naheliegend. Vom Prozess her bin ich aber froh, wenn du trotzdem deine Ideen und Wünsche bei der PBS einbringst.
