### ISSUE TITLE
Neuer Wagon "hitobito_saas"

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1794]
Als Entwickler und Betriebler von hitobito.com
möchte ich einen dedizierten Wagon haben,
um dort alle für uns spezifischen Features unterbringen zu können.

# Tech-Spec

- Struktur von `hitobito_generic`
- Künftig der Ort für Anpassungen die unser OpenShift oder unsere Strukturen betreffen

# ToDo

- Variante "Generic als Dependency"
  - [ ] `hitobito_generic` als Dependency 
  - [ ] Erweiterbarkeit prüfen
- Variante "Generic kopieren"
  - [ ] `hitobito_generic` kopieren
  - [ ] Alle Referenzen von Generic zu Saas umstellen
- [ ] `hitobito_tenants` als Dependency
- [ ] transifex-Projekt anlegen
- [ ] Composition-Repo anpassen

**Comment by mtnstar** [comment]
merged into #1901
