### ISSUE TITLE
Auto-Complete

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1797]
Als Person, die Rollen verteilt und dafür Personen sucht,
möchte ich wissen, ob noch weitere Ergebnisse vorhanden sind,
um meine Suche gegebenenfalls verbessern zu können

Neu soll daher am Ende der Liste noch ein Indikator (drei Punkte oder so) erscheinen, wenn mehr als 10 Ergebnisse vorhanden sind.

# Tech-Spec

- visueller Hinweis auf weitere Ergebnisse
- trotzdem wenige Daten herausgeben, da die Suche recht weit greift
- Betrifft Personensuche, theoretisch aber auch Firmensuche oder Gruppensuchen

# ToDo

- [ ] View anpassen: Indikator im Popup anzeigen
- [ ] Controller anpassen: Notwendigkeit des Indikators zurückgeben
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
