### ISSUE TITLE
PERSON: Hifetext zu Haushalt

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#1804]
Als administrierende Person in Hitobito 
wünsche ich mir einen Hilfetext zum Feature "Wohnt im Haushalt mit"
um schneller zu verstehen, wie Personen aus einem Haushalt entfernt werden können.

Neu soll es eine Infobox geben, welche die Vorgehensweise beschreibt, wie eine Person aus einem Haushalt zu entfernen ist.

# Tech-Spec

- Es soll eine Infobox zum Haushalt-Feature geben.
- Die Infobox erklärt wie eine Person entfernt wird.
- Möglicher Hilfetext:
Um eine Person aus dem Haushalt zu entfernen, kann bei dieser Person die Option "Wohnt im Haushalt mit" entfernt werden.

# ToDo

- [ ] Infobox
- [ ] Hilfetext verfassen und einfügen.
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
