### ISSUE TITLE
EVENTS: Kantonsübergreifende Sichtbarkeit von Kursen und Anlässen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1813]
Als Verwalter von Anlässen
möchte ich das global sichtbare Anlässe besser sichtbar sind,
um dies an die Erwartungen der Organisation anzupassen.

Neu soll das aktuelle Verhalten nur noch für die PBS gelten. Für die Jubla ist ein ähnliches Verhalten gewünscht, jedoch sollen hier alle Leitungsfunktionen die Kurse sehen. Für den SBV wäre es sinnvoll, wenn Anlässe, bei denen das so konfiguriert ist, direkt über die Hauptnavigation "Anlässe" sichtbar wären.

Anforderung PBS:

> [Es ist] gewünscht, dass Teilnehmerinnen sich nicht selber für Kurse anmelden, die nicht im eigenen Kanton stattfinden. Stattdessen sollen die Teilnehmerinnen jeweils die [Ausbildungsverantwortlichen] des eigenen Kantons informieren, diese verteilen dann die Personen auf (ausserkantonale) Kurse.

- https://github.com/hitobito/hitobito/issues/1757#issuecomment-1148363938
- #1047

Anforderung Jubla:

> Die Kursübersicht für die Jubla soll angepasst werden: Alle Personen ab Ebene Leitungsperson sollen die Kursübersicht analog einer Abteilungsleitung dargestellt erhalten; sprich: Standardmässig alle Ebenen mit Involvierung (die eigene Ebene und die darüberliegenden) anzeigen lassen; aber als Option mit dem drop-down-Menü auch alle anderen Kursorganisatoren auswählen können – oder durch Klick auf «Alle Gruppen» direkt alle Kurse anzeigen lassen.

> Um in der Übersicht trotzdem noch klar zu sehen, von welchem Kanton der Kurs organisiert wird, sollte als weitere Spalte (z.B. zwischen Datum und Anmeldestand) der Hauptorganisator (= Kanton, in welchem der Kurs erfasst wurde) sichtbar sein, damit sie sehen, in welchem Kanton sie sich anmelden.

- https://github.com/hitobito/hitobito/issues/1757#issuecomment-1167631251

![](https://user-images.githubusercontent.com/95908537/175995936-6a78f53a-6888-4bde-91b5-a1b2b87ca36b.png)

Anforderung SBV:

> Wir erwarten spontan, dass [Anlässe, die mit "Anlass ist für die ganze Datenbank sichtbar" markiert sind] allen Benutzern von hitobito angezeigt werden, wenn diese im Menü links unter Anlässe schauen. Dies ist jedoch nicht der Fall. (Beispiel-Event: https://sbv.puzzle.ch/de/groups/86/events/61 ist nicht sichtbar für die Person https://sbv.puzzle.ch/de/groups/1592/people/16366.html)

- https://github.com/hitobito/hitobito/issues/1793

# Tech-Spec

- Grundsätzlich sollten Anlässe global sichtbar gemacht werden können
- Für Kurse gelten besonderen Regeln, die im Wagon untergebracht werden
- für die PBS muss das bisherige Verhalten gleich bleiben

# ToDo

- [ ] Kurssichtbarkeit
  - [ ] Anforderungen PBS behalten
  - [ ] Anforderungen Jubla umsetzen
- [ ] Sichtbarkeit von Anlässen
  - [ ] Anforderungen SBV nach Möglichkeit (Timebox 1h) für alle umsetzen
- [ ] Ability `EventAbility` anpassen
- [ ] ggf. View/Controller anpassen, um die Anlässe via Hauptnavigation sichtbar zu machen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
Hinweise/Präzisierung zur Sichtbarkeit für **alle Personen ab Ebene Leitungsperson**

Aus meiner Sicht wird der Kursfiler ab Ebene Leitungsperson verwendet. Kinder nehmen in der Regel an Events der Schar teil und benötigen den Kursfilter nicht. Alle möglichen Kursteilnehmenden sind "mindestens" Leitende in einer Schar.


![image](https://user-images.githubusercontent.com/95908537/185595696-ef800d55-4701-4455-8f11-f7c0cce52d02.png)

**Comment by ThomasEllenberger** [comment]
Nach Absprache mit @richardjubla sind wir zum folgenden Lösungsansatz gekommen:

- Sämtliche Personen welche irgendwo eine Leaderrolle haben, sollen in der Kursübersicht links beim Filter sämtliche Kursregionen/Kantone angezeigt haben und auswählen/nach diesen filtern können.
![image](https://user-images.githubusercontent.com/100761305/186694738-8bfc10db-4987-4e27-b1db-8169177520c5.png)
- Wählt man eine Region aus, sollen sämtliche Kurse dieser Region mit dem Flag "für ganze Datenbank sichtbar" angezeigt werden. (Kurse ohne dieses Flag werden nicht angezeigt, es sei denn ich bin Mitglied dieses Kantonalverbands (Sichtbarkeit wie bisher))
- Wird der Kursfilter auf "alle Gruppen" gestellt, sollen sämtliche Kurse mit dem Flag "für ganze Datenbank sichtbar" angezeigt werden.

Damit der Benutzer besser identifizieren kann wo der Kurs stattfindet und von wem dieser durchgeführt wird, soll in der Kursübersicht neu das Feld "Anmeldung an" ersichtlich sein. (Siehe Mockup von @richardjubla im vorhergegangenen Post.)

**Comment by richardjubla** [comment]
Eventuell ist das Wichtig:

Sowohl auf dem Test- wie auch auf dem Produktiv-System sind bei etlichen Gruppen das Land "Schweiz" nicht hinterlegt.
Es ist wohl bei der Anpassung der Sprachen (von 1. Sprache zu Übersetzungen) verloren gegangen. 
Dadurch ist die Zuweisung bzw. Berechtigung für Kurse gestört -> Kurse können nicht erstellt oder bearbeitet werden. Siehe auch: https://help.puzzle.ch/#ticket/zoom/5157 

Lösung: Gruppe bearbeiten, leeres Feld bei "Land" mit Schweiz füllen und abspeichern.

**Comment by richardjubla** [comment]
Bug: E500

https://jubla.puzzle.ch/list_courses?filter%5Bsince%5D=28.09.2022&filter%5Buntil%5D=28.09.2023&filter%5Bstates%5D%5B%5D=&filter%5Bstates%5D%5B%5D=created&filter%5Bstates%5D%5B%5D=confirmed&filter%5Bstates%5D%5B%5D=application_open&filter%5Bstates%5D%5B%5D=application_closed&filter%5Bstates%5D%5B%5D=assignment_closed&filter%5Bstates%5D%5B%5D=completed&filter%5Bstates%5D%5B%5D=closed&filter%5Bplaces_available%5D=0&filter%5Bgroup_ids%5D%5B%5D= 
![image](https://user-images.githubusercontent.com/95908537/192703903-d92dcf56-835b-4b53-97b5-4e7b2153f4e6.png)

Reproduzieren:
Alle "Veranstalter" löschen und auf "Suchen" klicken.

**Comment by carlobeltrame** [comment]
@richardjubla merci für die Meldung. Da das bisher nur bei der Jubla Integration auftritt und wir noch nicht wissen wo es genau verursacht wurde habe ich dafür ein neues Ticket #1861 erstellt.

**Comment by richardjubla** [comment]
Rückmeldung zur zusätzlichen Spalte im Kurs-Filter:

Wir haben nicht ganz genau spezifiziert, wie und welche Informationen in diese Spalte angezeigt werden. Aktuell wird im Testsystem die Komplette Adresse von "Anmeldung an" angezeigt:
![image](https://user-images.githubusercontent.com/95908537/192965138-39e74bf1-efa1-410b-821b-501bc82db245.png)

Anstelle der kompletten Adresse soll lediglich der «Name der Ebene» in der Spalte angezeigt werden.
(Anpassen: Nur die erste fette Zeile, den Rest der Adresse weglassen. So wie in der Diskussion um die Liste vorgeschlagen: https://github.com/hitobito/hitobito/issues/1813#issuecomment-1225663708 ) 
![image](https://user-images.githubusercontent.com/95908537/192970116-936ef94f-81e3-42da-8201-2a3a025148b1.png)

**Comment by richardjubla** [comment]
@ThomasEllenberger
Wir sind mit Testen durch. Es gab keine zusätzlichen Rückmeldungen.
Offen sind die zurückgemeldeten Punkte #1861 und https://github.com/hitobito/hitobito/issues/1813#issuecomment-1262165112

**Comment by richardjubla** [comment]
Auf [Version 1.30.20](https://jubla.puzzle.ch/changelog) erfolgreich getestet -> OK 

Die offenen Punkte wurden erledigt. Die Komplette Adresse von "Anmeldung an" wird mit einem Workaround gelöst in dem unsere Kursanbieter keine Adresse für ihre Ebene hinterlegen. Das Anzeigen von Adresse für einen Event-Anbieter scheint mir technisch weiterhin korrekt.
