### ISSUE TITLE
INVOICE: Validierung Rechnungseinstellung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1825]
Damit die QR Rechnung gültig ist, muss die Adresse "Einzahlung für" drei Zeile haben.

Betrifft folgendes Textfile:
![image](https://user-images.githubusercontent.com/9592347/187866211-718cbd5d-2adb-48fe-8c3c-364a5e21652b.png)

Da dies mit der QR Rechnung relevant ist, sollten wir dies im GUI validieren. Weitere Details https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf

# Mockup

# Tech-Spec

- Jede Zeile muss auch tatsächlich Text beihnalten! Leere Zeilen reichen nicht. Es sollten aber auch nicht vorige leere Zeilen akzeptiert werden

# ToDo

- [x] Validierung auf Model einfügen
  - [ ] Rechnung(-sbrief) erstellen Knopf bei invalider InvoiceConfig deaktivieren und mit Tooltip erklären
    - [x] Bei Dropdowns müssen basierend auf der verwendeten InvoiceConfig einzelne Punkte deaktiviert werden
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kronn** [comment]
Der Button "Zahlung erfassen" auf der Invoice-Liste müsste auch noch disabled mit passendem Tooltip angezeigt werden.
