### ISSUE TITLE
TECH: Nextcloud Plugin

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#1827]
Bisher gibt es keine Verknüpfung zwischen Hitobito und Nextcloud

Neu soll es möglich sein sich mit Benutzerdaten von Hitobito auf einer Nextcloudinstanz anzumelden.
Zudem sollten über die Rollen in Hitobito Berechtigungen auf Nextcloud vergeben werden können.
Bei der Lösung sollte auf die Erweiterbarkeit geachtet werden, da in Zukunft auch noch weitere Features wie das direkte Speichern von Rechnungen, Briefen, etc. aus Hitobito auf Nextcloud denkbar sind.
Im Rahmen von diesem Konzeption-Issue prüfen wir, ob bereits passende oder erweiterbare Nextcloud-Plugins existieren oder ob dieses von Grund auf selber entwickelt werden muss.

Timebox: 1PT

# ToDo

- [ ] Bereits existierende Nextcloud-Plugins prüfen.
- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

**Comment by richardjubla** [comment]
_Meine Persönliche Meinung dazu. Basierend auf der Interpretation der Jubla-Vision zur jubla.db._

Hitobito und Next-/OwnCloud können oder sollten gut über Schnittstellen [(OAuth](https://github.com/hitobito/hitobito/blob/master/doc/development/08_oauth.md#oauth-20)) verbunden werden können. 
Ich kann mir vorstellen und sehe Beispiele, dass diese Verbindung von vielen Organisationen/Vereinen gewünscht oder geschätzt wird. Die Situation mit SharePoint/(Teams), gDrive/Dropbox oder eben Nextcloud ist für viele ein Thema. Dokumente sollen einfach (kollaborativ) verwaltet, geteilt aber auch sicher und langfristig 

Die Berechtigungen könnten aus den Rollen in hitobito Abgeleitet werden, müssten aber zwingend (auch) in der Nextcloud-Instanz geregelt und verwaltet werden. "Die Lösung" ist demzufolge in Nextcloud und nicht in Hitobito umzusetzen.
Das Auslagern von Core-Services (Rechnungen/ "direktes speichern") in externen Speicher halte ich für einen strategischen Fehler, sollte sich Hitobito nicht zu 100% auf diese Infrastruktur verantwortlich und abhängig machen.

**Comment by kronn** [comment]
Als vorerst Einziges wollen wir die OAuth-Anbindung sauber umsetzen, siehe #1854. Dieses Issue schliessen wir erstmal, bis andere Use-Cases uns eine effiziente und zielgerichtete Umsetzung ermöglichen.
