### ISSUE TITLE
INVOICE: Persistieren von XML Informationen beim Import von Zahlungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1829]
Als Kassier
möchte ich von einer Zahlung zusätzliche Informationen abrufen können,
um zukünftig nichtzuweisbare Zahlungen manuell eintragen zu können.

Ziel ist es den entsprechenden Teil des XML zur Zahlung zu persistieren. Dies soll beim Import und via EBICS erfolgen. In diesem Ticket werden die Daten erstmals persistiert und noch nicht im Gui dargestellt.

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [x] Migration erstellen, Feld hinzufügen
- [ ] https://github.com/hitobito/hitobito/blob/master/app/domain/invoice/payment_processor.rb#L67 neues Feld mit `credit_statement` abfüllen
- [ ] Überprüfen dass alle Informationen im Feld landen
- [ ] Specs schreiben
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
