### ISSUE TITLE
TECH: Wagon-Specs für Pitfalls bei zusätzlichen Pflichtfeldern auf Person

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1844]
Als hitobito-Entwickler
möchte ich direktes Feedback haben wenn eine neue `required`-Validierung in einem Wagon andere Features kaputt macht,
um keine kaputten Features auszuliefern (auch wenn sie bisher von einem Dachverband momentan gar noch nicht verwendet werden).

Neu sollen die Wagons mit Feature-Specs ausgestattet werden, die die bekannten Pitfalls bei solchen zusätzlich obligatorischen Feldern abfangen:
- [x] Anmeldung bei Anlässen, bei denen das Feld abgefragt wird
- [ ] Anmeldung bei Anlässen, bei denen das Feld nicht abgefragt wird
- [x] Externe Anmeldung bei Anlässen, bei denen das Feld abgefragt wird
- [ ] Externe Anmeldung bei Anlässen, bei denen das Feld nicht abgefragt wird
- [x] Selbst-Registrierungs-Formular
- [ ] Wagon Seeds
- [ ] Root Seeds
- [ ] Bonus: Bestehende Produktionsdaten die durch die neue Validierung ungültig werden (wohl unrealistisch, diese in einem Feature Spec abzudecken, aber wollte diesen Pitfall der Vollständigkeit halber noch erwähnen)

# Tech-Spec

- Die neuen Feature Specs sollen im Core im Wagon-Template (lib/templates/wagon/spec/features) eingefügt werden, damit sie in zukünftigen Wagons von Anfang an drin sind
- Die neuen Feature Specs müssen einmalig in alle bestehenden Wagons kopiert werden, da die bestehenden Wagons die Specs ja noch nicht via Template bekommen haben
- Die einzelnen bullet points von oben können bei Bedarf auch in separaten kleineren Tickets abgehandelt werden

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
