### ISSUE TITLE
MESSAGES: SMTP From / Handle bounces in new bulk mail stack

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1847]
Beim Versand von Mails via MailingLists (Abos) in Hitobito müssen die **FROM** und **SMTP ENVELOPE FROM** auf eine Adresse mit der Domain der aktuellen Hitobito-Instanz versehen werden.

```
...
From: Hans Muster via <abo_name@hitobito.example.com>
Reply-To: hans.muster@example.com
Return-Path: abo_name@hitobito.example.com (wird vom Mailserver gesetzt und kann nicht überschrieben werden, smtp envelope from)
To: abo_name@hitobito.example.com
Subject: Besprechung vom 31.03.2021 - Einladung & Traktanden
X-Hitobito-Message-UID: abcd42
...
```

# Hitobito Message UID Header

Vor dem Versand an die Empfänger einer BulkMail wird eine unique ID generiert. Diese ID wird dann als Header *X-Hitobito-Message-ID* in die zu versendende Mail eingefügt. 

# Bounce Mails

Wird eine Mail gebounced, so wird diese an die Aboadresse zurück gesendet. In Hitobito erkennen wir eine solche Bounce Message da der *X-Hitobito-Message-ID* Header vorhanden ist. Über diese ID können wir dann die Bounce der ursprünglichen Mail/Message zuweisen. 

Bounce Messages werden nur in Hitobito weitgergeleitet wenn die Source Message vorhanden und nicht älter als 24h ist. Soll verhindern das jemand mit einer alten Nachricht das System zuspamen kann. 

# Tech-Spec

- Message Model
  - Neues Attribut: uid, string, null: true, unique: true, index: true
  - Neues Attribut: bounce_parent_id: integer, null: true, belongs_to: :message
  - Neuer STI Typ: Message::BulkMailBounce
    - Validate presence of :bounce_parent
- https://github.com/hitobito/hitobito/blob/master/app/domain/mailing_lists/bulk_mail/retriever.rb

# ToDo

- [x] DB-Migration für :messages erstellen
- [x] Anpassungen Versand
  -  UID vor Versand von Messages generieren, komplex genug das sie nicht eraten werden kann
  -  *X-Hitobito-Message-UID* Header an Mail anhängen vor dem Versand
  - Return-Path header entfernen (wird automatisch vom Mailserver gesetzt)
  - From auf Sendernamen und aboadresse setzen: `Hans Muster via <abo_name@hitobito.example.com>`
  - Falls kein Sendername im Originalmail vorhanden, Nachricht bereits im Retriever verwerfen
  - https://github.com/hitobito/hitobito/blob/master/app/domain/messages/bulk_mail/mail_factory.rb#L34
- [x] Message::BulkMailBounce erstellen inkl. Validierung presence of :bounce_parent
- [x] In MailingLists::BulkMail::Retriever Erkennung für Bounce Messages einbauen
  - 1. Liste existiert?
  - 2. *X-Hitobito-Message-UID* Header vorhanden?
  - 3. evtl. anderes Erkennungsmerkmal Bounce Message prüfen?
  - 4. Source Message anhand UID gefunden?
  - 5. Message::BulkMailBounce mit Bounce-Inhalt in body erstellen und an Source Message anhängen (bounce_parent)
- [x] Weiterleiten an den Absender von Bounce Messages
  - Source Message ist nicht älter als 24h
  - Source Message anhand Hitobito Message UID ausfindig machen
  - Bounce an den Sender der Source Message weiterleiten
  - Absender noreply Adresse
- [ ] Update Docu: z.B. https://github.com/hitobito/hitobito/blob/master/doc/e-mail/abo_mails.md
