### ISSUE TITLE
OAuth: NextCloud Login mit Hitobito ermöglichen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1854]
Als Hitobito-Nutzer, der auch Nextcloud nutzt
möchte ich mich bei NextCloud via hitobito einloggen
und Rolleninformationen übergeben können,
um die Berechtigung für alle meine Vereinsmitglieder konsistent verwalten zu können.

NextCloud kann mit dem [OpenID User Backend](https://github.com/nextcloud/user_oidc) die Authentication via OAuth z.B. gegen hitobito vornehmen.

Idealerweise kann man die hitobito-Rollen NextCloud so mitteilen, dass daraus NextCloud-Gruppen mit entsprechenden Berechtigungen werden. 

# Tech-Spec

- Ziel ist die zentrale Nutzer- und Berechtigungsverwaltung
- schöner Nebeneffekt ist, dass man nur noch seinen hitobito-Login braucht
- die initiale Verbindung (Providerconfig in hitobito und NextCloud, Gruppen in NextCloud) erfolgt manuell bis es so oft passiert, dass wir es dokumentieren und später automatisieren können.

# ToDo

- [x] NextCloud-Testinstanz bereitstellen, um Integration zu validieren
- [x] Möglichkeit finden, um hitobito-Rollen an NextCloud weiterzugeben. (`user_oidc` mit PR 502)
- [x] Rollen-Klassen erweitern, um Gruppenmapping zu unterstützen (ein bestimmte Rolle innerhalb einer bestimmten Ebene bekommt direkt Gruppenname zugewiesen)
- [x] Gruppen erweitern, um Link zu NextCloud aufzunehmen (String `nextcloud_url` auf `groups`) (nur Layergruppen)
- [x] OAuth-Scope hinzufügen, um die für NextCloud notwendigen Daten zurückzugeben.
- [x] Doku hinzufügen, um tatsächliche Integration festzuhalten. 
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kronn** [comment]
Dieser PR erscheint mir geeignet, einen Großteil unserer Wünsche abzudecken: https://github.com/nextcloud/user_oidc/pull/502

**Comment by richardjubla** [comment]
Lieber @kronn & @thomasellenberger 

Ich möchte das generelle "Interesse" durch die jubla anmelden. 
Die FG Datenbank möchte die Story verfolgen um als Schar/Verein (Ebene/Gruppe) eine Verbindung zwischen jubla.db und einer eigenen Nextcloud Instanz (Standard Hosting) verbinden zu können. Vereinsmitglieder (db Profile) sollen sich aus der Datenbank direkt in Nextcloud anmelden können und dort sofort (oder mit minimalem Aufwand) ihre Berechtigungen vorfinden. 
Der Vorstand/Leitung sollte so mit einem "Standard-Produkt" (Nextcloud) auf einfache weise für seinen Verein eine schlüsselfertige Dokumentablage/Dokumentbearbeitung und Kollaborationslösung anbieten können. 
(Zeitrahmen offen, Inkrement 3/23 und 4/23 im Blick) 

Bitte mit mir den Kontakt aufnehmen um ein mögliches Projekt zu besprechen/starten

**Comment by nchiapol** [comment]
@richardjubla Wir beim Cevi sind an dieser Story auch sehr interessiert. Für uns sind dabei aber nicht nur die Scharen sondern alle Ebenen relevant. Auch Kantone/Regionen und die nationale Ebene haben zum Teil eigene NextCloud-Instanzen für ihre Fachgruppen/Kurse/...

**Comment by richardjubla** [comment]
> @richardjubla Wir beim Cevi sind an dieser Story auch sehr interessiert. Für uns sind dabei aber nicht nur die Scharen sondern alle Ebenen relevant. Auch Kantone/Regionen und die nationale Ebene haben zum Teil eigene NextCloud-Instanzen für ihre Fachgruppen/Kurse/...

Ich denke, wir sprechen hier vom gleichen Bedürfnis. Unsere Abgrenzung ist, dass jede Ebene (Verantwortung) für sich selbst funktioniert und es keine Ebene gibt (insbesondere nicht der Verband!), welcher die Zugriffe/Berechtigungen auf darunterliegende Gruppen/Ebenen vererbt.
Jede rechtliche Einheit (Verein) soll elbständig für seine eigene Nextcloud-Instanz zuständig sein. Der Verband wird/soll keine Infrastruktur zur Verfügung stellen, die Folgefragen und Abhängigkeiten hervorbringen würde.

**Comment by nchiapol** [comment]
Ja, ich denke wir haben das gleiche Bedürfnis - das war bei euch einfach nicht so explizit ausformuliert. Deshalb meine Ergänzung.

**Comment by richardjubla** [comment]
Lieber @ThomasEllenberger

Hätte gerne bis 15. August eine Offerte damit ich diese mit der Fachgruppe beurteilen/freigeben kann.
