### ISSUE TITLE
OPS: Debug or auto-resolve Truemail-errors

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1857]
As a person editing peoples data in hitobito
I want to avoid errors due presumably wrong e-mails
I order to focus on my work

Sometimes, Truemail fails to validate (perfectly valid) emails. A restart solves this. It has been observed after data-imports or some ongoing work on people.

We validate the e-mail on every save of a person.

If the validation fails for valid emails, it is perceived as an application error and generates some support-overhead.

# Tech-Spec

- Truemail should always validate mails correctly
- since a restart resolves this, we could add this to the health-check
- updating Truemail might help
- we should track when this happens
- maybe only validate e-mail if new record or e-mail address changed?

# ToDo

- [x] Add verification of known-good address to healthz-check
- [x] send error to sentry if a mail-address is invalid AND a known-good is also invalid
- [x] write Specs (happy response-mocking)
