### ISSUE TITLE
EVENTS: Anzeige von "Anmeldung an" abkürzen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1872]
Bezieht sich auf #1813 

Aktuell wird in der Kursübersicht das komplette Feld "Anmeldung an" angezeigt.
Neu soll nur noch die erste Zeile "Name der Ebene" von diesem Feld angezeigt werden.

![](https://user-images.githubusercontent.com/95908537/192970116-936ef94f-81e3-42da-8201-2a3a025148b1.png)

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [x] https://github.com/hitobito/hitobito_jubla/blob/master/app/views/events/courses/index.html.haml#L27 `complete_contact`zu `address_name` ändern
- [x] Specs anpassen
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by TheWalkingLeek** [comment]
Ich war so frech und hab den one-liner direkt commited
https://github.com/hitobito/hitobito_jubla/commit/1e21bf5f3450e3abe9ab30eaad01df40ed996a99
