### ISSUE TITLE
PERSON: Einverständnis Datenschutzerklärung (DSE) einholen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1881]
Als Verband möchte ich das Einverständnis von Neumitgliedern für meine Datenschutzerklärung (DSE) einholen.

Das Feature soll wenn möglich im Core umgesetzt werden. Hinweise und Rückmeldungen von anderen Hitobito-Kunden sind willkommen!
# Funktionalität
### Einverständniserklärung
Es gibt drei Szenarien, um das Einverständnis zur DSE abzuholen.

**1. Selbstregistrierung**
Das Neumitglied registriert sich selber in Hitobito. Dies kann via Link auf eine Gruppe oder via externer Anlass erfolgen. Die Person bestätigt selber, dass sie mit den Bedingungen einverstanden ist.

**2. Fremdregistrierung**
Die eintragende Person (zum Beispiel Adressverwalterin) bestätigt, dass das Neumitglied mit den Bedingungen einverstanden ist. Sie holt das Einverständnis manuell ab (Eintrittsformular, QR-Code auf entsprechende Dokumente, usw.)

**3. Anmeldung bei Lagern / Kursen**
Um das Einverständnis schneller von mehr Mitgliedern zu erhalten, soll auch bei der Lager- und Kursanmeldung das Einverständnis abgeholt werden, falls noch nicht vorhanden.

##### Allgemein
Hilfetexte erlauben, wo möglich, Erklärungen für die Personen, die eine Anmeldung machen, zu hinterlegen.

### DSE pro Ebene erlauben
Alle Ebenen haben die Möglichkeit, eigene Bestimmungen zum Datenschutz hochzuladen. Ist ein Dokument vorhanden, so wird es bei der Registrierung **zusätzlich** zu den anderen angezeigt.

- Der Upload erfolgt über Gruppe -> Bearbeiten.
- Es kann genau ein Dokument hochgeladen werden. 
- Es sind nur PDFs erlaubt. 
- Es gibt ein Titel-Feld, damit jedes Dokument mit einem passenden Namen beschriftet werden kann (Länge limitieren)

# Mockup

Selbstregistrierung
![DSE_Selbstreg](https://user-images.githubusercontent.com/1799621/197743734-f3cf809f-6645-48a3-b0ec-12bf0d177520.png)

Fremdregistrierung
![DSE_Fremdreg](https://user-images.githubusercontent.com/1799621/197743762-864263c2-8f51-4a56-86d0-1fa464537d14.png)

Lageranmeldung / Kursanmeldung
(nur oberer Screenshot ist relevant)
![DSE_Lager](https://user-images.githubusercontent.com/1799621/197743780-bc177426-2330-4452-854f-600f1cc3f1b1.png)

# Abgrenzung

- Nicht-Mitglieder brauchen keine Einverständnis zu geben
- Ein Dokument pro Ebene reicht. Dokumente können auch gemerged werden, wenn es mehr sein sollen.
- Links anstatt PDFs nein: Es besteht sonst die Gefahr, dass die verlinkte Seite verschoben oder nicht mehr vorhanden ist
- Text anstatt PDFs: In einer ersten Version nicht. Ev. mal als Weiterentwicklung
- Dokumente müssen nicht versioniert sein. Bei Änderungen muss typischerweise keine erneute Einverständnis eingeholt werden.
- Auch wenn eine Ebene eine neue DSE hinterlegt, werden vorerst nicht alle Einverständnisse gelöscht.
- Das externe Registrierungs-Formular der GLP wird für den Moment nicht angepasst

# Tech spec
- Umsetzung im Core
- Ein zusätzlicher, PBS-spezifischer Teil wird in #1956 umgesetzt

# ToDo

- [x] Migration erstellen
  - [x] `people, :privacy_policy_accepted_at, :timestamp, null: true`
    - [x] zu den internal attrs hinzufügen, ist vorerst nirgends im UI lesbar (nur schreibbar)
  - [x] Übersetzbares Feld `:privacy_policy_title` auf `Group` (nullable, `translates :privacy_policy_title` in group.rb)
- [x] Prüfen, ob https://github.com/kronn/date_checkbox hier (noch) funktioniert
- [x] Textfeld auf Gruppe (groups#edit, nicht group_settings) hinzufügen
  - [x] Feldname:  `privacy_policy_title`
  - [x] Längenlimit validieren (z.B. 64 Zeichen)
  - [x] Feld soll übersetzbar sein
- [x] Upload-Feld auf Gruppe (groups#edit, nicht group_settings) hinzufügen
  - [x] Feldname: `privacy_policy` "DSE/Datenschutzerklärung"
  - [x] nur PDF
  - [x] nur schreibbar auf Layern, nicht auf non-layer Gruppen
- [x] Views und Controllers anpassen
  - :exclamation: **Achtung** generell wird überall nur etwas angezeigt, wenn in der Layer-Hierarchie der betreffenden Person mindestens eine DSE hochgeladen ist
  - :exclamation: Die Formulare sollen jeweils invalide sein wenn die Checkbox nicht aktiviert ist (Validierung schreiben)
  - Die Checkboxen sollen jeweils einen Text enthalten, und zu den DSEs der Layer-Hierarchie der betreffenden Person verlinken. Jede DSE soll mit dem `privacy_policy_title` des jeweiligen Layers angezeigt werden
  - [ ] :bulb: Wenn die Zeit reicht: Sicherstellen dass Hilfetexte zu den Checkboxen erfasst werden können
  - [x] Selbstregistrierung [[view]](https://github.com/hitobito/hitobito/blob/master/app/views/groups/self_registration/_form.html.haml) [[controller]](https://github.com/hitobito/hitobito/blob/master/app/controllers/groups/self_registration_controller.rb)
  - [x] Registrierung bei externem Anlass [[view]](https://github.com/hitobito/hitobito/blob/master/app/views/event/register/register.html.haml) [[controller]](https://github.com/hitobito/hitobito/blob/master/app/controllers/event/register_controller.rb)
  - [x] Fremdregistrierung [[view]](https://github.com/hitobito/hitobito/blob/master/app/views/roles/_person_fields.html.haml) [[controller]](https://github.com/hitobito/hitobito/blob/master/app/controllers/roles_controller.rb) (nur bei "Neue Person erfassen")
    - :exclamation: **Achtung** das Wording der Checkbox ist hier anders, da nicht die Person sich selber anmeldet
  - [x] Anlassanmeldung [[view]](https://github.com/hitobito/hitobito/blob/master/app/views/event/participations/_form.html.haml) [[controller]](https://github.com/hitobito/hitobito/blob/master/app/controllers/event/participations_controller.rb)
   - :exclamation: **Achtung** wenn die betreffende Person schon einmal zugestimmt hat (`privacy_policy_accepted_at.present?`), dann soll die Checkbox aktiviert und disabled angezeigt werden.
    - :exclamation: **Achtung** Das Wording der Checkbox ist je nach `params[:for_someone_else]` anders
- [x] Specs schreiben
  - [x] für den Upload von DSEs schreiben
  - [x] für alle angepassten Formulare
  - [x] für alle angepassten Controllers im Fall dass keine DSE auf der Layer-Hierarchie hochgeladen ist
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by Michael-Schaer** [comment]
> [ ] Anlassanmeldung [[view]](https://github.com/hitobito/hitobito/blob/master/app/views/event/participations/_form.html.haml) [[controller]](https://github.com/hitobito/hitobito/blob/master/app/controllers/event/participations_controller.rb)
>    ❗ Achtung bei Anlässen nie anzeigen, nur bei Kursen und Lagern

Wenn möglich, würden wir folgendes gerne noch anpassen:
Die Checkbox zur DSE darf auch bei Anlässen angezeigt werden. Hier muss nichts eingeschränkt werden.

Stimmt das aus eurer Sicht auch, dass das eine Vereinfachung ist? Wenn ja, gerne aufnehmen.

**Comment by richardjubla** [comment]
In der Version 1.31.5 (jubla) wird in der Stage-Umgebung der event_participation_contact_data_privacy_policy_accepted nicht korrekt ausgegeben:

![image](https://github.com/hitobito/hitobito/assets/95908537/8be0ba16-4204-4b74-baca-e0022fe24580)

**Comment by richardjubla** [comment]
In der Version 1.31.5 (jubla) werden in der Stage-Umgebung die notwendigen Felder nicht korrekt Markiert. Muss- Felder sollten mit einem * gekennzeichnet sein, werden aber erst mit der Fehlermeldung als zwingende Felder markiert:


![image](https://github.com/hitobito/hitobito/assets/95908537/c1dbc324-eb16-462b-9138-e39da132b8c4)

**Comment by richardjubla** [comment]
Der Check für event_participation_contact_data_phone_numbers funktioniert in Version 1.31.5 (jubla) auf der  Stage-Umgebung nicht. Wird das Feld erzwungen, kann es nie korrekt eingegeben werden.


![image](https://github.com/hitobito/hitobito/assets/95908537/c4b0ecd2-32df-46ff-a291-4799d6e1cf21)
