### ISSUE TITLE
INVOICES: Absendername E-Mail Rechnungen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1893]
Es gibt ~~drei~~ zwei verschiedene Arten wie man Rechnungen per E-Mail an Empfänger senden kann:

1. Auf einer Rechnung selber über stellen/mahnen 'Status setzen und per E-Mail verschicken'
2. Auf einer Sammelrechnung ebenfalls über stellen/mahnen 'Status setzen und per E-Mail verschicken' mit Mehrfachselektion
3. ~~Via Rechnungsbrief und MessageDispatch~~ ist noch nicht implementiert, siehe #1434

Bei diesen E-Mails soll pro Layer der Name des Absenders angepasst werden können. 
Es wird nur der Absendername, jedoch nicht die E-Mail Adresse angepasst. (noreply@my-hitobito.example.com)
Optional Einstellung für Absender ABSENDER@my-hitobito.example.com. Domain ist fix und kann nicht geändert werden.

# Tech-Spec

- Umsetzung im Core
- https://github.com/hitobito/hitobito/blob/master/app/mailers/invoice_mailer.rb#L87
- https://github.com/hitobito/hitobito/blob/master/app/mailers/application_mailer.rb#L53

# ToDo

- [x] Auf den Rechnungseinstellungen neu die Option **E-Mail Absendernamen** hinzufügen (via Migration).
- [x] Neues Tab **E-Mail** bei Rechnungseinstellungen erstellen und das bestehende Feld **Antwort an E-Mail Adresse** dort einfügen.
- [x] Im [invoice mailer](https://github.com/hitobito/hitobito/blob/master/app/mailers/invoice_mailer.rb#L87) den `:sender` Header anpassen, falls das Feld auf dem Layer befüllt ist
- [ ] Optional den gleichen Prozess nochmals für Absender-Mail (hitobito-Domain ist fix und kann nicht geändert werden, nur der Mail-Name)
- [ ] Dieses Verhalten im Ticket #1434 ergänzen, damit dasselbe dann dort nicht vergessen geht
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
