### ISSUE TITLE
Kurse - Genderschreibweise auf Kursrollen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1896]
Die Jubla wünscht sich, dass die Rollen In Kurse gemäss ihrer geschlechtergerechten Kommunikation umbenannt werden.
Dies war Teil dess Issues https://github.com/hitobito/hitobito_jubla/issues/33.

## Alte Schreibweise:
Referent/-in
Helfer/-in
Teilnehmer/-in

## Neue Schreibweise:
Referent\*in
Helfer\*in
Teilnehmer\*in

# Abklären
- Soll Teilnehmer/-in auch in Teilnehmer\*in umbenannt werden?
- Soll diese Schreibweise auch in Lagern und Anlässen übernommen werden?
- Die alte Schreibweise wird aus dem Core so übernommen. Einzige Ausnahme die ich finden konnte ist der PBS-Wagon. Übernehmen wir die neue Schreibweise in den Core, oder wird dies Jubla-Spezifisch? (Wenn wir das in den Core übernehmen wäre die Genderschreibweise auf Rollen und Kursen dann Unterschiedlich - Nicht so schön)

# Tech-Spec

- Umsetzung im Jubla-Wagon
- Bei der PBS sieht man, was alles geändert werden müsste, um applikationsweit den Gender-Stern einzusetzen: https://github.com/hitobito/hitobito_pbs/pull/164. Das ist **nicht** Ziel dieses Issues hier.

# ToDo
- [x] In models.jubla.de.yml die drei Begriffe anders übersetzen
- [ ] Allenfalls Specs anpassen
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
@ThomasEllenberger danke für das issue.

In Jungwacht Blauring nehmen wir unsere gesellschaftliche Mitverantwortung wahr, die wir als Kinder- und Jugendverband bei Geschlechterthemen haben. In unseren Texten achten wir deshalb auf geschlechtergerechte Kommunikation. Konkret sollen auch bei Aktualisierungen der Datenbank jeweils die Texte aktualisiert werden.
https://mitglieder.jubla.ch/mitglieder/themen/gender/

Präzisierungen:
- Wir passen jeweils nur Texte an, die ohnehin bearbeitet oder angepasst werden
- Abhängigkeiten zum Core oder Funktionalitäten haben klar Vorrang. 
**- Sofern die Anpassung "unschöne" Auswirkungen auf Rollen und Kursen hat, machen wir sie nicht.** 
- Der Zusatz-Aufwand muss sich im minimalen, vertretbaren Rahmen bewegen, UX/UI & Konformität geht vor

**Comment by carlobeltrame** [comment]
@richardjubla zur Info, die PBS hat die Übersetzungen an allen möglichen Stellen angepasst. Siehe hier für eine Liste (du musst alle geänderten Dateien aufklappen): https://github.com/hitobito/hitobito_pbs/pull/164/files, und dazu kommen noch alle Mailtexte die ihr selber direkt in hitobito in den Einstellungen ändern könnt.
Das Thema geht also eigentlich weit über die Kursrollen hinaus (z.B. Sätze wie "Wo liegen seine*ihre Stärken?"). Wir passen in diesem Issue nur gerade die drei Kursrollen Referent\*in, Helfer\*in und Teilnehmer\*in an, ist das gut so? So bleibt der Aufwand in minimalem Rahmen wie du beschreibst, dafür ist aber halt nicht überall in der Applikation dieselbe Genderschreibweise eingesetzt.

**Comment by richardjubla** [comment]
> Wir passen in diesem Issue nur gerade die drei Kursrollen Referent*in, Helfer*in und Teilnehmer*in an, ist das gut so?

Korrekt!
