### ISSUE TITLE
PERSON: Erweitern Personenfilter durch Sprache

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#1905]
Als Benutzer
möchte ich eine Liste mit Personen welche eine definierte Sprache haben auswählen,
um ihnen anschliessend eine Rechnung stellen zu können

Der Personenfilter (https://sww.puzzle.ch/de/groups/35/people_filters/new) soll bei den Feldern um das Attribut "Sprache" ergänzt werden. Diese Attribut ist seit https://github.com/hitobito/hitobito/issues/1663 im Core vorhanden.

Achtung: Gewisse Wagons verwenden noch andere Sprachen, Korrespondenzsprache, etc.
Achtung: Ein solches Feature existiert bei der Mitte bereits. Dieses müsste durch das neue Core-Feature abgelöst werden, und allfällige gespeicherte Filter sollten migriert werden wenn möglich.

# Tech-Spec

- Umsetzung im Core
- Feature wird nur bei Core-Language Nutzenden aktiviert (Siehe FeatureGate#person_language_enabled?), bei SWW der Fall
- Das Feature der Mitte wird nicht auf den Core migriert, da diese ein eigenes Language Feld verwenden
- Der Filter der Mitte ignoriert aktuell die Matcher ("ist genau", "enthält", "enthält nicht"). Im Core sollen diese aber berücksichtigt werden
- Der Filter soll mittels Textinput funktionieren. Dropdown mit den available_languages wäre auch möglich. Zeitaufwand aber zu hoch 

# ToDo

- [ ] Neues Filter-Feld language in https://github.com/hitobito/hitobito/blob/master/app/models/person.rb#L84 ergänzen
  - [ ] Abhängig von `FeatureGate.if('person_language')` machen. Muss vom Timing her wahrscheinlich in initializer gemacht werden: https://github.com/hitobito/hitobito/blob/8a6ef125be5f67413dec8f0cfc5e2c87dfa0f2ce/config/initializers/person_language.rb#L2  
- [ ] Filter-Implementation in https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/attributes.rb so ergänzen, dass nach den übersetzten Werten ("Deutsch", "Englisch", ...) gefiltert wird 
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
Muss noch mit allen Wagons getestet werden die selber ein Sprach-Feld haben, und mit mindestens einem der das nicht hat.

**Comment by olibrian** [comment]
Habe die Instanzen SWW, Jubla, SBV und Mitte kurz neu gebaut und getestet. Sieht aus meiner Sicht gut aus.
