### ISSUE TITLE
TECH: Neues Ruby Base Image verwenden

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1914]
Aktuell verwenden wir noch das [CentOS S2I Image](https://hub.docker.com/r/centos/ruby-27-centos7)

Dieses möchten wir gerne auf das neue Ruby Base Image wechseln 

# ToDo

- [x] Dockerfile zum Ruby Base Image ändern. Siehe [Interne Vorlage](https://gitlab.puzzle.ch/pitc_ruby/ruby-ops/-/tree/master/ruby-engineering/projects/new_ruby_build_strategy), [WIP Branch](https://github.com/hitobito/hitobito/tree/new-dockerfile)
- [x] Sicherstellen, dass Wagons richtig gebaut werden
- [x] Sicherstellen, dass Images auch für Sphinx und DJ passen
- [x] Rebase auf Ruby-Branch 
- [x] reusable Github-Action nach Vorlage https://github.com/puzzle/decidim-biel/blob/master/.github/workflows/reusable-build.yaml einbauen
- [x] reusable Github Action zum Build vom Rails-Image
- [x] reusable Github Action zum Build vom Sphinx-Image 
- [x] konkrete Builds in hit-sjas-int
- [x] push in registry.puzzle.ch
- [x] Anpassung OpenShift-Config
	- [x] Deployment:rails
	- [x] Deployment:sphinx
	- [x] Deployment:delayed-job
	- [x] Deployment:migrations
- [x] Config Management apply
- [x] Smoke-Test auf integrationsumgebung
	- [x] rails-image startet ohne Fehler
	- [x] sphinx-images startet ohne Fehler
	- [x] DB-Verbindung
	- [x] Verbindung zu Sphinx-Suche
	- [x] Delayed::Job läuft
	- [x] Migrations läuft
	- [x] Login funktioniert
- [x] Versionsnummer als Image-Tag verwenden
	- [x] INT: Version, Build-Nummer oder SHA
	- [x] PROD: Version
- [x] Submodules aktualisieren
- [x] Übersetzungsupdates einbauen (entweder in den Build oder in das Update des composition-repo)
- [ ] Wenn möglich: alte Versionen löschen
- [x] Wenn möglich: Jemalloc einführen (Siehe #1895)

**Comment by mtnstar** [comment]
https://github.com/hitobito/hitobito/tree/ruby3.0

hier mal der branch mit WIP für eine lauffähige hitobito version mit ruby 3.0.

der server startet ... nach dem Login gibt es aber noch einen Fehler den ich nun debugge.

aber für einen ersten Test mit dem neuen Base-Image sollte das bereits ready sein.

docker setup mit version 3.0 branch ist hier: https://github.com/hitobito/development/tree/ruby-3.0

wir sollten aber sicher prüfen ob wir nicht gleich auf Ruby 3.2 upgraden können.

**Comment by Kagemaru** [comment]
Momentan bin ich am umkonfigurieren der OpenShift config. Hier der WIP: https://gitlab.puzzle.ch/pitc_hit/hitobito-configmanagement/-/merge_requests/8
