### ISSUE TITLE
GRUPPE: Gruppen-Log und Personen-Log

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1918]
Als Abteilungsleiter*in will ich wissen, wann eine Entität (Person, Rolle, Event, ...) in meiner Gruppe angepasst wurde, um nachstellen zu können, wer welche Änderungen vorgenommen hat.

### Hintergrund
Es gibt bereits einen Log für Personen. Dieser ist aber nur nützlich, wenn die Person, die angepasst wurde, bekannt ist. Wenn ich wissen möchte, ob in den letzten Tagen jemand angepasst wurde, muss ich alle Personen einmal öffnen und ihren Log studieren. Das Gruppen-Log soll eine Übersicht über Veränderungen bei Personen auf einen Blick ermöglichen. Ausserdem sollen Anpassungen an anderen Entitäten in der Gruppe geloggt werden.

### Lösungsansatz

Es wird ein neuer Tab “Log” auf der Gruppenebene eingeführt. Dort kann man zwischen zwei Logs auswählen. Für beide Logs soll aufgeführt sein:
- was geändert wurde
- wann die Änderung vorgenommen wurde (Datum und Uhrzeit) 
- durch welche Person die Änderung gemacht wurde (mit Link zum Profil)

Um die Ladezeiten zu verkürzen, dürfen die Logs zeitlich beschränkt werden (z.B. die letzten 3 Monate).

#### Log 1 - Personen-Log
Diese Ansicht aggregiert die Logs von Personen, die in dieser Gruppe eine Rolle haben.

#### Log 2 - Gruppen-Log
Dieser Log enthält Anpassungen an der Gruppe oder deren Entitäten (ausser das Editieren von Personen):
- Angaben der Gruppe bearbeitet 
- Direkte Untergruppen gelöscht
- Rollen hinzugefügt, bearbeitet oder entfernt
- Anlässe, Kurse und Lager hinzugefügt oder bearbeitet 
- Abos hinzugefügt, bearbeitet oder gelöscht

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- Umsetzung im Core
- Bestehende Arbeit von Nils auf Branch https://github.com/hitobito/hitobito/compare/feature/1918_group_and_people_log
- Das Personen-Log kann man bisher nur mit `full` Permission auf der Person einsehen. Daher muss man für das Gruppen-Log auch eine `full` Permission in der Gruppe haben.
- Trotzdem müssen wir die angezeigten Personen noch mit `PersonFullReadables` filtern, um sicherzustellen dass keine Kinder-Daten oder Daten von Personen mit geheimen Rollen (wie die Cevi-Spender) exponiert werden.
- Falls der User auch `full` Berechtigung in Untergruppen hat, werden auch die Logs von Personen in Untergruppen angezeigt
- Logs von Personen in Sub-Layers werden aber nie angezeigt. Das Gruppen-Log ist nicht Layer-übergreifend. (Personen die in meinem Layer UND in einem Sub-Layer sind sind aber natürlich schon sichtbar)
- Auf dem Gruppen-Log von Gruppe X wird es auch angezeigt, wenn eine Person in Gruppe X zufällig eine Rolle in einer komplett anderen Gruppe Y bekommt etc., wir filtern nicht heraus was zu dieser Gruppe "gehört".
- **Achtung**: Bug #1821 wird sich hier auswirken! Personen die ihre letzte Rolle in der Zukunft verlieren, werden hier fälschlicherweise wie gelöschte Personen behandelt werden.
- **Abgrenzung**: Die Archivierung von Rollen taucht bisher nicht einmal im Personen-Log auf. Daher lassen wir das für den Moment mal hier weg.
- **Abgrenzung**: Passive Rollen und externe Rollen sind zwar auf der Standard-Personenliste einer Gruppe ausgeschlossen, werden hier aber nicht speziell behandelt. Logeinträge von solchen Personen tauchen ganz normal im Gruppen-Log auf.
- **Anmerkung**: Eine Alternative zu diesem Ticket wäre es, ein externes Tool zu bauen, welches die neue API verwendet und Personen einer gewünschten Gruppe nach `updated_at` gefiltert abruft.

# ToDo

- [x] Neues Tab "Log" auf Gruppen (auch non-layer Gruppen) hinzufügen, mit `Group::LogController`
- [x] Der `Group::LogController` sucht alle relevanten Gruppen zusammen
  - [x] Die angeschaute Gruppe und all ihre Untergruppen, ohne allfällige Sub-Layers
  - [x] Diese Liste von Gruppen filtern nach `can(:log, candidate_group)`, gemäss folgender Ability (ähnlich wie die Ability `:log` die bereits auf Personen existiert):
    - [x] Falls der User `layer_and_below_full` im selben Layer wie die Gruppe oder in einem übergeordneten Layer hat, bekommt er die Ability `:log` auf der Gruppe
    - [x] Falls der User `layer_full` im selben Layer wie die Gruppe hat, bekommt er die Ability `:log` auf der Gruppe
    - [x] Falls der User `group_and_below_full` auf der Gruppe oder einer übergeordneten Gruppe in demselben Layer hat, bekommt er die Ability `:log` auf der Gruppe
    - [x] Falls der User `group_full` auf der Gruppe hat, bekommt er die Ability `:log` auf der Gruppe
- [x] Der `Group::LogController` sucht alle Personen dieser Gruppen zusammen
  - [x] Die Liste von Personen muss, wegen Spezialregeln mit `visible_from_above` und bei Cevi-Spendern, noch mit `PersonFullReadables` Scope gefiltert werden
  - [x] Archivierte Rollen zählen in diesem Zusammenhang wie gelöschte Rollen
- [x] ~~Zusätzlich stellt der `Group::LogController` noch eine Liste von Personen zusammen, welche mal eine Rolle in einer dieser Gruppen hatten, aber jetzt nicht mehr~~
  - [x] ~~Dazu alle Personen mit einer gelöschten Rolle in einer der Gruppen suchen (archiviert zählt nicht, muss deleted_at < NOW sein) und aus dieser Liste alle oben berechneten aktiven Personen entfernen~~
  - Dieses Vorgehen funktioniert nicht, weil wir die aktiven Personen mit PersonFullReadables filtern müssen. Eine Person die mal eine Rolle in der Gruppe verloren hat, jetzt aber noch eine aktive Rolle hat und trotzdem nicht readable ist für den eingeloggten User, würde fälschlicherweise in den Logs auftauchen (zwar nur ihre Rollenlöschungen, aber trotzdem falsch).
- [x] Der `Group::LogController` sucht alle Logeinträge dieser Personen zusammen
  - [x] Die Logeinträge werden als flache Liste aus der Datenbank geladen (mit `WHERE main_id IN (... aktive Personen ...)`) und nach Datum sortiert (aber immer noch als SQL Query, sodass wir paginieren können)
  - [x] ~~Bei den gelöschten Personen nur Log-Einträge von Rollenlöschungen in dieser Gruppe anzeigen (mit `OR (WHERE main_id IN (... gelöschte Personen ...) AND version.item_type="Role" AND version.event="destroy" AND version.item.group_id IN (... angezeigte Gruppen ...))`)~~
  - [x] Zusätzlich noch alle Rollenlöschungen in den Gruppen miteinschliessen, auch wenn die Rollen zu Personen gehören die inzwischen nicht mehr lesbar sind (weil keine Rolle mehr). Ungefähres SQL: `OR (version.item_type="Role" AND version.event="destroy" AND version.item.group_id IN (... angezeigte Gruppen ...) AND (version.item.deleted_at IS NULL OR version.item.deleted_at < NOW))`
- [x] Die Liste von Logeinträgen wird im UI auf dem neuen Tab angezeigt
  - [x] Paginierung
  - [x] View kann von https://github.com/hitobito/hitobito/blob/master/app/views/person/log/index.html.haml kopiert werden, muss aber angepasst werden um noch den Namen der geänderten Person anzuzeigen
- [x] Falls Zeit reicht, #1821 fixen, damit das Feature auch für Rollen mit Enddatum in der Zukunft richtig funktioniert
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by Michael-Schaer** [comment]
Merci für die Rückfrage! 

Ich würde hier den einfachen Weg gehen: Wenn die Person die Rolle in meiner Gruppe verliert, wird das im Gruppen-Log eingetragen. Alle anderen Infos über diese Person sind nur noch für diejenigen ersichtlich, die aktuell Zugriff auf die Person haben. Im schlimmsten Fall müsste ich also dieser Person erneut eine Rolle geben, um ihren Log sehen zu können.

**Comment by Michael-Schaer** [comment]
Danke für die Umsetzung! Das sieht schon einmal sehr toll aus!

Kann für den Tab auch ein Hilfetext gesetzt werden?

**Comment by carlobeltrame** [comment]
Bisher leider nicht, nein. Die Hilfetexte für "Seiten" bzw. Tabs sind [bisher](https://github.com/hitobito/hitobito/blob/master/app/domain/help_texts/list.rb#L53..L54) nur für diejenigen Controllers eingerichtet welche direkt den Namen eines Models haben, z.B. PeopleController -> Person, GroupsController -> Group. Das neue Gruppen-Log wird im Group::LogController berechnet, und Group::Log ist keine Model-Klasse (da dieser Controller halt bisher nicht Gruppen-Logs anzeigt sondern mehrere Personen-Logs zusammensucht). Wir könnten das einrichten wenn gewünscht. Oder wir könnten auch zuoberst im Gruppen-Log einen übersetzbaren erklärenden Text einblenden, das wäre schneller gemacht.
