### ISSUE TITLE
PERSON: Abo-Filter nach Alter und Sprache

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1919]
Als Benutzer möchte ich bei Abos die Zielgruppe nach Alter und Korrespondenzsprache einschränken können. Dies erlaubt es, zielgruppengerechte Versände auszuführen. Beispielsweise eine Einladung ab Alter X zu verschicken, oder einen Versand auf zwei Altersstufen aufzuteilen.

Filtermöglichkeiten nach Priorität:
- Alter <18 (Altersfilter kleiner als)
- Alter >22 (Altersfilter grösser als)
- Hat Sprache FR (Sprachfilter positiv)
- Hat nicht Sprache FR (Sprachfilter negativ)
- Alter zwischen 18 und 30 (kombinierter Altersfilter)
- Hat Sprache FR oder IT (kombinierter Sprachfilter)

Ergänzungen:
- Bitte überprüfen, ob die Sprache beim Personenfilter für die PBS funktioniert (https://github.com/hitobito/hitobito/issues/1905) und, falls einfach möglich, an den core angleichen.
- Die Suche soll nicht deutlich verlangsamt werden
- Wenn möglich soll das UI vom Personenfilter übernommen werden

# Mockup

![Screenshot 2023-09-13 at 17-42-54 MiData PBS_MSdS_MSS - Abotest](https://github.com/hitobito/hitobito/assets/7566995/c903ea93-c11e-4a1b-8858-67e671144d21)

# Tech-Spec

- Umsetzung im Core
- Im Mitte Wagon hat es bereits einen rudimentären [Filter nach Korrespondenzsprache](https://github.com/hitobito/hitobito_die_mitte/blob/master/app/domain/die_mitte/mailing_lists/subscribers.rb). Falls der Zeitrahmen nicht schon völlig gesprengt wird, würden wir dieses Die-Mitte-Feld gerne aufräumen (und die Einstellungen darin ins Core-Feature migrieren)
- Es ist der Wunsch da, das Filter-UI ähnlich wie die Personenfilter zu gestalten. Das hat aber nicht höchste Priorität. Falls es viel einfacher oder benutzerfreundlicher ist, können wir auch von diesen Visuals abweichen (die sind eher ein Gebastel).
- Die Filter-Logik müsste von den [Personenfiltern](https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/chain.rb) wiederverwendet werden können. Diese Filter Chains sind bereits in die Datenbank serialisierbar, und können einfach auf einen Scope `apply`ed werden.
- Die Filter können daher direkt als serialisiertes Feld auf der MailingList gespeichert werden.
- Im UI müssen aber nicht alle Personenfilter auch für MailingLists einstellbar sein. Wenn Zeit übrig ist kann man noch an weiteren solchen arbeiten, aber primär sind mal die Filter nach Alter und nach Korrespondenzsprache zu implementieren.

# ToDo
- [x] Im PBS Wagon: Bestehenden Sprachfilter vom Core aktivieren
  - [x] Dafür die Werte vom schon lange bestehenden PBS-spezifischen Feld `correspondence_language` ins neuere Core-Feld `language` migrieren (in einer DB-Migration)
  - [x] Alte `correspondence_language` Spalte entfernen
  - [x] Global suchen, wo dieses Feld im PBS-Wagon noch verwendet wird, und es durch das neuere `language` Feld ersetzen
  - [x] Im PBS Wagon in settings.yml `person_language.enabled` auf `true` setzen, damit der [Initializer](https://github.com/hitobito/hitobito/blob/master/config/initializers/person_language.rb) greift und das Core-Sprach-Feld aktiviert
  - [ ] Da wir nicht einfach bei allen bisher sprachlosen Personen die Sprache Deutsch setzen können: Sprache in der Migration intelligent nach Kanton setzen
    - [x] Über alle Personen mit `nil` Sprache iterieren (z.B. find_in_batches, es sind ca. 1 Drittel aller Personen betroffen)
    - [ ] Bei jeder Person die "Hauptrolle" bestimmen, d.h. die `primary_role` (falls diese existiert), egal ob diese noch aktiv oder gelöscht ist
    - [x] Von der Gruppe dieser Rolle die `hierarchy` nach oben durchsuchen nach einer Gruppe vom Typ `Group::Kantonalverband`
    - [x] Vom Kantonalverband den ersten Eintrag aus `kantonalverband_cantons` auslesen
    - [x] Von diesem politischen Kanton die Sprache ableiten, gemäss Liste von Safari:
      > **DE**
      > Aargau Appenzell Innerrhoden Appenzell Ausserrhoden Bern Basel-Land Basel-Stadt 
      > Glarus Graubünden Luzern Nidwalden Obwalden St. Gallen Schaffhausen Solothurn Schwyz Thurgau Uri Zug Zürich
      > 
      > **FR**
      > Freiburg Genf Jura Waadt Wallis Neuenburg 
      > 
      > **IT**
      > Tessin
    - [x] Falls irgendwo zwischendurch in dieser Kette von Logik kein Ergebnis gefunden wird (z.B. keine Rollen, kein Kantonalverband, etc.), einfach auf Deutsch zurückfallen.
- [x] Neue Spalte `text filter_chain` auf der Tabelle `mailing_lists` via Migration hinzufügen
- [x] In der ["Abonnenten"-Ansicht](https://github.com/hitobito/hitobito/blob/master/app/views/subscriptions/_list.html.haml) neuen Abschnitt ungefähr gemäss Mockup hinzufügen
  - [x] Eingestellte Filter visualisieren, z.B. wie im Mockup
- [x] Bei Klick auf den Edit-Button kommt man auf eine neue `edit_filter_chain` Action im `SubscriptionsController` (diese in den Routen hinzufügen)
- [x] View für die neue Action erstellen
  - [x] Filter-UI ungefähr an das [bestehende UI bei den Personenfiltern](https://github.com/hitobito/hitobito/blob/master/app/views/people_filters/_form.html.haml) anlehnen, muss aber nicht zwingend 1:1 dasselbe sein wenns Optimierungspotenzial gibt
  - [x] Mindestens die Filter nach Alter und Sprache im UI anzeigen. Wenn am Schluss noch mehr Zeit übrig ist, können auch noch mehr Filter bearbeitbar gemacht werden
- [x] Speichern-Aktion soll die neue `text_filter_chain` Spalte auf der MailingList befüllen (permitted_attrs o.ä. nicht vergessen). Bei den Personenfiltern passiert das durch konventionsgemässe Benennung der Inputfelder plus [Logik im PeopleFiltersController](https://github.com/hitobito/hitobito/blob/master/app/controllers/people_filters_controller.rb#L69)
- [x] Sicherstellen dass ein gesetzter Filter auch später wieder bearbeitet werden kann
- [ ] Optional falls die Zeit reicht: Für Filterung nach mehreren Sprachen (z.B. fr ODER it) einen neuen Vergleichsoperator "ist einer von" für mindestens das Sprache-Attribut implementieren, und zwar [im Formular](https://github.com/hitobito/hitobito/blob/master/app/helpers/people_filter_helper.rb#L33..L39) sowie [in der Filter Chain](https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/attributes.rb#L82..L84)
- [x] In [MailingList::Subscribers#people](https://github.com/hitobito/hitobito/blob/master/app/domain/mailing_lists/subscribers.rb#L15) neu noch die FilterChain der MailingList anwenden
- [ ] Specs schreiben für...
  - [x] Filter auf Abo anzeigen
  - [x] Filter auf Abo bearbeiten
  - [x] Filter wird bei Abo-Exports angewendet
  - [ ] Filter nach mehreren Attributen wird bei Abo-Exports angewendet
  - [x] Neuer Filter nach mehreren Sprachen funktioniert
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
@ThomasEllenberger die verlinkten Features beziehen sich auf die Filterung von Personenlisten. Hier in diesem Issue geht es stattdessen um die Filterung bei Abos.

**Comment by carlobeltrame** [comment]
@Michael-Schaer ich habe noch folgende offenen Fragen:
* Muss nur das gesamte Abo einmal nach Sprache und Alter filterbar sein? Oder jede Gruppen/Rollen-Kombination und jeder Anlass einzeln, sodass ich in demselben Abo sagen könnte "alle Mitglieder unter 30 der Abteilung X, plus alle volljährigen Teilnehmenden von Anlass Y"?
* Auf welche Art muss man nach Alter filtern können? Älter als? Jünger als? Älter oder gleich alt? Jünger oder gleich alt? Zwischen x und y Jahre / Tage alt? Filtern nach Alter oder filtern nach Geburtsdatum (d.h. sollen die Abonnenten mit zunehmendem Alter aus dem Abo ausscheiden / ins Abo aufgenommen werden können oder nicht)?

**Comment by Michael-Schaer** [comment]
Merci für die Rückfrage!

> Muss nur das gesamte Abo einmal nach Sprache und Alter filterbar sein? Oder jede Gruppen/Rollen-Kombination und jeder Anlass einzeln, sodass ich in demselben Abo sagen könnte "alle Mitglieder unter 30 der Abteilung X, plus alle volljährigen Teilnehmenden von Anlass Y"?

Ja, es reicht, wenn das ganze Abo einmal auf die Sprache gefiltert wird.

> Auf welche Art muss man nach Alter filtern können? Älter als? Jünger als? Älter oder gleich alt? Jünger oder gleich alt? Zwischen x und y Jahre / Tage alt? NICHT zwischen x und y Jahre alt? Filtern nach Alter oder filtern nach Geburtsdatum (d.h. sollen die Abonnenten mit zunehmendem Alter aus dem Abo ausscheiden / ins Abo aufgenommen werden können oder nicht)?

Bevorzugen würde ich, wenn das gleich ist wie beim Personenfilter. Aber wenn das den Export deutlich langsamer macht, müssen wir uns das nochmal überlegen. Ein anderes UI als beim Personenfilter fände ich eher schade.

**Comment by carlobeltrame** [comment]
> Bevorzugen würde ich, wenn das gleich ist wie beim Personenfilter.

Beim Personenfilter kann man nach Geburtsdatum wie auch nach Alter in Jahren filtern. Heisst das es sind auch bei Abos beide Arten von Altersfilter gewünscht?

**Comment by Michael-Schaer** [comment]
Das Alter sollte fürs Erste reichen.

**Comment by diegosteiner** [comment]
Ich habe eine erste Version umsetzen können:

![image](https://github.com/hitobito/hitobito/assets/939106/2264cd21-f430-4bc7-a084-226f14dfd437)

![image](https://github.com/hitobito/hitobito/assets/939106/a62078ae-da7c-4ed3-b7e0-a9bb0fe2b239)

nicht technische Fragen, die dabei noch aufgetaucht sind @Michael-Schaer , @carlobeltrame : 

- Sprachfilter: wie muss da das UI funktionieren? So Freitext wie hier ist vermutlich nicht Benutzerfreundlich genug. Allenfalls ein Dropdown mit den Sprachen, die im Wagon verfügbar sind? Dann macht aber die Bedingung «enthält» nicht mehr so viel Sinn.
- Anwendung des Filters: Ist es korrekt, dass mit dem Filter auch explizit hinzugefügte Personen (Subscribers) ausgeschlossen werden könnten?

**Comment by Michael-Schaer** [comment]
Hallo Filou

Merci für den Prototypen, der sieht gut aus!

> Sprachfilter

Hat sich das schon erledigt? Falls nein, fände ich das Dropdown schöner.

> Anwendung des Filters: Ist es korrekt, dass mit dem Filter auch explizit hinzugefügte Personen (Subscribers) ausgeschlossen werden könnten?

Ich würde es aus der Perspektive anschauen: Wenn eine Person sich für das Abo selber anmeldet, aber meine Filter-Kriterien nicht erfüllt, wird sie ausgeschlossen. 

Wenn sich die Person nicht selber anmeldet, könnten wir ev. noch eine Warnung einbauen. "Person X wurde hinzugefügt, entspricht aber nicht deinen Kriterien in den Globalen Bedingungen". Falls das noch im Scope drin ist...

**Comment by diegosteiner** [comment]
@carlobeltrame  und ich haben heute die Varianten durchgesprochen und sind auf folgende, einfache Lösung gekommen: Statt bei den «Feldern» wird der Sprach-Filter separat angezeigt, einfach als Checkboxen. So können alle Möglichkeiten am einfachsten abgedeckt werden:

![image](https://github.com/hitobito/hitobito/assets/939106/9c2fc06a-8997-4816-84f4-d0eb1deafa9d)

Wird so auch beim Personenfilter umgesetzt werden können. Passt das?

**Comment by carlobeltrame** [comment]
> Statt bei den «Feldern» wird der Sprach-Filter separat angezeigt, einfach als Checkboxen.

Mir ist noch aufgefallen dass dieser Sprach-Filter nur hinter einem `FeatureGate.if(:person_language)` verfügbar gemacht werden sollte.

Und Side Note @diegosteiner: Der Sprachfilter müsste theoretisch schon im Core aktiviert sein, falls dieser Feature Toggle aktiv ist: https://github.com/hitobito/hitobito/blob/134d9bd7c957eb40e5748bb09cdb360ae0ac2dc5/config/initializers/person_language.rb#L8..L13
Möglicherweise hattest du einfach den Rails Server noch nicht neu gestartet als du das das letzte Mal ausprobiert hattest? Jedenfalls sollten wir nirgends im Code davon ausgehen dass die `people.language` Spalte einfach existiert, sondern überall mit dem FeatureGate checken. Wenn wir das korrekt so machen, dann wird es auch keine negativen Auswirkungen auf Wagons haben, die keine oder eigene Sprach-Spalten haben (einziges konkretes Beispiel das ich noch gefunden habe ist bei [der Mitte](https://github.com/hitobito/hitobito_die_mitte/blob/master/lib/hitobito_die_mitte/wagon.rb#L28)).

**Comment by diegosteiner** [comment]
@carlobeltrame  Ah, alles klar! Ich setze due Checks noch um.
