### ISSUE TITLE
PEOPLE: JSON:API people#index

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1921]
Dieses Issue ist Teil von [Epic JSON-API](https://github.com/hitobito/hitobito/issues/1920)

GET `/api/people`

# Tech-Spec

- Feature Branch [feature/json-api](https://github.com/hitobito/hitobito/tree/feature/json-api)
- contactables (z.B. phone_numbers) werden nur ausgegeben falls ein entsprechender Parameter gesetzt ist
- Rollen/Primary Group werden nur ausgegeben falls ein entsprechender Parameter gesetzt ist
- max 100 Personeneinträge rendern + pagination unterstützen (Graphiti hat Support für kaminari welches wir bereits verwenden)

# ToDo

- [x] Testframework zu Graphiti ergänzen/installieren https://www.graphiti.dev/guides/getting-started/installation#adding-to-an-existing-app
- [x] Testcases zu people#index schreiben (nur mal titel, blöcke) mit context pro authentifizierungsart (service token, user session, ...)
  - Welche Personen dürfen gelesen/gelistet werden?
  - Access denied wenn nicht authentifiziert
  - Filter nach updated_at grösser als (wird für SWW benötigt um alle geänderten Personen aufzulisten)
  - Service Token auf root Gruppe der Zugriff auf sämtliche Personen in der DB hat
- [x] Anpassen von ServiceToken model und TokenAbility
  - generelles attribut layer_and_below, boolean, default: false, null: false
  - entfernen von people_below
  - TokenAbility anpassen und dessen specs fixen
- [x] Authentifizierung (devise) und Authorisierung (cancan) in neue Controller einbauen
- [x] Verwende default locale :en wenn nicht über localize etwas definiert wurde
  - siehe [commit](https://github.com/hitobito/hitobito/commit/d871721200a59155de5ce41f876f717443ca5942#diff-7981fc8c0d425e97a541d888080def3b61d02ae0206ee300cd1b1dbd6d245428R4)
- [x] Liste der zu rendernden Attribute in PersonResource ergänzen
  - Attribute sind teilweise abhängig von den Berechtigungen
- [x] Implementieren von #index People inkl. Filter nach updated_at, pagination
- [x] Parameter für include contactables (check Graphiti doc)
- [x] Vandal fixen -> siehe [Graphiti Vandal](https://www.graphiti.dev/guides/vandal)
- [x] API Doku erstellen (ggf. gleich unter /api/ als statisches HTML ?) oder link auf Github?
