### ISSUE TITLE
 PEOPLE: JSON:API people#show

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1922]
Dieses Issue ist Teil von [Epic JSON-API](https://github.com/hitobito/hitobito/issues/1920)

GET `/api/people/42`

# Tech-Spec

- Feature Branch [feature/json-api](https://github.com/hitobito/hitobito/tree/feature/json-api)
- contactables (z.B. phone_numbers) werden immer als relationsships mit gerendert bei #show
- Rollen/Primary Group werden immer als relationsships mit gerendert bei #show

# ToDo

- [x] Testcases zu people#show schreiben (nur mal titel, blöcke) mit context pro authentifizierungsart (service token, user session, ...)
  - Welche Personen dürfen gelesen werden?
  - Access denied wenn nicht authentifiziert
  - contactables werden mit ausgegeben
- [x] Authorisierung (cancan) für people#show einbauen
- [x] Implementieren von #show
- [ ] API Doku ergänzen
