### ISSUE TITLE
PEOPLE: JSON:API people#update, create

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1925]
Dieses Issue ist Teil von [Epic JSON-API](https://github.com/hitobito/hitobito/issues/1920)

PATCH `/api/people/42`

POST `/api/people/` optional

# Mockup

Einstellungen Service Token

![image](https://user-images.githubusercontent.com/655627/204162377-8601782d-0c0d-4938-8afa-12c119fd05ba.png)

# Tech-Spec

- Feature Branch [feature/json-api](https://github.com/hitobito/hitobito/tree/feature/json-api)
- contactables (z.B. phone_numbers) können ebenfalls updated werden

# ToDo

- [x] Testcases zu people#update schreiben (nur mal titel, blöcke) mit context pro authentifizierungsart (service token, user session, ...)
  - Welche Personen dürfen aktualisiert werden?
  - Access denied wenn nicht authentifiziert
  - contactables updaten
  - änderungen via PaperTrail festhalten
- [x] ServiceToken um weitere Berechtigungen/Optionen ergänzen:
  - Schreib-Rechte Personen (siehe Mockup)
- [x] Authorisierung (cancan) für people#update einbauen
- [x] Implementieren von #update
- [x] CSRF Token oder evtl. nur über Content Header limitieren
  - https://github.com/cerebris/jsonapi-resources/blob/856f139a95abb0a5efc2949d1706aa1f8f8048b0/lib/jsonapi/acts_as_resource_controller.rb#L168
- [ ] Implementieren von #create falls mit geringem Aufwand ergänzt werden kann (Rollen assignment ?)
- [x] Änderungen via PaperTrail protokollieren (egal ob ServiceToken, User, usw)
- [x] Fix token ability specs
- [x] add spec to make sure it's not possible to update internal attributes (strong params)
- [x] add spec to make sure it's not possible to update another person by overriding id in json payload

**Comment by mtnstar** [comment]
Bestehende Berechtigungen Service Token

![image](https://user-images.githubusercontent.com/655627/206391434-d1390801-3213-4614-a4fb-8ad81d979dfb.png)


Neue Berechtigungen Service Token

![image](https://user-images.githubusercontent.com/655627/206391269-75ffb9e4-eadd-4fec-a569-dbc8bf431103.png)
