### ISSUE TITLE
PEOPLE: JSON:API Finalisierung

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#1926]
Dieses Issue ist Teil von [Epic JSON-API](https://github.com/hitobito/hitobito/issues/1920)

# Tech-Spec

- Feature Branch [feature/json-api](https://github.com/hitobito/hitobito/tree/feature/json-api)
- evtl. api doc mit swagger? https://medium.com/@sushildamdhere/how-to-document-rest-apis-with-swagger-and-ruby-on-rails-ae4e13177f5d

# ToDo

- [x] fix people controller spec update nested phone numbers error 422
- [x] API Doku finalisieren und verifizieren
  - evtl. automatisierte Generation der API Doku? (Inspiration von https://transport.opendata.ch/docs.html ? )
  -  Alte People API Doku als deprecated markieren und auf neue API verweisen
  - Service Token Permissions, ggf. Changelog Eintrag dazu
- [x] Issue #1708 entweder schliessen oder mit aktuellem Stand JSON API ergänzen, Branch/PR zu #1708 löschen, schliessen?
- [x] SWW Wagon anpassen das Wagonspezifische People attrs gerendert werden sieh hitobito/hitobito_sww#50 (title, custom_salutation, Namenszusatz,  Abo # Magazin)
- [x] Rollen auf people#show evtl. auch #index mitausgeben (core)
- [x] vandal ui entfernen (auch aus doc) und nur noch mit swagger arbeiten
- [x] Add json:api link to Settings
- [x]  Update https://github.com/hitobito/hitobito/blob/master/doc/development/07_service_accounts.md
- [x] find bei #show, #update mit scope einschränken
- [x] Document people#index pagination
- [x] Root User wird nicht angezeigt, wenn kein Filter gesetzt ist (wenn man die API mit Olivier Brian abruft). Ein Filter sollte die Menge von Personen höchstens schmälern, nicht erweitern.
- [ ] Anpassung Dokumentation ServiceToken (änderungen berechtigungsmatrix) branch: feature/json-api-finis
- [x] Spec test für Erstellen einer neuen Telefonnr via PATCH person branch: feature/json-api-finis

**Comment by daniel-illi** [comment]
Analyse wieso root user angezeigt wird wenn ein filter gesetzt ist:

- [query ohne filter](https://app.zenhub.com/files/11764575/94a8fba8-fa67-4742-9b15-7e91f602d523/download)

- [query mit filter](https://app.zenhub.com/files/11764575/fb35228d-68e6-4f38-8671-9cc45b9ec955/download)

Der einzige Unterschied ist eine zusätzliche where condition `AND `people`.`updated_at` >= '2020-01-01 00:00:00'`

**Comment by daniel-illi** [comment]
Hoi zäme
Leider habe ich es nicht geschafft, das jsonapi feature vor meinen Ferien abzuschliessen :(

Ich habe die jsonapi Authorisierungsthematik mit Andi und Päscu Zumkehr besprochen.
* Damit die Berechtigungen auch bei sideloads korrekt gesetzt sind, muss der scope jeweils auf der Resource im `#base_scope` definiert sein. Wenn der scope im controller beim resource call als parameter mitgegeben wird, dann gilt der scope auch nur bei diesem Endpunkt. Das wird spätestens dann ein Problem, wenn die resource als sideload über einen anderen Endpunkt abgerufen wird.
* Ein Attribut/Relation kann zwar dynamisch als `:readable` markiert werden, indem ein symbol übergeben wird und eine gleichnamige guard Methode definiert wird. Dasselbe funktioniert leider nicht, um eine Relation als `:writable` zu markieren; wenn ein symbol übergeben wird, betrachtet graphiti dies als truthy und ruft die guard Methode gar nicht erst auf.
* Die readable/writable config bei Relations sind der falsche Ort, um Berechtigungen für sideload/sideposts zu prüfen. Das sollte direkt auf den entsprechenden Resourcen gemacht werden.
* Über den `#context` sollte nur auf Objekte zugegriffen werden, von welchen erwartet werden kann, dass sie immer existieren. Üblicherweise ist der `#context` der controller, über welchen der request empfangen wurde. Auf einer Resource kann man aber nicht wissen, welcher controller das genau ist, denn die Resource kann vom Controller direkt geladen worden sein, oder sie kann über den sideloading mechanismus instanziert worden sein. Im letzteren Fall wäre dann der `#context` der Controller eines "fremden" models. D.h. es sollte nur auf Methoden zugegriffen werden, welche im base controller (`JsonApiController`) vorhanden sind wie z.B. `#current_ability`, `#current_user`.

Ich kämpfe momentan noch mit den Abilities. Auf den Resourcen ist der `#base_scope` jeweils in dieser Art implementiert:

```
    def base_scope
      model_class.accessible_by(current_ability)
    end
```   
 
Das funktioniert leider nicht, wenn beim deklarieren der abilities die block Syntax verwendet wird und dies ist bei hitobito extensiv so gebraucht.
Bei der `PersonResource` wird das umgangen, indem die `PersonReadables` verwendet wird welche genau für diesen use case designt ist (Filtern von Personen scope).
Leider bin ich in diesem Bereich noch nicht genug fit (und ich bin von den hitobito abilities noch etwas überwältigt), um dasselbe für die Resourcen `AdditionalEmailResource`, `PhoneNumberResource`, `SocialAccountResource` umsetzen zu können.
Ich habe die entsprechenden Abilities zwar in `ContactAbility` (sowie in `TokenAbility` und `DoorkeeperTokenAbility`) "implementiert", aber mit block Syntax und daher funktionieren diese abilities nicht mit dem `accessible_by`
