### ISSUE TITLE
[Kurse] BSV-Export: Mindestalter-Einschränkung entfernen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1933]
Beim BSV-Export und dem erweiterten BSV-Export soll die Einschränkung auf das Mindestalter entfernt werden. Achtung: Das Maximalalter von 30 Jahren bleibt bestehen.

Dies soll im Zeitraum Ende März bis Ende April 2023 geschehen.

>Bisher wurden für BSV Subventionen nur Personen zwischen 17 und 30 Jahren berücksichtigt.
Ab dem 01.01.2023 gibt es neu nach unten keine Begrenzung mehr. Somit muss künftig das Mindestalter als Argument hinter unserem MiData Export verschwinden. Exports fürs 2. Halbjahr 2022 macht die PBS im Februar 2023, dann soll die Änderung noch nicht aktiv sein.

@richardjubla @nchiapol das betrifft euch vermutlich auch, oder?

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
@Michael-Schaer , JA ich habe folgende Infos dazu aus unserer Kursadmin (Remo Müller)

Folgende Eingabe erfolgt in Absprache mit Cevi (Thomas Schüpbach) und Pfadi (Philippe Keller) und soll für alle drei Jugendverbände umgesetzt werden:

Hintergrund:
Für Kurse ab dem 1.1.2023 gilt die neue BSV-Verordnung. In dieser fällt das Mindestalter von 17 Jahren weg. Als BSV-Teilnehmende sollen deshalb zukünftig alle Personen bis 30 Jahre gelten (nach Jahrgang, Obergrenze wie bisher). Diese sollen in den BSV-Angaben im jeweiligen Kurs als auch im BSV-Export miteinberechnet werden.

Zeithorizont
Der Release mit dieser Anpassung darf frühestens am 01.03.2023 erfolgen (davor muss der Export noch für das zweite Halbjahr 2022 wie bisher funktionieren) und soll spätestens bis am 30.06.2023 umgesetzt sein (danach wird der Export für das erste Halbjahr stattfinden müssen). Zeitraum ist auf Abläufe von Jubla und Pfadi (Philippe/Emi) abgestimmt, Bestätigung Cevi (Thomas) noch ausstehend.

Anpassungsvorschlag:
BSV-Angaben im Kurs:
Folgende Anzeige in jedem Kurs:

- «Teilnehmende (17-30)» umbenennen zu «Teilnehmende (bis 30)»
- In die Berechnung neu auch alle Teilnehmenden unter 17 Jahren einschliessen

BSV-Export in Kursübersicht:

- Für den Export die Spalte «Teilnehmende (17-30)» umbenennen zu «Teilnehmende (bis 30)»
- In die Berechnung neu auch alle Personen unter 17 Jahren einschliessen

**Comment by nchiapol** [comment]
@Michael-Schaer, @richardjubla: Thomas Schüpbach ist mit dem Anliegen ebenfalls bereits auf mich zugekommen - und ich hatte @ThomasEllenberger mal per Mail darauf angesprochen.

**Comment by Michael-Schaer** [comment]
Siehe: 
https://github.com/hitobito/hitobito_youth/pull/27
https://github.com/hitobito/hitobito_pbs/pull/265

Bei der Jubla müsste wohl noch der Titel hier angepasst werden:
https://github.com/hitobito/hitobito_jubla/blob/master/spec/domain/export/tabular/events/bsv_list_spec.rb

**Comment by ThomasEllenberger** [comment]
Hallo zusammen

@Michael-Schaer , @nchiapol , @richardjubla 
Müsste hier noch etwas umgsetzt werden (im ersten Post steht bis Ende April) oder hat sich dieses Issue durch die Commits von @Michael-Schaer erledigt?

Entsprechend würde ich dieses Issue schliessen, oder ein Folgeissue eröffnen mit den noch zu erledigenden Arbeiten.

**Comment by richardjubla** [comment]
Ich bin an einem Status zu diesem Ticket interessiert. Die @jubla-ch möchte die hier beschriebenen Anpassungen (und unseren [Ergänzungen ](https://github.com/hitobito/hitobito/issues/1933#issuecomment-1335226733)) ebenfalls Umsetzten (Inkrement 2/23). Idealerweise könnten dazu diese Issue mit den Ergänzungen von https://github.com/hitobito/hitobito/issues/1933#issuecomment-1484051539 übernommen werden.

**Comment by carlobeltrame** [comment]
@richardjubla Wenn ich mich richtig erinnere wurde exakt all das bereits von @Michael-Schaer am Hackathon umgesetzt. Den Jubla-Test hatte ich dann nach dem Review und Mergen noch angepasst.

**Comment by richardjubla** [comment]
> Den Jubla-Test hatte ich dann nach dem Review und Mergen noch angepasst.

Danke @carlobeltrame ! Sehe ich in der Testumgebung: 
![image](https://user-images.githubusercontent.com/95908537/233425498-df8b34c8-9fd4-4b71-a106-f8d72276b87c.png)

Wir werden demzufolge das Verhalten Testen und für uns "Abnehmen".

**Comment by tschuepbach** [comment]
Hallo zusammen

Ich denke es bräuchte noch folgende Anpassungen:
- [ ] Die Wohnkantone müssen nicht mehr erfasst werden
- [ ] Neu ist auch das Feld 105: Wurde der Kurs On-Line durchgeführt? (Ich habe noch nicht getestet, ob es diese Spalte für den Import wirklich braucht oder nicht. Bei den meisten Kursarten ist diese Frage bei der Erfassung per default aktiv oder nicht.

Zur Übersicht die Erfassungsmaske vom BSV: (Alter der TN ist noch falsch, sollte aber inzwischen angepasst sein)
![Erfassung_1](https://user-images.githubusercontent.com/40494600/233924900-6a5c4e02-8f7b-4b33-9776-f5fa2485e3f1.jpg)

![Erfassung_2](https://user-images.githubusercontent.com/40494600/233924919-9f9d539c-6379-4907-bc26-9c90d0afdc5a.jpg)

![Erfassung_3](https://user-images.githubusercontent.com/40494600/233924943-30ba803e-6b79-48f0-a74c-ed292be656ab.jpg)

**Comment by Michael-Schaer** [comment]
@tschuepbach Ich bin einverstanden mit deinen Vorschlägen. Allerdings verwenden wir das Import-Tool vom BSV. Die manuelle Maske brauchen wir nur bei Online-Anlässen und das sind etwa 10 pro Jahr. Das geht für uns also gut weiterhin manuell. 

Den BSV-Export würden wir also gerne der Import-Vorlage des BSV angleichen. Dieses ist allerdings noch nicht aktuell. Bzw. sind dort im Moment die Wohnkantone weiterhin als Spalte drin. Wir würden deshalb lieber noch warten, bis die Anpassung seitens BSV gemacht wurde. Dann können wir den Export 1:1 der neuen Vorlage anpassen.

Hier noch die Antwort auf unsere Frage, ob der Import noch aktuell sei:

> Besten Dank für Ihre Email und ja, wir haben festgestellt, dass die neuen Zuschläge (und Wegfall der Kantonsangaben) eine kleine technische Anpassung erfordern. Bitte gedulden Sie sich noch etwas mit dem Erfassen. Wir werden uns so bald als möglich wieder bei Ihnen melden.

**Comment by tschuepbach** [comment]
Spannend. Das BSV hat mir geantwortet, dass sie keine Import-Vorlagen zur Verfügung stellen. 😅Aus diesem Grund habe ich mich an der manuellen Eingabemaske orientiert. Wir warten ✌🏽

**Comment by Michael-Schaer** [comment]
Merci für die Links! Für uns würde es ausreichen, wenn wir das an einem Hackathon lösen. Z.B. die Wohnkanton-Spalte entfernen und und eine neue Spalte "Online (Werte sind immer 0)" einbauen.
