### ISSUE TITLE
Supports Applications Anpassungen reverten

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#1950]
## Beschrieb
Aufgrund eines Missverständnisses wurde #1904 falsch implementiert. Daher reverten wir jetzt die damit zusammenhängenden Anpassungen.
Wichtig ist, dass die Migration nicht entfernt, sondern das DB-Feld in einer neuen Migration entfernt werden muss. Grund dafür ist, dass es bereits auf einigen Umgebungen angewandt wurde.

## ToDo
- [x] Commits reverten
  - [x] https://github.com/hitobito/hitobito/commit/d5836e4d8be1fea8db064e7799f3f0942bca4826
  - [x] https://github.com/hitobito/hitobito/commit/caa3df961f194c21becc759b386766c9a2f44a5b
  - [x] https://github.com/hitobito/hitobito_jubla/commit/986f767f691b7420d6798569e7f95ce418366966
  - [x] https://github.com/hitobito/hitobito_pbs/commit/81d5a8305e8e93683ea6a1ad146762da4de7e565
- [x] Neue Migration im Core um `events.supports_applications` wieder zu entfernen
- [ ] Übersetzungstexte im Cevi Wagon anpassen
