### ISSUE TITLE
PERSON: Einverständnis Datenweitergabe J+S einholen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1956]
Als Verband möchte ich das Einverständnis von Neumitgliedern für meine Datenschutzerklärung (DSE) einholen.

Dieses Ticket ist der PBS-spezifische Teil extrahiert von #1881

# Funktionalität
### Einverständniserklärung bei Anmeldung bei Lagern / Kursen
Für Lager gelten spezielle Datenschutzbestimmungen (Beispiel: Weitergabe der Daten an J+S durch den Coach). Diese Bestätigung kann bei den Anmeldeangaben als vorkonfiguriertes, obligatorisches Feld hinzugefügt werden. Das Feld erscheint nicht, wenn der Rahmen als Nicht-J+S Lager gewählt ist:

![grafik](https://user-images.githubusercontent.com/1799621/197744689-fd5d22c7-db0c-4488-a27d-fd143163a669.png)

##### Allgemein
Hilfetexte erlauben, wo möglich, Erklärungen für die Personen, die eine Anmeldung machen, zu hinterlegen.

# Mockup
(nur unterer Screenshot ist relevant)
![DSE_Lager](https://user-images.githubusercontent.com/1799621/197743780-bc177426-2330-4452-854f-600f1cc3f1b1.png)

# Tech spec
- Umsetzung im PBS Wagon, weil das Feld "J+S-Rahmen" auch nur dort existiert
- Noch offen: Umsetzung als Attribut auf Participation, oder als spezielle, nicht löschbare, nicht bearbeitbare Anmeldeangabe (Event::Question)?
  - Vorteile Attribut auf Participation: Wird automatisch immer fix angezeigt, Validierung ist mehr Rails-like, Übersetzung trivial möglich, Platzierung der Frage nach allen anderen Fragen trivial immer fix, Hilfetext möglich, Wording kann (einfacher) variiert werden je nach dem ob ich mich selber oder jemand anderen für das Lager anmelde
  - Vorteile Event::Question: Visuell automatisch gleich behandelt wie andere Fragen, möglicherweise keine DB-Migration, Zustimmung ist als "Weitere Spalte" abrufbar (nur nützlich in der Übergangsphase während es noch Lager mit nicht akzeptierenden Participations gibt)

# ToDo

- [x] Views und Controllers anpassen
  - :exclamation: Das Formular soll jeweils invalide sein wenn die Checkbox nicht aktiviert ist (Validierung schreiben)
  - [x] **Im PBS-Wagon**: Bei Anlassanmeldung zu J+S-Lager / J+S-Kurs im Schritt Anmeldeangaben Checkbox mit der die Datenweitergabe an J+S akzeptiert werden muss
    - [x] Migration neue Spalte `participations, :j_s_data_sharing_accepted_at, :timestamp, null: true`
    - [x] Formular anpassen in neuer View Extension im PBS Wagon [[core view mit `render_extensions`]](https://github.com/hitobito/hitobito/blob/master/app/views/event/participations/_form.html.haml#L38) [[wagon controller]](https://github.com/hitobito/hitobito_pbs/blob/master/app/controllers/pbs/event/participations_controller.rb)
    - [x] Auch dieses Feld, wie alle anderen neuen Checkboxen, soll obligatorisch angehakt werden (Validierung schreiben)
    - [x] Text der Checkbox als Custom Content mit Links konfigurierbar machen, ähnlich wie der [Pfadi-Finder Custom Content](https://github.com/hitobito/hitobito_pbs/blob/master/db/seeds/custom_contents.rb#L519..L524)
    - :exclamation: **Achtung** Nur bei Lagern (Event::Camp) und Kursen (Event::Course und Event::Campy) welche `[:j_s_kind_j_s_child, :j_s_kind_j_s_youth, :j_s_kind_j_s_mixed].include?(j_s_kind)` haben
     - :exclamation: **Achtung** wenn die betreffende Person (Participation) schon einmal zugestimmt hat (`j_s_data_sharing_accepted_at.present?`), dann soll die Checkbox aktiviert und disabled angezeigt werden.
      - :exclamation: **Achtung** Wording der Checkbox muss je nach `params[:for_someone_else]` anders sein
- [ ] Specs schreiben
  - [ ] für das angepasste Formular
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by Michael-Schaer** [comment]
Merci fürs auftrennen der Specs! 

Was mich nun etwas verwirrt ist der Teil:

>Es gibt drei Szenarien, um das Einverständnis zur DSE abzuholen.
>3. Anmeldung bei Lagern / Kursen

Der passt irgendwie besser zum Haupt-Issue. Hier geht es ja ums Einverständnis für die J+S-Weitergabe und nicht für die DSE selber.

**Comment by daniel-illi** [comment]
Ich habe die neue Validierung und die Checkbox für Kursteilnehmer implementiert.
Nun habe ich realisiert, dass nicht nur die Teilnehmer "Participants" sinds, sondern auch alle anderen Personen wie Kursleiter etc.
@Michael-Schaer gehe ich richtig in der Annahme, dass die Einverständnisabfrage nur für Teilnehmer relevant ist?

**Comment by Michael-Schaer** [comment]
@daniel-illi Ich tendiere dazu, dass wir das für alle anzeigen. Bei Kursen macht das zwar nur so halb Sinn. 
Aber der Text kann sich ja auch ändern. In solchen Fällen wäre es dann gut, wenn alle informiert sind.

Das bringt mich zu einer Frage: Ist der Text bei Kursen und Lagern unterschiedlich konfigurierbar? Falls das möglich ist, wäre das ein Plus.
