### ISSUE TITLE
FILTER: Zusätzliche Spaltenauswahl Whitelisten

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1958]
### Aktuelles Verhalten

Seit der Umsetzung von PR #1695 müssen Spalten welche bei Personen & Kursansichten ausgewählt werden können Whitelisted werden.
Der Cevi fehlen desshalb einige Spalten, welche sie vorher auswählen konnten.

Spaltenauswahl aktuell auf der Integrationsumgebung:
Personentab:
![integration](https://user-images.githubusercontent.com/100761305/209092530-359e0e82-a290-468f-91f5-68a76fca53ae.png)

Kurse-Tab:
![kurs_in](https://user-images.githubusercontent.com/100761305/209092560-22c9ce48-fff3-4d4c-b0ec-662c98074f05.png)

### Gewünschtes Verhalten

Für die Cevi soll auf dem Personen-Tab, sowie auf dem Kurs-Tab sämtliche Spalten wieder auswählbar sein.

Personentab:
![production](https://user-images.githubusercontent.com/100761305/209092705-363fbccf-d157-4987-be9d-7522764479c3.png)

Kurse-Tab
![kurs_prod](https://user-images.githubusercontent.com/100761305/209092749-e796ccfb-0e3d-4b5b-b325-90e37ebfd10f.png)

### Schritte zu reproduzieren

1. Einloggen auf Cevi Integration
2. Beliebiges Personen oder Kurstab aufrufen
3. Zusätzliche Spalten auswählen anklicken

### Wann ist der Fehler aufgetreten?

01.12.2022

### hitobito version

1.28.37

### Organisation

Cevi

### TechSpec

- Umsetzung im Cevi Wagon
- Doku für das Spalten allowlisting System unter https://github.com/hitobito/hitobito/blob/master/doc/features/table-display-additional-columns.md
- Beispiel im Youth Wagon: https://github.com/hitobito/hitobito_youth/blob/master/lib/hitobito_youth/wagon.rb#L34..L36

### ToDos

- [x] Fehlende Spalten auf Personenlisten im Cevi Wagonfile allowlisten:
  - [x] Zusätzliche Angaben `additional_information`
  - [x] Titel `title`
  - [x] Beruf/Klasse `profession`
  - [x] Eintrittsdatum `joined`
  - [x] AHV-Nummer alt `ahv_number_old`
  - [x] Nationalität `nationality`
  - [x] Mitgliederkarte Nummer `member_card_number`
  - [x] Anrede `salutation`
  - [x] Kanton `canton`
  - [x] Konfession `confession`
  - [x] Korrespondenzsprache `correspondence_language`
  - [x] Alte Daten `old_data`
  - [x] Sprache `language`
- [x] Fehlende Spalten auf Participantion-Listen im Cevi Wagonfile allowlisten:
  - [x] Alle obigen Spalten von Personen
  - [x] AHV-Nummer `ahv_number`
  - [x] J+S Nummer `j_s_number`
  - [x] Nationalität gemäss J+S `nationality_j_s`
