### ISSUE TITLE
KURS: NDS-Export kann nicht importiert werden

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1960]
### Aktuelles Verhalten

Die NDS- Exporte aus der MiData funktionieren zum Upload in die NDS für Kurse noch nicht (für Lager kann es noch nicht getestet werden):

![grafik](https://user-images.githubusercontent.com/1799621/209175066-60ade477-e851-4d9a-a16a-e8e0a6cb36b2.png)

Erst wenn die Daten in die offizielle Vorlage kopiert werden, kann diese dann hochgeladen werden. Ob das ein Fehler von hitobito oder von der NDS ist, und was genau den Fehler auslöst, können wir zur Zeit nicht sagen.

### Gewünschtes Verhalten

Der NDS-Kurs-Export kann ohne Fehler in der NDS importiert werden.

### Schritte zu reproduzieren

- Kurs mit TNs exportieren (NDS-Kurs-Export)
- CSV in der neuen NDS importieren

### Wann ist der Fehler aufgetreten?

22.12.2022

### hitobito version

1.28.35

### Organisation

PBS/MiData

### Screenshots, weiterer Kontext

https://github.com/hitobito/hitobito/issues/1733

### Tech spec
Grund ist, dass die neue NDS UTF-8 encoding verlangt, aber wir konvertieren bisher für Excel-Kompatibilität alle CSVs zu ISO-8859-1.

### ToDos
- [ ] Im Core in https://github.com/hitobito/hitobito/blob/master/app/domain/export/csv/generator.rb#L44 die Options berücksichtigen und es erlauben, Options beim Konstruktor mitzugeben
- [ ] Im Core in https://github.com/hitobito/hitobito/blob/master/app/domain/export/tabular/base.rb#L21 ein Klassenattribut (oder eine statische Methode) für generator_options hinzufügen und diese beim Instanziieren des Generators mitgeben
- [ ] Im Youth Wagon bei den beiden NDS-Exports [[1]](https://github.com/hitobito/hitobito_youth/blob/master/app/domain/export/tabular/people/participations_nds_camp.rb) [[2]](https://github.com/hitobito/hitobito_youth/blob/master/app/domain/export/tabular/people/participations_nds_course.rb) die neuen Generator Options verwenden um das Encoding auf 'UTF-8' zu setzen.

**Comment by kronn** [comment]
Sollte zumindest für die PBS erledigt sein. Für die Jubla kann man das gleiche Setting auch setzen, wenn es sich bewährt.

**Comment by ThomasEllenberger** [comment]
Wird durch #2035 im Core gelöst.
PBS und Jubla haben bereits einen Fix in ihren Umgebungen: https://github.com/hitobito/hitobito_pbs/pull/250
