### ISSUE TITLE
KURS: NDS-Export - Nationalitäten

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#1961]
### Aktuelles Verhalten

Die neue NDS akzeptiert bei der Nationalität nicht mehr die gleichen Werte wie bisher. Deshalb schlägt der Import fehl.

Hitobito gibt Nationalität aus: DIV 
Erlaubte Werte: CH, FL, ANDERE, AUTRE, ALTRO

![grafik](https://user-images.githubusercontent.com/1799621/209175882-52b9c600-8db3-4683-a14c-d1d188e2d202.png)

### Gewünschtes Verhalten

Hitobito gibt einen erlaubten Wert für die Nationalität aus: CH, FL, ANDERE, AUTRE, ALTRO

### Schritte zu reproduzieren

Die anderen beiden Fehler aus dem Screenshot können zur Zeit ignoriert werden.

### Wann ist der Fehler aufgetreten?

22.12.2022

### hitobito version

1.28.35

### Organisation

PBS/MiData

### Screenshots, weiterer Kontext

https://github.com/hitobito/hitobito/issues/1733

### ToDos

- [x] Datenmigration schreiben die bei allen `Personen` und `Event::ParticipationContactData` in der Spalte `nationality_j_s` den Wert DIV durch ANDERE ersetzt
- [x] In `Youth::Person::NATIONALITIES_J_S` den Wert `DIV` durch `ANDERE` ersetzen
- [x] Optional: [Hier](https://github.com/hitobito/hitobito_youth/blob/master/app/views/people/_fields_youth.html.haml#L10) und [hier](https://github.com/hitobito/hitobito_youth/blob/master/app/views/event/participation_contact_datas/_fields_youth.html.haml#L13) das zweite `:to_s` durch ein `Proc.new` ersetzen welches I18n verwendet um den angezeigten Wert zu übersetzen (fr: AUTRE, it: ALTRO). In der DB speichern wir aber auf jeden Fall `ANDERE`.
