### ISSUE TITLE
Elternzugang 1-2: Ändern der Basisdaten des Kindes

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1966]
Teilissue von #603.

# User Story

Nachdem durch Issue #1965 die Möglichkeit geschaffen wurde, zwei Account miteinander zu Verknüpfen, und einen davon als Verwalter\*innen Account und einen als Kinder Account zu definieren, möchte ich als Verwalter\*in die Basisdaten meines Kindes bearbeiten können.

Dazu möchte ich mich in meinen Verwalter\*innen Account einloggen, dort auf den Link zum mir zugewiesenen Kinderaccount klicken und anschliessend auf dem Kinderaccount landen und auf diesem Änderungen vornehmen können, gleich wie wenn dies mein eigener Account wäre.

# Anforderungen

### Ändern der Basisdaten des Kindes

- Ein Verwalter\*innen Account erhält die gleichen Basisrechte zur Profilbearbeitung wie das Kind. Das heisst dieselben Rechte, welche das Kind hätte wenn es keine Rollen hätte. (Nur Rechte die im Core oder im Youth Wagon vergeben werden. Allfällige Zusatzrechte auf sich selber, welche in spezifischeren Wagons vergeben werden, sind hier vorerst mal ausgeschlossen)
- Etikettenformate in den Einstellungen können nicht von Verwalter\*innen bearbeitet werden. 
- Kalenderintegration und OAuth Autorisierungen kann weiterhin nur jede Person für sich selber ansehen. 
- Die Verwalter\*innen werden den Kalenderlink ihrer Kinder aktuell noch nicht sehen.
- Änderungen am “Kind” muss nachvollziehbar sein. (Im Log ersichtlich sein)
- Ich kann auf dem Kind keine Verwalter*innen entfernen wenn ich nur via Verwaltungsbeziehung Schreibzugriff auf das Kind habe. Um meine eigene Verwaltungsbeziehung zum Kind aufzulösen, muss ich mein eigenes Profil bearbeiten.

# Tech-Spec

- Umsetzung grundsätzlich im Youth Wagon, aber an einzelnen spezifischeren Wagons müssen die Anpassungen auch noch nachgeführt werden, wenn Berechtigungen dort überschrieben werden
- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

Bei den Wagon-spezifischen Anpassungen handelt es sich um folgenden Sachverhalt:
Es geht bei Jubla und Cevi um die Frage: Wen darf ich bearbeiten und ihm Eltern zuordnen oder entfernen?
Wir haben die Antwort so definiert: Ich darf das bei all den Personen auf die ich Schreibzugriff habe, aber nicht bei mir selber, und nicht bei meinen zugeordneten Kindern (ausser ich habe via eine (Adressverwalter-)Rolle auch unabhängig von meiner Elternbeziehung Schreibzugriff auf mein Kind).
Auf wen ich so Schreibzugriff habe, wird grösstenteils im Core definiert. Aber Cevi und Jubla haben beide gewisse Detailänderungen an diesen Berechtigungen gemacht, also weiteren Personen Schreibzugriff erteilt (z.B. wer darf Cevi-Spender bearbeiten, wer darf die Kursteilnehmenden von Kursen meiner Ebene bearbeiten). Diese Detailänderungen müssen wir folglich auch beim Erstellenvon Elternbeziehungen nachziehen, also diesen zusätzlichen schreibberechtigten Personen auch die Berechtigung geben, einem Kind Eltern zu geben oder sie zu entfernen.
Würden wir das nicht tun, wäre das auf mehrere Arten inkonsistent.
Einerseits wäre es für User komisch dass sie bei gewissen Personen, die sie bearbeiten dürfen, die Eltern nicht ändern können, bei anderen aber schon.
Andererseits könnte ja z.B. der Cevi sagen, Spender müssen sowieso keine Eltern haben. Wenn wir diese Detailanpassung für den Cevi nicht nachziehen, würde das aber nur beim Erstellen via Kind verhindert. Wenn ein Spendenverwalter nicht das Kind (den Spender) bearbeiten würde, sondern den Elternteil, dann könnte er dort den Spender als neues Kind hinzufügen oder entfernen. Das UI würde die Option "Spender mit Elternteil verbinden" nur im Bearbeiten-Formular des Elternteils erlauben, nicht im Bearbeiten-Formular des Kinds (Spenders), was wiederum inkonsistent ist.
Bei der PBS ist es eine andere Art der Anpassung. Einer der Berechtigungs-Checks die wir im Youth-Wagon anpassen müssen, wird im PBS-Wagon nochmals überschrieben (und die originale Regel die vom Youth-Wagon kommt wird ignoriert / mit der PBS-Regel ersetzt). Also wenn unsere Änderung an diesem Check bei der PBS greifen soll, müssen wir sie zusätzlich dort noch einmal machen.

# ToDo

- [x] In der PersonAbility neu `permission(:any).may(:show, :show_details, :show_full, :history, :update, :update_email, :primary_group, :log, :totp_reset)` sowie `permission(:and).may(:totp_disable)` zusätzlich auch vergeben, wenn eine Manager-Beziehung besteht.
  - [x] Achtung: Nicht einfach eine neue Zeile hinzufügen, die bisherigen Bedingungen müssen auch miteinbezogen werden. Also müssen vermutlich neue Condition-Methoden `herself_or_manager` bzw. `herself_or_manager_if_two_factor_authentication_not_enforced` erstellt werden.
  - [x] Jegliche oben nicht erwähnten Abilities (z.B. `:update_settings`) oder in den Wagon definierten Abilities werden **nicht** an Managers vergeben, sollen also weiterhin z.B. nur an `.herself` hängen
  - [x] Im PBS-Wagon muss die Condition-Methode `if_member_of_crisis_group_or_oneself` entsprechend auf `if_member_of_crisis_group_or_oneself_or_manager` erweitert werden
- [x] Neue Ability `may(:change_managers)` in der PersonAbility erstellen. Diese soll unter all denselben Umständen vergeben werden, wie die `may(:update)` Ability, aber **nicht** auf sich selber (`.herself_or_manager`)
  - [x] Im Jubla-Wagon muss diese neue Ability entsprechend auch noch bei zwei Spezialfällen [[1]](https://github.com/hitobito/hitobito_jubla/blob/master/app/abilities/jubla/person_ability.rb#L17) [[2]](https://github.com/hitobito/hitobito_jubla/blob/master/app/abilities/jubla/person_ability.rb#L23) vergeben werden
  - [x] Im Cevi-Wagon muss diese neue Ability entsprechend auch noch bei den Spezialfällen [[1]](https://github.com/hitobito/hitobito_cevi/blob/master/app/abilities/cevi/person_ability.rb#L18) [[2]](https://github.com/hitobito/hitobito_cevi/blob/master/app/abilities/cevi/person_ability.rb#L22..L30) vergeben werden.
- [x] Im [Youth::PeopleController](https://github.com/hitobito/hitobito_youth/pull/24/files#diff-b1661c3f8824e2a7ef161bba9a5b260a093b6a8d25944320fa6f827c721b86ba) (zum Zeitpunkt des Refinements noch nicht gemerged) die Zeile `if current_user.id == entry.id` ändern in `if cannot(:change_managers)`
- [x] In den [people/_fields_youth.html.haml](https://github.com/hitobito/hitobito_youth/pull/24/files#diff-640548e64c225b298bb3ce78af59c1f19c764a76d49179088256419e682ba2aa) (zum Zeitpunkt des Refinements noch nicht gemerged) die Zeile `- unless entry.id == current_user.id` ändern in `- if can(:change_managers)`
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
