### ISSUE TITLE
Elternzugang 1-3: Anmelden an einem Anlass

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1967]
Teilissue von #603.

# User Story

Wenn ich als Verwalter\*in durch einen externen Link, oder in Hitobito auf einen Anlass/Kurs/Lager gelange, will ich dort auswählen können wen ich zu diesem anmelde. Mich, oder einen durch mich verwalteten Account. 
Dabei will ich nicht Account wechseln müssen und will ohne auf einen anderen Account wechseln zu müssen auch mehrer Personen nacheinander anmelden können (mehrere Kinder, oder mich und mein Kind).

# Anforderungen

### Anmeldung an einen Anlass
- Bei der Anmeldung zu einem Anlass, Kurs oder Lager (Zukünftig nur noch Anlass genannt) kann die Person mit dem Verwalter\*innen Account wählen, ob sie sich oder eines der Kinder anmelden möchte.
- Verwalter*innen-Accounts können die gleichen Anlässe sehen wie ihre Kinder, auch wenn sie sich selber nicht auf diesen Anlass anmelden können.
- Dabei werden nur diejenigen Personen angezeigt, welche diesen Anlass sehen können (direkt, nicht via ihre Kinder).
- Falls jemand bereits für diesen Anlass angemeldet ist, wird er\*sie ausgegraut und unklickbar gemacht.
- Pro Teilnehmer\*in ist weiterhin eine separate Anmeldung nötig.
- An folgenden Orten ist dies möglich:
    • Direkt auf dem Anlass
    • Anlass/Kursliste auf Gruppe
    • Anlass-Liste (links im Menu /list_events)

# Mockup

![image](https://user-images.githubusercontent.com/100761305/210536468-3fc65252-a186-4012-8d4a-732a498101a2.png)

# Tech-Spec

- Umsetzung im Youth Wagon, aber einige Dinge müssen vermutlich im Core refactored werden, damit sie im Youth Wagon einfacher zu überschreiben sind.
- Bisher ist die Selbst-Anmeldung nur durch die Sichtbarkeit des Anlasses abgesichert. Also der Button "Anmelden" ist immer sichtbar, sobald ich den Anlass anzeigen kann (und der Anlass gerade Anmeldung unterstützt). Anders gesagt: Es gibt bisher keine Berechtigung, in der ich den Anlass sehen kann aber mich selber nicht anmelden kann. Da mit diesem Feature neu aber die Möglichkeit für Eltern dazukommt, Anlässe anzuzeigen, für die sie sich selber oder einige ihrer Kinder nicht anmelden können, müssen wir das neu zwingend überprüfen. Die Überprüfung könnte ungefähr so funktionieren: `Ability.new(child).can? :create, participation` und dann in der participation_ability.rb im Core Regeln dafür ergänzen, die die bisherigen Regeln von `can? :show, event` wiederspiegeln.
- Für die diversen Anpassungen an den Abilities könnten wir einen Mechanismus brauchen, der nicht nur `user` berücksichtigt, sondern auch `user.manageds`. Ich stelle mir etwas im folgenden Stil vor:
  ```ruby
  on(Event) do
    for_self_or_manageds do
      permission(:any).may(:show).in_same_layer_or_globally_visible_or_participating
    end
  end
  ```
  Bin aber noch nicht sicher, ob das einfach umsetzbar ist, oder ob wir einfacher jeweils alle untenstehenden Abilities von Hand überschreiben.
- Abgrenzung: Die externe Anmeldung (wenn man noch keinen Account auf hitobito hat) zu Anlässen die das zulassen ist hier ausgeklammert, wird in #1970 angeschaut
- Abgrenzung: Das direkte Erfassen neuer Kinder während der Anmeldung zu einem Anlass ist hier ausgeklammert, wird in #1969 angeschaut

# ToDo

- [x] Die Regel `permission(:any).may(:create).her_own_if_application_possible` muss im Core angepasst werden, damit sie miteinbezieht, ob die betroffene Person den Anlass überhaupt anzeigen darf. [Beispiel für Delegation an eine andere Ability](https://github.com/hitobito/hitobito/blob/master/app/abilities/person_duplicate_ability.rb#L31). Am besten gleich so implementieren: `Ability.new(participation.person).can? :show, event`, nicht mit `user` oder `current_person` oder so arbeiten, weil es so im Youth Wagon einfacher zu erweitern ist. 
- [x] In event_ability.rb die Bedingungen folgender Abilities so erweitern, dass sie jeweils nicht nur `user` berücksichtigen, sondern auch `user.manageds`:
  - [x] `permission(:any).may(:show).in_same_layer_or_globally_visible_or_participating`
  - [x] Wenn möglich, `class_side(:list_available).if_any_role` (falls der Elternteil keine Rollen hat aber das Kind schon, soll der Elternteil trotzdem Anlässe auflisten können)
- [x] In event/participation_ability.rb die Bedingungen folgender Abilities so erweitern, dass die `her_own` Bedungungen jeweils nicht nur `user` berücksichtigen, sondern auch `user.manageds`:
  - [x] `permission(:any).may(:show).her_own_or_for_participations_read_events`
  - [x] `permission(:any).may(:show_details, :print).her_own_or_for_participations_full_events`
  - [x] `permission(:any).may(:create).her_own_if_application_possible`
    - [x] Diese Regel wurde ja im Core oben angepasst. Im Youth Wagon muss geprüft werden, dass einerseits `participation.person` in `[user, *user.manageds]` enthalten ist, und andererseits muss weiterhin mit `Ability.new(participation.person).can? :show, event` geprüft werden, ob das Kind selber den Anlass sehen dürfte
  - [x] `permission(:any).may(:destroy).her_own_if_application_cancelable`
  - [x] Wenn möglich, `general(:create).at_least_one_group_not_deleted` (falls der Elternteil keine Rollen hat aber das Kind schon, soll der Elternteil trotzdem Anlässe auflisten können.) Falls das nicht möglich ist, muss möglicherweise dieser `general` Constraint im Core in alle normalen `permission(...).may(:create)` eingebaut werden, und dann im Youth Wagon entsprechend für sich selbst und für alle Manageds erlaubt werden
- [x] In event/application_ability.rb die Bedingungen folgender Abilities so erweitern, dass die `her_own` Bedungungen jeweils nicht nur `user` berücksichtigen, sondern auch `user.manageds`:
  - [x] `permission(:any).may(:show_priorities, :show_approval).her_own`
- [x] In event/invitation_ability.rb die Bedingungen folgender Abilities so erweitern, dass die `her_own` Bedungungen jeweils nicht nur `user` berücksichtigen, sondern auch `user.manageds`:
  - [x] `permission(:any).may(:decline).own_invitation`
- [x] In event/participation_contact_data_ability.rb die Bedingungen folgender Abilities so erweitern, dass die `her_own` Bedungungen jeweils nicht nur `user` berücksichtigen, sondern auch `user.manageds`:
  - [x] `permission(:any).may(:show, :update).her_own`
- [ ] Folgende Views und Helpers müssen im Youth Wagon erweitert werden, und dafür möglicherweise im Core refactored, damit sie einfacher im Wagon anzupassen sind.
  - [x] https://github.com/hitobito/hitobito/blob/master/app/controllers/events_controller.rb erweitern, sodass alle open_invitations und alle user_participations von sich selber und allen Kindern an die Views gegeben werden
  - [ ]  https://github.com/hitobito/hitobito/blob/master/app/views/events/_actions_show.html.haml und https://github.com/hitobito/hitobito/blob/master/app/helpers/dropdown/event/participant_add.rb
    - [x] Falls Kinder vorhanden sind, im Dropdown auch die Kinder anbieten
    - [x] Aber: Nur Personen (sich selber oder Kinder) anbieten, die `Ability.new(person).can? :create, hypothetical_participation_for(person)` können, also die **sich selber** für den Anlass anmelden könnten
    - [x] Personen die bereits am Anlass teilnehmen oder auf der Warteliste oder Pending sind als disabled anzeigen, mit Hinweis in Klammern "bereits angemeldet", "auf Warteliste", etc.
    - [x] Abmeldungs-Feature aus diesem Button entfernen, man kann sich via Participation Banner oder via optionales separates Dropdown abmelden
    - [ ] Optional: Zusätzlich ein ähnliches Dropdown hinzufügen, um sich selber oder Kinder wieder aus dem Anlass abmelden zu können. Natürlich nur angemeldete Personen anbieten, für welche `Ability.new(person).can? :destroy, participation` erlaubt ist
  - [x] https://github.com/hitobito/hitobito/blob/master/app/views/events/_banner_participating.html.haml und https://github.com/hitobito/hitobito/blob/master/app/helpers/event/participation_banner.rb erweitern sodass für sich selber und alle Kinder je ein Banner da ist (für alle die am Anlass angemeldet sind). Falls die Banner kombiniert werden, muss trotzdem noch die Möglichkeit da sein, jede Person einzeln wieder abzumelden
  - [x] https://github.com/hitobito/hitobito/blob/master/app/views/events/_banner_open_invitation.html.haml erweitern, sodass für sich selber und alle Kinder je ein Banner da ist (für alle die eingeladen sind).
- [x] Specs schreiben, mögliche zu testende Workflows siehe nächster Punkt
- [ ] **Wenn fertig implementiert, folgende Workflows noch einmal manuell durchtesten** (und am liebsten hätten wir für all diese auch automatisierte Tests, aber das ersetzt nicht das finale manuelle durchklicken):
  - [x] Ich habe keine Kinder, und melde mich für einen Anlass meiner Ebene an
  - [x] Ich habe Kinder, und melde mich selber für einen Anlass meiner Ebene an
  - [x] Ich habe Kinder in komplett anderen Gruppen, und melde ein Kind für einen Anlass *seiner* Ebene an (ich sollte mich selber dort nicht anmelden können)
  - [x] Ich bin für einen Anlass angemeldet, und sehe das auf einem entsprechenden Banner wenn ich den Anlass ansehe.
    - [x] Ich kann mich selber via Button im Banner vom Anlass abmelden
    - [ ] Falls Option umgesetzt: Ich kann mich selber via "Abmelden"-Button in den actions_show vom Anlass abmelden
  - [x] Mein Kind ist für einen Anlass angemeldet, und ich sehe das auf einem entsprechenden Banner wenn ich den Anlass ansehe.
    - [x] Ich kann mein Kind via Button im Banner vom Anlass abmelden
    - [ ] Falls Option umgesetzt: Ich kann mein Kind via "Abmelden"-Button in den actions_show vom Anlass abmelden
  - [x] Ich bin für einen Anlass eingeladen aber noch nicht angemeldet, und sehe das auf einem entsprechenden Banner wenn ich den Anlass ansehe
    - [x] Auf dem Einladungs-Banner von mir selber kann ich den Button bedienen, um mich selber anzumelden
  - [x] Mein Kind ist für einen Anlass eingeladen aber noch nicht angemeldet, und ein anderes Kind (oder ich selber) ist bereits angemeldet. Das sehe ich auf den entsprechenden Bannern wenn ich den Anlass ansehe
    - [ ] Auf dem Einladungs-Banner meines Kindes kann ich den Button bedienen, um mein Kind anzumelden
  - [x] In einem Anlass meiner Ebene kann ich niemanden anmelden, wenn die Anmeldung auf dem Anlass deaktiviert ist
  - [x] Einen Anlass der Gruppe meiner Kinder kann ich anzeigen, aber ich kann niemanden anmelden, wenn die Anmeldung auf dem Anlass deaktiviert ist
  - [ ] Ich kann meine eigene Teilnahme am Anlass bearbeiten (z.B. Event Questions beantworten, Bemerkungsfeld ausfüllen)
  - [ ] Ich kann die Teilnahme meiner Kinder bearbeiten (z.B. Event Questions beantworten, Bemerkungsfeld ausfüllen)
  - [x] (Testen mit PBS Wagon) Wenn ich mein Kind für einen Kurs anmelde (unabhängig dem Feld "Priorisierung" auf dem Event), ist die Anmeldung nicht automatisch zugeteilt, sondern landet in der rechten Spalte auf dem "Anmeldungen" Tab
  - [x] (Testen mit PBS Wagon) Wenn ich mich selber für einen Kurs anmelde (unabhängig dem Feld "Priorisierung" auf dem Event), ist die Anmeldung nicht automatisch zugeteilt, sondern landet in der rechten Spalte auf dem "Anmeldungen" Tab
  - [ ] (Testen mit non-PBS Wagon) Wenn ich mein Kind für einen Kurs anmelde (auf dem Priorization aktiviert ist), ist die Anmeldung nicht automatisch zugeteilt, sondern landet in der rechten Spalte auf dem "Anmeldungen" Tab
  - [ ] (Testen mit non-PBS Wagon) Wenn ich mich selber für einen Kurs anmelde (auf dem Priorization aktiviert ist), ist die Anmeldung nicht automatisch zugeteilt, sondern landet in der rechten Spalte auf dem "Anmeldungen" Tab
- [ ] Kunde wegen Übersetzungen informieren

**Comment by carlobeltrame** [comment]
Noch offen: Manuelles Durchtesten aller obiger Use Cases.
