### ISSUE TITLE
Elternzugang 1-4: Digitale Korrespondenz

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1968]
Teilissue von #603.

# User Story

Bin ich als Verwalter\*in von einem anderen Account eingetragen, so möchte ich auch sämtliche digitale Korrespondenz erhalten, welche an diesen Account versendet würde.

# Anforderungen

### Digitale Korrespondenz von Kinderaccounts erhalten
- Verwalter\*innen Accounts sollen sämtliche Korrespondenz der ihnen zugewiesenen Kinderaccounts erhalten.
- Hat ein Kinderaccount mehrere Verwalter\*innen, so erhalten alle die Korrespondenz.
- Dies gilt für den Abo-Mailversand, einen Email-Adressen-Export und für einen Mailchimp-Export

# Tech-Spec

- Abgrenzung: Folgende Mails können aus Sicherheitsgründen nicht an die Eltern zugestellt werden:
  - Passwort-Reset bzw. "Login schicken"-Mail
  - E-Mail-Verifikation
  - Login-E-Mail bei Selbstregistrierung via externen Anlass
  - BulkMail Delivery Report (wenn ich ein Mail an ein Abo mit aktivierter Versandbestätigung schicke, bekommt nur der Absender (Mail From) die Versandbestätigung. Wir rekonstruieren hier nicht, welche hitobito-Person das Mail versendet hat, darum können wir die Versandbestätigung auch nicht an die Eltern senden)
- Der Inhalt der Mails wird (zumindest vorerst) nicht abgeändert in der Kopie die die Eltern erhalten. Das könnte bei einigen Mails verwirrend sein (z.B. Anmeldungs-Bestätigung für Anlass, Impersonierungs-Notification), aber es wäre deutlich mehr Aufwand, die Mailinhalte überall anzupassen. Wo nötig kann später noch der Empfänger-Name in den Mailtext eingebaut werden, um die allfällige Verwirrung in Grenzen zu halten.
- Wäre machbar, aber wegen Zusatzaufwand nicht gewünscht:
  - Impersonierungs-Notications (wenn mich jemand imitiert oder damit aufhört bekomme ich ein Mail, falls ich einen Login habe. Soll dieses Mail auch ausgelöst werden wenn ich kein Login habe aber meine Eltern schon?) -> nicht nötig
  - Wenn mir ein Druckauftrag gestellt wird, dann geht das bisher nur an meine Haupt-Mailadresse (Druckaufträge sind bei den Jugendverbänden bisher soweit ich weiss gar nicht aktiviert) -> nicht nötig
  - Rechnungen die via E-Mail zugestellt werden (werden nur an die auf der Rechnung gespeicherte einzelne Empfänger-Adresse gesendet) -> separates Ticket #2057 
  - Möglicherweise vereinzelt weitere Mails, die in den Wagons definiert werden. Faustregel ist, wenn ein Mail bisher auch an die zum Versand markierten weiteren Mailadressen versendet wurde, dann geht es neu zusätzlich auch an die Eltern. Ehemaligen-Mails von der Jubla versenden z.B. bisher nur an die Haupt-Mailadresse, darum werden allfällige Eltern auch keine Ehemaligen-Einladungs-Mails für ihre Kinder bekommen. Wir könnten das natürlich ändern, falls konkrete Mailversände trotzdem an die Eltern gehen müssten. -> Jubla Ehemaligenmails nicht nötig

# ToDo

- [x] [MailRelay::AddressList](https://github.com/hitobito/hitobito/blob/master/app/domain/mail_relay/address_list.rb) im Youth Wagon so erweitern, dass der `people` Getter zusätzlich zu allen `@people` noch deren Verwalter\*innen zurückgibt
- [x] [Messages::BulkMail::AddressList](https://github.com/hitobito/hitobito/blob/master/app/domain/messages/bulk_mail/address_list.rb) im Youth Wagon so erweitern, dass die Methoden `preferred_addresses` und `default_addresses` noch die entsprechenden Versand-Mailadressen der Verwalter\*innen zurückgibt (mit `prepend` erweitern, dann hat man noch Zugriff auf die originale Core-Implementation, um die Versand-Mailadressen der Eltern zu bestimmen).
- [x] [Synchronize::MailChimp::Subscriber::mailing_list_subscribers](https://github.com/hitobito/hitobito/blob/master/app/domain/synchronize/mailchimp/subscriber.rb#L15..L20) im Youth Wagon so erweitern, dass die Mailadressen der Eltern in jedem Fall ebenfalls mitgegeben werden. Je nach Setting `mailing_list.mailchimp_include_additional_emails` nur die Haupt-Mailadresse oder auch die weiteren Mailadressen der Eltern.
- [ ] Optional: Im [ImpersonationController](https://github.com/hitobito/hitobito/blob/master/app/controllers/person/impersonation_controller.rb#L21) die Bedingungen im Core in eine Methode verpacken und im Youth Wagon zusätzlich auch den Login-Status jeglicher Verwalter\*innen berücksichtigen
- [x] In person/add_request_ability.rb die Bedingungen folgender Abilities so erweitern, dass die `her_own` Bedungungen jeweils nicht nur `user` berücksichtigen, sondern auch `user.manageds`:
  - [x] `permission(:any).may(:approve, :reject).herself`
  - [x] `permission(:any).may(:reject).her_own` (nein, das ist kein Duplikat von oben)
  - [x] `permission(:any).may(:add_without_request).herself`
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
> # Offene Fragen
> 
>       * Impersonierungs-Notications (wenn mich jemand imitiert oder damit aufhört bekomme ich ein Mail, falls ich einen Login habe. Soll dieses Mail auch ausgelöst werden wenn ich kein Login habe aber meine Eltern schon?)
Impersonierungs Notifications müssen vorerst nicht an Verwalter*innen versendet werden.
>       * Wenn mir ein Druckauftrag gestellt wird, dann geht das bisher nur an meine Haupt-Mailadresse (Druckaufträge sind bei den Jugendverbänden bisher soweit ich weiss gar nicht aktiviert)
Wird unseres Wissens von keinem Jugendverein verwendet und muss deshalb nicht berücksichtigt werden.
>       * Rechnungen die via E-Mail zugestellt werden (werden nur an die auf der Rechnung gespeicherte einzelne Empfänger-Adresse gesendet)
Wird separat in Issue https://github.com/hitobito/hitobito/issues/2057 angegangen und hier ausggeklammert.
>       * Möglicherweise vereinzelt weitere Mails, die in den Wagons definiert werden. Faustregel ist, wenn ein Mail bisher auch an die zum Versand markierten weiteren Mailadressen versendet wurde, dann geht es neu zusätzlich auch an die Eltern. Ehemaligen-Mails von der Jubla versenden z.B. bisher nur an die Haupt-Mailadresse, darum werden allfällige Eltern auch keine Ehemaligen-Einladungs-Mails für ihre Kinder bekommen. Wir könnten das natürlich ändern, falls konkrete Mailversände trotzdem an die Eltern gehen müssten.
Das spezifische Beispiel der Jubla muss ich noch abklären (Evtl kann @richardjubla sagen, ob Verwalter auch Ehemaligenmails erhalten müssen, oder ob diese ohnehin nur an Personen gehen welche alt genug sind um eine eigene Emailadresse zu haben.) Sämtliche anderen müssten wir getrennt anschauen sobald wir diese finden. Ich finde die oben genannte Faustregel jedoch fürs erste ausreichend.



>     * Abgrenzung: Folgende Mails können aus Sicherheitsgründen nicht an die Eltern zugestellt werden:
>       
>       * Passwort-Reset bzw. "Login schicken"-Mail
>       * E-Mail-Verifikation
>       * Login-E-Mail bei Selbstregistrierung via externen Anlass
>       * BulkMail Delivery Report (wenn ich ein Mail an ein Abo mit aktivierter Versandbestätigung schicke, bekommt nur der Absender (Mail From) die Versandbestätigung. Wir rekonstruieren hier nicht, welche hitobito-Person das Mail versendet hat, darum können wir die Versandbestätigung auch nicht an die Eltern senden)
> 
>     * Der Inhalt der Mails wird (zumindest vorerst) nicht abgeändert in der Kopie die die Eltern erhalten. Das könnte bei einigen Mails verwirrend sein (z.B. Anmeldungs-Bestätigung für Anlass, Impersonierungs-Notification), aber es wäre deutlich mehr Aufwand, die Mailinhalte überall anzupassen. Wo nötig kann später noch der Empfänger-Name in den Mailtext eingebaut werden, um die allfällige Verwirrung in Grenzen zu halten.

Diese Abgrenzungen wurden an die Community kommuniziert und sind so in Ordnung.
