### ISSUE TITLE
Elternzugang 2-1: Zusätzliche Kinder erfassen zu bestehendem Verwalter*innen Account

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1969]
Teilissue von #603.

# User Story

Als Verwalter\*in möchte ich nachdem ich mich mit meinem Account eingeloggt habe und auf einem Anlass/Kurs/Lager gelandet bin auch Kinder zu diesem Event anmelden könne, welche noch keinen Account besitzen. Nach dem erstellen des Accounts lande ich direkt  als diesen Account auf der Eventanmeldung.

# Anforderungen

### Zusätzliche Kinder erfassen zu bestehendem Verwalter\*innen Account
- Ein bestehender Account welcher sich auf ein Event anmeldet (dort gelandet via externem Link, oder über das Eventstab), soll die Möglichkeit haben, ein neues Kind zu erfassen und dieses für den Event anzumelden. 
- Entweder wird dies direkt in einem Dropdown-Menu bei «Anmelden» oder als zusätzlichen Button «Neues Kind für Anmeldung erfassen» umgesetzt. (oder beides?)
- Ein Kind, welches auf diese Art erfasstes wurde, soll automatisch zum Event angemeldet werden. Respektive soll man nach der Erstellung des Kinderaccounts als dieses in der Kursanmeldung landen. 
- Neu erstellte Accounts haben nur eine Eventrolle, sonnst keine Rollen.
- Ein Kind, welches auf diese Art erfasstes wurde, ist automatisch dem Verwalter zugeordnet.
- Beim erstellen des Kindes soll eine Duplettenkontrolle durchgeführt werden. Falls es einen bereits vorhandenen Account gibt, müsste eine Warnung erscheinen, dass es diesen bereits gibt und man sich an die Geschäftsstelle/Verwalter wenden soll. 
- Verwalter\*innen Accounts sollen auch beim Abmelden von Events auswählen können welche Person sie vom Event abmelden, wenn mehrere von ihnen verwaltete Personen angemeldet sind.

### Offene Fragen:
- Ist eine solche Anmeldung entsprechend nur für Events möglich auf welche sich externe Personen anmelden können?
> Da von SJAS und Pro Natura nicht spezifisch so gewünscht, und da sich die anderen Jugendvereine noch nicht sicher sind ob/wie sie dieses Feature nutzen würden, wird dies im Umfang des MVP erstmal für sämtliche Events möglich sein.
- Umsetzung nur für SJAS & Pro Natura, oder im Youth Wagon?
> Wenn es nicht zuviel Mehraufwand nebst dem MVP ist, dann am liebsten im Youth Wagon umsetzen, ~~jedoch für die einzelnen Kunden Wagons deaktivierbar machen.~~
- Dropdown, oder Button, oder beides?
> Abklären mit UX. möglichst einfach bedienbar für Eltern.
> Dropdown ist konsistenter mit anderen Features in Hitobito
- Dublettenabgleich: Erkennt eine Person wenn sie einen neuen Account erstellt, wenn es bereits ein Duplikat dazu gibt?
- Sollen neue Kinder auch direkt auf dem eigenen Account neu hinzugefügt werden können (nicht nur auf einem Event)?
> Ist gemäss Offerte nicht teil des MVP. Wenn nur geringer Mehraufwand, bitte direkt umsetzen.

### Abgrenzung:
- Verwalter Accounts erhalten durch dieses Feature kein spezielles Attribut durch welches festgehalten werden könnte, dass nur Verwalteraccounts selbstständig zusätzliche Kinder erfassen können. -> Wie es umgesetzt wird können sämtliche Accounts welche nicht bereits einem Verwalteraccounts untergeordnet sind sich zusätzliche Accounts hinzufügen.

# Mockup

Umsetzung entweder als Dropdown bei der Anmeldung, oder in einem zusätzlichen Button , oder beides?

![210536925-9f128b71-3ac0-4107-a5b0-04dc99f902ac](https://user-images.githubusercontent.com/655627/234561858-292ad0bf-0374-4afc-b90b-95b3d87a7aa6.png)

# Tech-Spec

- Umsetzung im Youth Wagon
- Die Doublettenprüfung muss für MVP noch nicht anbieten, trotz gefundener Doublette dennoch ein neues Kind anzulegen. In diesem Fall müssen die Eltern sich noch weiterhin bei der Anlassverantwortung melden.

## Neuer Ablauf (high level Beschreibung mit Mockups)
Schritte 1-3 werden in #1970 implementiert, Schritt 4 in diesem Issue, Schritt 5-6 in #1967.
  1. Nicht registrierte Person kommt auf die öffentliche Seite des Anlasses: 
![Screenshot 2023-04-21 at 16-18-46 MiData PBS_MSdS_MSS - Testevent](https://user-images.githubusercontent.com/7566995/233659762-08b6c25e-08bd-4c90-b42d-260bd8d66bd7.png)
  2. Gibt irgend eine Mailadresse ein, wählt einen der beiden Buttons (hat nur auf die Beschriftung im darauf folgenden Formular einen Einfluss) und kommt auf eine Registrations-Seite (nicht Kontaktangaben-Seite wie vormals)
![Screenshot 2023-04-21 at 15-36-23 MiData PBS_MSdS_MSS - Kontaktdaten der teilnehmenden Person erfassen](https://user-images.githubusercontent.com/7566995/233649695-df823ac3-83e8-4841-8a89-f2cc6ba0310f.png)
  3. Man kommt nicht wie vormals auf die Seite mit dem "Bemerkungen"-Feld, wo direkt eine Anlassteilnahme für den neu registrierten Benutzer erstellt würde, sondern nochmals zurück auf den Anlass, mit Bestätigung dass man sich jetzt anmelden kann
![Screenshot 2023-04-21 at 15-43-01 MiData PBS_MSdS_MSS - Testevent](https://user-images.githubusercontent.com/7566995/233651353-451709fd-1256-4092-8669-b69e263ffcfe.png)
  4. Mit dem Anmelden-Dropdown kann man nun sich selber anmelden oder ein neues Kind erfassen. Sich selber anmelden funktioniert wie bisher. Wird ein neues Kind erfasst, kommt man aufs "Kontaktdaten" Formular:
![Screenshot 2023-04-21 at 15-53-05 MiData PBS_MSdS_MSS - Kontaktdaten der teilnehmenden Person erfassen](https://user-images.githubusercontent.com/7566995/233653899-b01f72f8-4e62-465e-b0ee-eceff1d0c34b.png)
5. Im zweiten Schritt füllt man die Teilnahme-Angaben (Anlassfragen und Bemerkungen) aus:
![Screenshot 2023-04-21 at 15-58-15 MiData PBS_MSdS_MSS - Anmeldung als Teilnehmer_-in](https://user-images.githubusercontent.com/7566995/233655203-74670641-a06a-470a-8e7a-e324900fc858.png)
6. Man kommt auf die Teilnahme-Seite der eben erstellten Teilnahme:
![Screenshot 2023-04-21 at 15-59-40 MiData PBS_MSdS_MSS - Kind Hallo](https://user-images.githubusercontent.com/7566995/233655600-616bf402-ed53-4e2e-a7e9-7c370823be0f.png)

Um ein weiteres Kind anzumelden, kann man nochmals auf den Anlass gehen (mit Back Button oder indem man den externen Anlasslink erneut anklickt) und das Anmelden-Dropdown erneut verwenden.

# ToDo

- [x] Im [ParticipantAdd Dropdown](https://github.com/hitobito/hitobito_youth/blob/master/app/helpers/youth/dropdown/event/participant_add.rb) eine neue Option "Neues Kind erfassen und anmelden" einfügen
- [x] Diese neue Option führt einen zu einer View (in einem neuen Controller) die gleich aussieht wie die Event::RegisterController#register View wie sie im Core ist, mit event step wizard und participation_contact_data Formular
  - [x] Einziger Unterschied ist, dass das Haupt-E-Mail Feld nicht required ist
- [x] Beim Absenden wird, wenn die Validierungen gültig sind, eine neue Person angelegt und direkt dem eingeloggten User als Kind untergeordnet.
- [x] Dann wird man auf `new_group_event_participation_path(group, event)` weitergeleitet, als hätte man auf dem Anlass im PersonAdd Dropdown das neue Kind ausgewählt (siehe #1967 wo das implementiert wurde).
  - [x] Übersetzungstext `event/register.registered` abändern auf "*Die* persönlichen Daten wurden aufgenommen. Bitte ergänze nun noch die Angaben für die Anmeldung." (falls das nicht schon in #1967 gemacht wurde)
- [x] Feature Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Workflow von Anfang bis Ende "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Meine Gedanken zu den offenen Fragen:

>  Umsetzung nur für SJAS & Pro Natura, oder im Youth Wagon?

Kann aus meiner Sicht in den Youth Wagon. Es kommt auch bei uns vor, dass Geschwister oder Freunde der Familie fürs nur für ein Lager/Anlass angemeldet werden sollen.

>  Ist eine solche Anmeldung entsprechend nur für Events möglich auf welche sich externe Personen anmelden können?

Hier habe ich keine klare Meinung. Wahrscheinlich lassen sich mit einer solche Einschränkung aber mehr Fälle abdecken (und es ist einfacher als Admin eine Ausnahme manuell zu erfassen als alle Anmeldungen auf problematische Fälle zu kontrollieren.)

> Dropdown, oder Button, oder beides?

Drop-Down scheint mir eleganter und konsistent mit #1967


Weitere Überlegungen:
  * nicht explizit erwähnte Anforderung: "Ein Kind, welches auf diese Art erfasstes wurde, ist automatisch dem Verwalter zugeordnet."
  * Sollte ein Verwalter-Account auch unabhängig von der Anmeldung für sich ein neues Kind erfassen können? Das wäre nützlich für Eltern die bei SJAS möglichst rasch alle Kinder anmelden wollen, oder auch im Fall einer Ausnahme bei externen Anmeldungen. 
  * Wie wird ein neuer Account zu einem Verwalter-Account? Nicht jeder Account sollte sich selbst ein erstes Kind erfassen können.
  * Wichtig beim Erstellen des neuen Kindes ist die Dubletten-Kontrolle.

**Comment by carlobeltrame** [comment]
>     * Wie wird ein neuer Account zu einem Verwalter-Account? Nicht jeder Account sollte sich selbst ein erstes Kind erfassen können.

Diese Anforderung ist mir neu. In #1965 ist es vorgesehen, dass Person A eine neue Beziehung zwischen Person V (Verwalter\*in) und Person K (Kind) herstellen kann, sobald A Schreibzugriff auf K hat, ohne weitere Bedingungen. Dies wurde so konzipiert um der Anforderung rechnung zu tragen, dass Adressverwalter die Beziehung herstellen können, und dass Verwalter\*innen beliebige Rollen (oder gar keine) haben können müssen. "Adressverwalter" ist kein allgemeines Konzept von hitobito, sondern in jedem Wagon anders (oder gar nicht) definiert, daher müssen wir solche Bedingungen an die Berechtigungen (in diesem Fall Schreibberechtigung) knüpfen. Sonst müssten wir ja in jedem Wagon einzeln definieren, welche Rollen jetzt als Adressverwalter\*innen zählen.

Aus diesem Konzept folgt dann automatisch ein Szenario, in dem Person A die gleiche Person wie Person V ist: Man kann sie sich selber jederzeit beliebige Personen als Kinder zuweisen, auf die man schon vorher Schreibzugriff hatte.
Und auf die andere Seite, das Szenario in dem Person A die gleiche Person wie Person K ist: Man kann sich selber jederzeit beliebigen Personen "unterordnen", also sich beliebige Personen als Verwalter\*innen selber hinzufügen.

Falls es dir nur darum geht, das Anlegen von neuen Kindern bei der Anlassanmeldung zu limitieren (im Gegensatz zum Zuordnen von bestehenden Accounts): Ich kann mich nicht erinnern dass wir je über so eine Unterscheidung gesprochen haben. Hitobito kann nicht wissen ob du in real life ein Kind o.ä. hast. Mir fällt kein einfacher Weg ein, das zu lösen. Hast du einen konkreten Use Case im Kopf der diese Unterscheidung wirklich nötig machen würde? Vielleicht können wir daraus relevante Kriterien ableiten..?

**Comment by nchiapol** [comment]
Vielen Dank für dein Ausführungen. 

#### Grundsätzliches
Wie in #1965 beschrieben würde ich es vorziehen wenn

> Man kann sich selber jederzeit beliebigen Personen "unterordnen"

nicht möglich wäre. Schreibrechte auf Verwalter und Kind würde unserer Anforderung von "nur Adressverwalter/AL" besser abdecken. Dafür sehe ich "dass Verwalter*innen keine Rolle haben können" nicht als Anforderung (beim Verknüpfen) - ich weiss auch nicht wo die herkommt. 

#### Neue "Anforderung"
> Nicht jeder Account sollte sich selbst ein erstes Kind erfassen können.

ist in Bezug auf 

> Sollte ein Verwalter-Account auch unabhängig von der Anmeldung für sich ein neues Kind erfassen können? 

gedacht.  Aber auch wenn neue Kinder nur via Anmeldung angelegt werden können: Ein beliebiger TN Account sollte sich nur selbst für einen Anlass anmelden aber sich keine neuen Kinder-Accounts anlegen können.

> Ich kann mich nicht erinnern dass wir je über so eine Unterscheidung gesprochen haben

Korrekt. Wir sind bisher auch gar nicht davon ausgegangen, dass man sich bei uns selbst weitere Kinder erstellen kann. Ich fände diese Funktion aber eigentlich sinnvoll - allerdings nur für Accounts die bereits mindestens ein Kind verwalten und entsprechend bereits "geprüft" sind. 
Ansonsten schaffen wir einen Weg für alle Personen beliebige neue Accounts in der DB zu erstellen - ein Recht, das bisher stark eingeschränkt war. Das läuft Gefahr aus Jux oder mit böser Absicht Missbraucht zu werden - so wie jetzt schon die Felder Beruf oder Anrede Eltern oft mit Spass-Werten ausgefüllt 

#### Missbrauchs Use Cases
  * Junger TN oder verärgerter Ehemaliger legt sich ein Spass-Kind mit lustigem/beleidigendem Namen an und fügt dieses dann bei allen möglichen Lagern hinzu.

  * Jemand verwendet Selbstregistrierung um einen Account in der DB zu erhalten, erstellt dann diverse Fake-Accounts (braucht auf diesem Weg keine weiteren Mailadressen) und fügt diese Lagern (oder je nach Umsetzung von #1965 anderen Personen) hinzu.

#### Umsetzungsoptionen
Ich denke am flexibelsten würde das Recht "Neue Kinder erfassen" von zwei möglichen Bedingungen gewährt:

1.   Ein Account hat bereits Kinder
2.   Ein Account hat eine Rolle mit neuem `verwalter`-Recht

So könnten wir das neue Recht einfach nicht Verwenden und für SJAS & Pro Natura könnte bei der Selbstregistrierung einfach eine Rolle mit diesem Verwalter-Recht vergeben werden.

Alternativ könnte das Recht "Neue Kinder erfassen" auch pro Instanz konfigurierbar sein für entweder `alle accounts` oder `nur accounts` mit bestehenden Kindern. 

Und schliesslich ist es natürlich auch eine Option, dass "Neue Kinder erfassen" bei uns einfach nicht aktiviert ist.

**Comment by ThomasEllenberger** [comment]
Merci für eure Kommentare.

> Umsetzung nur für SJAS & Pro Natura, oder im Youth Wagon?

Kommt vermutlich noch auf die Antworten auf die anderen Fragen an, ob alle Accounts neue Kinder hinzufügen können oder nicht. 
Zudem hätte ich da sicher auch noch gerne die Meinung von @Michael-Schaer und @richardjubla.

> Ist eine solche Anmeldung entsprechend nur für Events möglich auf welche sich externe Personen anmelden können?

Soviel ich weiss sind bei SJAS und Pro Natura die Events immer für externe geöffnet. Daher würde ich diese Anforderung so erstellen, wenn nicht jemand etwas dagegen hat.

>  nicht explizit erwähnte Anforderung: "Ein Kind, welches auf diese Art erfasstes wurde, ist automatisch dem Verwalter zugeordnet."

Merci. Ergänzt.

> Sollte ein Verwalter-Account auch unabhängig von der Anmeldung für sich ein neues Kind erfassen können? Das wäre nützlich für Eltern die bei SJAS möglichst rasch alle Kinder anmelden wollen, oder auch im Fall einer Ausnahme bei externen Anmeldungen.

Dies war meines Wissens nie eine Anforderung. Müssten wir entsprechend vom Aufwand her abschätzen, wenn dies neu gewünscht wäre.

> Wie wird ein neuer Account zu einem Verwalter-Account? Nicht jeder Account sollte sich selbst ein erstes Kind erfassen können.

Für SJAS und Pro Natura ist klar erforderlich dass sich jemand der sich selbst als Externer auf einen Anlass anmeldet anschliessend gleich Kinder zu seinem Account erstellen kann, ohne dass jemand vom Büro da noch Rechte vergeben muss. Pro Umgebung einstellen zu können ob das möglich ist, oder man bereits ein bestehender Account sein muss, oder ein Verwalter Tag dass es bei SJAS und Pro Natura automatisch setzt sind für mich beides mögliche Gangarten falls wir dieses Feature im Youth-Wagon umsetzen. Auch hier müssten wir wieder sehen wieviel Komplexität dies hinzufügt und ob dies im bestehenden Budget umgesetzt werden kann.

> Wichtig beim Erstellen des neuen Kindes ist die Dubletten-Kontrolle.

Merci. Ergänzt. Denke es wäre nützlich dass wenn es hier ein Duplikat kommt, der Verwalter eine entsprechende Meldung erhalten würde, dass dies bereits existiert und er sich an einen Adressverwalter/Geschäftsstelle wenden muss.

**Comment by nchiapol** [comment]
> > Sollte ein Verwalter-Account auch unabhängig von der Anmeldung für sich ein neues Kind erfassen können?

> Dies war meines Wissens nie eine Anforderung.

Einverstanden. Aber ich denke es macht auf jeden Fall Sinn diese Option bei der Umsetzung bereits vorzusehen. Der Prozess um neue verwaltete Kinder zu erfassen, sollte so implementiert werden, dass er bei Bedarf auch von anderen Orten ausgelöst werden kann. Dass wir das dann tatsächlich irgendwo einbauen ist nicht unbedingt Teil eines MVP (Abhängig vom Prozess bei SJAS und Pro Natura).

> Für SJAS und Pro Natura ist klar erforderlich dass sich jemand der sich selbst als Externer auf einen Anlass anmeldet anschliessend gleich Kinder zu seinem Account erstellen kann [...]

Bis jetzt hatte ich das so verstanden, dass der Verwalter-Account nur Kinder und nicht sich selbst für den Anlass anmeldet. [1]  Entsprechend erwarte ich, dass zuerst ein Verwalter-Account angelegt werden muss. Das ist wohl sinnvollerweise die Selbstregistration, auch wenn die hier von der Anlass- statt der Gruppenseite aus gestartet wird und nach Abschluss wieder auf den  Anlass weitergeleitet werden muss. Da die Selbstregistration automatisch eine Rolle vergibt, sollte die Einschränkung damit auch möglich sein, ohne dass jemand vom Büro da noch Rechte vergeben muss. [2]

Haben SJAS und Pro Natura keine Accounts in ihrer Instanz, die sich keine Kinder erstellen sollten? 

[1] Der Verwalter darf sich natürlich selbst anmelden, in der Regel passiert das aber nicht.

[2] Und ich wäre sehr überrascht, wenn SJAS und Pro Natura nicht irgendwo eine Gruppe mit allen Verwaltern führen möchten (d.h. allen Verwaltern eine bestimmte Rolle zuweisen). Wie wollen sie Person am Telefon supporten, wenn sie  nicht auf ihre Accounts zugreifen können?

**Comment by richardjubla** [comment]
> Kommt vermutlich noch auf die Antworten auf die anderen Fragen an, ob alle Accounts neue Kinder hinzufügen können oder nicht.
> Zudem hätte ich da sicher auch noch gerne die Meinung von @Michael-Schaer und @richardjubla.

@ThomasEllenberger 

**Für die Jubla hat diese Story/Anforderung keine hohe Priorität. Wir gehen davon aus, dass Menschen in der Datenbank nicht primär über einen Anlass/Kurs/Lager erfasst werden. Dennoch können wir uns vorstellen, dass dieses Feature im Youth Wagon umgesetzt wird.** 


**Use Case Jubla / Begründung:**
Kinder (und neu deren Eltern) sind normalerweise bereits vor einem Event oder Lager mit der Schar irgendwie verbunden. Kinder als Vereinsmitglieder sollten in der Regel bereits vorhanden sein und ein neuer Datensatz (Anmeldung/Account) nur für einen Anlass/Kurs/Lager eher unüblich.
Wir gehen davon aus, dass sich in Zukunft die Eltern über eine externe Anmeldung (Selbstregistration in Hitobito) einen Account anlegen werden. Die Scharleitung/Adressverwaltung wird dann diese Eltern als Kontaktpersonen (Rolle Extern) als Kontakt pflegen und ihnen die Verbindung der Kinder/Verwalteter Accounts ermöglichen. Für Events/Lager kann dann der Verwalter*in (Eltern) die Anmeldung für die verwalteten Accounts (Kinder) machen (nicht Teil dieser Story).

Das Erfassen von zusätzlichen Kinder(n) wie beschrieben in dieser Story kann aber durchaus auch genutzt werden. Beispielsweise für ein Lager/Schneesportwoche. In diesem Beispiel würden Eltern (auf einen Anlass/Kurs/Lager mit der aktiven Option Externe Anmeldungen erlaubt) ihre Anmeldung für sich (als Verwalter) und ihre Kinder (als für den Event angemeldete und verwaltete Accounts) vornehmen wollen. (Ja, eine solche Anmeldung sollte aus unserer Sicht nur für Events möglich sein, auf welche sich externe Personen anmelden können.)

Die Beziehung der Schar zu diesen Menschen bezieht sich dann "nur" auf diesen Event. (Datensätze und Rollen werden auf den Event bezogen erfasst). Für weitere Verwaltung, Vereinszugehörigkeit etc. werden den Accounts entsprechende Rollen/Ebenen zugewiesen. 
 
**Gedanken** zum Ablauf und den offenen Fragen:
- Der Button (inkl. Konzept) für die Anmeldung bzw. Abmeldung für Events könnte vielleicht so aussehen:
![image](https://user-images.githubusercontent.com/95908537/213397961-11aaae69-c64d-4c17-8ae1-2f8f895f277d.png)
Dies wird aber wohl bedeuten, dass im gesamten Konzept an die An-/Abmeldung gedacht werden muss:
![image](https://user-images.githubusercontent.com/95908537/213395252-0b6dd256-3882-4182-a323-735c2a810ea1.png)

Ein (guter) Weg für die Anmeldung anstelle von Optionen (Dropdown/Button) sollte bevorzugt werden.
- Eine solche Anmeldung entsprechend nur für Events möglich machen, auf welche sich externe Personen anmelden können.
- Umsetzung im Youth Wagon. (Grund: Elternzugang als "gesamtes" Feature ist im Youth Wagon. Optional sauberes aktivieren/deaktivieren ermöglichen.)


- Ich bin mir nicht sicher: Der Button "Neues Kind für die Anmeldung erfassen" bzw. generell die Erfassung von neuen Kindern spielt sollte wohl so direkt wie möglich sein. Als Eltern möchte ich "in einem Durchgang" einen Account und direkt alle Kinder erfassen können. (Ohne den Umweg über Account -> Aktivierung -> Kinder erfassen -> Event -> Kinder Anmelden)

**Comment by Michael-Schaer** [comment]
Ich schliesse mich @nchiapol und @richardjubla an, dass dieses Feature nicht die erste Priorität hat, aber dennnoch nützlich ist für den Youth-Wagon.

> Wie wird ein neuer Account zu einem Verwalter-Account? Nicht jeder Account sollte sich selbst ein erstes Kind erfassen können.

Ich würde die Erfassung erst einmal für alle offen lassen. Wenn wir merken, dass die Funktion häufig missbraucht wird (und dann auch wissen von wem und wie) sollten wir die Funktion sicher einschränken. Wenn ich an die Selbst-Befähigung der Benutzer denke, macht es für mich auch Sinn, wenn wir das zumindest einmal ausprobieren würden.

**Comment by richardjubla** [comment]
**Heureka! Viel Freude zum Vorschritt!!**


....und bereits eine erste Frage:

**Muss ein Kind zwingend eine Haupt-E-Mail Adresse haben und diese aktiv benutzt werden?**

Ein wichtiger Aspekt des Elternzugangs war/ist es doch, dass keine oder nicht mehrere Haupt-E-Mail-Adressen für die Kinder benötigt werden. Unsere Eltern haben sich gewünscht, mit einem Profil/Login mehrere Kinder zu verwalten. 
Nun ist aber für eine Event-Anmeldung das Feld "Haupt-E-Mail" obligatorisch und eine Anmeldung für ein Kind ohne Haupt-E-Mail gar nicht möglich. 
Ist auf der Ebene/Gruppe die Option "Anfragen" aktiviert (bei der PBS überall), wird für eine Event-Anmeldung eine Transaktionsmail an die Gruppenleitung und das Kind ausgelöst. Aus meiner Sicht kann/soll das Kind aber nicht über eine Zugriffsanfrage entscheiden können/müssen.

**Comment by carlobeltrame** [comment]
Hoi Richi. Wo hast du das getestet? In meinen letzten Tests musste das angemeldete Kind keine Haupt-Mailadresse angeben. Vor- und Nachname haben gereicht. Die Anlassverantwortlichen können dies aber glaube ich selber forcieren wenn sie es wollen, nicht?

Eine Zugriffsanfrage wird nicht ausgelöst wenn man sich selber für einen Anlass anmeldet (weil man ja selber über die Weitergabe der eigenen Daten an die Anlassverantwortung entscheidet). Entsprechend habe ich in https://github.com/hitobito/hitobito_youth/commit/d2c9b738d26cfe76db47891b4f010ae8607e515f noch implementiert, dass auch keine Zugriffsanfrage erstellt wird wenn ein Elternteil sein Kind für einen Anlass anmeldet. Auch hier wieder, hast du den topaktuellsten Stand des Codes irgendwo getestet, oder wie kommst du auf deine Aussagen?

**Comment by richardjubla** [comment]
[Version 1.28.74](https://jubla.puzzle.ch/changelog) 

- forcieren bzw. weglassen der Haupt-E-Mail-Adresse geht für Anlässe nicht
- Sofern das Kind ein aktives login hat (Haupt-E-Mail-Adresse) bekommt es auch eine Anfrage für die Zuteilung zu einem Event


![image](https://github.com/hitobito/hitobito/assets/95908537/89fd0540-27ed-4dfc-9030-81160f6b58e7)
![image](https://github.com/hitobito/hitobito/assets/95908537/2a925eae-9478-45a4-8063-d81bdefeae0b)

**Comment by carlobeltrame** [comment]
Ach so, das erklärts ein Stück weit. Du hast spätestens gestern auf der Integration getestet. Den Fix mit der Zugriffsanfrage habe ich erst gestern gemacht, daher ist das erst ab heute aktiv.
Den Punkt mit der obligatorischen Haupt-Mailadresse werden wir im Rahmen unseres eigenen Testings in #1967 noch selber durchtesten, wenn alle Änderungen fertig sind. Ich meine es gestern geschafft zu haben, ein komplett neues Kind ohne Mailadresse hinzuzufügen, aber wir sehens dann noch.

Merci jedenfalls schon mal fürs Testen, aber es ist ein Stück weit noch zu erwarten dass gewisse Dinge heute noch nicht so funktionieren, weil noch nicht alle Teile des Features gemerged sind. Wir werden dir auf jeden Fall mitteilen wenn der Elternzugang auf der Integration komplett ist und eure Testläufe im grossen Rahmen beginnen können.
