### ISSUE TITLE
Elternzugang 2-2: Neuer Verwalter*innen Account erstellen und Kinder zu diesem hinzufügen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1970]
Teilissue von #603.

# User Story
Als Verwalter\*in welche noch keinen Account hat möchte ich mit möglichst wenig Aufwand Accounts für mich und meine Kinder machen und meine Kinderanschliessend auf das Event anmelden können, welches für Externe verfügbar ist.

# Anforderungen 

### Neuer Verwalter\*innen Account erstellen und Kinder zu diesem hinzufügen

- Meldet man sich über einen externen Link an einem Event an, sollen entweder Kinder-Accounts erstellt werden können, welche dann direkt zum Event angemeldet werden, oder einen Verwalter\*innen-Account soll erstellt werden können, welcher selbst nicht zum Event angemeldet wird, aber anschliessend gemäss #1969 Kinderaccounts erstellen kann.
- Nach dem Erstellen des Verwalte\*innen-Accounts kann ein erstes Kind erfasst werden, welches automatisch für den Event angemeldet wird. Anschliessend landet man wieder auf dem Event und kann zusätzliche Kinder erfassen. Diese werden anschliessend wieder direkt am Event angemeldet werden.
- Der neu erstellte Verwalteraccount hat keinerlei Rollen. Der Kinderaccount hat nur im Event eine Eventrolle.

# Mockup
![image](https://user-images.githubusercontent.com/100761305/210537186-84f5949a-5100-44ec-bef1-e47e60b68ef5.png)

# Tech-Spec

- Umsetzung im Youth Wagon

## Neuer Ablauf (high level Beschreibung mit Mockups)
Schritte 1-3 werden in diesem Issue implementiert, Schritt 4 in #1969, Schritt 5-6 in #1967.
  1. Nicht registrierte Person kommt auf die öffentliche Seite des Anlasses: 
![Screenshot 2023-04-21 at 16-18-46 MiData PBS_MSdS_MSS - Testevent](https://user-images.githubusercontent.com/7566995/233659762-08b6c25e-08bd-4c90-b42d-260bd8d66bd7.png)
  2. Gibt irgend eine Mailadresse ein, wählt einen der beiden Buttons (hat nur auf die Beschriftung im darauf folgenden Formular einen Einfluss) und kommt auf eine Registrations-Seite (nicht Kontaktangaben-Seite wie vormals)
![Screenshot 2023-04-21 at 15-36-23 MiData PBS_MSdS_MSS - Kontaktdaten der teilnehmenden Person erfassen](https://user-images.githubusercontent.com/7566995/233649695-df823ac3-83e8-4841-8a89-f2cc6ba0310f.png)
  3. Man kommt nicht wie vormals auf die Seite mit dem "Bemerkungen"-Feld, wo direkt eine Anlassteilnahme für den neu registrierten Benutzer erstellt würde, sondern nochmals zurück auf den Anlass, mit Bestätigung dass man sich jetzt anmelden kann
![Screenshot 2023-04-21 at 15-43-01 MiData PBS_MSdS_MSS - Testevent](https://user-images.githubusercontent.com/7566995/233651353-451709fd-1256-4092-8669-b69e263ffcfe.png)
  4. Mit dem Anmelden-Dropdown kann man nun sich selber anmelden oder ein neues Kind erfassen. Sich selber anmelden funktioniert wie bisher. Wird ein neues Kind erfasst, kommt man aufs "Kontaktdaten" Formular:
![Screenshot 2023-04-21 at 15-53-05 MiData PBS_MSdS_MSS - Kontaktdaten der teilnehmenden Person erfassen](https://user-images.githubusercontent.com/7566995/233653899-b01f72f8-4e62-465e-b0ee-eceff1d0c34b.png)
5. Im zweiten Schritt füllt man die Teilnahme-Angaben (Anlassfragen und Bemerkungen) aus:
![Screenshot 2023-04-21 at 15-58-15 MiData PBS_MSdS_MSS - Anmeldung als Teilnehmer_-in](https://user-images.githubusercontent.com/7566995/233655203-74670641-a06a-470a-8e7a-e324900fc858.png)
6. Man kommt auf die Teilnahme-Seite der eben erstellten Teilnahme:
![Screenshot 2023-04-21 at 15-59-40 MiData PBS_MSdS_MSS - Kind Hallo](https://user-images.githubusercontent.com/7566995/233655600-616bf402-ed53-4e2e-a7e9-7c370823be0f.png)

Um ein weiteres Kind anzumelden, kann man nochmals auf den Anlass gehen (mit Back Button oder indem man den externen Anlasslink erneut anklickt) und das Anmelden-Dropdown erneut verwenden.

# ToDo

- [x] EventAbility im Youth Wagon abändern, sodass man Anlässe mit externen Anmeldungen auch ansehen kann wenn man eingeloggt ist. `permission(:any).may(:show).in_same_layer_or_globally_visible_or_participating_or_public`
- [x] Übersetzungstext `event.register.email_check.enter_email` abändern auf "Bitte gib deine E-Mailadresse ein, *mit der du dich registrieren möchtest*."
- [x] Button(s) gemäss Mockup anpassen / zweiten Button ergänzen. Der zweite Button führt an denselben Ort, aber mit einem Query Parameter `?manager=true`
- [x] Ersten Schritt der externen Anlassanmeldung abändern (View kopieren und komplett überschreiben) app/views/event/register/register.html.haml
  - [x] Speicher-Buttons oben am Formular entfernen (dem Formular `buttons_top: false` mitgeben)
  - [x] Übersetzungstext `event/register.form_data_missing` abändern auf "Bitte fülle das folgende Formular aus, um dich zu registrieren."
  - [x] Step Wizard Anzeige entfernen
  - [x] Titel abändern auf "Kontaktdaten" (bzw. "Kontaktdaten der erziehungsberechtigten Person" falls Query Parameter `?manager=true`)
  - [x] Statt event/participation_contact_datas/form nur noch die minimalen Felder wie in der Selbstregistration anzeigen https://github.com/hitobito/hitobito/blob/master/app/views/groups/self_registration/new.html.haml
  - [x] Falls Query Parameter `?manager=true`, dann bei den Feldern Vorname und Nachname das Label ändern auf "Vorname erziehungsberechtigte Person" / "Nachname erziehungsberechtigte Person". Die Felder an und für sich funktionieren aber genau gleich wie ohne den Query Parameter.
- [x] In Event::RegisterController#register am Ende (im Erfolgsfall) zum Anlass redirecten statt wie bisher zum `new_group_event_participation_path`
- [x] Feature Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
**Gedanken** zu dieser Story

**- Button: Als Verwalter*in anmelden**
Hier sehe ich viel Potenzial und Notwendigkeit für eine gute Beschriftung und Menü-Führung. Der User muss unmissverständlich die Wahl und deren Möglichkeiten und Folgen direkt erkennen können.  UX Profis sollen sich hier einbringen. 
![image](https://user-images.githubusercontent.com/95908537/213510896-b2090cfb-f36c-4b3a-b6d6-e61cb44d67f4.png)
(Im Vorschlag ist z.B. zu sehen, dass der alert-info-Block (Jubla-Blog / FG Datenbank) völlig am falschen Ort ist)

 
**- Der neu erstellte Verwalteraccount hat keinerlei Rollen**
Ich glaube die Notwendigkeit für dieses Verhalten zu verstehen: Der Verwalter gehört nicht zum Event, da er sich ja selbst (in der Regel) nicht dafür anmeldet. Auf der anderen Seite sollte/will der Event-Veranstalter die Verwalter vielleicht irgendwie doch handhaben oder sehen. Hier müssen wir wohl konsequent denken und damit umgehen, dass lediglich die Angemeldeten Personen zu einem Event gehören. Der Weg zum Verwalter für Rechnungen, Kommunikation, etc. geht hier immer über die (angemeldeten) verwalteten Accounts. 
Sobald der Verwalter irgendwie gebunden werden soll/muss. Wird er einer Gruppe/Ebene zugeteilt oder sich selber zuteilen müssen (selbstregistration für Gruppen)

**- Mehrwert bei Verwalter-Anmeldung**
Nach Möglichkeiten suchen, damit der Verwalter möglichst viele Felder bei der Anmeldung für seine Kinder nicht mehrfach eingeben muss.

**Comment by richardjubla** [comment]
**Use Case Jubla / Begründung für Neuer Verwalter*innen Account** 

Aktuell wird ein neuer Account durch eine externe Anmeldung direkt der Ebene zugeteilt, welche den Event durchführt. (Es ist keine Bestätigung der E-Mail-Adresse oder double-opt-in nötig, was im Bereich Datenschutz/Anmeldekosten heikel ist). Mit der Anmeldung wird der Account Teilnehmer des Event und erhält die Rolle "Teilnehmer*in". Mit einer **Ab**meldung wird diese Person mit der Rolle "Extern" der Ebene versehen, welche den Event durchführt. 
Ein **Verwalter-Account** könnte mit der externen Anmeldung entstehen. In dieser Story nach bekommt er keine Rolle, ist aber wohl der Ebene zugeteilt, welche den Event durchführt. (Die Ebenen-Leitung (Scharleitung/Adressverwaltung) finden diese Accounts als Externe-Personen auf der Ebene ihrer Schar.)
Erstellte und Angemeldete Accounts würden wohl für den Event die Rolle "Teilnehmer*in" , erhalten. Sie sind der Ebene zugeteilt, welche den Event durchführt. (Achtung: Selbst wenn die Teilnehmer Kinder sind, gilt für sie der "Schutz" der Rolle "Kind" nicht, da die Rolle nicht vergeben wird und für angemeldete Teilnehmende an einem Event nicht gilt: Die Rolle "Kind" ist nur von Personen in der gleichen Ebene sichtbar, nicht von Personen aus darüber liegenden Ebenen.)
(Verwaltete) Accounts -> Teilnehmer am Event -> sind danach "ganz normale" Teilnehmer deren Verhalten sich nicht von den anderen Accounts unterscheiden. Für Korrespondenz wird 1:1 die Daten des Verwalter-Accounts verwendet. 

Für die Durchführung des Event ist ebenfalls "nur" der Teilnehmer-Account verfügbar. Alle Informationen oder Abhängigkeiten der Verwalter-Beziehung für den Anlass müssen anderweitig organsiert werden. (Beispiel: Angemeldetes Kind taucht am Anlass nicht auf).

Nach dem Anlass verbleiben die erstellen Accounts (Verwalter / Kinder) in der Ebene, welche den Event durchführt hat. Eine Bereinigung oder Bewirtschaftung der Accounts ist angebracht, aber nicht zwingend notwendig (Bereinigung alter/inaktiver Accounts). Verwalter-Accounts können sich oder ihre verwalteten Accounts auf der Ebene der Anmeldung (oder über eine externe Anmeldung für andere Ebenen der Hitobito-Instanz) für weitere Events anmelden. 
Die Ebenen-Leitung (Scharleitung/Adressverwaltung) kann sowohl die Verwalter wie auch alle Event-Teilnehmer selbständig verwalten und bei Bedarf in weiteren Ebenen (Kindergruppe, Eltern-Gruppe, etc.) oder mit Abos und Tag verwalten. 
Die Adressverwaltung ist Ansprechperson für die Verwalter-Beziehungen und kann Mutationen für den Vereinsalltag vornehmen.
