### ISSUE TITLE
Konzeptionierung: Automatisierte Releases

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1973]
Um automatische Releases zu bekommen, brauchen wir

- einen nachvollziehbaren Build: #1914
- erfolgreich laufende Test-Suites in allen Wagons: #1974
- neue Features hinter FeatureGates: :white_check_mark:
- automatische Vorbereitung der Releases: #1975

In erster Näherung setzen wir die kleinere Lösung um.

# ToDo

- [x] Issue für Umsetzung erstellen
- [x] Workflow des Features beschreiben
- [x] ggf. Mockup erstellen
- [x] Tech-Spec ergänzen
- [x] ToDo für Umsetzung definieren

**Comment by TheWalkingLeek** [comment]
:+1:
