### ISSUE TITLE
SPECS: Status der CI-Runs an statuscope melden

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1974]
Um automatische Releases zu unterstützen
soll das Ergebnis des CI-Runs an statuscope gemeldet werden
damit das Team im Fehlerfall schnell reagieren kann
und wir möglichst zu jedem Zeitpunkt ein erfolgreich getestete App haben.

Teil von #1973 

# Tech-Spec

- nach einem Test-Run muss statuscope über das Ergebnis informiert werden

# ToDo

- [x] GH-Actions anpassen
- [x] Applikationen für core in statuscope anpassen
  - [x] core: hitobito-core-specs
  - [x] interval: 3 Tage = `260_000`
  - [x] team: hitobito
- [x] Applikationen für Wagon-specs in statuscope anlegen
  - [x] name: hitobito-WAGON-specs
  - [x] interval: 1 Tag = `90_000`
  - [x] team: hitobito
- [x] Dashboard prüfen
