### ISSUE TITLE
RELEASE: Vorbereitung ohne User-Input lösen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1975]
Um den Release automatisierbar zu machen, soll ein Release-Script erstellt werden, um mit Composition-Repo und einer Versionsnummer die erforderlichen Repositories so anzupassen, dass ein Image daraus gebaut werden kann, dass einen Release darstellt

# Tech-Spec

- nur ein Composition-Repo und eine Versionsnummer soll nötig sein
- Die Versionsnummer kann automatisch erzeugt werden
  - Schema VERSION.JAHR-MONAT[.PATCH]
  - Die Hauptversion ist im Source hinterlegt. Jahr, Monat und ggf. Patchnummer werden berechnet
  - Version zum Start: 1.30
  - später dann 2.0, 2.1, etc
  - Patch könnte noch zur Unterscheidung von mehreren Releases innerhalb eines Monats hinzugefügt werden
- Das Script soll die original-Repos bearbeiten

# ToDo

- [x] Script im Core-Repo in bin/release anlegen
- [x] (Vorlage: siehe bisheriger Release-Prozess)
- [x] GH-Action erstellen, um das script aufzurufen.
- [x] vorerst nur mit manuellem Trigger
- [x] ToDo im PR erledigen 
- [ ] Workflow aus pronatura in alle Composition-Repos kopieren
- [x] Script aus bisherigem Ort löschen
- [x] Doku dort anpassen
