### ISSUE TITLE
GROUPS: Gruppe löschen schwieriger machen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#1976]
Als Gruppenverwalter in hitobito
möchte ich es schwieriger haben, Gruppen zu löschen,
um versehentliche Gruppenlöschungen zu vermeiden.

Es ist erstaunlicherweise tatsächlich regelmässig ein Problem, dass ganze Gruppen aus Versehen gelöscht werden. Das obwohl heute bereits mindestens 3 Fehlklicks nötig sind, um eine Gruppe zu löschen. Dabei werden die enthaltenen Rollen mitgelöscht (Enddatum gesetzt). Die Gruppe kann von den Usern "reaktiviert" werden, aber die darin enthaltenen Rollen sind dann weg. Möglicherweise verwechseln einige Nutzende die Gruppe löschen Funktion mit der Funktion, ein einzelnes Mitglied zu "löschen".

Neu soll beim Löschen einer Gruppe nicht mehr ein simpler JavaScript Alert mit generischem Text erscheinen, bei welchem die User stumpf auf OK klicken können, wie sie es sich gewohnt sind. Stattdessen soll man während dem Löschen einer Gruppe zur Bestätigung den Gruppennamen in ein Eingabefeld einfüllen müssen.

# Mockup

![Screenshot from 2023-01-10 11-20-22](https://user-images.githubusercontent.com/7566995/211525403-7afce648-726f-4c92-99d1-57494fe4cf85.png)

Weitere Ideen:
- Verlangen, dass "Generalsekretariat löschen" eingetippt wird
- Im Dialog auch die Anzahl und Art der gelöschten Rollen anzeigen
- Im Titel bereits möglichst spezifisch vom Gruppennamen sprechen, da dieser in einer Wand von Text am ehesten noch gelesen wird
- Mehr rote Warnfarben und Icons einsetzen

# Tech-Spec

- Umsetzung im Core
- Der Mechanismus ist von GitHub abgeschaut, wo man zum Löschen eines Repositories auf ähnliche Art dessen Namen eintippen muss
- ähnliche Modal Dialoge gibt es bereits bei den Mehrfachaktionen in Personenlisten (wenn man ein Häkchen bei Personen setzt) [[1]](https://github.com/hitobito/hitobito/blob/master/app/views/people/_multiselect_actions.html.haml#L6..L10) [[2]](https://github.com/hitobito/hitobito/blob/master/app/controllers/role_lists_controller.rb#L15) [[3]](https://github.com/hitobito/hitobito/blob/master/app/views/role_lists/new.js.haml) [[4]](https://github.com/hitobito/hitobito/blob/master/app/views/role_lists/_new.html.haml) [[5]](https://github.com/hitobito/hitobito/blob/master/app/views/role_lists/_form.html.haml)

# ToDo

- [x] Neue Action `confirm_deletion` im [GroupsController](https://github.com/hitobito/hitobito/blob/master/app/controllers/groups_controller.rb) welche [nur auf JS-Requests](https://github.com/hitobito/hitobito/blob/master/app/controllers/role_lists_controller.rb#L15) antwortet
- [x] JS-Template erstellen, welche ähnlich wie bei den [bestehenden Modal Dialogen](https://github.com/hitobito/hitobito/blob/master/app/views/role_lists/new.js.haml) ein HTML-Template rendert und dieses in die Seite einfügt wenn der Browser den JS-Code interpretiert
- [x] HTML-Template erstellen gemäss Mockup (weitere Ideen die unter dem Mockup stehen umsetzen soweit als sinnvoll erachtet)
  - [x] Der Submit Button soll via JS deaktiviert sein, solange das Input-Feld nicht den gewünschten Wert enthält. Dabei sollen Whitespace am Anfang und Ende sowie Gross-/Kleinschreibung ignoriert werden.
  - [x] Es ist okay, wenn der User den Gruppennamen in das Textfeld copy-pastet. Allein schon die Interaktion mit Freitext forciert die mentale Anwesenheit des Users.
  - [x] Das Formular im Dialog soll auf die bisherige DELETE-Action im GroupsController targeten. Es ist egal ob der Inhalt des Textfelds mitgesendet wird, die Validierung bzw. (De-)Aktivierung des Submit-Buttons kann komplett in JavaScript ablaufen.
- [x] Im Dropdown-Menü auf der Gruppe den [Löschen-Eintrag](https://github.com/hitobito/hitobito/blob/master/app/helpers/dropdown/group_edit.rb#L39..L40) ändern, sodass er nicht mehr den JS-Alert verwendet (`data: { confirm: ... }`), sondern die neue `confirm_deletion` Action mit `format: :js` aufruft (mit `remote: true` damit die Seite beim Klicken nicht neu geladen wird, sondern stattdessen der retournierte JS-Code in der laufenden Seite ausgeführt wird)
- [x] Feature Specs schreiben (ähnlich wie für die [Multiselect Actions](https://github.com/hitobito/hitobito/blob/master/spec/features/role_lists_controller_spec.rb), aber in einer neuen Spec-Datei /spec/feature/groups_controller_spec.rb
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
Wir schlagen vor und wären bereit, das Thema nach Möglichkeit in der Youth-Community zu verfolgen. Ausschlaggebend ist die Grösse des Projekts und die beschränkten Ressourcen von unserer Seite. (Wir sind uns bewusst, dass wir mit der Erweiterung um "alle Löschdialoge" und der "Log-Funktion" den Umfang dieser Anpassung erhöhen oder sogar übertreiben, dieser Aspekt dürfte und müsste durchaus noch eingegrenzt werden)

Hier die Issue/Stroy von unserer Sicht her: https://github.com/hitobito/hitobito_jubla/issues/51

**Comment by nevio18324** [comment]
I went through all dialogs i was able to find use one of those 2 options.
1. stimulus controller which creates a [BootstrapModal](https://getbootstrap.com/docs/5.3/components/modal/) 
2. js template to replace the html of `#modal_placeholder` with the modal these don't have a stimulus controller but are still styled using bootstrap modal classes
