### ISSUE TITLE
RECHNUNGEN: Nur noch QR  Rechnungen auswählbar machen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#1982]
Da in der Schweiz nur noch QR Rechnungen verwendet werden dürfen und rote/orange Einzahlungsscheine gar nicht mehr verwendet werden dürfen, sollen diese in Hitobito zukünftig auch nicht mehr auswählbar sein.

Es sollen...
1. ... alle Kunden durch PL's informiert werden dass nur noch QR Rechnungen verwendet werden dürfen und sie dies bitte auf sämtlichen ihrer Rechnungseinstellungen ändern sollen.
2.  ...beim Dropdown in den Rechnungseinstellungen soll nur noch "QR Rechnungen" ausgewählt werden können. Bei neu erstellten Rechnungseinstellungen soll "QR Rechnungen" vorausgewählt sein.
3.  ...sämtliche Umgebungen überprüft werden dass nirgends mehr etwas anderes als QR-Rechnungen ausgewählt ist, und sonnst durch uns einmalig angepasst werden.

Wurde in https://github.com/hitobito/hitobito_svse/issues/11 bereits angedacht.
Umsetzung im Core
Umsetzung soll möglichst einfach und mit geringem Zeitaufwand gemacht werden.  Deshalb nur im Dropdown nicht mehr auswählbar machen.
Alte Rechnungen welche mir anderen Einzahlungsscheinen erstellt wurden, sollen immernoch mit alten angezeigt werden.

# Tech-Spec

- nur noch QR-Rechnungen (oder keine) erlauben
- alte Rechnungen sollten gültig bleiben
- Rechnungseinstellungen sollten auf keine oder QR-Rechnungen umgestellt werden
- Konstante PAYMENT_SLIPS entsprechend anpassen, sofern es nicht Rechnungen zerstört
- https://github.com/hitobito/hitobito/blob/aeacf53e5c29ec04af7b755f0fb92b40a93f99f3/app/models/concerns/payment_slips.rb#L13

# ToDo

- [ ] Migration erstellen, um InvoiceConfig anzupassen
- [ ] ggf. View anpassen, um nur noch QR oder keine zu anzubieten
- [ ] ggf. Model anpassen, um nur noch QR oder keine zu erlauben
- [ ] alte Daten testen, vermutlich wurden nur QR-Rechnungen erstellt
	- [ ] Multitenant-Umgebung?
	- [ ] Die Mitte?
	- [ ] Wanderwege?
	- [ ] vielleicht kurz überall prüfen...
- [ ] Specs anpassen
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by ThomasEllenberger** [comment]
Getestet auf Integrationsumgebung SWW, Cevi und Core.

Sämtliche Einzahlungsscheine sind noch immer auswählbar:
![grafik](https://github.com/hitobito/hitobito/assets/100761305/31c32584-a148-4168-844d-2971858ebb62)
