### ISSUE TITLE
FILTER: Zusätzliche Spaltenauswahl Whitelisten - Jubla

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2007]
### Aktuelles Verhalten

Analog #1958 fehlen seit der Umsetzung von PR #1695 auch bei der Jubla Filteroptionen im Kurse-Tab.
Info @richardjubla

### Gewünschtes Verhalten

Bitte im Kurse-Tab die folgenden Spalten wieder auswählbar machen:
- Kurse: AHV-Nummer
- Kurse: J+S Nummer
-  Wohnkantone
- ~Alle zusätzlichen Anmeldeangaben in Kursen~

### Schritte zu reproduzieren

-

### Wann ist der Fehler aufgetreten?

10.02.2023

### hitobito version

1.28.44

### Organisation

Jubla

### TechSpec

- Umsetzung im Jubla Wagon
- Doku für das Spalten allowlisting System unter https://github.com/hitobito/hitobito/blob/master/doc/features/table-display-additional-columns.md
- Beispiel im Youth Wagon: https://github.com/hitobito/hitobito_youth/blob/master/lib/hitobito_youth/wagon.rb#L34..L36

### ToDos

- [ ] Fehlende Spalten auf Participantion-Listen im Cevi Wagonfile allowlisten:
  - [ ] AHV-Nummer `ahv_number`
  - [ ] J+S Nummer `j_s_number`
  - [ ] Wohnkanton `canton` von der Person (eventuell nicht direkt auf der Participation gespeichert)

**Comment by carlobeltrame** [comment]
Die Anmeldeangaben und Administrationsangaben sind bereits vom Core her auswählbar.

**Comment by carlobeltrame** [comment]
Der PR wurde geschlossen, aber der Commit ist auf dem Jubla-Wagon drauf, und auf Jubla Int scheints zu funktionieren. Ich schliesse das hier mal.
