### ISSUE TITLE
ROLLE: Anfragen bei Gruppen erzwingen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#2008]
Anschliessend an https://github.com/hitobito/hitobito/issues/1653 soll die Gruppenschutzfunktion nun obligatorisch für alle Gruppen aktiviert werden.

- Button entfernen / ausblenden
- Bei allen Gruppen per default aktivieren

# Tech-Spec

- change im pbs wagon only

# ToDo

- [x] getter `require_person_add_requests` und `require_person_add_requests?` in Group model überschreiben und immer true zurück geben
- [x] in `Group::PersonAddRequestsController` actions #activate, #deactivate disablen (z.B. exception raisen)
  - entsprechende specs schreiben die sicherstellen das die Actions nicht mehr verwendet werden können
- [x] aktivieren/deaktivieren button sowie zugehöriger Hinweistext ausblenden in view. 
  - group/person_add_request/_actions_index.html.haml
- [x] Manuell testen
