### ISSUE TITLE
PERSONENFILTER: 500er bei layer und deep range filtern

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#2013]
### Aktuelles Verhalten

Wenn bei jeglichen Gruppen im Jubla Wagon der Filter "Gesamte Ebene/Gruppe" angewählt wird, wird ein 500er Fehler ausgelöst:
```Mysql2::Error: Unknown column 'roles.type' in 'order clause'```

### Gewünschtes Verhalten

Der Fehler soll nicht mehr auftreten, sowohl Filter als auch Sortierung sollen sich korrekt verhalten

### Schritte zu reproduzieren

1. Personenliste einer Gruppe öffnen
2. "Gesamte Gruppe/Ebene" Filter anwählen

Passiert aktuell sowohl auf Prod, Int als auch lokal

### Wann ist der Fehler aufgetreten?

20.02.2023

### hitobito version

1.28.30

### Organisation

Bisher nur bei Jubla rekreieren können

### Screenshots, weiterer Kontext

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/60310/?query=is%3Aunresolved%20is%3Aunassigned

### ToDos

ToDo

- [ ] Fehler scheint einerseits durch `order_by_role` aufzutreten: https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/list.rb#L87
- [ ] Andererseits durch das passen von `nil` statt `@group`: https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/list.rb#L69
- [ ] Weiterer Ansatz ist, weshalb und ob es effektiv nur bei der Jubla auftritt

**Comment by tschuepbach** [comment]
Tritt beim Cevi (produktiv) auch auf, egal ob nach Rollen, Qualis etc. gefiltert wrid. Betrifft wohl nur
- In der aktuellen Ebene und allen darunter liegenden Ebenen und Gruppen
- In der aktuellen Ebene und allen ihren Gruppen

**Comment by carlobeltrame** [comment]
Beim Cevi konnte ich es auf der Produktion nicht mehr nachstellen. Bei der Jubla tritt es auf der Integrationsumgebung und Produktionsumgebung weiterhin auf.
