### ISSUE TITLE
EVENTS: Hauptleiter haben gleiche Rechte wie Geschäftsstellen_Nacharbeiten

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2015]
Nacharbeiten zu [cevi_#82](https://github.com/hitobito/hitobito_cevi/issues/82)

# Feedback
Beim Kurs mit automatischer Zuteilung scheint auf den ersten Blick fast alles 
korrekt. Die gewünschten Knöpfe werden angezeigt. "Ablehnen" funktioniert 
jedoch noch nicht (Fehler: "Sie sind nicht berechtigt, diese Seite 
anzuzeigen") und hat ein anderes Symbol sowie eine andere Position als bei der 
GS.

Beim Kurs mit manueller Zuteilung werden Anmeldungen immer noch automatisch 
zugeteilt. Zudem fehlt der Knopf "Ablehnen" ganz. 

## Testprozess:

Bitte folgenden Testprozess durchspielen bis er funktioniert:

* 2 Kurse, beide mit "Maximale Teilnehmerzahl" = 1
  - Kurs A mit "Automatisch zugeteilt" = True 
  - Kurs M mit "Automatisch zugeteilt" = False

* Bei jedem Kurs 2 TN anmelden (via imitieren des Teilnehmers)
  - Bei A wird der erste automatisch zugeteilt, der zweite landet auf der 
Warteliste
  - Bei M müssen beide noch manuell bestätigt werden.

* Den Hauptleiter imitieren und das "Anmeldungen"-Tab kontrollieren.

* Bei Kurs M die erste Anmeldung zuteilen.

* Bei Kurs A die erste Anmeldung nach rechts verschieben und dann wieder nach 
links.

* Bei den verbliebenen Anmeldungen rechts auf den Namen klicken und den TN 
"Ablehnen".

* Bei jedem Kurs eine Anmeldung via "Teilnehmer/-in hinzufügen" ergänzen.

Aktuellen Test-Kurse sind:
  A: https://cevi.puzzle.ch/groups/5/events/1178
  M: https://cevi.puzzle.ch/groups/5/events/1177

# ToDo

- [x] Anlasshauptleiter erhalten keinen Fehler mehr wenn sie Teilnehmende "Ablehnen"
- [ ] Position & Symbol von "Ablehnen" Button analog Geschäftsstelle
- [x] Bei Kurs mit manueller Zuteilung: Default = Auf Warteliste
- [ ] Bei Kurs mit manueller Zuteilung: Ablehnen Knopf ergänzen
