### ISSUE TITLE
Anpassungen Weiterentwicklungen Insieme 2022_2

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2019]
Folgeticket zu [insieme#143](https://github.com/hitobito/hitobito_insieme/issues/143)

Die Features wurden getestet und es gibt noch folgende Rückmeldung:

### Der FTE Export  funktioniert korrekt, doch bei der änderung der Honorare wird noch etwas falsch angezeigt:
«Übersicht Basisinfo» soll wie im ersten Testing-Feedback spezifiziert ohne und mit Honorare gleich (im bsp==1) angezeigt werden.

Ausgangslage:
https://insieme.puzzle.ch/de/groups/89/time_record/2022/base_information
Ausserschwyz
Zeiterfassung Angestellte: 1900h
Honorare in Kostenrechnung: 0
![grafik](https://user-images.githubusercontent.com/100761305/221804424-f83d03d4-2106-46ff-82f8-17bbb450902b.png)

Mutation:
https://insieme.puzzle.ch/de/groups/89/time_record/2022/base_information
Ausserschwyz
Zeiterfassung Angestellte: 1900h
Honorare in Kostenrechnung: 130’000
![grafik](https://user-images.githubusercontent.com/100761305/221804735-bd3c2af4-e92b-4715-a83c-3e69ccd7da43.png)

Gewünscht: Keine Veränderung in der Basisübersicht. Resultat gewünscht wie in Ausgangslage. (Honorarkomponente wird fälschlicherweise hier abgezogen).

 
### Meldung überbuchter Kurs:

Vor Anpassung Woche vom 13.2.23: Vorläufige Anmeldung (=Person auf warteliste) stimmt mit Meldung überein aber Text taucht in französischer version nicht auf (auch transifex nicht).
Jetzt: Keine Warteliste. 14 Teilnehmer für Kurs mit maximal 12, entsprechend auch keine Meldung.

https://insieme.puzzle.ch/de/groups/240/events/course?returning=true

-> Gewünscht wäre, dass die TN über der maximalen Anzahl auf die Warteliste kommen und eine Meldung erscheint, deren Inhalt mit diesem Vorgehen übereinstimmt.

# ToDo

- [x] Honorarkomponente in Basisübersicht nicht abziehen
- [x] Warteliste prüfen, ggf. für Kurse aktivieren
- [x] Meldung bei Warteliste prüfen, ggf. korrigieren
