### ISSUE TITLE
MESSAGE: Korrektur Adressposition

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#2037]
### Aktuelles Verhalten

Beim Erstellen eines Briefes ist es in den Einstellungen möglich zu wählen, ob die Adresse links oder rechts bündig sein soll.
Die Darstellung der Adresse auf der linken Seite funktioniert einwandfrei.
Wenn jedoch die Darstellung auf der rechten Seite gewählt wird, dann wird die Adresse in der Mitte des Briefes (von der Mitte aus nach rechts) angezeigt.
Dies ist insbesondere bei den Rechnungsbriefen des SVSE störend.
Dadurch sind Couverts mit Sichtfenster auf der rechten Seite nicht mehr brauchbar.

### Gewünschtes Verhalten

Rechts orientierte Adressen auf Briefen müssen weiter rechts angezeigt werden, sodass die Couverts mit Sichtfenster auf der rechten Seite wieder verwendet werden können.
Das Sichtfenster, der verwendeten Couverts, beginnt 12cm vom linken Rand und ist 8.5cm breit.
Somit wäre die Positionierung der Adresse gewünscht, **wie sie bei den Rechnungen bereits umgesetzt ist**.

### Schritte zu reproduzieren

1. Im Abo-Tab einen Brief erstellen.
2. Unter Einstellungen die Adresse auf die rechte Seite setzen.

### Wann ist der Fehler aufgetreten?

November 2022

### hitobito version

1.28.40

### Organisation

SVSE

### Screenshots, weiterer Kontext

![image](https://user-images.githubusercontent.com/69250571/225359646-e3bf105c-ec86-4925-bd0a-ad74159ba5df.png)

### ToDos
- [x] Konstante `RIGHT_ADDRESS_X` im [Brief-Header-Renderer](https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/messages/letter/header.rb#L12) auf 290 setzen, wie es bei den [Rechnungen](https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/invoice/receiver_address.rb#L11) auch ist
- [ ] Allfällig fehlschlagende Tests fixen, insbesondere müssten Tests in [letter_header_spec.rb](https://github.com/hitobito/hitobito/blob/master/spec/domain/export/pdf/messages/letter/header_spec.rb) kaputt gehen.
- [ ] Überprüfen dass die beim SWW manuell einstellbare Adressposition weiterhin funktioniert https://github.com/hitobito/hitobito_sww/blob/master/app/domain/sww/export/pdf/address_renderers.rb 
- [ ] SWW-Wagon-Specs auch laufen lassen und schauen ob alles noch okay ist

**Comment by carlobeltrame** [comment]
Es ist ein Trade-Off zwischen Kompatibilität mit beliebigen Fenstercouverts und unterstützter Länge der Adressen. Bei grossen Haushalten kann die Empfänger-Zeile beliebig lang werden. Welche spezifischen Fenstercouverts verwendet der SVSE? Welches Produkt? Welche genauen Spezifikationen hat das Fenster? Also konkret, wo genau in cm ist das Fenster?

**Comment by carlobeltrame** [comment]
Möglich, aber mit ähnlich unfundierten Schätzungen sind wir auch schon bei der aktuellen Lösung gelandet. Lieber jetzt einmal abklären, dann haben wir später eine Begründung wenn es nochmals jemand ändern will.

**Comment by nchiapol** [comment]
Mindestens für die Cevi Region Zürich ist die aktuelle Position der Rechnung sehr gut.

Wir haben Couverts mit Fenster rechts (11.7 cm vom linken Couvert Rand bis 1.2cm vom rechten Rand)
Schiebe ich das Papier im Couvert ganz nach links und unten, beginnt die Adresse 0.5cm vom linken (und 1.5cm vom oberen) Rand des Fensters.
![screenshot_2023-03-15_212520](https://user-images.githubusercontent.com/1123483/225433923-24393fb7-265a-468b-8537-68924cf3c4a7.png)

Ist das Papier rechts oben, sind die Abstände der Address 2.3 cm von links und 0.4cm von oben.
