### ISSUE TITLE
MESSAGES: Dynamische Rechnungsposten für Rechnungsbrief

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#2039]
In #1877  haben wir generalisiert umgesetzt, dass dynamische Rechnungsposten im Wagon definiert werden können. Beim Erstellen von Rechnungen wird dann auch neu pro dynamischer Rechnungsposten ein Button angezeigt, welcher zu einem vorgefüllten Formular mit besagtem Rechnungsposten führt.
Dies wurde aber bisher nur für Sammelrechnungen umgesetzt und soll jetzt auch für Rechnungsbriefe realisiert werden.

# Tech-Spec

- Umsetzung im Core

# ToDo

- [x] MessagesController anpassen. Sodass er Rechnungsposten per Query Parameter entgegen nehmen kann und diese anlegt. Siehe: https://github.com/hitobito/hitobito/blob/master/app/controllers/invoice_lists_controller.rb#L139
- [x] Button anpassen. Sodass für alle dynamischen Rechnungsposten ein weiterer Knopf angezeigt wird. "Rechnungsbrief erstellen" Knopf wird dann also zum Dropdown. Siehe: https://github.com/hitobito/hitobito/blob/master/app/helpers/dropdown/invoice_new.rb#L79
- [x] Specs schreiben -> Ist im Mitte Wagon.
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
