### ISSUE TITLE
SUCHE: Suche läuft in ein 504 Gateway Time-out

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#2056]
### Aktuelles Verhalten

Bei der Suche läuft die App in ein 504 Gateway Time-out. Dieses Problem bis anhin nicht ganz nachvollzogen werden. Der Bug tritt bei der Mitte im Kanton Luzern oft auf, teilweise auf der Geschäftsstelle. Mit dem Admin User konnte ich das Problem nicht nachvollziehen.

Meldung:

![image](https://user-images.githubusercontent.com/9592347/228183669-09518273-1d6b-47ac-9132-58ef6e3e8feb.png)

### Gewünschtes Verhalten

Suche läuft nicht mehr in ein Time-out

### Schritte zu reproduzieren

Konnte bis anhin nicht nachvollzogen werden.

Als Hypothese steht im Raum, dass dieser Bug bei Personen welche Rechnungszugriff haben auftaucht. Dies würde erklären wieso wir als Admin dies nicht haben. Sphinx durchsucht auch sämtliche Rechnungen. Daher ist hier der Scope sehr gross.

### Wann ist der Fehler aufgetreten?

20.3.2023

### hitobito version

1.28.44

### Organisation

Die Mitte

### ToDos

- [x] Prod DB Dump in lokale Umgebung importieren und mit mit einer Person aus Luzern mit Rechnungsberechtigungen prüfen ob Sphinx Abfragen wirklich sehr lange dauern? Unterschied zu Login mit Person ohne Rechnungsberechtigung?
- [x] 'haproxy.router.openshift.io/timeout' auf Rails Ingress setzen? Default scheint 30s [Default](https://access.redhat.com/documentation/en-us/red_hat_decision_manager/7.3/html/managing_and_monitoring_decision_server/configuring-openshift-connection-timeout-proc)
- [x] Falls Problem nachvollzogen werden kann, needs-confirmation tag entfernen
- [ ] ggf. Follow-Up ticket erstellen um bestätigtes Problem zu Fixen
- [ ] Ticket schliessen falls nicht nachvollzogen werden kann.

**Comment by daniel-illi** [comment]
MR zur Erhöhung des request timeout auf 60s: https://gitlab.puzzle.ch/pitc_hit/hitobito-configmanagement/-/merge_requests/6

**Comment by kronn** [comment]
Anpassung auf OpenShift wurde vorgenommen.
