### ISSUE TITLE
HOTFIX - Jubla #1733 & #2035

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2058]
Hotfix für den Jubla Wagon am 04.04.2023.
Inhalt: Nur Issues #1733 und #2035 
Gezielt ausgeklammert wird #1961, weil dort eine Datenbankmigration drin ist und noch mehr Risiko dazukäme, und weil bei der Jubla (gemäss Richi) nur Leute mit Nationalität Schweiz oder leer drin sein sollten.

# Tech-Spec

- #2035 muss noch zuerst umgesetzt werden

# ToDo

- [x] Core: Fix für #2035 auf master umsetzen
- [x] Allfällig fehlschlagende Tests in Core und Wagons fixen. Mögliche Test-Failures [hier](https://github.com/search?q=org%3Ahitobito+csv+path%3A%2F%5Espec%5C%2F%2F+NOT+repo%3Ahitobito%2Fhitobito_pbs+NOT+repo%3Ahitobito%2Fhitobito_cevi+language%3ARuby&type=code&l=Ruby)
- [x] Core: a3b105eaee7df22858e8d7dc819c834f5e1ee17c auschecken
- [x] Core: #1993 übernehmen
- [x] Core: Umgesetzten Fix für #2035 übernehmen
- [x] Youth Wagon: hitobito/hitobito_youth@8f4f810266fa87d0285cf69b8c1109a5b6d031d6 auschecken
- [x] Youth Wagon: #1733 übernehmen
- [x] Jubla Wagon: hitobito/hitobito_jubla@fcfe0c9744f53c3d69585464ef5521ebb58ed262 auschecken
- [x] Jubla Wagon: hitobito/hitobito_jubla@dd2bd76d0b8f32c8fea1e09e8d83bea3ab4cca2c übernehmen
- [x] Lokal testen ob der NDS-Lager und NDS-Kurs Export wie gewünscht aussieht (z.B. leere PEID-Spalte müsste vorhanden sein) und UTF-8-encodet ist (Text Editor weiss das, und auch noch kurz CSV in Excel / Libreoffice aufmachen)
- [x] Hotfix mit ops/bin/release vorbereiten, Versionsnummer 1.28.30.1
- [ ] Releasen

**Comment by richardjubla** [comment]
Danke für diesen "Task/Hotfix". Von meiner Seite die "Erwartungshaltung": Mit dem Hotfix ermöglichen wir den UTF8 Export mit den Spalten für den NDS-Import.  Wir sind uns bewusst (und nehmen in kauf), dass wahrscheinlich der Inhalt und allfällige Details oder Anforderungen explizit durch die exportierende Person manuell überprüft werden muss. -> Person macht Export, prüft und editiert Zeilen (nicht Spalten!) und kann die Datei abspeichern und bei NDS hochladen.
 
Eine Überarbeitung und "finale" Auslieferung (Abgleich der neusten Entwicklungen, evtl. Bugs, etc.) erfolgt mit dem nächsten Release. Es ist klar, dass wir nach dem Hotfix wider in einen normalen Testsystem /  Produktivsystem-Modus zurück wollen.
