### ISSUE TITLE
PERSON: Geburtsjahr ohne -tag

### ISSUE THREAD

**Issue by lukas-buergi** [hitobito/hitobito#2072]
Wir haben leider manchmal nur das Geburtsjahr von Leuten, ohne Datum, weil wir Formulare teils sehr darauf optimieren, dass sie in wenigen Schritten schnell ausgefüllt werden können und uns eigentlich nur das Geburtsjahr für eine grobe Alterseinschätzung interessiert und nicht das exakte Alter.

Es wäre darum gut, den Monat und Tag irgendwie optional machen zu können. Je nach dem wie man das macht, würde es sich dabei anbieten auch zu ermöglichen, das Jahr nicht anzugeben und nur den Tag, aber letzteres brauchen wir nicht.

Vielleicht wäre das einfachste, es so zu machen, um den genauen Tag optional zu machen:

- Ein binäres birth_year_only Feld dem Person-Model hinzufügen
- Das Geburtstagsfeld ist aktuell ja sowieso ein Textfeld und kein Date-Picker, also könnte man sich dort beim Speichervorgang einklinken und auch eine 4-stellige Jahreszahl akzeptieren, die dann mit einem beliebigen Tag (z.B. 31.12.) im Geburtstags-Datum-Feld gespeichert werden kann. Wenn hier nur die Jahreszahl eingegeben wird, dann wird birth_year_only auf wahr gesetzt, sonst auf false.
- Für die Anzeige vom Datum könnte man wohl in format_helper.rb eine format_person_birthday-Methode schreiben, die den Tag bei der Anzeige weglässt, wenn birth_year_only gesetzt ist.

# ToDo

- [ ] Herausfinden ob der Ansatz irgendwas kaputt macht / überhaupt praktikabel ist
- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen

**Comment by lukas-buergi** [comment]
Note: The date-picker field (for example in the invoice date range selection) throws a 500 error if an invalid date is entered with the keyboard.

**Comment by lukas-buergi** [comment]
https://github.com/hitobito/hitobito/pull/2077
