### ISSUE TITLE
Readthedocs: Übersetzung FR & IT

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2097]
Im Issue #1894  und dem PR https://github.com/hitobito/user_documentation/pull/24 haben wir umgesetzt, dass unser ReadtheDocs auf Franzosisch und Italienisch übersetzt werden kann.

Die PBS hat nun im Transifex beide Sprachen zu 100% übersetzt.
Diese Übersetzungen sollen nun im Readthedocs auch entsprechend angezogen werden.

# ToDo

- [x] prüfen, ob die Sprachen in readthedocs vorhanden sind
- [x] prüfen, ob die Sprachen automatisch von `rake build:all` abgedeckt sind
- [x] ~Übersetzungen bauen~
- [x] Übersetzungen von transifex aktualisieren
- [x] prüfen, ob Automatisierung möglich oder nötig ist
