### ISSUE TITLE
PERSON: Datenlöschung

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/hitobito#2105]
Blockiert durch #2106, weil die Logik für die Minimierung (Felder die zurückgesetzt werden) und für die definitive Löschung dort implementiert werden.

Als Adressverwalter\*in meiner lokalen Gruppe möchte ich für erfasste Personen eine Datenlöschung wahrnehmen können. Diese kommt zum Einsatz, wenn eine Person ausdrücklich wünscht, nicht mehr geführt zu werden. Es gibt aber Kriterien, die verhindern, dass die Person dann auch wirklich gelöscht wird. Für diese manuelle Datenlöschung können die Mechanismen aus der automatisierten Datenlöschung teilweise übernommen werden (https://github.com/hitobito/hitobito/issues/2106).

## Neuer Button unter "Ohne Rollen"
Die Liste "Ohne Rollen" soll pro Person einen Button erhalten, um eine Datenlöschung zu überprüfen. Dieser Button entspricht aber nicht der aktuellen Delete-Funktion, sondern wird parallel dazu eingeführt. Der Button ist sichtbar für Personen mit `layer_and_below_full` einer Ebene. Der Button kann pro Wagon aktiviert / deaktiviert werden.

### Bedingungen für eine Löschung
Analog zu https://github.com/hitobito/hitobito/issues/2106 sollen Kriterien pro Wagon definiert werden können, wann eine Datenlöschung manuell ausgeführt werden darf. Die Kriterien unterscheiden sich von den Kriterien für die automatisierte Löschung. Für den Youth-Wagon schlagen wir folgende Bedingungen vor:

- Keine Kursteilnahme in den letzten 10 Jahren
- Keine Lagerteilnahme in den letzten 10 Jahren

Da der Button in der Liste "ohne Rollen" platziert wird, kommt das versteckte Kriterium "Person hat keine Rolle" hinzu. Dieses Kriterium ist wichtig, damit Personen nicht von fremden Ebenen gelöscht werden können. Nach unserem Verständnis sollte das für alle Wagons zutreffen.

Beim bestätigen des Buttons werden die Kriterien überprüft und die entsprechenden Optionen dem User gezeigt: 
- Benutzer darf gelöscht werden (+ Button "Benutzer definitiv löschen")
- Benutzer darf nicht gelöscht werden (mit konfigurierbarem Text für die Begründung)
- Falls nicht schon minimiert: Benutzer minimieren (mit konfigurierbarem Text, was das bedeutet)

### Löschung
Der Benutzer wird komplett gelöscht. Dies entspricht der Löschung hier: https://github.com/hitobito/hitobito/issues/2106#issuecomment-1589666528

### Minimierung
Nur die durch den Wagon definierten Felder des Benutzers werden gelöscht. Dies entspricht der Minimierung hier: https://github.com/hitobito/hitobito/issues/2106#issuecomment-1589666528

## Abgrenzung
Aus Sicht PBS sollen Benutzer\*innen für sich selber keine Datenlöschung auslösen können. Gerade bei Mitgliedern kommt eine Datenlöschung oft mit dem Austritt aus der Abteilung gleich. Diesen Zusammenhang sollen die Funktionsträger der Gruppe herstellen, nicht die Benutzer\*innen selber.

Benachrichtigungen sollen vorerst keine verschickt werden (z.B. an andere Gruppen, bei denen die Person noch Mitglied war). Eine solche wäre zwar wünschenswert, jedoch gibt es eine solche Benachrichtigung beim heutigen Prozess auch nicht, deshalb lassen wir das fürs erste weg.

Für den Youth-Wagon: Anlass-, Kurs- und Lagerteilnahmen in der Zukunft werden, wie bisher auch, nicht beachtet. Die gelöschte Person ist dann einfach nicht mehr als Teilnehmer*in angemeldet. Datenlöschungen müssen manchmal auch schnell gehen, deshalb soll das nicht beachtet werden.

Die bestehende Lösch-Funktion für Admins (bei der PBS) soll nicht angerührt werden. Admins können weiterhin ohne Einschränkung Personen manuell löschen (z.B. Dublikate, usw.).

# Mockup

![grafik](https://github.com/hitobito/hitobito/assets/1799621/257a1a4b-f23e-4bbe-a997-8e0911af5f1c)

# Alte Spezifikation:
~~Als Adressverwalter\*in meiner lokalen Gruppe möchte ich für erfasste Personen eine Datenlöschung wahrnehmen können. Diese kommt zum Einsatz, wenn eine Person ausdrücklich wünscht, nicht mehr geführt zu werden.~~

~~Neuer Abschnitt in der Sicherheitsansicht~~
~~Ein neuer Abschnitt mit Button "Datenlöschung" soll in der Sicherheitsansicht erscheinen. Dieser Abschnitt ist nur für Personen mit `layer_full` oder höher (in einer Gruppe der Zielperson) sichtbar. Zum Button soll eine Beschreibung angezeigt werden:~~

> ~~**Du willst alle Daten von Anna Müller löschen?**~~
> ~~Mit dieser Funktion kannst du das Profil und alle dazugehörigen Daten unwiderruflich aus der Datenbank entfernen. Diese Funktion sollte nur verwendet werden, wenn eine Datenlöschung verlangt wurde oder wenn es sich um ein Duplikat handelt. Um eine Person aus der Gruppe zu entfernen, lösche bitte nur die entsprechende Rolle im **Info-Reiter**.~~

~~Bedingungen für eine Löschung~~
~~Pro Wagon sollen Bedingungen definiert werden können, wann eine Person gelöscht werden darf. Für den Youth-Wagon schlage ich folgende Bedingungen vor:~~

- ~~Keine Kursteilnahme in den letzten 10 Jahren~~
- ~~Keine Lagerteilnahme in den letzten 10 Jahren~~

~~Wenn die Kriterien nicht erfüllt sind, wird der Button versteckt / ausgegraut. Es erscheint eine Warnung: ~~
> ~~Diese Person darf aus Archivierungszwecken nicht gelöscht werden.~~

~~Löschung~~
~~Beim Betätigen des Buttons soll eine Warnung angezeigt werden:~~
> ~~Willst du Anna Müller / Lira unwiderruflich löschen? Damit werden auch alle Rollen, sowie Anmeldungen für vergangene und zukünftige Anlässe für die Person gelöscht. Bitte tippe "DELETE" in das folgende Feld, um die Person zu löschen...~~

~~Wenn die Löschung bestätigt wird, werden alle Informationen zu der Person gelöscht, wie bereits heute via "Löschen" auf dem Profil möglich.~~

~~Abgrenzung~~
~~Aus Sicht PBS sollen Benutzer\*innen für sich selber keine Datenlöschung auslösen können. Gerade bei Mitgliedern kommt eine Datenlöschung oft mit dem Austritt aus der Abteilung gleich. Diesen Zusammenhang sollen die Funktionsträger der Gruppe herstellen, nicht die Benutzer\*innen selber.~~

~~Benachrichtigungen sollen vorerst keine verschickt werden (z.B. an andere Gruppen, bei denen die Person noch Mitglied war). Eine solche wäre zwar wünschenswert, jedoch gibt es eine solche Benachrichtigung beim heutigen Prozess auch nicht, deshalb lassen wir das fürs erste weg.~~

~~Anlass-, Kurs- und Lagerteilnahmen in der Zukunft werden, wie bisher auch, nicht beachtet. Die gelöschte Person ist dann einfach nicht mehr als Teilnehmer*in angemeldet. Datenlöschungen müssen manchmal auch schnell gehen, deshalb soll das nicht beachtet werden.~~

~~@richardjubla, @nchiapol Merci für eure Rückmeldungen!~~

# Tech-Spec

- #1780 gleich mitlösen, ist sowieso nötig damit dieses Feature Sinn macht
- Umsetzung im Core
- Logik für Minimierung und für definitive Löschung von #2106 übernehmen
- via FeatureToggle einschaltbar (damit es auch deaktiviert werden kann wenn ein Wagon die Löschungslogik noch nicht so genau definiert hat oder auch die automatische Datenlöschung komplett deaktiviert hat)
- Für komplettes Feature ist `:layer_and_below_full` Berechtigung auf diesem oder einem darüber liegenden Layer nötig

# ToDo

- [x] Neues FeatureGate `people.manual_deletion` o.ä. anlegen
- [x] Neuer Controller `People::ManualDeletionController`, nested unter dem `PeopleController`
  - [x] Alle Actions im Controller sind durch das FeatureGate deaktivierbar
  - [x] Alle Actions im Controller überprüfen die `:layer_and_below_full` Berechtigung
  - [x] `show` Action (GET) reagiert nur aufs `:js` Format
    - [x] JS View rendert HTML Dialog Partial
    - [x] Erklärender statischer Text im Dialog (können die Wagons dann in ihren Übersetzungen anpassen wenn sie wollen)
    - [x] Für die Person in der URL die folgenden Regeln überprüfen und jegliche nicht erfüllte Regeln im Dialog darstellen:
      - [x] Person hat keine aktive Rolle (wird aber in der Realität immer erfüllt sein, weil der Dialog nur auf der Ansicht "Ohne Rollen" aufrufbar ist)
      - [x] Person hat keine Anlassteilnahme in Anlässen in den letzten 10 Jahren
      - [x] Nur für Minimierung: Person ist nicht bereits minimiert (minimized_at ist nil)
      - [x] Regeln sollen im Wagon überschreibbar, ergänzbar und entfernbar sein
    - [x] Zwei Submit Buttons: "Person minimieren" und "Person definitiv löschen"
      - [x] Buttons sind je `disabled` wenn die obigen Bedingungen nicht eingehalten sind (Minimierungs-Bedingung gilt natürlich nur für Minimierungs-Button)
      - [x] Minimieren-Button triggert die `People::ManualDeletionController::minimize` Action
      - [x] Definitiv-löschen-Button triggert die `People::ManualDeletionController::delete` Action
    - [x] Dialog soll auch schliessbar / abbrechbar sein, möglichst auf verschiedene Wege, z.B. ausserhalb klicken, ESC drücken, Abbrechen-Link, X-Button in der Ecke
  - [x] `minimize` Action (POST)
    - [x] Überprüft nochmals ob die Bedingungen aus dem Dialog alle eingehalten sind (inkl. Person ist nicht bereits minimiert)
    - [x] Wenn ja, verwendet die Minimierungs-Logik von #2106 
    - [x] Flash Message und zurück auf "Ohne Rollen" redirecten
  - [x] `delete` Action (POST)
    - [x] Überprüft nochmals ob die Bedingungen aus dem Dialog alle eingehalten sind
    - [x] Wenn ja, verwendet die Löschungs-Logik von #2106 
    - [x] Flash Message und zurück auf "Ohne Rollen" redirecten
- [x] Auf der [Ansicht "Ohne Rollen"](https://github.com/hitobito/hitobito/blob/master/app/views/group/deleted_people/_list.html.haml) eine Spalte gemäss Mockup hinzufügen
  - [x] Spalte taucht nicht auf wenn das FeatureGate deaktiviert ist
  - [x] Spalte taucht nicht auf, wenn man die `:layer_and_below_full` Berechtigung nicht hat
  - [x] Bei Klick auf den Button (Icon darf natürlich auch anders gewählt werden) wird via `remote: true` die JS-View `People::ManualDeletionController#show` (also der Dialog) aufgerufen
- [ ] Bug #1780 beheben (falls noch Zeit)
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by carlobeltrame** [comment]
Soll das wirklich für lokale Adressverwalter\*innen möglich sein? Was wenn die Person in mehreren Gruppen Rollen hat? Wie verhindern wir Missbrauch? Klar, bisher wenn du die Löschung als Admin machen musst hast du auch keine Ahnung ob es legitim ist, aber die Hürde ist sehr viel höher wenn man das "der PBS zur Löschung übergeben" muss anstatt zwei Klicks zu machen.
Vielleicht könnten wir es zumindest auf `layer_and_below_full` einschränken, sodass ALs das dürfen, aber Adressverwalter*innen nicht?

**Comment by nchiapol** [comment]
Aus unserer Sicht darf das Löschen von Personen die noch irgendwo verknüpft sind nur für Admins möglich sein. Unsere Erfahrung zeigen, dass schon Admins der Regionen nicht korrekt mit dieser Fähigkeit umgehen - wir haben bereits zwei mal alle Daten wichtiger Personen (Geschäftsleiter einer anderen Region) verloren, weil dieses Recht bei uns zu breit vergeben wurde. (Die Einschränkung auf keine Teilnahmen hätte hier aber sicher geholfen.)
Ich hätte deshalb lieber eine Funktion ähnlich den Anfragen: Für Personen kann eine Löschung beantragt werden. Die Admins auf Dachverbandsebene erhalten ein Mail mit dem Hinweis und haben dann irgendwo ein Tab mit den offenen (und idealerweise bearbeiteten, d.h. akzeptierten und abgelehnten) Löschanträgen.

Weitere Gedanken:
  * Das Recht für Löschanträge könnte grosszügig (layer_full) und ohne Rücksicht auf Teilnahmen verteilt werden.
  * Basierend auf der Erfahrung mit Anfragen, glaube ich, dass auch Löschanträge rasch genug verarbeitet werden würden. (Mit dem Vorteil, dass der Prozess eben auch in den ersten 10 Jahren nach einem Kursbesuch funktioniert.)
  * Falls das Recht bei der PBS breiter vergeben werden soll, würde ich empfehlen das als eigene Permission zu definieren. So könnte das dann gezielt einzelnen Rollen vergeben werden.
  * Ich werde das auch im Anderen Ticket noch ergänzen: Ich hätte die 10 Jahre gerne konfigurierbar. (Kann aber hier und beider automatischen Löschung identisch sein.)

**Comment by Michael-Schaer** [comment]
> Soll das wirklich für lokale Adressverwalter*innen möglich sein? Was wenn die Person in mehreren Gruppen Rollen hat? Wie verhindern wir Missbrauch? Klar, bisher wenn du die Löschung als Admin machen musst hast du auch keine Ahnung ob es legitim ist, aber die Hürde ist sehr viel höher wenn man das "der PBS zur Löschung übergeben" muss anstatt zwei Klicks zu machen. Vielleicht könnten wir es zumindest auf `layer_and_below_full` einschränken, sodass ALs das dürfen, aber Adressverwalter*innen nicht?

Ja, das stimmt, `layer_full` ist vielleicht gerade einer zu viel. Ich hatte an die regionalen und kantonalen PowerUser gedacht (die von der Adressverwaltung erben), aber vergessen, dass diese `layer_and_below_full` haben. Diese sind aus meiner Sicht in der Zielgruppe, gerade wenn es ums Zusammenfügen von Dubletten geht.
 
> Woher kommt die Aussage "manchmal muss es schnell gehen"? Stehen im Datenschutzgesetz irgendwelche Fristen? Was riskieren wir wenn eine ausserordentliche Löschung halt nicht innert 10 Sekunden als Schnellschuss umgesetzt werden kann?

Im Musterbrief vom EDÖB wird die Auskunft innerhalb von 30 Tagen verlangt: https://www.edoeb.admin.ch/edoeb/de/home/datenschutz/grundlagen/auskunftsrecht.html 
Mein Anliegen ist hier vor allem, das man das auch schnell erledigen kann, wenn man vorher 25 Tage lang die Verantwortung herumgeschoben hat oder jemanden nicht erreicht hat. Ausserdem möchte ich den Overhead für alle klein halten. Worst Case ist, dass eine Voranmeldung für einen Kurs die Löschung blockiert und man dann den ganzen Supportweg bis zum Ticket an Puzzle durchgehen muss. Daher soll die Löschung bewusst nur bei definitiven Anmeldungen in den letzten 10 Jahren verhindert werden. Je besser wir das abstecken können, desto weniger Speziallfälle müssen wir dann manuell (und schnell) behandeln.

**Comment by Michael-Schaer** [comment]
> Aus unserer Sicht darf das Löschen von Personen die noch irgendwo verknüpft sind nur für Admins möglich sein. Unsere Erfahrung zeigen, dass schon Admins der Regionen nicht korrekt mit dieser Fähigkeit umgehen - wir haben bereits zwei mal alle Daten wichtiger Personen (Geschäftsleiter einer anderen Region) verloren, weil dieses Recht bei uns zu breit vergeben wurde. (Die Einschränkung auf keine Teilnahmen hätte hier aber sicher geholfen.)

Ich bin einverstanden damit, dass die Funktion nur wenigen Rollen zur Verfügung stehen soll. Ist `layer_and_below_full` das gleiche, was du bei euch als "Admin" bezeichnest? Oder habt ihr effektiv :admin Berechtigungen in den Regionen / Gruppen?

Ich habe mir noch überlegt, ob das Löschen verhindert wird, wenn Rollen in einer anderen Ebene vorhanden sind. Das wird aber auch sehr kompliziert, wenn ich diese andere Ebene gar nicht auf dem Profil sehe (z.B. Rolle "Wölfli").

> Ich hätte deshalb lieber eine Funktion ähnlich den Anfragen: Für Personen kann eine Löschung beantragt werden. Die Admins auf Dachverbandsebene erhalten ein Mail mit dem Hinweis und haben dann irgendwo ein Tab mit den offenen (und idealerweise bearbeiteten, d.h. akzeptierten und abgelehnten) Löschanträgen.

Bei Anfragen bin ich vor allem kritisch, weil das die Funktionalität doch recht aufbläst. Ich möchte das Löschen eigentlich lieber möglichst einfach und dumm halten ;) 

> Basierend auf der Erfahrung mit Anfragen, glaube ich, dass auch Löschanträge rasch genug verarbeitet werden würden. (Mit dem Vorteil, dass der Prozess eben auch in den ersten 10 Jahren nach einem Kursbesuch funktioniert.)

Findest du denn die Einschränkung falsch, dass das Löschen verhindert wird bei Kurs/Lagerbesuchen?

So wie das Ticket bisher beschrieben ist, wird die Admin-Löschfunktion (bei uns haben diese nur ca. 10 Personen) nicht beeinträchtigt. Das heisst, wenn es mal eine Dublette gibt und beide Accounts schon in einem Kurs/Lager waren, kann ich als Admin trotzdem noch löschen.

> Ich werde das auch im Anderen Ticket noch ergänzen: Ich hätte die 10 Jahre gerne konfigurierbar. (Kann aber hier und beider automatischen Löschung identisch sein.)

Ja, unbedingt! Und Kurse und Lager sollten zwei Variablen sein!

**Comment by carlobeltrame** [comment]
> Ich hatte an die regionalen und kantonalen PowerUser gedacht (die von der Adressverwaltung erben), aber vergessen, dass diese `layer_and_below_full` haben. Diese sind aus meiner Sicht in der Zielgruppe, gerade wenn es ums Zusammenfügen von Dubletten geht.

Für Dubletten-Zusammenführung hat hitobito aber einen eigenen Mechanismus, den die regionalen und kantonalen PowerUser bereits heute bedienen können (auf der Personenliste der "Duplikate" Knopf). Ist dir das bewusst? Wo liegen die Limitierungen dieses Features? Ich habe das Gefühl dass das Duplikats-Problem mit diesem Feature abgedeckt werden sollte, nicht mit einer kompletten Datenlöschung die den regionalen Leuten übergeben wird.

Es häufen sich in letzter Zeit bei Puzzle Anfragen von verschiedenen hitobito-Nutzerorganisationen, weil die Leute immer wieder mal _aus Versehen_ ganze Gruppen löschen (daraus ist #1976 entstanden). Daher bin ich immer noch skeptisch, diese unwiderrufliche Löschungsmöglichkeit an die Basis zu geben (und das obwohl ich sonst praktisch immer dafür bin, die Rechte im Baum herunterzugeben).

**Comment by nchiapol** [comment]
* Wir hatten effektiv `:admin` in den Regionen (da wir ohne Dachverband begonnen hatten)
* Betreffend Anfragen: Ich glaube die zusätzliche Komplexität hier ist gerechtfertigt - und die Möglichkeit frühere Lösch-Entscheide nachzuvollziehen ist ein grosser Mehrwert (wir konnten bisher nicht identifizieren wer für die fehlerhaften Löschungen verantwortlich ist...)
* Bezüglich Einschränkung bei Kurs/Lagerbesuch: Die finde ich super - aber wenn es einen Grund gibt Personen ganz zu löschen (und nicht nur die Daten zu minimieren) dann kann dieser Grund sicher auch in den 10 Jahren auftreten. Ich würde deshalb einen Prozess vorziehen, der auch diese Situation abdeckt.

**Comment by richardjubla** [comment]
Meine vorerst unverbindlichen Gedanken dazu. Ich versuche eine ofiziellen/konstruktiven Input der Jubla zu koordinieren:


**Die hier geführten Diskussion sollten aus meiner Sicht den automatisierten (privacy by design) oder "einfachen Weg"  zur Datenlöschung beschreiben der vor oder unabhängig vom rechtlichen Ablauf erfolgt. Sobald "Bedingungen" die Löschung nicht ermöglichen, kämen sie in Konflikt mit dem verbindlichen Antrag und müssten wiederum rechtssicher behandelt werden können.** 


Zum Auskunftsrecht bzw. Recht auf vergessen (Löschantrag) gemäss DSG:

Dies sind aus meiner Sicht offizielle und rechtlich bindende Abläufe die auf ebene "hitobito" (auf core Ebene) oder individuell (auf dem Papierweg) zu lösen sind. Hier könnte Hitobito ein Interesse an einer offiziellen Lösung haben da es eventuell eine generelle Anforderung an ein solches Produkt ist.

Schliesslich braucht es dazu eine Auswies-Kopie und wird normalerweise eingeschrieben an die "Datenschutz-Adresse" gesendet. Aktuell sehe ich den Aufwand nicht gerechtfertigt geeignete Massnahmen zu treffen, um die Identifizierung der betroffenen Person zu gewährleisten und deren Daten vor dem Zugang unbefugter Dritter bei der Bekanntgabe zu schützen. (Dieser Prozess müsste in Hitobito umgesetzt werden!)

Auskunftsbegehren können auch der Präsident*in/Vorstand des einzelnen Vereins (manuell) beantworten oder an den Verband hochreichen. Hier wäre cool, wenn jeder selbst einen Export aller Daten machen könnte (Feature im Tab Sicherheit).
Ein Austritt (Löschung) ist an jeden Verein zu stellen in dem man Mitglied ist. Bei der Jubla ist ein Austritt aus der Schar, dem Kanton und dem Verband/Ehemaligenwesen individuell möglich/notwendig. Deshalb ist eine Löschung ein Austritt aus dem gesamten Verband und auch mit aller Konsequenz an ihn zu richten. 


Bei uns wäre das Vorgehen aktuell wie folgt:
Ein Löschantrag muss an den Verband (Verbandssekretariat) eingereicht werden. Wir werden dies wahrscheinlich mit einem Formular/FAQ "unterstützten", da wir hier auf die Folgen (Verbands-/Vereinsaustritt, Verlust aller Daten, etc.) hinweisen wollen. Wer uns einen Brief (Musterbrief) schreibt, wird aus der Datenbank gelöscht und kriegt eine Bestätigung der Löschung auf dem Papierweg/Mail.

**Comment by Michael-Schaer** [comment]
Angepasste Spezifikation:

Als Adressverwalter\*in meiner lokalen Gruppe möchte ich für erfasste Personen eine Datenlöschung wahrnehmen können. Diese kommt zum Einsatz, wenn eine Person ausdrücklich wünscht, nicht mehr geführt zu werden. Es gibt aber Kriterien, die verhindern, dass die Person dann auch wirklich gelöscht wird. Für diese manuelle Datenlöschung können die Mechanismen aus der automatisierten Datenlöschung teilweise übernommen werden (https://github.com/hitobito/hitobito/issues/2106).

## Neuer Button unter "Ohne Rollen"
Die Liste "Ohne Rollen" soll pro Person einen Button erhalten, um eine Datenlöschung zu überprüfen. Dieser Button entspricht aber nicht der aktuellen Delete-Funktion, sondern wird parallel dazu eingeführt. Der Button ist sichtbar für Personen mit `layer_and_below_full` einer Ebene. Der Button kann pro Wagon aktiviert / deaktiviert werden.

![grafik](https://github.com/hitobito/hitobito/assets/1799621/257a1a4b-f23e-4bbe-a997-8e0911af5f1c)

### Bedingungen für eine Löschung
Analog zu https://github.com/hitobito/hitobito/issues/2106 sollen Kriterien pro Wagon definiert werden können, wann eine Datenlöschung manuell ausgeführt werden darf. Die Kriterien unterscheiden sich von den Kriterien für die automatisierte Löschung. Für den Youth-Wagon schlagen wir folgende Bedingungen vor:

- Keine Kursteilnahme in den letzten 10 Jahren
- Keine Lagerteilnahme in den letzten 10 Jahren

Da der Button in der Liste "ohne Rollen" platziert wird, kommt das versteckte Kriterium "Person hat keine Rolle" hinzu. Dieses Kriterium ist wichtig, damit Personen nicht von fremden Ebenen gelöscht werden können. Nach unserem Verständnis sollte das für alle Wagons zutreffen.

Beim bestätigen des Buttons werden die Kriterien überprüft und die entsprechenden Optionen dem User gezeigt: 
- Benutzer darf gelöscht werden (+ Button "Benutzer definitiv löschen")
- Benutzer darf nicht gelöscht werden (mit konfigurierbarem Text für die Begründung)
- Falls nicht schon minimiert: Benutzer minimieren (mit konfigurierbarem Text, was das bedeutet)

### Löschung
Der Benutzer wird komplett gelöscht. Dies entspricht der Löschung hier: https://github.com/hitobito/hitobito/issues/2106#issuecomment-1589666528

### Minimierung
Nur die durch den Wagon definierten Felder des Benutzers werden gelöscht. Dies entspricht der Minimierung hier: https://github.com/hitobito/hitobito/issues/2106#issuecomment-1589666528

## Abgrenzung
Aus Sicht PBS sollen Benutzer\*innen für sich selber keine Datenlöschung auslösen können. Gerade bei Mitgliedern kommt eine Datenlöschung oft mit dem Austritt aus der Abteilung gleich. Diesen Zusammenhang sollen die Funktionsträger der Gruppe herstellen, nicht die Benutzer\*innen selber.

Benachrichtigungen sollen vorerst keine verschickt werden (z.B. an andere Gruppen, bei denen die Person noch Mitglied war). Eine solche wäre zwar wünschenswert, jedoch gibt es eine solche Benachrichtigung beim heutigen Prozess auch nicht, deshalb lassen wir das fürs erste weg.

Für den Youth-Wagon: Anlass-, Kurs- und Lagerteilnahmen in der Zukunft werden, wie bisher auch, nicht beachtet. Die gelöschte Person ist dann einfach nicht mehr als Teilnehmer*in angemeldet. Datenlöschungen müssen manchmal auch schnell gehen, deshalb soll das nicht beachtet werden.

Die bestehende Lösch-Funktion für Admins (bei der PBS) soll nicht angerührt werden. Admins können weiterhin ohne Einschränkung Personen manuell löschen (z.B. Dublikate, usw.).

**Comment by nchiapol** [comment]
Ich fände eine Lösung via Anträge immer noch sinnvoller - aber ich denke mit dieser Spezifikation können wir auch leben.

Ein zwei Rückfragen/Anmerkungen:
  * "Da der Button in der Liste "ohne Rollen" platziert wird, kommt das versteckte Kriterium "Person hat keine Rolle" hinzu." macht für mein Verständnis folgende beiden Punkte unnötig:
    * "Aus Sicht PBS sollen Benutzer*innen für sich selber keine Datenlöschung auslösen können." Entweder habe ich eine Rolle die "ohne Rollen" sehen kann oder ich bin selbst in "ohne Rollen", beides gleichzeitig ist nicht möglich.
    *  "Benachrichtigungen sollen vorerst keine verschickt werden (z.B. an andere Gruppen, bei denen die Person noch Mitglied war).". Die Person kann in keiner Gruppe mehr Mitglied sein, sonst hätte sie noch eine Rolle...
  * "Anlass-, Kurs- und Lagerteilnahmen in der Zukunft werden, wie bisher auch, nicht beachtet." Ich bin einverstanden, dass das kein zwingender Hinderungsgrund sein sollte - aber ich denke es wäre wichtig, wenn im entsprechenden Dialog mit den Optionen darauf hingewiesen würde. So kann ich die entsprechenden Verantwortlichen wenigstens manuell informieren.

**Comment by Michael-Schaer** [comment]
Danke @nchiapol für die Hinweise. ich bin einverstanden mit deinen Punkten. Ich werde die Spezifikation aber so belassen, weil die Offerte schon gemacht wurde. Wenn es reicht, können wir deinen Punkt noch umsetzen.
