### ISSUE TITLE
MESSAGES: Personen als Empfänger zu Abo hinzufügen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito#2110]
Für Personen, welche die Abos verwalten, soll es möglich sein in einer beliebigen Gruppe Personen anzuwählen und diese anschliessend direkt zu einem Abo hinzuzufügen. Neu soll also die Möglichkeit bestehen, mehrere Personen gleichzeitig zu einem Abo hinzuzufügen. Funktionalität kann hier ähnlich umgesetzt werden, wie das Hinzufügen von mehreren Personen zu Veranstaltungen. Sobald mindestens eine Person angewählt wird, erscheint neben dem Button für das hinzufügen zu Veranstaltungen auch ein Button für das Hinzufügen zu Abos.

Neue Struktur Action-Buttons:

![image](https://github.com/hitobito/hitobito/assets/655627/e81493e7-fb97-478a-83ba-c513eccbe37d)

:warning: Für **Zu Abo hinzufügen** ein Button und nicht wie hier im Mockup ein DropDown erstellen, **+** Icon verwenden

# Workflow

1. Benutzer wählt mehrere Personen in einer Personenliste an, die Multi Action Toolbar wird angezeigt
2. Beim Klick auf 'Zu Abo hinzufügen' öffnet sich ein Modal mit einem Type-Ahead in dem dem Benutzer sämtliche Abos auf die er Schreibrechte hat aufgelistet werden.
3. Nachdem der Benutzer ein Abo gewählt hat, kann er die Personen via 'Hinzufügen' hinzufügen
4. Es wird eine Flash-Message zur Bestätigung angezeigt: 'Es wurden 42 Personen dem Abo Blabli als Empfänger hinzugefügt.'

![image](https://github.com/hitobito/hitobito/assets/655627/1aae5004-493b-45fd-b8f6-f57bbc9c0501)

ähnlicher Dialog wie bei Tags und Veranstaltungen

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/views/people/_multiselect_actions.html.haml
- Neue Dropdown Klassen für RoleActions
- Eigener Controller für Modal dialog erstellen: siehe https://github.com/hitobito/hitobito/blob/master/app/controllers/role_lists_controller.rb
- Entweder https://github.com/hitobito/hitobito/blob/master/app/controllers/subscriber/person_controller.rb so erweitern das dieser auch mit einer Liste von Personen-IDs umgehen kann, zusätzlich das dieser auch mit der Async-Action umgehen kann oder den Modal controller entsprechend mit dieser Action ausrüsten
- Sicherstellen das wenn Personen bereits subscriber sind, es zu keinem Fehler kommt. (Bereits best. Subscribers einfach ignorieren und als Erfolgreich-Hinzugefügt anschauen)

# ToDo

- [x] Drop-Down für Rollen Actions erstellen und Buttons in dieses Drop-Down verschieben
- [x] Neuen Button 'Zu Abo hinzufügen' erstellen
- [x] Controller für Modal Action erstellen
- [x] Controller für Erstellen der MailingList Subscriber erstellen oder den best. Controller anpassen (siehe Tech-Spec)
- [x] Feature Spec ergänzen
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
