### ISSUE TITLE
GROUPS: Tabs für Bearbeitungs-Formular

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2116]
Das Formular für die Bearbeitung der Gruppenattribute wird immer unübersichtlicher. Weiter ist geplant das man künftig mehr Metainformationen auf der Gruppe hinterlegen kann. Aus diesem Grund sollen die Felder in Tabs gruppiert werden analog wie wir das bereits von den Anlässen kennen.

| Allgemein | Externe Anmeldung | Kontaktinformationen | Wagon-Tab 1 | Wagon-Tab 2 |

- Allgemein: Alle nicht sonst einem Tab zugeordneten Felder
- Externe Anmeldung: selbstsprechend (nur anzeigen falls Feature Selbst-Reg aktiviert)
- Kontaktinformationen: Contactables
- Wagon Tabs können via render extensions ergänzt werden

# Tech-Spec

- little bit like: https://github.com/hitobito/hitobito/blob/master/app/views/events/_form.html.haml
- and https://github.com/hitobito/hitobito/blob/master/app/views/events/_form_tabs.html.haml
- but keep it simpler as possible
- https://github.com/hitobito/hitobito/blob/master/app/views/groups/_form.html.haml
  - render extension field in Allgemein

# ToDo

- [x] Neue Partial Views erstellen und Felder aufteilen
- [x] Sicherstellen das alle Specs weiterhin funktionieren
- [x] best. render extension field in mind. 1 wagon der dieses Feature braucht testen
