### ISSUE TITLE
TECH: Ruby 3.x und Gems upgrade

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito#2128]
Upgrade von Ruby und Gems

# ToDo

- [x] Hitobito mit Ruby 3.0 lauffähig machen
- [x] Brakeman upgraden
- [ ] ggf. weiteres Upgrade auf Ruby 3.2
- [ ] Depandanbot meldungen prüfen und ggf. weitere Gems updaten

**Comment by mtnstar** [comment]
* https://github.com/heartcombo/devise/compare/v4.8.1..v4.9.2
* https://github.com/wardencommunity/warden/compare/v1.2.8...v1.2.9

**Comment by kronn** [comment]
included in #2213
