### ISSUE TITLE
PEOPLE: Letzte aktive Rolle auf Person speichern

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#2136]
Das ermitteln von "Personen ohne Rollen" ist technisch jedes Mal ein ziemlicher Aufwand. Insbesondere da es ein Zustand einer Person ist, der nur selten ändert.

Daher ist das Ziel nun, ein separates Feld auf der Person zu hinerlegen welches die ID zur letzen soft-gelöschten Rolle hinterlegt hat.
Das Feld ist nur befüllt wenn die Person sonst keine aktive Rolle hat.

# Tech-Spec

- Umsetzung im Core

# ToDo

- [ ] Migration erstellen: `last_active_role_id`
- [ ] RecurringJob anlegen welcher täglich(?) läuft
  - [ ] befüllt `last_active_role_id` wenn nötig
  - [ ] entfernt `last_active_role_id` wenn nötig
- [ ] `Group::DeletedPeople` anpassen sodass es mit `last_active_role_id` arbeitet
- [ ] Evtl. gibt es noch andere Orte an denen die Personen ohne Rollen gesammelt werden, diese auch anpassen
- [ ] Wagons überprüfen
- [ ] Sicherstellen dass alle Specs laufen
- [ ] Specs schreiben
- [ ] Volltextsuche Performance testen
- [ ] Mit angemessener Rolle "durchklicken"
