### ISSUE TITLE
PEOPLE: Geschwister in Abteilung als computed value

### ISSUE THREAD

**Issue by simfeld** [hitobito/hitobito#2147]
Stand heute gibt es zwei Konzepte von Gschwistern in hitobito:

1. Geschwister (in der Abteilung/Gruppe), boolean
2. Geschwister, self-relation zu people

![grafik](https://github.com/hitobito/hitobito/assets/9254954/3ac99808-c2c9-4c2c-bf76-702b49003b94)

Das Konzept Nr. 1 ist soweit ich feststellen kann eine Erweiterung im PBS-Wagon: https://github.com/hitobito/hitobito_pbs/blob/2ba6ed5aa034d997e4d9114629831c7b1f3c0bf1/app/models/pbs/person.rb#L65. Dieses Issue betrifft somit nur den PBS-Wagon.

Die Information dieser beiden Felder/Relationen ist teilweise redundant und kann zu Verwirrung führen.

Use Cases für Abbildung von Geschwister-Relationen:

1. Vergünstigungen von Lagerbeiträgen, Vereinsbeiträgen etc. bei mehreren Kindern derselben Familie, typischerweise innerhalb einer Gruppe
2. Abbildung von familiären Verbindungen, ggf. auch über Gruppe hinaus
4. mehr? TBA

Neu soll das Feld "Geschwister (in der Abteilung)" aus der Geschwister-Relation berechnet werden. Das Feld kann also nicht mehr manuell auf der Person definiert werden, sondern ergibt sich aus der betreffenden Gruppe sowie den Geschwister-Relationen der gegebenen Person.

Das Feld wird von "Geschwister (in der Abteilung)" umgedeutet auf "Geschwister in der aktuell angezeigten Gruppe/Personenansicht". Der Bezug auf "in der Abteilung" war sowieso nicht klar definiert, da eine Person grundsätzlich Rollen in mehreren Abteilungen haben kann, womit ein einzelnes Boolean-Feld nicht mehr eindeutig ist. Sehr wahrscheinlich war mit Abteilung die Hauptgruppe gemeint, wobei die Hauptgruppe nicht zwingend eine Abteilung sein muss.

Das berechnete Feld "Geschwister in der aktuell angezeigten Gruppe/Personenansicht" wird in folgenden Ansichten angezeigt:
- Einzelne Personenansicht: hat Person Geschwister mit Rolle in der Gruppe, welche durch id in der url identifiziert wird (= Gruppe der aktuellen Ansicht)
- Personenliste einer Gruppe: hat Geschwister mit Rolle in dieser Gruppe
- Teilnehmendenliste eines Anlasses/Lagers/Kurses: hat Geschwister unter den Teilnehmenden

Out of scope / Folge-Erweiterung: Geschwister in Erstellung von Sammelrechnungen miteinbeziehen (z.B. Rabatt).

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- Umsetzung im PBS Wagon, weil das Feld "Geschwister (in der Abteilung)" bisher auch nur dort existiert, und weil die Definition der "aktuell angezeigte Gruppe/Personenansicht" relativ PBS-spezifisch ist:
- Die Aussagen "Geschwister mit Rolle in dieser Gruppe" etc. werden umgedeutet auf "Geschwister mit Rolle in derselben Ebene", da das näher an der bisherigen Bedeutung des alten manuell setzbaren Felds ist
- Das bisherige, manuell setzbare Feld `brothers_and_sisters` ist auf der Personen-Detailansicht sowie im "Alle Angaben" Export von Gruppenmitgliederlisten und Anlass-Teilnahmelisten und in der JSON API verfügbar. Das neue berechnete Feld soll an denselben Orten auftauchen, unter dem Namen `has_siblings_in_layer` bzw. `has_siblings_in_event`.
- Personenfilter mit `range=deep` werden von dieser Berechnung ignoriert. Das Feld bleibt dann z.B. mit der Bezeichnung "Geschwister in Pfadi Züri", und ignoriert jegliche Geschwister-Rollen in Abteilungen der Pfadi Züri.
- In Anlässen (und Lagern und Kursen) ist es egal, welche Anlassrolle die Geschwister haben. Leitung, Teilnehmende, Küche etc. werden alle als Geschwister mitgezählt.
- Das Feld als zusätzliche Spalte in Personenlisten verfügbar zu machen ist optional, falls die Zeit noch reicht.

# ToDo

- [x] Migration schreiben, welche die [Spalte `brother_and_sisters`](https://github.com/hitobito/hitobito_pbs/blob/master/db/migrate/20131211121712_add_pfadi_attributes.rb#L22) (ohne `s` bei `brother`) entfernt
- [x] In der [Personen-Detailansicht](https://github.com/hitobito/hitobito_pbs/blob/master/app/views/people/_details_pbs.html.haml) `brothers_and_sisters` entfernen, und stattdessen ein berechnetes Feld anzeigen
  - [x] Das berechnete Feld sollte im UI "Geschwister in MeinLayer" heissen, wobei MeinLayer das Layer der aktuell angezeigten Gruppe ist (in der View als `group.layer_group` oder `parent.layer_group` verfügbar)
  - [x] Logik für Layer-Geschwister im [`Pbs::PersonDecorator`](https://github.com/hitobito/hitobito_pbs/blob/master/app/decorators/pbs/person_decorator.rb) implementieren, unter dem Namen `def siblings_in_layer(layer)` o.ä.
  - [x] Alle Geschwister der Person können als `entry.relations.where(kind: 'sibling')` berechnet werden, und müssen dann noch gefiltert werden, sodass nur Geschwister mit Rollen in demselben Layer gelten. Rollen in (Gruppen von) Sub-Layers können ignoriert werden. Die Subgruppen eines Layers können z.B. mit `group.groups_in_same_layer` berechnet werden. Achtung: Nur aktive Rollen (`deleted_at` NULL oder in der Zukunft) sollen berücksichtigt werden!
  - [x] Möglicherweise kann, wegen dem Argument das in `siblings_in_layer` hineingegeben werden muss, nicht mehr einfach `render_attrs` verwendet werden. In diesem Fall muss man wohl manuell mit `labeled_attr` oder sogar `format_attr` arbeiten. Zur Referenz: Diese Methoden sind im Core im [FormatHelper](https://github.com/hitobito/hitobito/blob/master/app/helpers/format_helper.rb#L111) definiert.
- [x] Im ["Alle Angaben" Tabular People Export](https://github.com/hitobito/hitobito_pbs/blob/master/app/domain/pbs/export/tabular/people/people_full.rb) ein berechnetes Feld einfügen
  - [x] Logik vom `PersonDecorator` wiederverwenden
  - [x] Die aktuell angezeigte Gruppe (bzw. ihr Layer) ist im Export bisher nicht so einfach verfügbar. Die `group` ist aber im Core [PeopleExportJob](https://github.com/hitobito/hitobito/blob/master/app/jobs/export/people_export_job.rb#L68) bereits bekannt, und muss "nur" noch [im PBS Wagon](https://github.com/hitobito/hitobito_pbs/blob/master/app/jobs/pbs/export/people_export_job.rb) in den Exporter hineingegeben werden, falls ein `full?` Export gewünscht ist.
  - [ ] Die Spalte im Export sollte bestenfalls auch wieder "Geschwister in MeinLayer" heissen, wobei MeinLayer das Layer der aktuell angezeigten Gruppe ist. Notfalls ginge aber auch ein statisches Label "Geschwister in der Ebene"
  - Beispiele für berechnete Felder in einem Export sind z.B. in der [PersonRow](https://github.com/hitobito/hitobito_pbs/blob/master/app/domain/pbs/export/tabular/people/person_row.rb) zu finden
- [x] Im [Personen-Endpoint](https://github.com/hitobito/hitobito_pbs/blob/master/app/serializers/pbs/person_serializer.rb) der JSON API das berechnete Feld hinzufügen
  - [x] Technische Bezeichnung z.B. `has_siblings_in_layer`
  - [x] Inhalt vom `PersonDecorator` wiederverwenden
  - [x] Die Gruppe, deren Layer wir brauchen, ist in diesem Serializer als `context[:group]` verfügbar
  - Ein Beispiel für ein computed Property ist im [Core Serializer](https://github.com/hitobito/hitobito/blob/master/app/serializers/people_serializer.rb#L34) zu sehen
- [x] Die Participation-Detailansicht verwendet [dasselbe Partial](https://github.com/hitobito/hitobito/blob/master/app/views/event/participations/_attrs.html.haml#L15..L16) wie die Personen-Detailansicht. Für das Geschwister-Attribut wollen wir aber je nach Kontext einen anderen Wert (und ein anderes Label) anzeigen. Daher im [selben Partial wie bereits zuvor](https://github.com/hitobito/hitobito_pbs/blob/master/app/views/people/_details_pbs.html.haml) via `parent.is_a? Event` oder `try(:participation).present?` o.ä. detektieren, ob wir gerade die Personenliste eines Anlasses oder einer Gruppe anzeigen
  - [x] Das berechnete Feld sollte im UI "Geschwister in MeinAnlass" heissen, wobei MeinAnlass der aktuell angezeigte Anlass ist (im Partial möglicherweise als `parent` verfügbar)
  - [x] Logik für Anlass-Geschwister z.B. im [`Pbs::Event::ParticipationDecorator`](https://github.com/hitobito/hitobito_pbs/blob/master/app/decorators/pbs/event/participation_decorator.rb) implementieren, unter dem Namen `def siblings_in_event(event)` o.ä.
  - [x] Falls weder `parent` noch `participation` etc. im Partial verfügbar sind, brauchts vielleicht noch eine Core-Anpassung, um das noch hineinzugeben... Oder man überschreibt das ganze `event/participations/_attrs` Partial im Wagon, was auch nicht sehr schön ist...
  - [x] Alle Geschwister der Person können als `entry.relations.where(kind: 'sibling')` berechnet werden, und müssen dann noch gefiltert werden, sodass nur Geschwister mit Participation in demselben Anlass gelten. Jegliche Anlassrollen sind okay, egal ob es Teilnehmende oder Leitende oder sonst was sind. Achtung: Nur aktive Participations (`active: true` oder via `.active` Scope) sollen berücksichtigt werden!
- [x] Im ["Alle Angaben" Tabular Participations Export](https://github.com/hitobito/hitobito_pbs/blob/master/app/domain/pbs/export/tabular/people/participations_full.rb) ein berechnetes Feld einfügen
  - [x] Logik vom `ParticipationDecorator` wiederverwenden
  - [x] Der aktuell angezeigte Anlass ist im Export bisher nicht so einfach verfügbar. Er ist aber im Core [EventParticipationsExportJob](https://github.com/hitobito/hitobito/blob/master/app/jobs/export/event_participations_export_job.rb#L14) unter `@filter.event` verfügbar und muss "nur" noch [im PBS Wagon](https://github.com/hitobito/hitobito_pbs/blob/master/app/jobs/pbs/export/event_participations_export_job.rb) in den Exporter hineingegeben werden, falls ein `full?` Export gewünscht ist.
  - [ ] Die Spalte im Export sollte bestenfalls auch wieder "Geschwister in MeinAnlass" heissen, wobei MeinAnlass der aktuell angezeigte Anlass ist. Notfalls ginge aber auch ein statisches Label "Geschwister im Anlass"
  - Ein Beispiel für ein berechnetes Feld in einem Export ist z.B. in der [ParticipationRow](https://github.com/hitobito/hitobito_pbs/blob/master/app/domain/pbs/export/tabular/people/participation_row.rb) zu finden
- [x] Im [Participation-Endpoint](https://github.com/hitobito/hitobito_pbs/blob/master/app/serializers/pbs/event_participation_serializer.rb) der JSON API das berechnete Feld hinzufügen
  - [x] Technische Bezeichnung z.B. `has_siblings_in_event`
  - [x] Inhalt vom `ParticipationDecorator` wiederverwenden
  - [x] Der Anlass ist in diesem Serializer als `item.event` verfügbar
- [x] Global im PBS Wagon nach `brother_and_sisters` (ohne `s` bei `brother`) suchen und alle weiteren Verwendungen entfernen bzw. wo sinnvoll ersetzen (z.B. in den Specs)
- [ ] Michael Schär wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
Der Jubla-Wagon kennt auch Geschwister:

Es gibt das Feld Familienmitglider welches den Wert "Geschwister" und eine Verbindung zu einem Profil (vermutlich Lesebrechtigung) eingetragen werden kann.  
![image](https://github.com/hitobito/hitobito/assets/95908537/7aeb552c-bd2a-4925-aa68-5b78fad78751)

**Comment by simfeld** [comment]
@richardjubla Danke, das war mir nicht bewusst. Ich denke aber nach wie vor, dass die von mir vorgeschlagenen Änderungen nur den hitobit_pbs-Wagon betreffen, da an der Geschwister-Relation (core feature) keine Anpassungen vorgenommen werden müssen.

**Comment by diegosteiner** [comment]
> Die group ist aber im Core PeopleExportJob bereits bekannt, und muss "nur" noch im PBS Wagon in den Exporter hineingegeben werden, falls ein full? Export gewünscht ist.

Das hineingeben ist schwierig, die `export`-Methode wird statisch ausgeführt, aktuell sehe ich keinen sinnvollen Weg, wie ich die `group` übergeben könnte. Folgende Möglichkeiten gäbe es aus meiner Sicht:

- Den Exporter vor dem Aufruf von `export` instanzieren und den `ExportJob` als Parameter mitgeben. Dies hätte aber unter Umständen weitreichende Änderungen in allen Wagons zur Folge
- Den [ExportJob im PBS Wagon](https://github.com/hitobito/hitobito_pbs/blob/master/app/jobs/pbs/export/people_export_job.rb) so anpassen, dass beim Full Export der group Parameter ebenfalls mitgegeben wird. Das würde aber Logik vom core sehr unschön überschreiben
- Die `group` irgendwie in den [PeopleFull Export](https://github.com/hitobito/hitobito_pbs/blob/master/app/domain/pbs/export/tabular/people/people_full.rb) hineinwurschteln. Ich zweifle aber, dass ich das sauber hinbekomme.

@carlobeltrame hast du noch bessere Ideen?

**Comment by carlobeltrame** [comment]
@diegosteiner wie wäre es wenn du die Methode `data` im Wagon überschreibst, und dort drin, falls der Export `full?` ist, die `group` in den Konstruktor des Exporters hineingibst? So ähnlich machen wir das schon bei den TableDisplay Exports [im Core](https://github.com/hitobito/hitobito/blob/master/app/jobs/export/people_export_job.rb#L41) in der `data` Methode.

**Comment by diegosteiner** [comment]
> @diegosteiner wie wäre es wenn du die Methode `data` im Wagon überschreibst, und dort drin, falls der Export `full?` ist, die `group` in den Konstruktor des Exporters hineingibst? So ähnlich machen wir das schon bei den TableDisplay Exports [im Core](https://github.com/hitobito/hitobito/blob/master/app/jobs/export/people_export_job.rb#L41) in der `data` Methode.

@carlobeltrame habe ich jetzt mal so gut es ging umgesetzt. PR kann gereviewt werden.
