### ISSUE TITLE
SECURITY: SBOMs für alle hitobito-Instanzen generieren

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2177]
Als sicherheitsbewusste Person bei Puzzle
möchte ich pro hitobito-Instanz jederzeit einen aktuellen SBOM-Report haben,
um schnell auf neu entdeckte Sicherheitslücken reagieren zu können.

Als Proof of Concept sammeln wir bereits bei der Jubla-Instanz diese SBOM-Informationen: https://github.com/hitobito/ose_composition_jubla/blob/devel/.github/workflows/sbom.yml
Auf ähnliche Weise soll bei allen anderen Composition Repos ein ähnlicher Workflow das SBOM bei jedem Release an die Puzzle SBOM Registry reporten.

# Tech-Spec

- Nötige Secrets sind bereits auf der hitobito-Organisation definiert, daher müsste es also reichen, nur diesen Workflow in alle Composition Repos zu kopieren.

# ToDo

- [x] Workflow in alle anderen Composition Repos kopieren
- [x] Falls nötig leicht anpassen (z.B. welche Wagons inkludiert werden etc.)
- [x] Workflow einmal von Hand anstossen und bei Puzzle Security nachschauen / nachfragen gehen ob es so klappt
