### ISSUE TITLE
MAIL RETRIEVER: Mails mit gewissen Betreffzeilen werden nicht versendet

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2179]
### Aktuelles Verhalten

Beim Versand von Mails via Abos wird mit dem neuen Mailstack das Mail temporär in die Datenbank gespeichert. Die Betreffzeile wird als zusätzliche Information in eine eigene Datenbankspalte geschrieben. Bei gewissen Betreffzeilen schlägt dies fehl, möglicherweise weil irgendwo in der MySQL-Verbindung ein Encoding noch nicht korrekt eingestellt ist. Die Tabelle selber hat bereits die Collation utf8mb4_unicode_ci.
Ein Beispiel ist die folgende Betreffzeile, wobei MySQL ab dem `ügt` reklamiert:
```
Anlass hinzugefügt
```

Zusätzlich schlägt es auch fehl, wenn der Betreff länger als 256 Zeichen lang ist, Beispiel:
```
An Error Occurred! Uncaught PHP Exception Requests_Exception: "cURL error 28: Operation timed out after 10009 milliseconds with 0 bytes received" at /home/pfadisch/www/pfadizytturm_prod/current/pfadizytturm.ch/vendor/rmccue/requests/library/Requests/Transport/cURL.php line 443 
```
Laut dem Internet können Betreffzeilen von E-Mails technisch bis zu 998 Zeichen lang werden, in der Datenbank haben wir aber aktuell ein Limit von 256 Zeichen.

### Gewünschtes Verhalten

Beiliebige Mails mit jeglichen Sonderzeichen und Emoji im Betreff können weitergeleitet werden.

### Schritte zu reproduzieren

Betroffene Mail liegt in der PBS Mailbox im Ordner "Failed".

### Wann ist der Fehler aufgetreten?

16.08.2023

### hitobito version

1.30.3

### Organisation

PBS

### Screenshots, weiterer Kontext

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/63186/

### Tech-Spec
- https://github.com/hitobito/hitobito/blob/master/app/domain/mailing_lists/bulk_mail/retriever.rb
- https://github.com/hitobito/hitobito/blob/master/spec/domain/mailing_lists/bulk_mail/retriever_spec.rb
- https://github.com/hitobito/hitobito/tree/master/spec/fixtures/email
- https://github.com/hitobito/hitobito/blob/master/spec/support/mailing_lists/imap_mails_spec_helper.rb
- https://github.com/mikel/mail

### ToDos
- [ ] Test schreiben mit E-Mail das ein Subject mit mehr als 256 Zeichen hat (retriever_spec)
- [ ] Beim Betreff nur die ersten 256 Zeichen persistieren (wird nur für die Anzeige im UI benötigt und nicht für den Versand)
- [ ] Test schreiben für E-Mail mit ungültigem Encoding im Betreff (retriever_spec)

**Comment by carlobeltrame** [comment]
Fixed in #2201
