### ISSUE TITLE
ELTERNZUGANG: Nacharbeiten MVP

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2196]
In einem Austausch mit allen beteiligten Parteien wurden die offenen Punkte aus Issue #2125 besprochen.
Daraus wurden die folgenden Punkte definiert welche im Umfang des MVP noch umgesetzt werden sollen.

- [x] Beim Anmelden zu einem Anlass haben Verwalter\*innen auch Personen zur Auswahl, welche diesen Anlass selbst nicht sehen könnten. Die Anmeldung kann anschliessend durchgespielt werden. Erst beim Abschliessen erhält man die Fehlermeldung "Sie sind nicht berechtigt diese Seite anzuzeigen".
Diese Fehlermeldung soll angepasst werden um aussagekräftiger zu sein. Vorschlag: "Die ausgewählte Person erfüllt die Anlassanforderungen nicht."
- [x] Geht man auf der Ebene selbst auf einen Anlass und versucht sich da anzumelden kann man das nicht, da die Anzumeldenden Personen im Hintergrund sind. Siehe Mockup#1
Dies soll behoben werden, damit das Droptdown immer komplett sichtbar ist.
- [X] Will ein Verwalter ein Kind an einen Anlass anmelden, schlägt dies fehl mit der Fehlermeldung "Sie sind nicht berechtigt, diese Seite anzuzeigen". Der Verwalter selbst kann sich anmelden, und das Kind kann sich selbst ebenfalls anmelden.
Dies wurde bisher nur auf Cevi_int beobachtet.
Verwalter sollen ihre Kinder korrekt bei Anlässen anmelden können ohne Fehlermeldung.
- [ ] Das aufrufen des Logs bei durch einen Verwalteraccount neu erstellten Kindes führt bei der Jubla_INT zu einem 404 Fehler. -> Kein Problem solange Teil 2 des Elternzugangs bei der Jubla ausgeschaltet ist.
- [x] Auf den Umgebungen von Jubla, Cevi und PBS sollen für den Moment die Features vom Elternzugang Teil 2 deaktiviert werden. Es sollen sich also keine Personen als Verwalter selbstregistrieren können, und Account sollen sich nicht selbst zusätzliche Kinder erfassen können.

# Mockup

**Mockup 1**
![grafik](https://github.com/hitobito/hitobito/assets/100761305/4d003813-e2a5-4261-91bc-6c1c395e0895)

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Ich habe unseren Fehler noch einmal reproduziert - auch auf einer ganz frischen lokalen Entwicklungsinstanz. 

Das Problem tritt auch dort wie oben beschrieben auf.  Ein paar Beobachtungen:

* Der Fehler tritt auf nachdem die Kontaktdaten kontrolliert wurden, beim öffnen des Formulars für die Anmelde-Angaben.
* Der Fehler scheint von app/controllers/application_controller.rb:83, store_current_person zu kommen (mindestens markiert der Debugger die Stellen)
* Ich hatte überlegt, ob das mit dem zusätzlichen Schutz für Teilnehmer-Rollen bei uns zu tun hat - das Problem tritt aber auch auf, wenn das Kind keine Teilnehmer Rolle sondern Gruppenleiter (in der Teilnehmergruppe) oder Freier Mitarbeiter (auf der Jungschar) hat.
* Das Kind kann sich nur selbst anmelden, wenn es eine Haupt-E-Mail erfasst hat. Für den Fehler ist es aber irrelevant, ob beim Kind eine Haupt-E-Mail eingetragen ist oder nicht.
* Hier auch noch den relevanten Teil des Logs beim auslösen des Fehlers: [log-messages.txt](https://github.com/hitobito/hitobito/files/12648174/log-messages.txt)

**Comment by nchiapol** [comment]
So etwas hatte ich befürchtet. Um das genauer zu untersuchen fehlt mir aber die Hitobito-Erfahrung (bzw. die Zeit ;-) - Ich hoffe, meine Beobachtungen helfen aber wenigstens euch etwas.

**Comment by ThomasEllenberger** [comment]
> Geht man auf der Ebene selbst auf einen Anlass und versucht sich da anzumelden kann man das nicht, da die Anzumeldenden Personen im Hintergrund sind. Siehe Mockup#1
Dies soll behoben werden, damit das Droptdown immer komplett sichtbar ist.

Dieser Punkt hat sich dank des Bootstrap Upgrades #1754  soeben erledigt.
Sobald dieses Issue gemerged ist wird dies auch auf den Testumgebungen korrekt dargestellt werden.

**Comment by ThomasEllenberger** [comment]
- Der erste und der letzte Punkt wurden in Issue #2259 umgesetzt.
- Der vierte Punkt ist bei der Jubla aktuell kein Problem mehr, da der 2. Teil des Elternzugangs bei der Jubla aktuell deaktiviert ist und man dadurch ohnehin keine neuen Kinder bei einem Anlass erfassen kann.
- Weiterhin offen ist der Bug bei der Cevi. Diesen konnte auch nach allen weiteren Fixes erneut nachstellen.

**Comment by nchiapol** [comment]
Anmerkung zu unserem Problem: 
Basierend auf  Carlos Hinweis oben wären evtl. die erweiterten Zugriffsrechte auf die Participation-Lists ein möglicher Grund. Bei uns gibt es in Gremien eine Rolle "Aktive Kursleiter" die zugriff auf die TN-Listen haben. Falls ich Zeit finde, werde ich versuchen dem auch noch nachzugehen.

**Comment by nchiapol** [comment]
@ThomasEllenberger damit du das auch sicher siehst. Ich habe eben einen Pull-Request für unser Problem erstellt. Hoffe das erlaubt eine rasche Beurteilung des allenfalls noch verbleibenden Aufwands.

**Comment by ThomasEllenberger** [comment]
Da aus diesem Issue 4 der 5 Punkte erledigt wurde, und der fünfte aktuell nicht angegangen wird, da bei der Jubla dieser Teil des Elternzugangs ausgeschaltet ist, werde ich dieses Issue schliessen.
