### ISSUE TITLE
INVOICE: Ebics Z54 in Epics Gem contributen

### ISSUE THREAD

**Issue by nilsrauch** [hitobito/hitobito#2197]
Damit Hitobito mit den schweizer Banken sprechen kann haben wir das Z54 Protokoll im Hitobito Source anhand des Design Patterns des `epics` Gem gebaut.

Ziel ist es, diese Anpassungen ins Epics Gem zurückzuführen und dann im Hitobito wieder korrekt einzubinden

# Tech-Spec

- Epics Gem erweitern

# ToDo

- [ ] Epics Gem klonen
- [ ] Code aus Hitobito nach `epics` kopieren und integrieren
- [ ] PR stellen
- [ ] Sobald PR gemerged & released
  - [ ] `epics` Gem im Hitobito erneuern
  - [ ] Implementation anpassen

**Comment by daniel-illi** [comment]
Da haben wir etwas zu lange gewartet mit dem contributen: seit Version 2.3.0 (Juni 2024) unterstützt `epics` bereits Z54 🙃
