### ISSUE TITLE
Etikettendruck - Alphabetische sortierung

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2199]
### Aktuelles Verhalten

Bei einem Export der Etiketten sind diese nicht immer alphabetisch sortiert.
Bei mehreren Exporten konnte beobachtet werden, dass es jeweils am Anfang und am Ende des Exports einige Adressen hat, welche nicht korrekt sortiert wurden.
Dies konnte auch unabhängig von Haushalten nachgewiesen werden. Es kommt also auch bei Listen, in welchen niemand in einem gemeinsamen Haushalt ist, zu Fehlern in der Sortierung.

Soviel ich weiss, werden die Etiketten heute nach der Personen ID sortiert, gar nicht nach dem Namen?

### Gewünschtes Verhalten

Bei einem Etiketten-Export sollen sämtliche Daten korrekt in alphabetischer Reihenfolge des Nachnamens (bei gleichem Nachnamen den Vornamen zusätzlich verwenden) sortiert sein.

Zentral ist, dass die Sortierung von Etiketten und Briefen, bei Personenlisten und Haushaltsexporten gleich ist.

#### Offene Frage:

Ein offener Punkt sind noch Haushalte, hier müsste definiert werden, wie und wo diese einsortiert werden sollten.

Jeweils alphabetisch nach dem ersten Nachnamen des Haushalts?

### Schritte zu reproduzieren

1. Etiketten-Export ausführen, beispielsweise in dieser Gruppe https://rando-community.ch/de/groups/128/people?returning=true (Achtung, prod-Umgebung!)
2. Am Anfang der Liste hat es fünf, am Ende der Liste ca. 100 Adressen, welche nicht korrekt sortiert sind.

### Wann ist der Fehler aufgetreten?

18.09.2023

### hitobito version

1.30.0

### Organisation

SWW

### ToDos

Idealerweise aber optional wird die Sortierung aus dem Frontend auch für die Exporte übernommen.

- [x] aktuelle Sortierung herausfinden (Mitgliedernummer/Name/ID/???)
- [x] Standardsortierung alphabetisch aufsteigend nach Nachname, Vorname
- [x] Bei Haushalten die erste Person hierfür verwenden
- [x] Prüfen, ob die Sortierung direkt aus dem Frontend übernommen werden kann
- [x] Manuell testen
- [x] Specs schreiben, um die einheitliche Sortierung zu gewährleisten
- [x] Eintrag im CHANGELOG unter unreleased machen

**Comment by IvoStierli** [comment]
Gemäss meiner Einschätzung sortiert Hitobito die Etiketten defaultmässig nach der Hitobito-Mitglieder-Nummer statt alphabetisch. 
Aus unserer (SVSE) Sicht, soll dieser Bug asap gefixt werden, da es für unsere Vereine sehr aufwändig ist, die Etiketten manuell nach den alphabetisch sortierten Begleitbriefen zu ordnen. Die Etiketten sind ohne alphabetische Sortierung nicht nutzbar.

**Comment by ThomasEllenberger** [comment]
> Gemäss meiner Einschätzung sortiert Hitobito die Etiketten defaultmässig nach der Hitobito-Mitglieder-Nummer statt alphabetisch. Aus unserer (SVSE) Sicht, soll dieser Bug asap gefixt werden, da es für unsere Vereine sehr aufwändig ist, die Etiketten manuell nach den alphabetisch sortierten Begleitbriefen zu ordnen. Die Etiketten sind ohne alphabetische Sortierung nicht nutzbar.

@IvoStierli 
Dieses Issue wird bei uns aktuell nicht priorisiert.
Möchtet ihr dieses umsetzen lassen, kann ich dir gerne eine Offerte zukommen lassen.

**Comment by diegosteiner** [comment]
@ThomasEllenberger werden beim Export **mit Haushalt** die Einträge nach grösse des Haushaltes sortiert. Diese Sortierung ist mit diesem Issue hier dann nicht mehr möglich. Ist das ok oder sollten wir uns das nochmals genauer überlegen?

**Comment by carlobeltrame** [comment]
> aktuell werden beim Export **mit Haushalt** die Einträge nach grösse des Haushaltes sortiert.

Zum Kontext: Diese Logik habe ich glaube ich mal für das Briefe-Feature gebaut, damit man bereits auf der Vorschau, welche nur die ersten paar Seiten des PDFs generiert, sieht ob einzelne Haushalte das Layout sprengen weil sie so viele Mitglieder haben.

**Comment by ThomasEllenberger** [comment]
@diegosteiner , @kronn Ich kann dies leider nicht erfolgreich testen. Der Export wird bei mir nicht fertig.
Selbst bei nur 7 Personen ist das nach 1h noch immer am laufen.
Könnt ihr euch das nochmal anschauen?

**Comment by kronn** [comment]
Der erzeugte Fehler ist `Prawn::Errors::CannotFit` und kommt von einer Stelle, die nicht im Rahmen des Features geändert wurde. Es scheint daran zu liegen, dass das gewählte Etikettenformat keine passenden Abmessungen hat. Fehlermeldung: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/73670

Mit einem anderen Etikettenformat funktioniert der Export: https://sww.puzzle.ch/de/groups/20/people.pdf?household=true&label_format_id=6&returning=true
