### ISSUE TITLE
SECURITY: Dependabot konfigurieren

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#2209]
Als Betreiber von Hitobito
möchte ich, dass alle bekannten Sicherheitslücken in Abhängigkeiten auch gemeldet werden,
um etwas mehr Sicherheit zu haben.

Neu soll daher eine dependabot.yml in hitobito (-core) und den Wagonrepo eingefügt werden.

# Tech-Spec

- Doku: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
- Meldungen für
  - Bundler
  - npm und/oder yarn
  - Github Actions
  - Docker?
- nach Möglichkeit PRs erstellen lassen
- Prüfungsintervall mindestens wöchentlich, vielleicht öfter?

# ToDo

- [ ] dependabot.yml im Core
- [ ] dependabot.yml in Wagons
- [ ] Prüfungsintervall im Team klären
- [ ] Zusammenspiel mit Releases klären

**Comment by carlobeltrame** [comment]
Gemeldet werden die Sicherheitslücken in Drittsoftware auch ohne dependabot.yml bereits.
Ein dependabot.yml bewirkt, dass Dependabot automatisch PRs erstellt oder sogar Fixes automatisch merged. Wenn wir der Meinung sind dass wir dafür ausreichend Testabdeckung haben, würde ich noch als Alternative [Renovate](https://github.com/renovatebot/renovate) in den Ring werfen. Ich habe Renovate auch schon in anderen Projekten eingesetzt, es ist ähnlich einfach einzurichten wie Dependabot Version Updates, ist extrem flexibel bei den Konfigurations-Möglichkeiten, und wurde auch schon an einem Puzzle Techworkshop angeschaut (bin nicht sicher ob es bei Puzzle jetzt schon irgendwo im Einsatz ist).

**Comment by olibrian** [comment]
Bei einem anderen komplexen, grösseren Ruby Projekt haben wir bereits Erfahrung mit Renovate gesammelt. Hier unbedingt den Austausch suchen.

**Comment by kronn** [comment]
Da ich schon von mehreren Stellen renovate gehört habe, hole ich mir mal diese Erfahrung noch dazu und passe das Issue hier dann vermutlich an. Mittlerweile ich mein Gefühl auch eher Richtung renovate. Und wie Carlo schon richtig feststellte: schon die defaults geben uns einige Meldungen und auch Update-PRs.
