### ISSUE TITLE
MESSAGES: Alten Mail Stack ausbauen

### ISSUE THREAD

**Issue by njaeggi** [hitobito/hitobito#2210]
Ab dem 17.10.23 sollten alle Instanzen den neuen Mailstack haben, somit kann der alte entfernt werden

# Tech-Spec
Environment variable
  - https://github.com/hitobito/hitobito/blob/master/config/settings.yml#L52
  
Mail Relay
  - https://github.com/hitobito/hitobito/blob/master/app/jobs/mail_relay_job.rb
  -  https://github.com/hitobito/hitobito/tree/master/app/domain/mail_relay
  
Specs
   - https://github.com/hitobito/hitobito/tree/master/spec/domain/mail_relay
   
# ToDo
- [ ] RAILS_MAIL_RETRIEVER_CONFIG  entfernen
- [ ] alten Code entfernen
- [ ] alte Tests entfernen
- [ ] mail_relay Code in youth wagon entfernen
- [ ] openshift secrets für alten mail client entfernen
- [ ] doc updaten
