### ISSUE TITLE
GROUPS: Log für mounted_attributes

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2211]
Mit https://github.com/hitobito/hitobito/issues/2165 haben wir mounted attributes eingeführt. Dies ermöglicht uns auf STI-Klassenebene Attribute zu definieren. 
Beim SAC wird dies momentan dazu verwendet um Metadaten z.B. auf einer Sektion abzulegen. Die Metadaten sollen aber nur auf einer Sektion, jedoch nicht auf einer Untergruppe oder dem Top Layer zur Verfügung stehen. 
Aktuell haben wir das Attribut foundation_year auf Group::Sektion. Weitere Attribute folgen bald. 

Mit diesem Ticket soll nun sichergestellt werden, dass Änderungen an diesen Attributen ebenfalls im Log der Gruppe protokolliert werden (paper_trail)

Idealerweise werden einfach alle mounted_attrs mit protokolliert, also wie 'normale' Attribute behandelt bei Änderungen. 

# Tech-Spec
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/sektion.rb#L23
- https://github.com/hitobito/hitobito/blob/master/app/models/concerns/mounted_attr.rb

# ToDo

- [ ] mounted_attrs verstehen und eine erste, kurze Doku dazu schreiben
- [ ] Änderungen durch paper_trail protokollieren lassen
- [ ] Changelog entry unter unreleased
- [ ] Manual testing

**Comment by daniel-illi** [comment]
Ich halte die Implementierung mit dem `MountedAttribute` model und dem `mounted_attr` helper für problematisch. 
Es wird eine normale `has_many` relation hinter accessors versteckt, welche mit Instanzvariablen changes an den MountedAttribute managen. Dadurch wird das dirty tracking von ActiveRecord ausgehebelt.
Updates an den MountedAttribute werden in einem `after_save` hook gemacht, was eine Einbindung in `paper_trail` deutlich erschwert.

Eine Möglichkeit wäre, die Funktionalität mit `ActiveRecord::Store` zu implementieren. Damit sollte die `paper_trail` integration automatisch funktionieren da ActiveRecord Standardfunktionalität verwendet wird, und die Attribute sind direkt auf dem Model gespeichert ohne dass eine separate table nötig ist.

Ev. wäre es auch eine Option, die `mounted_attr` Implementierung anzupassen so dass keine Instanzvariablen verwendet werden sondern dass direkt die MountedAttributes geändert werden. So sollte das dirty tracking auch funktionieren.
