### ISSUE TITLE
DEPLOYMENT: Einheitliche Versionsnummern wieder ermöglichen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2214]
Als WV der regelmässige Releases macht
möchte ich bei allen releaseden Umgebungen dieselbe Versionsnummer vergeben können,
um die Versionsnummer nicht immer unnötig um 15 Versionen zu erhöhen.

Als WV der regelmässige Releases macht
möchte ich in allen Composition Repos gleichzeitig die GitHub Action parallel laufen lassen können,
um beim Deployment Zeit zu sparen.

Neu soll die Versionsnummer auch manuell vergeben werden können, oder es soll angegeben werden können ob die bestehende latest Version vom Core wiederverwendet werden soll.
Zusätzlich soll die prepare-release GitHub Action in diesem Fall auch in mehreren Composition Repos gleichzeitig laufen können.

# Mockup

Zum Beispiel ermöglichen, manuell eine Versionsnummer einzugeben (optional):
![Screenshot 2023-10-09 at 10-16-43 Prepare Release · Workflow runs · hitobito_ose_composition_glp](https://github.com/hitobito/hitobito/assets/7566995/cef8db9a-89d2-4b80-8086-9dc5702205d2)

# Tech-Spec

- Versionsschema ist major.minor.patch nach semver
- regelmäßige Releases (aktuell quartalsweise) inkrementieren zumindest die minor version
- spezielle und einzelne Releases sowie hotfixes inkrementieren die patch-version
- die GH-actions sollten den Release komplett vorbereiten können (regelmäßig, einzeln oder mit manueller version) 
- Versionsschema ist in ~`bin/release`~ `bin/version` untergebracht

# ToDo

## initialer Plan

- [x] prepare-release für production reparieren (path anpassen?) 
- [x] Versionsschema "current-month" entfernen 
- [x] prepare-release um Parameter "release-type" erweitern 
- [x] prepare-release um Parameter "custom-version" erweitern (oder Parameter "next-version")
- [x] release-type "regular", verwendet die neueste minor-version seit einer Woche, sonst wie patch
- [x] release-type "patch", der die patch-version inkrementiert
- [x] release-type "custom", verwendet eine explizite Versionsnummer aus Parameter "custom-version" 
- [x] workflows in den composition-repos anpassen
- [ ] Doku im codi anpassen 

## Ideen während der Umsetzung

- [ ] neuen Workflow "Update production" in den Wagons erstellen?
- [ ] validation der parameter einbauen?

**Comment by amaierhofer** [comment]
Sieht soweit ich das beurteilen kannn bis jetzt gut aus. Mir fehlt noch die Beschreibung wie/wo ich das dann im github ui(?) verwenden kann.
