### ISSUE TITLE
INVOICE: Strukturierte Adressen bei Rechnungen / ISO20022

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2226]
Gemäss Informationen von Postfinance und SIX-Group werden strukturierte Adressen bei Rechnungen ab 2025 obligatorisch. Dies bedeutet, dass das Adressfeld in Strasse und Hausnummer geteilt werden muss. Mehrzeilige Adressfelder sind auch nicht mehr zulässig.

Stand heute zieht Hitobito beim erstellen von Rechnungen die Adressdaten "Namen", "Vornamen", "Adresse", "PLZ" und "Ort" in ein Feld als Rechnungsadresse zusammen.

## Weiterführende Informationen:

- https://www.iso20022.org/
- https://www.postfinance.ch/content/dam/pfch/doc/j_n/news_dez_2022_de.pdf
- https://www.postfinance.ch/content/dam/pfch/doc/j_n/news_dec_2023_de.pdf
- https://www.six-group.com/de/products-services/banking-services/payment-standardization/swiss-payments.html#scrollTo=strukturierte-adressen

# Tech-Spec

- strukturierte Adressen sind ab 2025 im Zahlungsverkehr obligatorisch
- die meisten Felder sind bereits strukturiert vorhanden
- das bisherige Feld "Adresse" muss in "Strasse" und "Hausnummer" geteilt werden
- CareOf kann als zusätzliche Adresszeile verwendet werden
- Postbox enthält die Postfach-Informationen
- Die Reihenfolge der Felder ist
    - Anrede
    - Namen
    - Zu Händen von/zusätzliche Adresszeile
    - Strasse und Hausnummer
    - Postfach
    - PLZ und Ort
    - Land

# ToDo

- [x] Migration "Vorbereitung" erstellen
  - neue Spalte person.street
  - neue Spalte person.housenumber
  - neue Spalte person.address_care_of
  - neue Spalte person.postbox
  - neue Spalte group.street
  - neue Spalte group.housenumber
  - neue Spalte group.address_care_of
  - neue Spalte group.postbox
- [x] Views anpassen, um neue Eingabefelder zu haben und alte zu löschen
- [x] Controller anpassen, um permitted_attrs zu korrigieren
- [x] Model anpassen, um Validierungen korrekt zu halten
- [x] Migration "Transfer" erstellen
  - ActiveRecord nur verwenden, um die Attribute zu kopieren
  - korrekt kopierte Daten aus address löschen
  - bei Personen save verwenden, um den papertrail-callback auszuführen
  - erst Personen, danach die Gruppen
- [x] Verwendung von Papertrail prüfen (Personen-Log)
- [x] Sicherstellen, dass Transfer Fehler ausgibt
- [x] Transfer auch für SaaS testen
- [x] Tabular (CSV/Excel)-Exporte anpassen
- Specs anpassen
  - [x] core
  - [x] cevi
  - [x] die_mitte
  - [x] digisus_lab
  - [x] dsj
  - [x] generic
  - [x] glp
  - [x] insieme
  - [x] jemk
  - [x] jubla
  - [x] kljb
  - [x] pbs
  - [x] pro_natura
  - [x] sac_cas
  - [x] sbv
  - [x] sjas
  - [x] skv
  - [x] svse
  - [x] sww
  - [x] tenants
  - [x] youth
- [x] Migration "Abschluss" erstellen
  - komplette Migration in Abschluss aufnehmen
  - alte Spalte person.address löschen
  - Guard einbauen, dass vorher die Datenmigration gelaufen ist
  - RELEASE-Notes hinzufügen, um auf manuelle Migration hinzuweisen.
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

## Weitere Aufgaben und Notizen

- [x] `PersonDecorator#complete_address`
- [x] `PersonResource#address` (4 neue schreibbare Felder, address als nur-lese-Feld behalten)
- [x] Die Adresse wird im Export "Spaltenauswahl" noch nicht korrekt ausgegeben. Siehe auch https://github.com/hitobito/hitobito/issues/2705#issuecomment-2250411599
- [x] Die Adressen werden auf Etiketten Exporten noch nicht korrekt ausgegeben. Siehe auch https://github.com/hitobito/hitobito/issues/2717
- [x] Zusätzliche Adresszeile auf Rechnungen: https://help.puzzle.ch/#ticket/zoom/8541 / https://github.com/hitobito/hitobito/issues/3423
- [x] Anlass Anmeldungen: https://help.puzzle.ch/#ticket/zoom/8184
- [x] Hat evtl auch noch damit zu tun: https://github.com/hitobito/hitobito/issues/3090

**Comment by codez** [comment]
Kleines Detail: `care_of` finde ich auf den ersten Blick zu wenig verständlich und könnte (je nach anderweitigen Erweiterungen) verwirrend sein. Könnten wir das auch `address_supplement` nennen? Dann wäre es klar bei der Adresse verordnet.

**Comment by kronn** [comment]
Wir könnten das Feld `address_care_of` nennen. Bei der weiteren Verwendung und in Anlehnung an den Standard der Post wäre das dann etwas hoffentlich eindeutig. Die strukturierte Adresse der Post kennt eben diese "zusätzliche Adresszeile" nicht. Generische zusätzliche Adresszeilen kommen unterhalb der normalen Adresse, also noch unter dem Land. Dies ist natürlich nicht, was hier gewünscht ist. Inhaltlich ist das Feld recht eindeutig "zu Händen von" / "CareOf". Und bei allen strukturierten Exporten gehört es auch in das CareOf-Feld. Daher möchte ich das gerne im Namen behalten. Je länger ich mir die Benennung ansehen, desto mehr möchte ich erst alles namespacen und dann doch die Adresse komplett aus der Person entfernen und eher als eigenes Model mit `belongs_to :person` umsetzen. Das würde dann auch mehrere Adressen ermöglichen (je nach Wagon z.B. Privat, Rechnung, Betreuer, Firma) und könnte alle bisher etwas verteilten Adress-Concerns bündeln. Für den Scope dieses Issue erscheint mir das aber wieder over-engineering. Daher:

Würde das leichte "namespacing" zu `address_care_of` ausreichen, um es besser zu gruppieren?
