### ISSUE TITLE
PEOPLE: Rollen mit Von-Datum in der Zukunft

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2237]
Heute ist es bereits möglich Rollen mit End-Datum in der Zukunft zu erstellen. Eine erste Implementation wurde mit #1748 noch verbessert.

Nun soll es neu ebenfalls möglich sein eine Rolle mit Start-Datum (Von) in der Zukunft zu haben:

- Personen mit zukünftiger Rolle werden standardmässig nicht in Personen-Listen/Exporten einer Gruppe angezeigt
- Zukünftige Rollen sollen auf dem Verlauf-Tab (history) der Person sichtbar sein
  - Neue Unterteilung mit Überschriften wie im Mockup (Aktive, Künftige, Inaktive Rollen)
- Das **Bis** Datum muss immer entweder leer oder min. gleich oder später als das **Von** Datum sein. Anders gesagt, das **Bis** Datum darf, wenn ausgefülllt, nie vor dem **Von** Datum liegen.
- Bei Rollen mit Start-Datum in der Zukunft wird zusätzlich im Label die Info **ab 1.1.2024** angezeigt (ab Start-Datum)
- In der STI Klasse einer Gruppe kann definiert werden ob Personen mit zukünftiger Rolle standardmässig in dieser Liste angezeigt werden:
  - list_future_people: true
- Personen mit FutureRole haben standardmässig :basic_permissions_only
- Personen welche andere Personen in einer Gruppe lesen/bearbeiten können, können auch Personen mit FutureRoles in der selben Gruppe lesen/bearbeiten
- Bei aktiven Rollen, kann das Von Datum nicht in die Zukunft verschoben werden (Aus einer bestehenden Rolle kann keine FutureRole erstellt werden). Grund: Allfällige create-Hooks sind ja bereits durchgelaufen, wir wollen diese nicht noch einmal ausführen
- Wird bei einer bestehenden FutureRole das Von Datum auf Heute oder auf ein Datum in der Vergangenheit gesetzt, wird die Rolle sofort aktiv

# Mockup

## Person Verlauf Tab

![image](https://github.com/hitobito/hitobito/assets/655627/57815cd4-ff09-4156-8f39-4432c4acd68e)

## Person show

![image](https://github.com/hitobito/hitobito/assets/655627/557b94ba-4d3e-4363-be08-778c3aa80cea)

## Person Role Filter

![image](https://github.com/hitobito/hitobito/assets/7566995/b6693fc5-8e7a-4574-9492-2b1c34fe12ea)

# Tech-Spec

- Zukünftige Rolle ohne Callbacks erfassen (after_create Callback sollen erst ausgeführt werden wenn die Rolle aktiv wird)

im Group Model

```
...
:has_many :people, -> { |include_future = false| select_scope ... }
...
```
- PersonReadables und PersonWritables specs ergänzen und sicherstellen das Zugriff auf Personen mit FutureRoles sichergestellt ist (include_future = true)

## Person Filter Role
- https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/role.rb
- Der Personen/Role Filter soll FutureRole ebenfalls berücksichtigen:
  - **FutureRole#future_role_type** bei Filtern berücksichtigen falls Option Zukünftige Rollen miteinbeziehen ausgewählt

## FutureRole als STI Typ

- FutureRole erbt von Role
- via eine FutureRole kann die primary_group nicht gesetzt werden
- Zusätzliches Attribut für zu generierenden Rollen Typ sobald Rolle aktiv wird: future_role_type
- Neues Attribut create_on
- Neuer DJ welcher regelmässig die FutureRoles prüft und ggf. aktiviert (**create_on**)
  - wenn der Job bei einem Role#create! failed, soll dieser eine Exception reporten, jedoch dann einfach mit der nächsten FutureRole weitermachen. Sprich der Job kann nicht durch eine einzelne, failende Rolle blockiert werden
  - es wird eine neue Role vom Typ **future_role_type** erstellt und der **FutureRole** entry gelöscht, somit werden die after_create, after_save callbacks ausgeführt
  - **future_role_type**, **create_on** ist leer auf dem neuen Role-Entry
  - ~kann die Rolle nicht erstellt werden, soll eine Exception geraised werden und der FutureRole entry irgendwie als fehlerhaft markiert. z.B. rot markiert mit dem Hinweis: 'Rolle konnte nicht erstellt werden'~ wir gehen davon aus das in diesem Fall alle 15min wenn der Job läuft eine Exception geraised wird die wir dann im sentry sehen bis das Problem behoben wurde.
- In Role Base Class sicherstellen das **future_role_type** und **create_on** immer leer sind
- in FutureRole muss **future_role_type** und **create_on** immer gesetzt sein
  - **create_on** muss in der Zukunft liegen
- FutureRoles werden hard-deleted wenn eine Gruppe archiviert wird

## PaperTrail und FutureRole

- Wenn FutureRole erstellt wird: Mitglied Mitglied in Mitglieder (Familie) ab 1.1.2024 wurde hinzugefügt
- Log entry das Rolle erstellt/aktiv wurde wenn der Job die effektive Rolle erstellt (converted)

# ToDo

- [x] Bestehender Code im PR #2230 studieren
- [x] FutureRole Model inkl. Validierungen, Scope sowie DB Migration für zusätzliche Attribute erstellen
- [ ] Validierungen auf Role Base class erstellen
- [x] Fälle handhaben bei welchen die Von/Bis Daten einer bestehenden Rolle bearbeitet werden
  - Aktive Rolle kann nie eine FutureRole werden
  - FutureRole wird sofort in eine aktive Role umgewandelt falls Von Datum Heute oder in der Vergangenheit gesetzt wird
- [x] Person#history in Aktive, Künftige und Inaktive Rollen unterteilen
- [x] Person#show Rollen mit Künftige Rollen ergänzen
- [x] FutureRole label mit Datum ab z.b.: 'ab 1.1.2024' ergänzen
- [ ] Specs für: PersonReadables, PersonWritables, Abilities, PeopleController inkl. Tabular Exports
- [x] DJ Job ActivateFutureRoleJob oder ähnlich erstellen
- [x] FutureRoles hard-deleten wenn Gruppe archiviert wird
- [ ] ~Personen-Filter mit Option 'Zukünftige Rollen miteinbeziehen' erweitern~ #2254
- [x] PaperTrail logging für FutureRoles anpassen
- [ ] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
- [ ] Durch z.B. Tom testen lassen (manual Testing auf Integration)

**Comment by mtnstar** [comment]
![image](https://github.com/hitobito/hitobito/assets/655627/0f870aac-64f2-4562-b0af-6ee06fa72c68)

mit dem Stand des PRs #2230 kommt folgende Fehlermeldung wenn man versucht eine Rolle mit Von in der Zukunft zu erstellen

**Comment by mtnstar** [comment]
![image](https://github.com/hitobito/hitobito/assets/655627/67dfaac3-8606-45af-85a7-9dbeb411e906)

**Comment by mtnstar** [comment]
![image](https://github.com/hitobito/hitobito/assets/655627/cff2b4f8-6356-489c-8966-7aefd8f4b542)

**Comment by ThomasEllenberger** [comment]
Hat eine Person keine aktiven Rollen, sondern nur Zukünftige und Inaktive werden in der Personenübersicht die Zukünftigen Rollen als aktive Rollen angezeigt.

Verlauf:
![image](https://github.com/hitobito/hitobito/assets/100761305/b31cd826-2997-46ab-9bb5-384d549892a5)

Personen-Info:
![image](https://github.com/hitobito/hitobito/assets/100761305/9b968529-d447-4659-9a93-0c3f6a3e358a)

**Comment by mtnstar** [comment]
> Die Personenfilter für Rollen in der Zukunft konnte ich nicht erfolgreich testen. Die Auswahl für "Auch zukünftige Rollen miteinbeziehen erscheint nicht. Getestet auf: PBS-INT ![image](https://private-user-images.githubusercontent.com/100761305/291897656-90ca3797-f88d-4f6a-aeb0-4abf0111d081.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODIxMDcsIm5iZiI6MTcwMzA4MTgwNywicGF0aCI6Ii8xMDA3NjEzMDUvMjkxODk3NjU2LTkwY2EzNzk3LWY4OGQtNGY2YS1hZWIwLTRhYmYwMTExZDA4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNDE2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzJmZWQwMGYxYTAyZTc1MmYyNTAzNjY4ZmM2MTExNWM1ZDY0ODExOWQ0MWQ2MjA4MDVlZGExMWNjNDI4YjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UodcsQCkD4pYhBCGlMeexVpswhHvObHdiu-mYvBxDb8)

das Suchen nach FutureRole ist bisher nicht implementiert, dazu gibt's ein zusätzliches Ticket: https://github.com/hitobito/hitobito/issues/2254

**Comment by mtnstar** [comment]
> Hat eine Person keine aktiven Rollen, sondern nur Zukünftige und Inaktive werden in der Personenübersicht die Zukünftigen Rollen als aktive Rollen angezeigt.
> 
> Verlauf: ![image](https://private-user-images.githubusercontent.com/100761305/291895880-b31cd826-2997-46ab-9bb5-384d549892a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODIxMDcsIm5iZiI6MTcwMzA4MTgwNywicGF0aCI6Ii8xMDA3NjEzMDUvMjkxODk1ODgwLWIzMWNkODI2LTI5OTctNDZhYi05YmI1LTM4NGQ1NDk4OTJhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNDE2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGY1NDBiYWMyNzZlYjQxYThlYzU3NzU5NjgyNzg5MWRkYjllMzUwYTEzZTdlMDU0NGIxZmI3NzM2OWJiYjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KzOz0u0NbUIfaLr0gDMUp9bfXlIImCPA9IA4AzsVUF4)
> 
> Personen-Info: ![image](https://private-user-images.githubusercontent.com/100761305/291895976-9b968529-d447-4659-9a93-0c3f6a3e358a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODIxMDcsIm5iZiI6MTcwMzA4MTgwNywicGF0aCI6Ii8xMDA3NjEzMDUvMjkxODk1OTc2LTliOTY4NTI5LWQ0NDctNDY1OS05YTkzLTBjM2Y2YTNlMzU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNDE2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWM3YTcxMTQ3ZTQyZWQyZjZiZGQ0NjIwODBlOWFiOGZhNWVhMDAzNTQ4MmY0NTFiZjRhYTliZWJhYmJkMWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xfJdIhzIgu-WqMB8f_5pkoaLep1y-66ts_uhLDOGZyQ)
> 
> Dies scheint auch der Fall zu sein wenn man aktive und zukünftige Rollen in der gleichen Gruppe hat. Vermute das Problem tritt auf weil alle Rollen in der Gruppe unter dieser aufgelistet werden. ![image](https://private-user-images.githubusercontent.com/100761305/291901459-02660766-111c-4857-8443-aa6d9a97605f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODIxMDcsIm5iZiI6MTcwMzA4MTgwNywicGF0aCI6Ii8xMDA3NjEzMDUvMjkxOTAxNDU5LTAyNjYwNzY2LTExMWMtNDg1Ny04NDQzLWFhNmQ5YTk3NjA1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNDE2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2VkZjQyMzc2MGE0YzY1Zjk4ZGEzMTMxZmQ3MmYxMmE1ZDA1MjBjNmFiY2E4M2EyZDFiYzlkNjg0ZTk5NjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X9FH2yJFw0Sdh_LEsZXiWA7Dyap9xrptlhraKtM8CL4)

interessant, bei sac-int passiert das nicht.

ich habe ein Ticket gemacht #2321

**Comment by richardjubla** [comment]
Der Pull ist immer noch offen: https://github.com/hitobito/hitobito_jubla/pull/60
