### ISSUE TITLE
TECH: Ruby 3.2 upgrade

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2242]
Ruby 3.0 is supported until 31. March 2024.

# Tech-Spec

- we want a supported and secure runtime
- Ruby 3.2 is supported until 2026-03-31
- gems need and should be updated

# ToDo

- [x] Upgrade Ruby to 3.2
- [x] Upgrade bundler to latest
- [x] Upgrade gems defensively (keep rails and such)
- [x] make `rake about` work
- [x] adapt app and specs if needed
- [x] resolve any deprecations warnings
- [x] CHANGELOG-entry "Update auf Ruby 3.2 (hitobito#2242)"
