### ISSUE TITLE
GROUPS: Erweiterung json:api für Gruppen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2243]
Das neue **json:api** soll für Gruppen erweitert werden. Aktuell können über **/api** Personen (people) managed werden (crud).

Der SAC benötigt vorerst vor allem lesend Zugriff auf Gruppen:

- Auflisten aller definierten Sektionen und Ortsgruppen (Filter by sti type)
- Abfragen der sektionsspezifischen Attribute (mounted_attrs) wie z.B. foundation_year, canton, usw.

Mit diesem Ticket sollen die beiden Endpoints **GET /api/groups** sowie **GET /api/groups/:id** realisiert werden.

Standardmässig werden archivierte Gruppen nicht aufgelistet. optional kann dies über ein Parameter gemacht werden (falls einfach realisierbar)

```
GET https://sac-cas.puzzle.ch/api/groups?type=sektion,ortsgruppe
```

Dieses Format ist nur ein Beispiel, gern generell so nahe wie möglich am Standard von Graphiti bleiben, und das Feature im Core umsetzen.

## Attribute

Folgende Gruppen-Attribute sollen auf list/show ausgegeben werden:
- :id, :parent_id, :name, :short_name, :type, :email, :address, :zip_code, :town, :country, contact_id, :created_at, :updated_at, :deleted_at, :layer_group_id, :creator_id, :updater_id, :deleter_id, :require_person_add_requests, :description,:archived_at,  :self_registration_url
- optional: :logo
- nur sac wagon:  :navision_id, mounted attributes Sektion (foundation_year, canton)

# Tech-Spec

- Hinweise beachten: https://github.com/hitobito/hitobito/blob/master/doc/development/05_json_api.md#hitobito-developer
- Sicherstellen das mounted_attrs ebenfalls via json:api auf der Gruppe zur Verfügung stehen
- Swagger UI: https://sac-cas.puzzle.ch/api-docs/
- API Doc: https://github.com/hitobito/hitobito/blob/master/doc/development/05_json_api.md
  - wird auch in jeder Hitobito Instanz unter /api gerendert. z.b. https://sac-cas.puzzle.ch/api
- https://github.com/hitobito/hitobito/blob/master/app/controllers/json_api_controller.rb

# ToDo

- [ ] Neuen Controller, route endpoint, graphiti resource, specs
- [ ] Updaten der api doku
- [ ] manuelles Testen z.b. mit curl und/oder dem swagger ui
- [ ] CHANGELOG entry

**Comment by daniel-illi** [comment]
Also die core changes sehen gut aus und sind IMO bereit zum mergen.
Nun fehlen noch die wagon Anpassungen.
