### ISSUE TITLE
ROLES: Error-Handling künftige/inaktive Rollen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2255]
mit #2237 haben wir neu Rollen mit Von-Datum in der Zukunft. Seit längerem gibt es auch die Möglichkeit Rollen so zu konfigurieren, das sie an einem Datum in der Zukunft terminiert werden. 
Für beide Szenarien kommt ein DelayedJob zum Einsatz welcher die Rolle entweder am Stichdatum löscht (bis Datum der Rolle) oder ein anderer Job der die Rolle dann erstellt (FutureRole)
Bei beiden Vorgängen kann theoretisch einiges schief gehen sodass wir inkonsistente Daten haben:

- Einer der beiden Jobs läuft nicht
- eine Rolle kann nicht konvertiert werden zum Zeitpunkt des Von-Datums z.B aufgrund Validierungsfehlern oder wenn die after_create Hooks failen
- dito für Löschen der Rolle, dort vorallem bezüglich der after_destroy callbacks.

## Gewünschtes Verhalten

- Eine Rolle wird entsprechend markiert wenn sie **outdated** ist -> Siehe Mockups
- eine Exception wird im Job geworfen und ans sentry reported (sollte bereits so umgesetzt sein, prüfen und ggf. noch spec ergänzen)
- die Jobs versuchen immer wieder die fehlerhafte Rolle zu erstellen/zu löschen (sollte bereits so umgesetzt sein, prüfen und ggf. noch spec ergänzen)
- Beim FutureRole Job werden Errors heute in das Label Feld geschrieben. Dieses Verhalten entfernen. Validierungsfehler können im UI manuell nachgestellt werden. Sicherstellen das der Validierungsfehler in der Exception welche ans Sentry gesendet wird ersichtlich ist.
- Rollen sollen immer gelöscht oder konvertiert werden sollen wenn Validierungs-Fehler auf der Person vorhanden sind

### 1. Rolle mit Bis-Datum heute oder in der Vergangenheit:

![image](https://github.com/hitobito/hitobito/assets/655627/95c36ad6-fa2e-4e75-bf02-e744537d6ef0)

Beim Versuch die Rolle zu **Speichern** würde ein allfälliger Fehler als Flash-Message angezeigt

### 2. FutureRole mit Von-Datum heute oder in der Vergangenheit

![image](https://github.com/hitobito/hitobito/assets/655627/856f1dab-a7fd-45c5-a8df-49868176a92a)

## Tech-Spec

- Unabhängig von den CronJobs weiss eine Rolle falls sie **outdated** ist:
  - 1. Bei einer FutureRole ist dies der Fall wenn das Von-Datum Heute oder in der Vergangenheit ist (convert_on)
  - 2. Bei einer aktiven Rolle ist dies der Fall wenn das Bis-Datum Heute oder in der Vergangenheit ist (delete_on)

**Fall 1 - outdated FutureRole:**
- Es wird ein :warning: als Teil des Labels der Rolle angezeigt (font-awesome Icon im UI)
- auf dem Edit-Form der Rolle wird der Text/Flash Message aus dem obigen Mockup angezeigt
- Errors die beim Speichern auftreten sollen als Flash-Message im UI angezeigt werden (sollte bereits Standard-Verhalten sein)
- Speichern ohne Validierungsfehler konvertiert die outdated FutureRole

**Fall 2 - outdated active Role:**
- Es wird ein :warning: als Teil des Labels der Rolle angezeigt (font-awesome Icon im UI)
- Im Label wird in diesem Fall noch das Bis-Datum ergänzt. z.B. (bis 1.11.2023)
- auf dem Edit-Form der Rolle wird der Text/Flash Message aus dem obigen Mockup angezeigt 
- Errors die beim **Speichern** auftreten sollen als Flash-Message im UI angezeigt werden
- Speichern ohne Validierungsfehler löscht die outdated Rolle
- Gleicher Text für Flash-Warning wie bei Fall 1, jedoch mit **terminiert** anstatt aktiviert werden ...

https://fontawesome.com/v5/icons/exclamation-triangle?f=classic&s=solid

## DelayedJobs

- [x] Falls möglich beide Jobs immer zur vollen Stunde laufen lassen: x:00:10, viertelstündlich macht eigentlich keinen Sinn
- [x] Exception Message nicht mehr im Label speichern

# ToDo

- [x] DelayedJobs Error Handling bereinigen/vereinfachen
- [x] Rollen-Model mit dem Feature **outdated** ausrüsten
- [x] Anpassungen im UI vornehmen Person#aside role, -Person#history, Role#edit, ggf. weitere Orte?-
- [x] Manuelles Testen
