### ISSUE TITLE
ELTERNZUGANG: Umsetzungsticket Nacharbeiten

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2259]
Durch dieses Issue werden zwei Punkte der Elternzugangs Nacharbeiten aus #2196 umgesetzt.

- [ ] Bisher haben Verwalter*innen beim Anmelden zu einem Anlass auch Personen zur Auswahl, welche diesen Anlass selbst nicht sehen könnten. Die Anmeldung kann anschliessend durchgespielt werden. Erst beim Abschliessen erhält man die Fehlermeldung "Sie sind nicht berechtigt diese Seite anzuzeigen".
Neu soll diese Fehlermeldung  angepasst werden um aussagekräftiger zu sein. Vorschlag: "Die ausgewählte Person erfüllt die Anlassanforderungen nicht." Zusätzlich soll die Fehlermeldung nach Möglichkeit bereits angezeigt werden bevor man den gesammten Anmeldeprozess durchspielt
- [ ] Für Teil 2 des Elternzugangs (#1969 & #1970) bei welchen es darum geht, dass Verwalter*innen Accounts sich selbst neue Kinderaccounts hinzufügen, oder bei der Selbstregistration direkt zusätzliche Kinderaccounts anlegen können, soll es einen Featuretoggle geben. 

# Tech-Spec

- Zum ersten Punkt: Dieses Problem schon früher anzuzeigen ging nach bisheriger Logik nicht, wie sich bei der Umsetzung des Elternzugangs Teil 2 herausgestellt hat. Wenn man sich ein neues Kind erstellt, dann hat dieses in diesem Moment gar keine Rollen und somit auch keine Berechtigungen, den Anlass zu sehen. Da man den Anlass-Anmeldungsprozess auch zu dem Zeitpunkt noch abbrechen kann wo das neue Kind bereits erstellt ist, müssen wir vordergründig alle Kinder so behandeln als dürften sie den Anlass sehen.
- Die Wagons welche dieses Anlegen von neuen Kindern wirklich brauchen (SJAS, Pro Natura) brauchen es primär in Anlässen mit externer Anmeldung. Die anderen Elternzugangs-Wagons (PBS, Cevi, Jubla, SAC) brauchen das Anlegen von neuen Kindern direkt beim Anlass vorläufig nicht. Daher können wir bei Anlässen welche KEINE externen Anmeldungen erlauben es auch generell verbieten, neue Kinder zu erfassen.
- In der [Umsetzung des Elternzugangs](https://github.com/hitobito/hitobito_youth/pull/32/files#diff-54db626037b88718a04283f9d4a18566e37e89f92005b4cba2aadd67177f508dR16) wurde eine Anpassung an den Berechtigungen gemacht, dass Events mit externen Anmeldungen auch für eingeloggte Personen immer sichtbar sind, also implizit auch "sichtbar für die ganze Datenbank" sind. Somit müssten bei Anlässen mit externen Anmeldungen nie Berechtigungsprobleme auftreten.
- In Anlässen OHNE externe Anmeldungen gibt es aufgrund der obigen Punkte jetzt keinen Grund mehr, warum wir die fehlenden Berechtigungen nicht schon im Dropdown anzeigen könnten.

# ToDo

## Punkt 1: Berechtigungen bei Anlassanmeldung
- [x] Im Youth Wagon den Key `de.events.form.caption_external_applications` überschreiben, um die bereits aktive Berechtigungsthematik zu beleuchten: `'Externe können sich für diesen Anlass anmelden. Der Anlass ist damit auch für die ganze Datenbank sichtbar.'`
- [x] In views.youth.de.yml einen neuen Key `de.unauthorized.new.event/participation` hinzufügen mit dem Wert `Die ausgewählte Person erfüllt die Anlassanforderungen nicht.`
- [x] Im [ParticipantAdd Dropdown](https://github.com/hitobito/hitobito_youth/blob/master/app/helpers/youth/dropdown/event/participant_add.rb#L73) das Item `.register_new_managed` nicht hinzufügen, wenn der Anlass keine externen Anmeldungen erlaubt
- [x] Im [ParticipantAdd Dropdown](https://github.com/hitobito/hitobito_youth/blob/master/app/helpers/youth/dropdown/event/participant_add.rb) bei Hinzufügen jeder Person überprüfen, ob die Person den Anlass sehen darf. Falls nicht, Item deaktiviert / ausgegraut anzeigen und in Klammern einen Hinweis `(darf den Anlass nicht sehen)` anhängen
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessenen Rollen "durchklicken"

## Punkt 2: Feature Toggle für Elternzugang Teil 2
- [x] Im Youth Wagon ein FeatureGate `people.people_managers.self_service_managed_creation` anlegen, Default `true`
- [x] Im [ParticipantAdd Dropdown](https://github.com/hitobito/hitobito_youth/blob/master/app/helpers/youth/dropdown/event/participant_add.rb#L73) das Item `.register_new_managed` nicht hinzufügen, wenn das neue FeatureGate deaktiviert ist
- [x] Im [Controller welcher für das Anlegen neuer Kinder verantwortlich ist](https://github.com/hitobito/hitobito_youth/blob/master/app/controllers/event/participation_contact_data/managed_controller.rb) via `before_action` abbrechen, falls das neue FeatureGate deaktiviert ist
- [x] In der [show-View für externe Anlässe](https://github.com/hitobito/hitobito_youth/blob/master/app/views/event/register/_email_check.html.haml#L16) den zweiten Submit-Button nicht anzeigen, falls das neue FeatureGate deaktiviert ist
- [x] Im dazugehörigen [Controller](https://github.com/hitobito/hitobito_youth/blob/master/app/controllers/youth/event/register_controller.rb#L24) in der Methode `manager` immer `false` zurückgeben, falls das neue FeatureGate deaktiviert ist
- [x] Neues FeatureGate bei PBS, Cevi, Jubla und SAC deaktivieren
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by mtnstar** [comment]
@TheWalkingLeek wenn du ja noch etwas am Elternzugang machst, könntest du das noch etwas schöner Stylen?


![Image](https://github.com/hitobito/hitobito/assets/655627/6aa988f0-2f5c-4d52-a5e9-a6ab0ae5aea2)

Die Auflistung der Kinder/Verwalterinnen? villeicht reicht es einfach die Einrückung zu fixen

**Comment by ThomasEllenberger** [comment]
Testing:

Folgendes Verhalten konnte ich testen, welches meines Erachtens nicht wie spezifiziert funktioniert:

- Kann ein Elternteil einen Anlass nur durch seine Kinder sehen, kann es sich dennoch an den Anlass anmelden und es erscheint erst am Ende des Anmeldeprozesses die Fehlermeldung "Sie sind nicht berechtigt, diese Seite anzuzeigen. 
Korrekt wäre wenn das Elternteil ebenfalls ausgegraut wäre und sich selbst nicht an den Anlass anmeldne kann wenn es den Anlass nur durch eines seiner Kinder sehen kann.
- Bei Personen welche man nicht für einen Anlass anmelden kann kommt die Meldung "(darf den Anlass nicht sehen)". Besser wäre "(Ist nicht berechtigt sich zu dem Anlass anzumelden)"
