### ISSUE TITLE
ROLES: Verbesserungen FutureRoles, Rollen Daten Editieren

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2265]
# 1. Aufteilung History in Aktive, Künftige und Inaktive Roles

Wie usprünglich in #2237 konzipiert soll unter people/:id/history eine Aufteilung zwischen Aktive, Künftige und Inaktive Rollen gemacht werden

## Mockup

**Person Verlauf Tab**

![image](https://github.com/hitobito/hitobito/assets/655627/57815cd4-ff09-4156-8f39-4432c4acd68e)

# 2. Rolle sofort löschen wenn bis in der Vergangenheit

## Schritte um Nachzukonstruieren

1. Rolle neu auf Person
2. Von Datum vor 3 Monaten
3. Bis Datum gestern
4. Speichern

Rolle wid angezeigt und erst abgeräumt wenn People::DestroyRolesJob läuft

## Erwatetes Verhalten

Die Rolle wird sofort gelöscht (soft oder hard, siehe 3.)

ggf. bereits gefixt mit #2255 ?

# 3. Berücksichtigen von minimum_days_to_archive

`role: minimum_days_to_archive: 7` definiert ab wann eine Rolle soft-deleted wird.

mit den diversen Umbauten rund um Rolle von/bis, ging die Berücksichtigung dieser Config verloren.

Die Rolle die unter 2. beschrieben ist, sollte also bei 7 Tagen nicht hard, sondern soft-deleted/archiviert werden

Zusätzlich: Beim SAC Wagon sollen Neuanmeldung Rollen immer nur soft-deleted werden, egal was für ein Wert für minimum_days_to_archive gesetzt ist.

# Tech-Spec

- 

# ToDo

- [x] Aufteilen person#history in aktive, künftige, inaktive Rollen
- [x] Rolle sofort löschen wenn Bis in der Vergangenheit beim Erstellen/Editieren
- [x] minimum_days_to_archive berücksichtigen
- [x] minimum_days_to_archive für SAC Neuanmeldung anpassen
- [x] Mit angemessener Rolle "durchklicken"
- [ ] @ThomasEllenberger benachrichtigen nach Deployment auf Integration, er soll FutureRole und Archivierte Roles, eigentlich alles Rund um Rollen von/bis auf herz und nieren testen, :pray:

**Comment by mtnstar** [comment]
> Rollen werden korrekt, sofort gelöscht wenn man das Enddatum auf <heute setzt. Im Verlauf erhielten die so terminierten Rollen bei mir die folgend Fehlermeldung: Nicht sicher ob dies korrekt ist, oder woran dies liegt? (getestet auf PBS-INT)
> 
> ![Image](https://private-user-images.githubusercontent.com/100761305/291895192-f0100b2a-8982-438a-8d82-75ea9fd3039e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODE5MTgsIm5iZiI6MTcwMzA4MTYxOCwicGF0aCI6Ii8xMDA3NjEzMDUvMjkxODk1MTkyLWYwMTAwYjJhLTg5ODItNDM4YS04ZDgyLTc1ZWE5ZmQzMDM5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNDEzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGMxMWY2MWJjNjEwMTZmN2ZmODg5NDQ2MzlkMjIwOWUzNjRmZGI0NWUyYjdhNDU5NDg2ODk5OGI1MzlhMDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cuIHOFCR_uNDat9pllHeLV2I571EV3DSMxmJJu_Vyig)

das hat @amaierhofer gerade noch gefixt und ich habe es gemerged. 
habe gerade das deployment von pbs int angestossen, könntest du @ThomasEllenberger dann nochmals testen ob das nun richtig angezeigt wird?
