### ISSUE TITLE
MAILING_LISTS: Gruppen mit static_name können nicht mehr gesucht werden

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2270]
mit https://github.com/hitobito/hitobito/pull/2219 wurde group static_name eingeführt.

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/d8efebae-b67a-431c-acfa-992d397270e4)

Beim bei den Abo Abonnenten Typeahead werden diese nicht aufgelistet. (Gruppe suchen ...)

Gewünschtes Verhalten: Diese Gruppen können ebenfalls aufgelistet und ausgewählt werden.

# ToDo

- [x] Typeahead endpoint fixen
- [x] System spec ergänzen
- [x] Prüfen ob es sonst in Hitobito noch einen Ort gibt wo diese Gruppen nicht erscheinen
