### ISSUE TITLE
ROLES: Anzeige bis in Label

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2279]
Im Aside: Nur Rollen-Namen Fett, bis mit kleinbuchstaben und nicht fett

![image](https://github.com/hitobito/hitobito/assets/655627/30037f9e-588e-4497-b464-cf45afcb9b97)

In History: bis gar nicht anzeigen da bereits als Spalte vorhanden, outdated info aber schon

![image](https://github.com/hitobito/hitobito/assets/655627/a9f10411-0b48-41e4-bacb-646a3e42e86b)

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/decorators/role_decorator.rb
- https://github.com/hitobito/hitobito/blob/master/spec/decorators/role_decorator_spec.rb
  - homogenisieren Code in Spec von terminated vs. outdated role

# ToDo

- [ ] Role Decorator für aside anpassen
- [ ] Role Decorator für history anpassen
- [ ] mit angemessener Rolle durchklicken
