### ISSUE TITLE
PEOPLE: PrivacyPolicy akzeptieren im Selbstregistrierungsformular verschwindet nach Validierungsfehler

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2281]
Wenn bei der Selbstregistrierung Datenschutzerklärungen akzeptiert werden müssen, wird eine entsprechende Checkbox mit Links zur Datenschutzerklärung angezeigt. Wenn aber beim Absenden des Formulars ein Validierungsfehler auftritt, dann wird spätestens seit #2221 die Checkbox nicht mehr angezeigt.
![Screenshot 2023-11-30 at 09-53-20 hitobito - Test Titel](https://github.com/hitobito/hitobito/assets/7566995/15b8d53f-d123-4d90-8518-e9fd4492b2e8)

Das Problem wird im [PrivacyPolicyFinder](https://github.com/hitobito/hitobito/blob/master/app/domain/group/privacy_policy_finder.rb) oder im Formular selber vermutet. Der Finder wird auch noch an anderen Orten in hitobito verwendet, und zeigt möglichst intelligent die Checkbox nicht an, wenn die Datenschutzerklärung bereits akzeptiert wurde.

Allerdings sollte die Datenschutzerklärung nicht als akzeptiert gelten, bevor dies in die Datenbank gespeichert wurde. Der Finder sollte also noch intelligenter darauf achten, was der Stand in der DB ist, um zu entscheiden ob die Checkbox angezeigt wird oder nicht.

Note: Die Checkbox darf durchaus als aktiviert gerendert werden, falls sie vor dem Validierungsfehler bereits aktiviert wurde. Aber es wäre unüblich, die Checkbox einfach gar nicht mehr anzuzeigen, noch bevor dies wirklich gespeichert ist.

# TODO
- [x] [PrivacyPolicyFinder](https://github.com/hitobito/hitobito/blob/master/app/domain/group/privacy_policy_finder.rb) anpassen
- [ ] Durchtesten ob die Selbstregistrierung mit und ohne Privacy Policy noch funktioniert
- [ ] Allenfalls Feature Spec ergänzen
