### ISSUE TITLE
MESSAGES: Abo Clean-Up Einstellungen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2329]
Die Einstellungen rund um die Abos sind historisch gewachsen und müssen vor weiteren Erweiterungen bereinigt werden.

## 1. Einstellungen > Drop-Down Rechnung erstellen

Das Drop-Down `Rechnung erstellen` soll vom `Einstellungen` auf das `Abonnenten` Tab verschoben werden.

![image](https://github.com/hitobito/hitobito/assets/655627/291473cf-3c44-42c9-b893-07b646bc862c)

## 2. Tabs für mailing_list form

wie wir das schon für die Gruppen Parameter eingeführt haben, sollen auch die Felder des Abos mit Tabs gegliedert werden:

- Allgemein: Name, Beschreibung, Herausgeber, 'Abonnenten dürfen sich selbst an-/abmelden'
- Mailing-Liste (E-Mail): Restliche Mailinglisten Felder (Mailinglisten Adresse, Zusätzliche Absender, ...)
- Mailchimp: MailChimp Listen-ID, MailChimp API-Schlüssel, Alle Versandadressen synchronisieren

## 3. Attribute auf MailingList#show

Aktuell sieht diese Page so aus:

![image](https://github.com/hitobito/hitobito/assets/655627/38a28388-6988-4943-a2ba-e8b203a79f2c)

Wie im Form sollen die Attribute Gruppiert werden:

![image](https://github.com/hitobito/hitobito/assets/655627/e9e478c8-765d-4790-8d0a-b9b112c44df6)

- Beschreibung ebenfalls als Attribut mit Label in der Liste
- Abschnitt Mailing-Liste (E-Mail) nur anzeigen falls Mailingliste definiert (liste@example.com)
- Abschnitt Mailchimp nur anzeigen falls konfiguriert sowie wenn man Schreibrechte auf die ML hast
- MailChimp API-Schlüssel nie anzeigen
- Sicherstellen das genügend Platz für die Labels vorhanden ist (width)

## 4. Rename Tab Einstellungen zu Info

Wie bei Gruppen, Personen usw. das das Tab Einstellungen in Info renamed werden und als erstes Tab erscheinen.

![image](https://github.com/hitobito/hitobito/assets/655627/710afed5-9c06-4c13-ad5d-e8d77115821e)

Ist die Option Abonnenten dürfen sich selbst an/abmelden aktiv, so wird ein 'Anmelden' Button unter Info angezeigt. Sicherstellen das Personen lesezugriff auf dieses Info Tab des Abos haben. Ist man bereits angemeldet, wird ein Abmelden button angezeigt. Lesezugriff auf Abo ist nur möglich falls ich mich selber an/abmelden darf.

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/views/mailing_lists/_form.html.haml
- https://github.com/hitobito/hitobito/blob/master/app/views/mailing_lists/_attrs.html.haml

# ToDo

- [ ] Rechnung erstellen Drop-Down verschieben, Anmelden Button entfernen
- [ ] mailing_list form in Tabs aufteilen
- [ ] Attribute auf mailing_list#show gruppieren
- [ ] Rename Tab Einstellungen
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by daniel-illi** [comment]
* An-/Abmeldebutton auf Infoseite verhält sich unter Umständen nicht richtig: #2349
