### ISSUE TITLE
MESSAGES: Neue An-/Abmelde Optionen für Abos

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2334]
partially blocked by #2329 

Aktuell gibt es einfach die Option `Abonnenten dürfen sich selbst an/abmelden` auf jedem Abo. Ist diese aktiv, so wird jeder Person in der DB ermöglicht sich für dieses Abo an/abzumelden. 

Neu soll es möglich sein die Anmelde/Abmelde-Option auf die konfigurierten Abonnenten einzuschränken. 

Beim SAC ermöglicht dies das Abo für die Zeitschrift **Die Alpen** auf die aktiven Mitglieder einzuschränken. Aktive Mitglieder erhalten dieses Magazin per Post, können es aber auch selbst abbestellen. 

# Mockup

mailing_list form

![image](https://github.com/hitobito/hitobito/assets/655627/3ae552ed-9c65-437e-8416-98bc607219e6)

- Anstatt Option Global -> Alle Personen

Ist ein der ersten beiden Optionen gewählt, so wird die Option für standardmässig angemeldet oder abgemeldet angezeigt.

![image](https://github.com/hitobito/hitobito/assets/655627/247f3252-871a-494c-854c-eaf8672612a4)

Falls sinnvoll, diese beiden Optionen in einem eigenen Form-Tab 'An-/Abmeldung' unterbringen.

Beim SAC kann man **Die Alpen** auch elektronisch haben. Dies soll aber vorerst noch nicht der default sein, sondern ein Mitglied soll dies aktiv abonnieren bei Bedarf. Ist also hier 'Ab-gemeldet' ausgewählt, so sind alle Personen standardmässig unsubscribed für die mailing_list

Abonnenten können jederzeit editiert werden. Sicherstellen beim hinzufügen/entfernen von Abonnenten die Subscribers entsprechend updated werden. (subscriber clean up)

 'Abonnenten dürfen sich selbst an-/abmelden' auf 'Nur innerhalb konfigurierten Abonnenten' gesetzt, folgenden Hinweis auf Abonnenten anzeigen:

![image](https://github.com/hitobito/hitobito/assets/655627/28342e3e-62be-44a2-89eb-adfce9687490)

Ebenfalls bei allen Edit Abonnenten Forms beim Speichern button einen Hinweis anzeigen änderungen auswirkung haben auf die die abonnierten Personen.

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/models/mailing_list.rb
- https://github.com/hitobito/hitobito/blob/master/app/models/subscription.rb
- https://github.com/hitobito/hitobito/blob/master/app/domain/mailing_lists/subscribers.rb
- Darauf achten dass die [Berechnung der Abonnenten](https://github.com/hitobito/hitobito/blob/master/app/domain/mailing_lists/subscribers.rb) nicht unnötig komplizierter wird, und die Filterung mit den neuen [Abo-Filtern](https://github.com/hitobito/hitobito/pull/2202) weiterhin funktioniert

## MailingLists::SubscriberCleanUp + Job

Ist die Option 'Abonnenten dürfen sich selbst an-/abmelden' auf 'Nur innerhalb konfigurierten Abonnenten' gesetzt, so müssen die Abonnenten bei Änderungen dessen Konfiguration aktualisiert bzw. bereinigt werden. Dazu soll eine Domain-Klasse erstellt werden. Diese stellt sicher das nur gültige/berechtigte Abonnenten vorhanden sind. 

Eine Person kann aber zum Beispiel auch eine Rolle verlieren, sodass sie theoretisch nicht mehr berechtigt für ein Abo ist. Aus diesem Grund soll ein CleanUp Job z.B. stündlich alle Abos entsprechend bereinigen. 

Diese Logik auch triggern falls die Option  'Abonnenten dürfen sich selbst an-/abmelden' geändert wird. Ausser diese Option wird als attr_readonly konfiguriert was durchaus legitim ist falls es sinnvoll weniger Aufwand für die Umsetzung bedeutet.

:warning: Alle Abonnenten Optionen berücksichtigen, auch z.B. Globale Bedingungen

# ToDo

- [ ] Neue Optionen/Enum auf mailing_list
- [ ] Migration bestehender An-/Abmelde Optionen sicherstellen
- [ ] Subscription model entsprechend erweitern
- [ ] Ability anpassen, wer darf Subscriben/Unsubscriben
- [ ] Kombinationsmöglichkeiten bestimmen und entsprechende Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
