### ISSUE TITLE
MESSAGES: Layer/Gruppen Info Auflistung Person#Abos

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2337]
Sind in einer Hitobito-Instanz viele abonnierbare Abos vorhanden, kann dies unter Person -> Abos sehr schnell unübersichtlich werden. Mit diesem Ticket sollen die sichtbaren/abonnierbaren Abos nach Layer gruppiert und die Gruppen-Info angezeigt werden.

# Mockup

![image](https://github.com/hitobito/hitobito/assets/655627/6c23a8b4-e030-4aeb-b9d1-80d581223a25)

- Einträge werden nach Layer gruppiert in einer eigenen Tabelle unter **Meine Abos** sowie **Verfügbare Abos**
- Befindet sich das Abo auf einer Gruppe, werden zusätzlich die Parent Gruppennamen in der Spalte Name angezeigt
- Styling fixen: Alle Columns sollten tabellenübergreifend die gleiche Breite haben

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/controllers/person/subscriptions_controller.rb

# ToDo

- [x] Abos bereits in im Controller nach Layer gruppieren, Gruppen-Info adden falls benötigt
- [x] View inkl. Styling anpassen
- [x] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
