### ISSUE TITLE
PEOPLE: Mitgliederausweis als Core-Feature

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2352]
Für den [SKV](https://github.com/hitobito/hitobito_skv) haben wir bereits einen Digitalen Mitgliederausweis mit QR Code zur Verifikation eingeführt. Auch der SAC benötigt dieses Feature sodass es Sinn macht dieses Feature in den Core zu verschieben und eine gemeinsame Basis zu nutzen.

Bei beiden Organisationen ist die Mitgliedschaft gültig wenn eine aktive Mitglieder-Rolle der Person assigned ist.

## Verify Endpoint

Um die Mitgliedschaft zu prüfen wird ein Verify Endpoint zur Verfügung gestellt. Dieser kann über eine URL sowie einem Verify-Token aufgerufen werden. (auch ohne Login)

`https://my-hitobito.example.com/verify_membership/yhEdkted42`

Ist man eingeloggt und hat Leserechte auf die Person, ist eine Prüfung auch via ID der Person möglich:

`https://my-hitobito.example.com/people/42/verify_membership`

Beide Endpoints sollen auch maschinenlesbar als JSON verwendet werden können:

`https://my-hitobito.example.com/people/42/verify_membership.json` bzw. `https://my-hitobito.example.com/verify_membership.json?token=yhEdkted42`

## Mitgliederausweis

# Mockup

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/controllers/people/membership/verify_controller.rb

Beim SKV ist dieses Feature schon eine weile produktiv, sicherstellen das hier nichts kaputt geht

# ToDo

- [ ] Migration erstellen
- [ ] 
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kronn** [comment]
Erledigt durch #2511
