### ISSUE TITLE
Externe Registrierung für Rollen mit Contact_Data

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito#2357]
Die Externe Registrierung ermöglicht die direkte Erstellung eines "aktiven" Profil in der jeweiligen Mitgliederdatenbank. Dabei kann dem Profil auch direkt eine Rolle zugewiesen werden. Natürlich sind keine Rollen mit Schreibrechten auswählbar, da somit ein Profil sofort schreibrechte in der Mitgliederdatenbank erhalten würde.
Dem Profil kann aber eine Rolle mit dem Attribut [Contact_Data](https://hitobito.readthedocs.io/de/latest/access_concept.html#spezialfall-contact-data) zugeteilt werden. Ist die Rolle einer Person als kontaktrelevant markiert, so hat diese Person auf alle anderen Personen mit kontaktrelevanten Rollen Zugriff. Gleichzeitig ist sie auch für alle anderen Personen mit kontaktrelevanten Rollen sichtbar. 

![image](https://github.com/hitobito/hitobito/assets/95908537/a7d6f002-a5f0-41f6-bbb8-fe035c42cedb)

Aus meiner Sicht müsste doch sichergestellt sein, dass **keine Rollen ohne Schreibrechten kontaktrelevant** ist oder **keine Rolle mit kontaktrelevantz durch externe Registrierung** erlangt werden dürfte? 
Ich glaube, dass es mehre Wagon mit solchen möglichen Varianten gibt. Ich möchte nicht, dass durch eine Fehlkonfiguration ein Profil durch externe Registrierung an alle kontaktrelevanten Informationen in einer Hitobito-Instanz kommt. 

# Techspec

- Rollenauswahl im Core auf Rollen ohne Permissions 
- Rollenauswahl für Wagons überschreibbar machen
- Validierung für `self_registration_role_type` auf Group hinzufügen
- Verhalten im PBS Wagon auf Kompatibilität prüfen
- Migration für Gruppen, die eine ungültige Rolle ausgewählt haben

# ToDo

- [x] `GroupDecorator#allowed_roles_for_self_registration` anpassen
- [x] `Role::Types` mit class_attribute `allowed_permissions_for_self_registration`
- [x]  `allowed_permissions_for_self_registration` mit `[:group_read]` im Jubla Wagon ergänzen
- [x] Specs ergänzen und anpassen
- [x] Kunde wegen wegfallenden Selbstregistrierungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
Im PBS-Wagon sind gemäss Text in der App keine Rollen auswählbar, die es erlauben, andere Personen zu sehen. Ich kann leider nicht prüfen, ob da was vergessen ging oder der PBS-Wagon selber mehr angepasst hat.

![image](https://github.com/hitobito/hitobito/assets/95908537/58075769-8126-4f58-b612-c292d2491218)

**Comment by richardjubla** [comment]
Zur Offerte: Hier muss ich mehr Kontext haben zur Youth-Lösung oder ob unser Wagon vergessen wurde. Warum haben wir nicht «auch» die Einschränkung, dass keine Rollen wählbar sind welche andere Profile sehen können?

**Comment by richardjubla** [comment]
@ThomasEllenberger 
> Habe mir dies erneut angeschaut, und tests bei Jubla, Cevi, PBS sowie im Core durchgeführt.
> 
> Vorschlag: Mein Vorschlag wäre hier, dies direkt im Core für alle zu ändern. Ich sehe keinen Grund, warum irgendetwas was mehr als "group_read" hat sich selbst registrieren können sollte. Entsprechend würde ich für Selbstregistrierung nur noch Rollen ohne Berechtigung oder mit "group_read" zulassen. Sämtliche anderen Berechtigungen sollen nicht mehr auswählbar sein. (Alternative: Noch restriktiver, analog der PBS, nur Rollen auswählbar machen welche keine Berechtigung haben.)


Ich unterstütze diesen Vorschlag:

- Umsetzung im Core für uns gut möglich
- Wir sehen auch keinen Grund, mehr als "group_read" anzubieten. Da wir keinen Abhängigkeiten haben oder planen, sehen wir es als "Vorteil", wenn alle anderen Berechtigungen oder Abhängigkeiten für Rollen generell ausgeschlossen sind (Stichwort Impersonate, etc.).
- Aktuell gehen wir davon aus, dass eine externe Registrierungen zu einer einseitigen Absicht führt, welche durch die Leitung/Adressverwaltung zwingend zu bearbeiten und zu überprüfen ist (Profil wird in andere Gruppe verschoben, Rollen angepasst, etc.). Die restriktivere Alternative ist demnach die zu wählende Option (Privacy by Design) und der Verein kann wählen, ob er die Rolle "Extern" analog zu externen Event-Anmeldungen oder die Rolle "Versandadresse" zuweisen möchte.

**Comment by diegosteiner** [comment]
@ThomasEllenberger ich habe das Issue refined und mit @mtnstar angeschaut.

**Comment by diegosteiner** [comment]
Ich habe mal einen ersten Wurf umgesetzt:

![image](https://github.com/user-attachments/assets/d3059805-e9b5-442a-bf02-ba9c621b858f)

Speziell erwähnen muss ich, dass im core nun Rollen mit gar keinen Permissions erlaubt werden, und im Jubla Wagon die Permission `:group_read` hinzugefügt wird. Die Permission wird im Select-Feld neu zusätzlich angezeigt.

**Comment by richardjubla** [comment]
> Speziell erwähnen muss ich, dass im core nun Rollen mit gar keinen Permissions erlaubt werden, und im Jubla Wagon die Permission `:group_read` hinzugefügt wird. Die Permission wird im Select-Feld neu zusätzlich angezeigt.


Gemäss Thomas sollte im Core für Selbstregistrierung nur noch Rollen ohne Berechtigung oder mit "group_read" zugelassen werden. Ich habe mich auf dieser Basis angeschlossen. Für uns wäre auch OK, das Verhalten vom Core zu übernehmen. Mein Argument für group_read war nicht, dass wir das exklusiv benötigen.

**Comment by richardjubla** [comment]
@kronn 

Thema: Adressverwaltung über Externe Registrierung möglich im Top-Knoten NEJB.
Vorschlag: Core-Regelung für Externe Registrierung für ausschliesslich Rollen **ohne** jegliche Rechte: (z.B. Extern, Versandadresse)
