### ISSUE TITLE
GROUPS: Gruppen mit static_name vs. Edit form / Kurzname

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2364]
### Aktuelles Verhalten

Hat eine Gruppe einen übersetzbaren static_name, so wird im Edit-Form der Name immer noch als editierbar angezeigt. Ausserdem kann man den Kurznamen manuell überschreiben sodass im Nav-Tree dann der Kurzname anstatt des übersetzten Static-Names angezeigt wird.

### Gewünschtes Verhalten

Static Name der Gruppe sollte überall read-only sein. 

### Schritte zu reproduzieren

1. Beliebige static-name Gruppe z.B. im SAC Wagon Untergruppe Sektion -> Mitglieder bearbeiten
2. Kurznamen eintragen
3. Speichern

### Organisation

sac_cas

### Screenshots, weiterer Kontext

Die beiden Felder im Form **disablen** wenn static_name

![image](https://github.com/hitobito/hitobito/assets/655627/25203694-df5e-4976-9352-5efa53893bf9)

### ToDos

- [x] group#form anpassen
- [x] short_name getter anpassen
- [x] permitted_attrs - [:name, :short_name] bei static_name groups
