### ISSUE TITLE
TECH: Webpacker und Asset Pipeline ersetzen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#2388]
Als Entwickler und Betreiber von Hitobito
möchte ich webpacker und die asset pipeline ablösen,
um eine zeitgemässe Lösung als Vorbereitung auf Rails 7 zu haben.

Neu könnte z.B. esbuild oder so eingesetzt werden.

# Tech-Spec

- Webpacker als nicht mehr gewartetes Gem ablösen
- prüfen, ob die asset pipeline noch benötigt wird
- das bisherigen JS und CSS so prinzipiell unverändert ausgegeben werden
- idealerweise kann nodejs als dependency aus dem Build entfernt werden.

# ToDo

- [ ] Umsetzungsplan ergänzen oder anpassen
- [ ] Webpacker entfernen
- [ ] Neuen Frontend-Build einbauen
- [ ] Core testen
- [ ] alle Wagons testen
- [ ] Dockerfile anpassen, um neuen Build zu haben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by kronn** [comment]
duplicate of #2272
