### ISSUE TITLE
PEOPLE: Selbstregistrierung Einverständnis der Erziehungsberechtigten

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2404]
Als Verwalter\*in einer Gruppe mit Selbstregistrierung
möchte ich bei der Selbstregistrierung optional die Volljährigkeit bzw. das Einverständnis von Erziehungsberechtigten abfragen,
um mich rechtlich abzusichern.

Neu soll bei der externen Registrierung optional eine required Checkbox hinzugefügt werden können: "Ich bestätige dass ich mindestens 18 Jahre alt bin oder das Einverständnis meiner Erziehungsberechtigten habe."

# Mockup
![Screenshot 2024-02-07 at 13-26-05 MiData PBS_MSdS_MSS - Test Pfadigruppe](https://github.com/hitobito/hitobito/assets/7566995/57e32c56-5eac-40ba-ba92-c8340c97066b)

![Screenshot 2024-02-07 at 13-29-02 MiData PBS_MSdS_MSS - Registrierung zur Gruppe](https://github.com/hitobito/hitobito/assets/7566995/2f08d147-b6ac-44ae-9567-97b32557b6b5)

# Tech-Spec

- Umsetzung im Core
- Zusätzlich Umsetzung im SAC-Wagon für das überschriebene [Neuanmeldungen-Formular](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/self_registration_neuanmeldung.rb) auf den Formularschritt Zusatzdaten
- Der Wert der Zustimmung muss nirgends persistiert werden. Es reicht wenn es eine required Checkbox ist, die einen am Abschicken des Formulars hindert.

# ToDo

- [ ] Neue Spalte auf Gruppe `require_adult_consent` boolean, default false, not null
- [ ] Attribut auf der Gruppe bearbeitbar machen, auf dem Tab "Externe Registrierung"
- [ ] Falls true, required Checkbox im Selbstregistrierungsformular anzeigen, bei den privacy policy fields zu. Default nicht angehäkelt
- [ ] Überprüfen, dass man das Formular nicht abschicken kann, ohne die Checkbox zu aktivieren
- [ ] Falls noch Zeit: Bei group#edit das Tab "Externe Registrierung" ganz ausblenden, falls keine erlaubten Rollentypen in der Gruppe für die Selbstregistrierung auswählbar sind (#2374)
- [ ] Im SAC-Wagon im [Neuanmeldungen-Formular](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/self_registration_neuanmeldung.rb) die Checkbox (falls auf der Gruppe aktiviert) im Schritt 4 Zusatzdaten einfügen, und auch da überprüfen dass das Formular nicht abgesendet werden kann ohne die Checkbox zu aktivieren
- [ ] Feature Specs in Core schreiben
- [ ] Feature Specs in SAC Wagon schreiben
- [ ] **Übersetzungs-Key hier im Issue als neuen Kommentar posten**, damit sich andere Verbände bereits Gedanken über den Wortlaut machen können (explizit gewünscht von der Jubla)
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
Hinweise "zur freien Verwendung"

- Ohne Speicherung (Nachweisfähigkeit) der 18J. Abfrage (meistens Double-opt-in /IP-Log notwendig) ist dieses Feld rechtlich wohl kaum anwendbar und somit auch nicht praktikabel
- "Grundsätzlich" sollte doch "Hitobito" ab 12/13 Jahren "selbständig" genutzt werden können. Die Applikation sollte generelle Regeln (im Core) oder individuelle Regeln (Ebene/Gruppe) abbilden. 
- Aus UX Sicht ist das ein Conversion-Killer: Die 18Jahre gehören in die "Bestimmungen" der Ebene/Gruppe und sind kaum eine so generell verwendbare hitobito-Bestimmung.
- Wir sind hier an einem Punkt von "AGB's" und Selbstregistrierung welche eine nachträgliche Prüfung überspringen sollen. Demnach ist zu argumentieren, dass eine Selbstregistrierung **NICHT** direkt zu einer Mitgliedschaft oder Verbindlichkeiten führen dürften. (Die Datenschutzerklärung/Statuten mit informativem Charakter haben hier eine ganz andere Aufgabe!, das Feature selbst geht aktuell von "Interessenten" aus.)
- Wenn die Selbstregistrierung direkt zu einer Mitgliedschaft oder Verbindlichkeiten führen sollte, müsste aus meiner Sicht die Features der Selbstregistrierung stark ausgebaut werden: Es müsste alle Bedingungen für eine Mitgliedschaft erfüllen können.
- Anstelle von 18 Jahren auf die Handlungsfähigkeit setzten: https://de.wikipedia.org/wiki/Handlungsf%C3%A4higkeit_(Schweiz) / Aus Sicht hitobito/core den Text als Hilfstext selbst konfigurierbar machen. 
- Abgleich zwischen Elternzugang und Selbstregistrierung: Mit dem Feature im Youth-Wagon sollte die Selbstregistrierung **NUR** für Eltern vorgesehen sein. Kinder werden doch nicht so registriert oder gleich von den Eltern selbst angelegt.



![image](https://github.com/hitobito/hitobito/assets/95908537/9335cc5e-1791-4b93-a557-a1595f62e919)

**Comment by carlobeltrame** [comment]
Merci Richi fürs Teilen deiner Gedanken! Das Feature wurde vom SAC gewünscht, aber wir haben nicht mehr alle Zeit der Welt um eine Deluxe-Version in der Community auszudiskutieren, rechtlich abzuklären und umzusetzen. Daher ist hier mal eine erste simple Version zur Umsetzung geplant, die später bei Bedarf gerne noch ausgebaut und verbessert werden kann.

Deinen Aussagen, wofür das Selbstregistrierungsformular gedacht ist (u.a. dass sich im Youth Wagon nur Eltern registrieren sollten) stimme ich NICHT zu, über alle hitobito-Kunden hinweg gesehen. Bei der PBS ist das jeder Abteilung überlassen. Beim SAC ist die Selbstregistrierung sehr stark ausgebaut und führt in  den meisten Fällen zu einer aktiven Mitgliedschaft, und in gewissen anderen Fällen zu einem kostenpflichtigen Abonnement, was den einschaltbaren Alters-Check in diesem Issue motiviert.

In der aktuell vorgesehenen Version wird die Checkbox auf jeder Gruppe (für jedes einzelne Selbstregistrierungsformular) individuell ein- und ausschaltbar sein. Der Wortlaut des Textes ist via Wagon-Übersetzungen global anpassbar. Ist das in dieser Form ein Problem für die Jubla, sollen wir das also hinter einen Feature Toggle stellen, mit dem wir die Nutzung bei der Jubla vorerst komplett verbieten können?

**Comment by nchiapol** [comment]
Aus Sicht des Cevi scheint mir die vorgesehene Implementation fürs erste ok. Für uns braucht es kein globales Feature-Toggle.

**Comment by richardjubla** [comment]
> Merci Richi fürs Teilen deiner Gedanken! Das Feature wurde vom SAC gewünscht, aber wir haben nicht mehr alle Zeit der Welt um eine Deluxe-Version in der Community auszudiskutieren, rechtlich abzuklären und umzusetzen. Daher ist hier mal eine erste simple Version zur Umsetzung geplant, die später bei Bedarf gerne noch ausgebaut und verbessert werden kann.
> 
In diesem Setting sind/waren meine Inputs "zur freien Verwendung". Trotzdem und insbesondere deshalb danke für deine Antwort.


> Deinen Aussagen, wofür das Selbstregistrierungsformular gedacht ist (u.a. dass sich im Youth Wagon nur Eltern registrieren sollten) stimme ich NICHT zu, über alle hitobito-Kunden hinweg gesehen. Bei der PBS ist das jeder Abteilung überlassen. Beim SAC ist die Selbstregistrierung sehr stark ausgebaut und führt in den meisten Fällen zu einer aktiven Mitgliedschaft, und in gewissen anderen Fällen zu einem kostenpflichtigen Abonnement, was den einschaltbaren Alters-Check in diesem Issue motiviert.
> 
Ich habe nicht gesagt oder gemeint, dass sich im Youth Wagon nur Eltern registrieren sollten. Mit der Notwendigkeit zum Besitz einer E-Mail-Adresse ist eine gewisse Hürde (Handlungsfähigkeit/Vertretung) aber bereits da. 
Mit dem Elternzugang und dem Selbstregistrierungsformular haben wir uns für die jubla überlegt, wie wir aus Interessenten/Event-Anmeldungen verwertbare Kontakte (Mitglieder) machen. https://github.com/hitobito/hitobito_jubla/issues/75
Sehr hilfreich ist zudem, dass das Feature Selbstregistration gut beschrieben wurde: https://hitobito.com/de/community-events/events/news/effiziente-selbstregistration-in-hiobito

> In der aktuell vorgesehenen Version wird die Checkbox auf jeder Gruppe (für jedes einzelne Selbstregistrierungsformular) individuell ein- und ausschaltbar sein. Der Wortlaut des Textes ist via Wagon-Übersetzungen global anpassbar. Ist das in dieser Form ein Problem für die Jubla, sollen wir das also hinter einen Feature Toggle stellen, mit dem wir die Nutzung bei der Jubla vorerst komplett verbieten können?

**Nein, es ist kein Feature Toggle nötig.** Die individuelle Steuerung genügt. 
Wir werden prüfen, den Wortlaut analog zur [Datenschutzerklärung ](https://github.com/hitobito/hitobito_jubla/issues/50) für die jubla geeignet anzupassen. (Idealerweise ist von beginn weg klar, wo und welche Texte anzupassen sind, diese wirklich alle anpassbar sind und es nicht zu validierungsfehlern kommt)

**Comment by amaierhofer** [comment]
Locales keys sind aktuell wie folgt: 


```
self_registration_require_adult_consent: Einverständnis von Erziehungsberechtigten
```
```
help_self_registration_require_adult_consent: Bei der Registrierung abfragen, ob die 
   Person schon 18 Jahre ist bzw. das Einverständnis der Erziehungsberechtigten hat.
```
```
adult_consent_field:
  caption: Ich bestätige dass ich mindestens 18 Jahre alt bin oder das Einverständnis 
      meiner Erziehungsberechtigten habe.
```
