### ISSUE TITLE
TECH: HitobitoLog - Verhindern das Logeinträge mehrfach angelegt werden

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2407]
wir verwenden das 'neue' Hitobito Log um Validierungsfehler beim Verschieben von Personen aus der Neuanmeldung Gruppe im SAC Wagon. Dieser Job läuft alle 15min. Tritt ein Fehler auf, so gibt es dadurch pro 15min einen neuen Logeintrag was nicht sehr sinnvoll erscheint.

![image](https://github.com/hitobito/hitobito/assets/655627/cf57c8aa-59d7-40d9-97cd-7d32d579f43c)

Falls ein Logeintrag mit dem gleichen Subject, Kategorie, Level sowie Meldung bereits vorhanden ist, soll neu dieser Eintrag durch einen neuen ersetzt werden:

1. Beim loggen prüfen ob ein Eintrag mit gleichem Subject, Category, Level and Message vorhanden ist
1. Falls ein solcher vorhanden ist, den bestehenden Eintrag löschen und durch einen neuen ersetzen

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/utils/hitobito_logger.rb
- https://github.com/hitobito/hitobito/blob/master/spec/utils/hitobito_logger_spec.rb

# ToDo

- [ ] Implement TDD
- [x] DB Index für die kombinierten Spalten anlegen, da die Tabelle recht gross werden kann und Suche nach vielen Feldern nötig ist
- [ ] ~Filtern nach log level fixen~ works as designed (show all levels >= selected)
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
