### ISSUE TITLE
PEOPLE: Personen-Attribute die für die Person selber readonly sind

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2408]
Als Person beim Mitgliederdienst des SAC
möchte ich sicher sein können dass die Mitglieder gewisse Daten über sich selber nicht mutieren können,
um die korrekte Fakturierung und Betrieb sicherstellen zu können.

Neu soll es möglich sein, gewisse Attribute auf der Person A für die Person A selber readonly zu machen. Die Felder sollen weiterhin bearbeitbar sein durch Personen welche Schreibrechte auf Person A haben.

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- Falls Person A eine Rolle mit Schreibrechten in irgendeiner Gruppe hat, ist es okay wenn sie dadurch auch sich selber bearbeiten kann. Die Einschränkung soll primär für Personen gelten, welche einfach nur [sich selber](https://github.com/hitobito/hitobito/blob/master/app/abilities/person_ability.rb#L20..L21) bearbeiten dürfen.
- Vorschlag: Neues class_attribute "self_service_readonly_attrs" ähnlich wie used_attrs machen, mit welchem in Wagons einzelne Felder readonly gemacht werden können
- Edge Case: Elternzugang. Der Elternzugang sollte die Einschränkung nicht umgehen. Erst wenn ich wirklich eine Rolle mit Schreibrechten habe, darf ich die Felder bearbeiten.
- Beim SAC sind bisher als solche Felder bekannt: birthday, additional_information

# ToDo

- [ ] Ticket fertig konzipieren und aus Architektursicht besprechen
- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by mtnstar** [comment]
@carlobeltrame beim SAC sollten die Eltern das Geburtsdatum ihrer Kinder auch nicht selber ändern können. ich weiss nicht ob das eine Erweiterung sein wird im SAC wagon oder ob das ggf. im Core/Youth Wagon gelöst werden soll.

**Comment by Largo** [comment]
Stand 2024/05/06: Code der Grundfunktionalität kommt gut voran.

**Comment by mtnstar** [comment]
@largo bei der Person resource (json api) gibt's bereits was das Permissions prüft ob ein Update gemacht werden darf oder nicht. https://github.com/hitobito/hitobito/blob/master/app/resources/person_resource.rb#L32

**Comment by Largo** [comment]
Im Gespräch mit  @amaierhofer und @mtnstar kam eine andere Möglichkeit auf die wir prüfen wollen. Anstatt  class attribute  personal_readonly_attrs auf dem Model, kann vermutlich in den Abilities via cancancan accessible attributes definiert werden, wer schreiben darf.

Ich lese mich da erstmal noch weiter rein.


Codebeispiel: 
```ruby
class Person
before_validation :assert_herself_does_not_change

...
def assert_herself_does_not_change
  errors.add(:birthday, :readonly) if PaperTrail.request.whodunnit == id && cannot(:update_personal_readonly_attrs, self)
end
```

[cancancan/docs/accessible_attributes.md at develop · CanCanCommunity/cancancan](https://github.com/CanCanCommunity/cancancan/blob/develop/docs/accessible_attributes.md)

**Comment by Largo** [comment]
Meeting: 2024/05/08. Wir haben beschlossen die Abilities erstmal nicht via [cancancan accessible attributes ](https://github.com/CanCanCommunity/cancancan/blob/develop/docs/accessible_attributes.md) umzusetzen.

**Comment by mtnstar** [comment]
@Largo hat damit begonnen dieses Feature umzusetzen ... ist also WIP
verschiebe dieses Ticket mal zurück nach Refinement damit es später neu in der Sprint Planung eingeplant werden kann.
