### ISSUE TITLE
EVENTS: Bemerkungsfeld anzeigen und exportieren können

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2421]
Als Person die einen Event organisiert bin ich daran interessiert, dass ich das
Feld "Bemerkungen", welches bei jedem Anlass automatisch generiert wird, auch
in der Teilnehmerübersicht einblenden und in einem Export exportieren kann.

Bei jedem Event wird automatisch eine Frage "Bemerkungen" generiert. Im
Gegensatz zu zusätzlichen Anmeldeangaben kann diese in der Personenübersicht
jedoch nicht angezeigt und nur durch den Export "alle Angaben" exportiert
werden.

- Umsetzung im Core:
  - Neu sollen die Bemerkungen in der Teilnehmerübersicht in der Spaltenauswahl auch als zusätzliche Spalte angezeigt werden können. 
  - Zusätzlich soll die Spalte ebenfalls im Excel und CSV Export vorhanden sein, wenn die Spalte eingeblendet ist und man die Spaltenauswahl exportiert (Im Export "Alle Angaben" ist die Spalte bereits vorhanden).
- Umsetzung im SWW-Wagon
  - Das Feld Bemerkungen soll auch im PDF Export exportiert werden. Evtl. ist es Zielführend, wenn der PDF-Export bei SWW zukünftig im Querformat gemacht, wird, statt im Hochformat.

# Mockup

![grafik](https://github.com/hitobito/hitobito/assets/100761305/56879e1d-0071-46e3-bd96-d4f1bfd40d04)

# Tech-Spec

- Bemerkungen sollen sichtbar und exportierbar werden
- TableDisplay ansehen, ob dort ein Whitelisting nötig ist
- PDF-Export auf Querformat ändern, um das Blatt besser zu nutzen

# ToDo

- [ ] Core: TableDisplays anpassen
- [ ] Core: Anzeige prüfen
- [ ] Core: CSV-Export prüfen
- [ ] SWW: PDF-Export prüfen
- [ ] SWW: PDF als Querformat erstellen
- [ ] Specs schreiben

**Comment by tschuepbach** [comment]
In unserer Umgebung werden die Felder "Bemerkungen", sowie "interne Bemerkungen" bereits im Export "Alle Angaben" exportiert. Dieser Export steht aber explizit nur de Rolle "Hauptleitung" zur Verfügung..

Beispiel: https://cevi.puzzle.ch/groups/6/events/1182
[event_participation_export.xlsx](https://github.com/hitobito/hitobito/files/14356645/event_participation_export.xlsx)

**Comment by ThomasEllenberger** [comment]
merci @tschuepbach 
Kann das im Core nachstellen. "Bemerkungen" wird beim Export "Alle Angaben" bereits exportiert.

**Comment by ThomasEllenberger** [comment]
@tschuepbach: Nach deinem Input habe ich das Ticket noch angepasst. 
Gerne hätten wir zumindest die ersten beiden Punkte der Anforderung im Core umgesetzt, da ich hier durchaus einen Nutzen für andere Kunden sehe. Da auch alle zusätzlichen Felder der Anmeldeangaben so angezeigt und exportiert werden können, wären wir hier mit der Logik anschliessend wieder kongruenter.
Ich habe es aktuell allerdings so formuliert, dass dies nur im SWW-WAgon gemacht wird, da dies so wie ich dich verstehe sonnst bei euch mehr Leuten Sicht auf dieses Feld gibt.
Kannst du mir mitteilen ob dies bei euch ein Problem ist? Sonnst würden wir das gerne im Core machen.
@nchiapol: Zur Kenntnissnahme

**Comment by nchiapol** [comment]
@ThomasEllenberger: Das Feld Bemerkungen ist bei uns beschrieben mit "Bemerkungen (Allgemeines, Gesundheitsinformationen, Allergien, usw.)" d.h. ja, das Feld enthält besonders schützenswerte Daten. Entsprechend sollte das Feld überall (Anmeldung-Details, TN-Liste, Exporte) weiterhin nur für bestimmte Rollen verfügbar sein. (Ob das das ganze Kursteam oder nur die Hauptleitung/Personen der Geschäftsstelle kann aber diskutiert werden. Gibt IMO für beides Argumente.)

Solange das ein-/ausblenden und das Exportieren die Berechtigungen korrekt berücksichtigt, sollte das aber trotzdem im Core umgesetzt werden können. (Wenn ich die verschiedenen Diskussionen letztes Jahr zu diesem Thema richtig in Erinnerung habe, erlaubt die Spalten-Auswahl eine bessere Berücksichtigung der Rechte als die ursprünglichen Exporte. IIRC kann man die Spalten zwar immer einblenden, sie bleiben aber einfach leer, wenn man keine Berechtigung hat - leider auch nicht unbedingt das beste UX.)

**Comment by ThomasEllenberger** [comment]
@nchiapol Ich habe dies in eurer Integration einmal getestet. 
Die Tatsächliche Sichtbarkeit der Daten in den Spalten wie bei dir beschrieben ist irgendwie speziell...So wie ich das sehe, kann man die Daten in der Spalte nur sehen, wenn man auch ausserhalb des Kurses Leserechte auf diese Person hat.
Soviel ich feststellen konnte, könnten neu alle Kursrollen, welche nicht Hauptleiter oder Teilnemer sind die Bemerkungen auch einsehen.  Hauptleiter können bereits heute den Export allgemeine Angaben machen, und Teilnehmende können gar keinen Export machen. Neu könnten also Leitende, Küche, Kassier, etc -Rollen auf einem Anlass die Spalte Informationen einsehen, wenn sie diese in der Spaltenauswahl einblenden. Ob sie darin Daten sehen können hängt davon ab, ob sie auch ausserhalb des Kurses Leserechte auf die Teilnehmende Person haben.

--> Meines Erachtens wird dadurch die Sichtbarkeit dieser Felder nicht genug ausgeweitet als dass wir das nicht im Core umsetzen möchten. Insbesondere jetzt, wo die Möglichkeit besteht dass diese nach dem Kursende automatisch gelöscht werden.
@nchiapol Bitte um kurze Bestätigung dass dies so für euch ok. Sonnst müssen wir das im Wagon machen.

@kronn Kannst du während dem Refinen/vor dem Umsetzen evtl  eine kurze Prüfung im Code machen, ob meine Aussage stimmt?

**Comment by nchiapol** [comment]
@ThomasEllenberger der Vollständigkeit halber: Wie erwartet kann die Bemerkungsspalte jetzt zwar auch von normalen Leitern eingeblendet werden. Sie bleibt aber leer, selbst wenn man auf das Profil der betroffenen Person Zugriff hatte. 

Aus UX-Sicht ist das unglücklich, da die betroffenen Personen nicht erkennen können, dass Informationen nicht angezeigt werden. Bei Allergien ist das möglicherweise sogar ein Sicherheitsproblem. 

Als Küche (d.h. mit "Leiter"-Rechten)
![screenshot_2024-03-24_215731](https://github.com/hitobito/hitobito/assets/1123483/e7922cea-986c-4336-8a5f-743e02043e24)

Wenn ich Zugriff auf die Details habe (bei uns auch die Hauptleiter):
![screenshot_2024-03-24_220252](https://github.com/hitobito/hitobito/assets/1123483/40a82e4d-2ea1-4cb7-81d3-b2c10df8ac79)

Falls das bis zum Release nicht mehr behoben werden kann, sollte das auf jeden Fall in einem eigenen Issue getrackt werden - zudem wäre wohl eine Warnung in den Release-Notes sinnvoll.

**Comment by nchiapol** [comment]
Ausserdem noch etwas kleines, das in unseren Tests aufgefallen ist: Zeilenumbrüche werden in der Tabelle mit "" ersetzt. D. h. der Text kann dann etwas zusammenhängen. Bspw. Allergie: Tomaten\r\nKrankenkasse: Visana" wird zu "Allergie TomatenKrankenkasse: Visana". (anstatt mit "" zu ersetzen wäre wohl " " besser)

**Comment by ThomasEllenberger** [comment]
@nchiapol 
Danke für die Inputs.
Wir haben dieses Issue nun noch erweitert, damit für Benutzer ersichtlich ist, wenn sie keine Berechtigung haben gewisse Daten einzusehen.
Hat man keine Berechtigung eine Information einzusehen erscheint nun die Meldung "Fehlende Berechtigung".

Bsp:  Hier hat die Person "Leitung" Rechte die Bemerkungen von sich selbst einzusehen. Deshalb sieht sie, dass dort nichts ausgefüllt wurde. Sie hat keine Rechte für alle anderen Teilnehmenden und sieht desshalb "Fehlende Berechtigung" unabhängig davon ob diese Fragen von den jeweiligen Personen ausgefüllt wurden, oder nicht.
![grafik](https://github.com/hitobito/hitobito/assets/100761305/000c9864-2205-466e-ac11-ce6f933ad15e)
