### ISSUE TITLE
Streamline Date.parse across the project

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#2427]
Als Programmierer von Hitobito
möchte ich einen einheitlichen Weg haben, ein Datum mit einem Standardwert aus Parametern/User-Input o.ä. anzunehmen
um doppelten Code und doppelte Bugs zu vermeiden

Neu soll `Date.parse` nicht immer wieder leicht anders verwendet werden, sondern einen zentrale Domainklasse das parsing übernehmen. Diese sollte neben dem Parameter auch einen Standardwert bekommen können. Rückgabewert ist immer ein gültiges Datum (oder der Standardwert).

# Tech-Spec

- Zentralisierung des Konzepts `Date.parse(param) rescue ...`
- Code in Migrationen nicht anpassen (Migrationen sollen die Anwendung nicht verwenden)

# ToDo

- [ ] Domainklasse `DateParse` erstellen
- [ ] Core nach `Date.parse` durchsuchen und alles ersetzen
- [ ] Alle Wagons durchsuchen und alles ersetzen
- [ ] Specs schreiben

**Comment by carlobeltrame** [comment]
https://xkcd.com/927/
