### ISSUE TITLE
DEPENDENCIES: update Cancancan 

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#2458]
Our current version of cancancan is not the latest and the upgrade-path is currently blocked.

https://github.com/hitobito/hitobito/commit/4c11db97f2893174627651377ee31261e03c0437

In order to unblock this, we need to adapt our Ability DSL, mostly the class_side-definitions.

https://github.com/CanCanCommunity/cancancan/blob/develop/CHANGELOG.md

# Tech-Spec

- allow updates of cancancan
- keep current permissions (ability-DSL may change, if documented properly)

# ToDo

- [ ] Ability-DSL anpassen 
- [ ] Specs schreiben
- [ ] Mit einer Rolle mit wenig Rechten "durchklicken"
- [ ] Mit einer Rolle mit vielen Rechten "durchklicken"
- [ ] In Wagons mit zusätzlichen Event-Typen testen
- [ ] JEMK
- [ ] PBS
- [ ] SJAS
- [ ] ...?
- [ ] Bei Änderungen in der Verwendung der DSL hierfür Doku schreiben und einen Eintrag im Changelog machen

**Comment by amaierhofer** [comment]
Ist mit #3103 gekommen
