### ISSUE TITLE
OIDC: Feature parity zwischen den Profile und Userinfo Endpoints

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2490]
Als Person die eine OAuth oder OIDC Applikation an hitobito anbindet
möchte ich die gleichen Attribute im Profile Endpoint (OAuth 2.0) wie auch im Userinfo Endpoint (OIDC) haben,
um dieselben Features unabhängig vom eingesetzten Flow umsetzen zu können.

Neu sollen die /oauth/profile und /oauth/userinfo Endpoints dieselben Informationen ausgeben, soweit dies rückwärtskompatibel möglich ist.

# Tech-Spec

- Als ersten Schritt wurde in #2475 bereits im Userinfo-Endpoint in der Liste der Rollen das Attribut `role_class` hinzugefügt.
- In hitobito/hitobito_sac_cas#389 wurde oder wird das erste Mal in einem Wagon die Profile und Userinfo Payloads angepasst. Diese sollen weiterhin funktionieren.
- Ein System schaffen, mit dem in Zukunft die Daten in diesen beiden Endpoints auch möglichst synchron bleibt. Z.B. im Profile Endpoint die doorkeeper-Konfiguration ansaugen, und nur noch Ausnahmen für Rückwärtskompatibilität einfügen.

# ToDo

- [x] Im ProfilesController die Daten vom doorkeeper_openid_connect Initializer ansaugen
- [x] Logik von `public_attrs_with_roles` in Decorators auslagern, welche im Wagon einfacher überschrieben werden können
- [x] Via detailliertere Tests sicherstellen dass alle Daten die bisher verfügbar waren weiterhin verfügbar sind, in beiden Endpoints und in allen Scopes
- [x] Developer Dokumentation im Repo updaten
- [x] Mit angemessener Rolle "durchklicken" bzw. mit HTTP Client und oauthdebugger.com / oidcdebugger.com manuell durchtesten
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
