### ISSUE TITLE
PEOPLE: Basis Digitaler Mitgliederausweis in den Core verschieben

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2511]
Für SKV und jetzt auch den SAC haben wir den digitalen Mitgliederausweis eingeführt. Beides basiert auf dem selben Code. Diese Basis soll nun in den Core verschoben werden. 

Welche Rollen mitgliedschaftsrelevant sind wird im jeweiligen Wagon definiert.

## SKV

- Der PDF Ausweis bleibt im SKV Wagon und wird nicht in den Core verschoben noch beim SAC in dieser Form verwendet

# Tech-Spec

## Verify Endpoint

- https://github.com/hitobito/hitobito_skv/blob/master/app/domain/people/membership_verifier.rb im Core erstellen 

```ruby
class People::MembershipVerifier

  def initialize(person)
    @person = person
  end

  def enabled?
    respond_to?(:member?)
  end

  # implement method in wagon
  #def member?
  #end
end
```

- Im SKV und SAC Wagon entsprechend customizen
- ist membership_verifier#member? im Wagon vorhanden, agiert dies gleich als Feature Gate, sprich damit ist das MemberShipVerify Feature aktiviert (oder ggf. anderen, eleganteren Mechano um das Feature via Wagon zu aktivieren)
- Beispiel SKV integration Mitglied: https://skv.puzzle.ch/verify_membership/MvBF9zubmAdhTrzq14J7L8cA
- Aktivieren der verify_membership Route im Core falls Feature aktiv, falls nicht aktiv 404
- https://github.com/hitobito/hitobito_skv/blob/master/app/controllers/people/membership/verify_controller.rb in den Core verschieben
- View aus dem SKV Wagon in den Core verschieben: https://github.com/hitobito/hitobito_skv/blob/master/app/views/people/membership/verify/show.html.haml
- Im SAC Wagon wird die View später customized (ggf. mit render extension)

## Person verify token

- DB Migration Add Membership Verify Token to People:
  - https://github.com/hitobito/hitobito_sac_cas/blob/master/db/migrate/20230601092901_add_membership_verify_token_to_people.rb in den Core verschieben
  - add_column skippen falls bereits vorhanden (im SAC und SKV Wagon der Fall)
  - SKV: https://github.com/hitobito/hitobito_skv/blob/master/db/migrate/20211221132609_add_membership_verify_token_to_people.rb
  - Migrations in den Wagons entweder belassen oder allenfalls löschen, was sinnvoller ist
- [person#init_membership_verify_token!](https://github.com/hitobito/hitobito_skv/blob/master/app/models/skv/person.rb#L17) in den Core verschieben
- ggf. init_membership_verify_token! via membership_verify_token triggern falls noch kein token gesetzt

# ToDo

- [x] Person verify token aus dem SKV Wagon in den Core verschieben (Migration, Person Model)
- [x] Verify Endpoint aus dem SKV Wagon in den Core verschieben inkl. Specs
- [x] Generierung QR Code in Core verschieben (PDF bei SKV verwenden)
- [x] Sicherstellen Specs/Funktionalität im SKV
- [x] Code aus dem SAC Wagon entsprechend entfernen und Core Feature nutzen, PDF Ausweis mal bestehen lassen (der PDF Ausweis wird vermutlich ersetzt)
- [x] Manuell Testen
- [x] Kurze Doku im Core Repo
- [x] CHANGELOG entry im core

**Comment by mtnstar** [comment]
> Wenn ich ein QR Code mit dem Mobiltelefon scanne, erhalte ich folgendes Ergebnis zurück: ![image](https://private-user-images.githubusercontent.com/132900428/289907160-bfcd6196-240d-48f3-b77b-406d9f01f29c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDg5MTYsIm5iZiI6MTcxMDg0ODYxNiwicGF0aCI6Ii8xMzI5MDA0MjgvMjg5OTA3MTYwLWJmY2Q2MTk2LTI0MGQtNDhmMy1iNzdiLTQwNmQ5ZjAxZjI5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxMTQzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWVlMDAyZjYxZTZkZTEwNjY1MTFlNTM3NDVjNzY2NWMwNTNlY2I1MjQ5ZDExODIyNDQ0MTU4NThlMGFkMTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XktDFlbYmD0hRTW03whXgn5DtCyLCWM5JxxUl1p6gAw)
> 
> Die Darstellung des Fotos könnte optimiert werden. Ist dies vorgesehen?

das wir zusammen mit #78 gefixt

**Comment by tobiasstern** [comment]
Anzeige des PDFs und Aufruf der verify page funktioniert immer noch. Weitere Anpassungen geplant in Tickets gemäss https://saccas.atlassian.net/browse/HIT-44 und https://saccas.atlassian.net/browse/HIT-41

-> closed


![Image](https://github.com/hitobito/hitobito/assets/11408951/c231d2e1-f8b8-44d4-8d2e-a8a0c313cd23)
