### ISSUE TITLE
INVOICES: Ebics Fehlerverhalten fixen

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#2584]
### Aktuelles Verhalten

Der Ebics Import funktioniert bis zu einem gewissen Punkt, bei dem das Fehlerverhalten versagt und der komplette Job abbricht.
Da der Job über alle `PaymentProviderConfigs` (und somit Gruppen) iteriert, funktionieren alle Imports bis zu dem Fehlerfall problemlos. Alle Configs danach werden aber nicht importiert.

### Gewünschtes Verhalten

Der Fall soll korrekt abgefangen werden, heisst:
1. Der Job sollte unter allen Umständen weiterlaufen und alle Configs durcharbeiten
2. Der Fehler soll anschliessend im Logging auffindbar sein

### Schritte zu reproduzieren

Leider haben wir kein richtiges Testsystem bei welchem wir diesen Fehler nachstellen können.
Vielleicht kann mit umfangreicheren Tests die Situation provoziert werden

### Wann ist der Fehler aufgetreten?

Siehe Sentry

### hitobito version

2.1.4

### Organisation

Die Mitte (effektiv aber bei allen)

### Screenshots, weiterer Kontext

Sentry Issue: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/65772/?environment=production

Problem ist, dass aus irgend einem Grund sowohl `@payments`, als auch `@errors` `nil` ist. Entweder die werden irgendwann auf `nil` gesetzt oder `#initialize` wird nicht aufgerufen.

Das führt dann erst dazu dass `@payments` einen `NoMethodError` auslöst. Dieser wird im `rescue` block gefangen aber dann wird innerhalb dieses blocks noch ein `NoMethodError` wegen dem `@errors` ausgelöst.

# Tech-Spec

## Payments::EbicsImportSchedulerJob (neu)

- Erstellt/scheduled pro PaymentProviderConfig einen Job ->  Payments::EbicsImportJob

## Payments::EbicsImportJob

- DB Migration die sicherstellt das keine Payments::EbicsImportJob mehr scheduled sind
- Nimmt neu eine PaymentProviderConfig als Argument
- Beim Löschen einer PaymentProviderConfig werden alle Scheduled Jobs dazu gelöscht

### Hitobito Log

 - subject: PaymentProviderConfig
 - info: Starting Ebics Import
 - Loggen was hier sinnvoll und möglich ist, wünschenswert wären die erstellten Payment IDs
 - Payment IDs evtl. gleich mit dem Formatter verlinken (format_hitobito_log_entry_payload)
 - bei Error das Ebics XML per S3 speichern und den Download Link im Payload zur Verfügung stellen
 
![image](https://github.com/user-attachments/assets/c07217a4-e4b8-4a71-88f2-e09e61b07283)

## PaymentProviderConfig

- evtl. has_many: :hitobito_log_entries
- after_destroy :clear_scheduled_ebics_import_jobs

# ToDo

- [x] Payments::EbicsImportSchedulerJob erstellen
- [x] Payments::EbicsImportJob nur noch mit einer PaymentProviderConfig als Argument
- [ ] Logging für Payments::EbicsImportJob implementieren
- [x] Invoices Modul doku updaten
