### ISSUE TITLE
TECH: Wagon Specs parallel laufen lassen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2588]
Als Hitobito Dev
möchte ich dass die verschiedenen Arten von Specs auch in Wagons parallel laufen,
um bei flaky Specs die anderen Arten von Specs trotzdem am Laufen zu haben und so Zeit zu sparen.

Die Änderung von #2586 soll auch für Wagon Specs ergänzt werden.

# Tech-Spec

- Der Speedup ist bei den Wagon Specs sekundär, aber die Transparenz und Repeatability die wir vom parallelen laufen lassen bekommen sind definitiv ein Timesaver.
- In GitHub Actions laufen Jobs parallel, aber Steps sequenziell
- Jeder Job braucht seinen eigenen Setup, darum müssen wir z.B. setup-ruby in jedem Job einzeln laufen lassen
- Für DRY kann man ein Set von Steps als [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) auslagern
- Eine Composite Action kann man im Workflow auch direkt [vom Filesystem lesen](https://github.com/hitobito/hitobito/blob/master/.github/workflows/tests.yml#L113) (was natürlich zuerst das Auschecken des entsprechenden Repos bedingt)
- Für die Wagon Tests könnte das aus mehreren Gründen leicht schwieriger umzusetzen sein als im Core (sollte aber alles lösbar sein):
  - In den Wagons haben wir bisher nur einen einzelnen [Rake Task](https://github.com/hitobito/hitobito/blob/master/.github/workflows/wagon-tests.yml#L185) `ci:wagon` welcher alle Specs sequenziell ausführt. Wir müssen dies auf mehrere kleinere Rake Tasks umstellen
  - Für die Wagon Specs wird ein sogenannter [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows) aus dem Core angezogen, damit wir bei Änderungen nur eine Datei im Core statt 15+ Dateien in den Wagons anpassen müssen. Damit könnte das relative Referencing der composite action im Filesystem etwas komplizierter werden.
  - Gewisse Wagons brauchen eine Wagon Dependency (konkret: brauchen den Youth Wagon), andere aber nicht

# ToDo

- [x] [Reusable workflow](https://github.com/hitobito/hitobito/blob/master/.github/workflows/wagon-tests.yml) im Core anpassen, sodass für die einzelnen Arten von Specs (rubocop, main specs, feature specs, sphinx specs) je ein Job gespawnt wird
- [x] Gemeinsamen Setup in eine composite action im Core auslagern, und diese composite action in den Jobs verwenden
- [ ] Sicherstellen, dass [notify-statuscope](https://github.com/hitobito/hitobito/blob/master/.github/workflows/wagon-tests.yml#L197) nur dann läuft wenn alle Spec-Jobs erfolgreich waren
