### ISSUE TITLE
PG-MIGRATION: Replace all CASE statements

### ISSUE THREAD

**Issue by njaeggi** [hitobito/hitobito#2605]
CASE statements (mostly used in ORDER BY in our case) make queries more difficult to migrate. When a query uses DISTINCT and and CASE statement we are forced to use GROUP BY.

To prevent using GROUP BY and aggregate functions we want to remove all CASE statements in our queries and simplify our sort approach with other solutions.

# ToDo
- [x] Add generated sort_name column to person
- [x] Adjust order_by_name method in person model to use new sort_name column
- [ ] Add new table event_role_types
- [x] Seed Event::role_types on app start
- [x] Check for changes in Event model to prevent seeding role_types every app start
- [x] Replace other CASE statements
