### ISSUE TITLE
PG-MIGRATION: Finish pg_search Implementation

### ISSUE THREAD

**Issue by njaeggi** [hitobito/hitobito#2607]
A first approach to implement pg_search was already made here: https://github.com/njaeggi/hitobito/tree/feature/postgresql-fulltext-search

# ToDo

- [ ] Implement feedback: https://github.com/mtnstar/niklas-ipa-hitobito/pull/2
- [ ] Find Solution for Infix Search
- [ ] Implement all missing Entities (Events, Addresses, Invoices)
- [ ] Improve Performance, first approach: https://codimd.puzzle.ch/8CyPwK18TQmFZlMY2Nq36w?both
