### ISSUE TITLE
PEOPLE: Household model implementieren

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2614]
blocks #2616, #2624, #2622, hitobito/hitobito_sac_cas#549

Die alte Domainklasse `Person::Household` ist historisch gewachsen, hat eine eigenwillige Schnittstelle und ist schwierig anzupassen.
Sie soll ersetzt werden durch ein ActiveModel `Household`.

> [!WARNING]
> Im neuen `Household` model werden keine Berechtigungen mehr geprüft. Es muss dort wo der `Household` verwendet wird geprüft werden, ob der user Schreibrecht hat und braucht auf die referenzierten Personen.

# Use Cases

## Haushalt erstellen

* Household instanzieren mit Person `reference_person` ohne `household_key`
* Personen hinzufügen
* `Household.save` validiert den Household, generiert neuen `household_key` und aktualisiert Personen

## Person hinzufügen

* Household instanzieren mit Person `reference_person` mit `household_key`
* Weitere Person hinzufügen
* `Household.save` validiert den Household und aktualisiert Personen

## Person entfernen

* Household instanzieren mit Person `reference_person` mit `household_key`
* Person entfernen
* `Household.save` validiert den Household und aktualisiert Personen

## Haushalt auflösen

* Household instanzieren mit Person `reference_person` mit `household_key`
* `Household.destroy` 
  * entfernt auf allen Personen den `household_key`
  * setzt `@destroyed` (Haushalt kann nicht gespeichert werden wenn gesetzt)

# Tech-Spec

```mermaid

classDiagram
  class HouseholdMember["HouseholdMember include ActiveModel::Model"] {
    new(household, person_id)$
    household
    person_id
    person()
    errors()
  }

  class Household["Household include ActiveModel::Model"] {
    new(reference_person)$
    reference_person: Person
    household_key
    household_members: List~HouseholdMember~
    household_members_attributes=(attributes)
    add(person)
    remove(person)
    valid?()
    errors()
    warnings()
    save()
    destroy()
    -next_key()
  }

  Household --> HouseholdMember

```

## Household::new(reference_person)

* neuen `Household` instanzieren
* `@reference_person` zuweisen
* `@household_key` zuweisen von `reference_person.household_key`
* für `@household_members` Personen von DB laden mit `Person.where(household_key: @household_key)` und in `HouseholdMember` wrappen

## Household#add(person)

* Person in `HouseholdMember` wrappen und in `@household_members` hinzufügen
* ~Falls `person` einen `household_key` hat, alle Personen mit demselben `household_key` inzufügen  
  (e.g. `self.household_members += person.household.household_members`. `Person#household` accessor ist weiter unten beschrieben)~
* Falls `person` bereits in einem Haushalt ist, kann der Haushalt nicht gespeichert werden und es wird ein Error den Errors hinzugefügt

## Household#remove(person)

* aus `@household_members` element zu person entfernen

## Household#valid?

* prüft alle `Household` validations

## Household#save

* Alle DB Operationen laufen in einer Transaktion
* falls `household_members` nur 1 Person enthält, leeren
* `yield [new_people, removed_people]`  
  neue und entfernte Personen yielden, damit das Verhalten im SAC wagon customized werden kann.  
  * `new_people`: allen Personen in `household_members` bei welchen `p.household_key == household_key`
  * `removed_people`: allen Personen mit `p.household_key == household_key` welche nicht in `household_members` enthalten sind  
  ```ruby
  Person.where(household_key: household_key).where.not(id: household_members.map(&:id)).update_all(household_key: nil)
  ```
* falls `household_key` nil ist (neuer Household), `@household_key` zuweisen mit `#next_key` (ausser Household ist leer)
* bei allen Personen in `household_members` Adresse der `reference_person` und `household_key` übernehmen
* bei allen `removed_people` den `household_key` entfernen (`removed_people.update_all(household_key: nil))`
* changes loggen analog `Person::Household#household_log`

## Household#destroy

* `yield people`
  Household Personen yielden, damit das Verhalten im SAC wagon customized werden kann.  
  * `people`: `Person.where(household_key: household_key)`
* bei allen Personen `people` den `household_key` entfernen (`people.update_all(household_key: nil)`)
* in Transaktion

## Household#household_members_attributes=(attributes)

* wird benutzt für nested form
* `attributes` enthält eine Liste von Personen ids
* Personen anhand der ids aus DB laden, in `HouseholdMember` wrappen und an `household_members` zuweisen

## private Household#next_key

* generiert den nächsten household_key, benötigt beim Speichern eines neuen Household   
  Implementation von `Person::Household` übernehmen

## Validations

https://api.rubyonrails.org/classes/ActiveModel/Errors.html

* `Household#errors` enthält wie gewohnt die regulären Validierungsfehler  
  Valideriungen:
    * `check_household_members_valid`: 
      + ruft auf allen `household_members#valid?(validation_context)` auf (der validation context muss weitergereicht werden, damit die Validierungen im HouseholdMember mit dem korrekten Context laufen)
      + wenn ein `HouseholdMember` nicht valid ist, sollen die `household_member#errors` dem `household#errors` hinzugefügt werden. Ebenso sollen die `household_member#warnings` dem `household#warnings` hinzugefügt werden. So können diese ebenfalls in den error messages auf dem form angezeigt werden
* `Household#warnings` enthält Validierungsfehler, welche dem user als Warnung angezeigt werden, die aber das Speichern nicht verhindern. Siehe Beispielcode unten  
  Validierungen: 
  * nur 1 Person im Haushalt:  
    `"Der Haushalt wird aufelöst da nur noch 1 Person vorhanden ist"`
  * die Personen haben unterschiedliche Adressen:  
    `"Für alle Mitbewohner wird die Haushaltsadresse von "#{reference_person.name} übernommen"`

  Beispielcode für separate "warnings" validierungen:

  ```ruby
  class MyModel
    include ActiveModel::Validations

    validates :name, presence: true # normale validierung generiert errors
    validate :check_name_length # custom validierung, errors werden den warnings hinzugefügt

    def warnings
      @warnings ||= ActiveModel::Errors.new(self)
    end

    def check_name_length
      @warnings.add(:name, :too_short) if name.length < 5
    end

  end

  ```

* `Person#household`  
  Methode auf dem `Person` model zum Instanzieren eines `Household` mit der Person als `reference_person`:
  ```ruby
  def household
    Household.new(self)
  end
  ```

# ToDo

- [x] Domainklasse erstellen oder anpassen
- [x] Specs schreiben
- [ ] ~Core documentation update (people::household)~ @mtnstar holt dies mit der Überarbeitung der doc noch nach
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
