### ISSUE TITLE
PEOPLE: Household management views/controller

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2616]
blocked by #2614, #2622 
blocks #2624, hitobito/hitobito_sac_cas#550, hitobito/hitobito_sac_cas#564

Mit #2614 wurde das neue `Household` activemodel implementiert.
Nun soll dazu controller und view gebaut werden, um den `Household` einer `Person` zu verwalten.

Mit #2622 wurde auf der Person show view ein Household aside eingebaut mit Platzhalter Buttons. Diesen soll nun Funktion gegeben werden.

Beim Klick auf den "Verwalten" Button wird die Household edit view geöffnet, in welcher Personen hinzugefügt und entfernt werden können. Bei jeder Aktion wird der Haushalt validiert und wenn er valide ist, ist der "Speichern" Link klickbar, ansonsten ist er disabled und es werden die Validierungsfehler angezeigt.
Personen können mittels eines type-ahead Suchfeldes hinzugefügt werden, wobei nur Personen angeboten werden, auf welchen der user Schreibrechte hat oder welche bereits dieselbe Adresse haben wie der Haushalt.

Beim Klick auf den "Auflösen" Button wird die Household destroy action aufgerufen, welche den Haushalt löscht und wieder auf die Person show view umleitet.

## Mockups

**Household aside auf Person show view**
![Screenshot from 2024-05-21 13-18-23](https://github.com/hitobito/hitobito/assets/636849/506e64c4-9942-4c07-88bd-716863430698)

**Household edit view**
![Screenshot from 2024-05-21 16-35-00](https://github.com/hitobito/hitobito/assets/636849/29900e6c-a83a-4f4f-b086-9b277b091436)

# Tech-Spec

## Route

```ruby
resources :people, only: [] do
  resource :household, except: [:new, :create]
end
```

## HouseholdsController

* in `before_action`:
  * `@person` initializieren: `Person` laden anhand `params[:person_id]`, `404 NOT FOUND` falls nicht gefunden
  * `authorize!(create_households, Person)`

* `#entry`
  ```ruby
  def entry = @entry ||= person.household
  ```

* `#edit`
  * params zuweisen
  * prüfen, ob alle Personen bereits die Household Adresse besitzen oder ob der user Schreibrechte auf die Personen hat. dummy code:
    ```ruby
      entry.people.all? do |person| 
        same_address?(entry, person) || authorize!(:write, person)
      end
  * entry validieren
  * `respond_with(entry)`

* `#update` 
  * params zuweisen
  * prüfen, ob alle Personen bereits die Household Adresse besitzen oder ob der user Schreibrechte auf die Personen hat. dummy code:
    ```ruby
      entry.people.all? do |person| 
        same_address?(entry, person) || authorize!(:write, person)
      end
  * entry speichern
  * bei `success` auf 
  * auf `group_person_path` redirecten, sonst Household#edit rendern

* `#destroy`
  * `entry.destroy` aufrufen falls `entry.valid?`
  * auf `group_person_path` redirecten


## Views

* Siehe mockups oben
* **Person Show view**
  * Buttons im Household aside verlinken   
     **kann erst gemacht werden nachdem #2622 gemergt ist**
    * "Erstellen" resp. "Verwalten" verlinken auf `edit_group_person_household_path`
    * "Auflösen" verlinkt zu household#destroy und öffnet Bestätigungsdialog:  
      ```ruby 
      link_to("Auflösen", person_household_path(person_id: person.id), method: :destroy, confirm: "Haushalt wirklich auflösen?")`
      ```

* **Household Edit view**  
  * Implementieren als Person Sheet
  * View in ein turbo frame wrappen
  * Hidden form mit nested fields für die `household_members` (nested fields für das `id` Attribut)
  * Stimulus controller `household-edit` 
    * action `addPerson`: fügt nested fields für Person dem form hinzu und submittet es an die `#edit` action des rails controllers
    * action `removePerson`: entfernt nested fields der Person vom form und submittet es an die `#edit` action des rails controllers
  * Liste der Personen im Haushalt (`household#household_members`)
    * Person verlinken wenn user Leserecht auf sie hat
    * Alter in Klammern hinter dem Namen
    * `trash` icon auf jeder Zeile zum Entfernen der Person, ruft `removePerson` action auf stimulus controller auf.  
      Falls die Person keine bestätigte Email Adresse besitzt, soll das icon deaktiviert sein (ausgegraut) und als tooltip einen Hifetext haben:  
      `"Die Email Adresse muss bestätigt werden, bevor die Person aus der Familie entfernt werden kann."`
    * Zeile mit `background-color: var(--bs-alert-color)` falls `household_member.errors.present?`
    * Zeile mit `background-color: var(--bs-warning-color)` falls `household_member.warnings.present?` ausser wenn auch errors vorhanden sind
  * Suche mit type-ahead zum Hinzufügen von Personen  
    * Es können nur Personen gefunden werden, welche dieselbe Adresse besitzen oder auf welche der user Schreibrecht hat
    * Gleiche Funktionalität wie bestehendes Suchfeld auf Person edit view im "Wohnt im Haushalt mit" (`app/views/person/households/_fields.html.haml:22`)  
      Wenn möglich den `TomSelect` controller verwenden (ohne die 'multiple' Option): https://github.com/hitobito/hitobito/pull/2613/commits/4665501471275975704050ac4df7a400aae15029?w=1  
      Anwendungsbeispiel: https://github.com/hitobito/hitobito_sac_cas/pull/542/commits/a8e9ccdeb49b6a89a294adbf3c99a03e52532cc8?w=1#diff-42a1a948d80faaae52394b9b39fb4419ee3798f78262d8f6f166f0d4c0ea380d  
      Der `TomSelect` controller wird mit hitobito/hitobito_sac_cas#524 erstellt.
    * Im stimulus controller auf den event `"change"` hören und `addPerson` action aufrufen (der event hat den gewählten value als Parameter)  
      https://tom-select.js.org/docs/events/
  * Anzeige der Validierungsfehler `household#errors`
  * Anzeige der Validierungswarnungen `household#warnings`
  * Infotext Haushaltsadresse info inkl. Anzeige der Haushaltsadresse der `household.reference_person`
  * `Übernehmen` Link ist nur klickbar, wenn keine errors vorhanden sind (aber warnings dürfen vorhanden sein), submittet das form an die `#update` action

# ToDo

- [ ] Route
- [ ] Controller
- [ ] Person show view aside
- [ ] Household edit view
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by richardjubla** [comment]
Hinweis: "Jedes" Profil findet in seinem Profil die Möglichkeit einen Haushalt zu erstellen. Der Haushalt kann dann wegen den fehlenden Berechtigungen nicht erstellt werden. Ein Speichern führt zur Meldung das der Haushalt gelöscht wurde. 

![image](https://github.com/user-attachments/assets/87960d79-c03e-4c7d-9cbc-022f9a55bcf0)
![hitobito-household-query](https://github.com/user-attachments/assets/a4504d9b-26c3-49e5-874d-a5d45aad60b9)
