### ISSUE TITLE
OAUTH: Consent Screen optional überspringen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2618]
Als Verband der OAuth (und OIDC) Applikationen verwaltet
möchte ich die Option haben, bei verbandsinternen OAuth-Applikationen den Consent Screen zu überspringen,
um eine nahtlosere User Experience zu bieten wenn die betroffenen Daten nur innerhalb des Verbands weitergegeben werden.

Neu soll es pro OAuth-Applikation möglich sein, zu konfigurieren, ob die Applikation vertrauenswürdig ist und der Consent Screen daher übersprungen werden soll.

# Mockup

![Screenshot 2024-05-17 at 15-14-18 MiData PBS_MSdS_MSS - Local application](https://github.com/hitobito/hitobito/assets/7566995/5f132dfb-10f7-48b3-98bd-a47bd77d4142)

Wenn der neue Haken aktiviert ist, sollte der folgende Consent Screen beim erstmaligen OAuth-Login nicht mehr auftauchen:
![image-20240517-065304](https://github.com/hitobito/hitobito/assets/7566995/6923198d-5e99-4b02-89c4-8ba78fc18780)

# Tech-Spec

- Umsetzung im Core
- Neues Boolean Flag auf OAuth Applikation einfügen, Default ist off, damit das bisherige Verhalten beibehalten wird
- https://doorkeeper.gitbook.io/guides/configuration/skip-authorization
- Achtung beim testen: Der Consent Screen kommt nur beim ersten Login eines Users bei einer OAuth Applikation. Um danach erneut wieder einen Consent Screen zu provozieren, kann man als User in den Einstellungen -> OAuth Autorisierungen den gegebenen Consent revoken (Eintrag löschen).

# ToDo

- [x] Neues Boolean Feld `skip_consent_screen` auf OAuth Applikationen einfügen
- [x] In `#new`, `#edit` und `#show` der OAuth Applikation rendern
- [x] Im [doorkeeper initializer](https://github.com/hitobito/hitobito/blob/master/config/initializers/doorkeeper.rb) das `skip_authorization` einsetzen, mit einem Block der prüft ob die OAuth Applikation mit `skip_consent_screen` markiert ist
- [x] Feature Tests schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
