### ISSUE TITLE
LANGUAGE: Generic Wagon - Abo Sprachen-Filter, falsches Sprachfeld

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito#2620]
### Aktuelles Verhalten

Im Generic-Wagon kann auf der Person das Feld `person_correspondence_language` ausgefüllt werden.
Im Abo Filter kann jedoch nur nach dem Attribut `language` gefiltert werden. Dieses wird im Generic-Wagon jedoch nicht verwendet.

### Gewünschtes Verhalten

Im Abonnement soll in den Globalen Bedingungen korrekt nach `person_correspondence_language` gefiltert werden können.
Der Filter für `language` kann entfernt werden.

Optional: Im Wagon der Mitte den Filter auch gleich so anpassen dass nicht mehr nach `language`  gefiltert werden kann. (Da kann aktuell nach beidem gefiltert werden,)

### Schritte zu reproduzieren

1. Generic-Wagon
2. Abo Filter nach Sprache einstellen
3. Funktioniert nicht, da `language`  bei allen Personen Deutsch ist und auf Personen nicht geändert werden kann

### Wann ist der Fehler aufgetreten?

21.05.2024

### hitobito version

2.1.4

### Organisation

PPS

### ToDos

- [x] Filter nach `language` nur anzeigen, wenn dies verwendet wird
- [x] Filter nach `correspondence_language` ermöglichen, wenn dies vorhanden ist
- [x] mit angemessener Rolle durchklicken
- [x] CHANGELOG anpassen

**Comment by fragl0s** [comment]
Besten Dank fürs erfassen und beheben diese Fehlers.

**Comment by carlobeltrame** [comment]
Das scheint für mich ein Rückschritt zu sein. Wäre es nicht besser, im Generic Wagon und optional bei der Mitte mal die Migration auf das neuere standardisierte `language` Feld abzuschliessen?

**Comment by kronn** [comment]
@carlobeltrame Ich möchte vor allem erstmal im Core beides sauber unterstützen, da ich hier nur kleine Anpassungen erwarte.

Grundsätzlich legst du hier aber einen Finger in die Wunde und es ist absolut der Plan, dies konsistent mit dem Attribut aus dem Core zu lösen.
