### ISSUE TITLE
PEOPLE: People::Household cleanup

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2624]
blocked by #2614, #2616

Mit #2614 wurde das `Household` implementiert, welches das `People::Household` ersetzt. Mit diesem ticket sollen alle Referenzen auf `People::Household` angepasst werden um stattdessen `Household` zu verwenden und die alte Klasse entfernt werden.

# ToDo

- [x] `People::Household` entfernen
- [x] `PeopleController`:
  * Methoden und dazugehörige callbacks entfernen: `#validate_household`, `#persist_household`, `#household`
  * von `self.permitted_attrs` das `household_people_ids` entfernen
- [x] `Person::HouseholdsController` entfernen und ebenso dazugehörige Route
- [x] `Person`:
  * `attr_accessor :household_people_ids` entfernen
  * `#household_people` anpassen: `where(id: household_people_ids)` aus query entfernen
- [x] `config/settings.yml:221`  
    * von `help_text_blacklist.person` das `household_people_ids` entfernen
- [x] `config/locales`: 
  * `de.person.households` entfernen
- [x] `app/views/person/households` entfernen
- [x] in `app/views/contactable/_address_fields.html.haml` das div `updates-household-address` anpassen:  
      anzeigen, wenn `entry` eine `Person` ist und ein `household_key` gesetzt hat
- [x] `app/javascript/javascripts/modules/people/households.js.coffee` entfernen
- [x] im SAC wagon:   
  * in i18n files den Text von `contactable.address_fields.updates_household_address` anpassen:  
    `"Adresse wird für alle Familienmitglieder aktualisiert"`
- [x] Specs fixen (diverse Specs benutzen `People::Household`, um das test setup vorzubereiten)
- [x] Mit angemessener Rolle "durchklicken"
