### ISSUE TITLE
PEOPLE: Anpassungen SelfInscription

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2640]
Das "Self-Inscription" feature soll erweitert werden, so dass es möglich ist, die Funktionalität abhängig von der Gruppe anzupassen.  
Im Core implementieren wir dazu den generischen Teil.

# Tech-Spec

- ActiveModel `SelfInscription` implementieren  
  Als Vorlage dient https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/self_inscription.rb  
  - Attribute `:person`, `:group`
  - keine Validierungen
  - ```ruby
    def group_for_title = @group
    ```
  - ```ruby
    def role 
      @role ||= group.self_registration_role_type.constantize.new(
        group: group,
        person: person
      )
    ```
  - `def save`: wenn `.valid?` und `role.valid?`: `role.save`
- `Groups::SelfInscriptionController` anpassen
  - ```ruby
    def self.model_class
      @model_class ||= SelfInscription
    end
    ```
  - `build_role` ersetzen durch `build_entry`:
    ```ruby
    def build_entry = SelfInscription.new(person: person, group: group)
    ```
  - Notification mail Aufruf in callback verschieben:
    ```ruby
    after_create :send_notification_mail
    ```
  - ```ruby
    def return_path = group_person_path(person.default_group_id, person)
  - `def create` entfernen
- View anpassen
  + `app/views/groups/self_inscription/new.html.haml`:  
    `entry.group_for_title` verwenden für den call von `render_self_registration_title`
- i18n
  * `groups.self_inscription.create.role_saved` verschieben nach `self_inscription.create.flash.success`

# ToDo

- [ ] `SelfInscription` active model erstellen
- [ ] `Groups::SelfInscriptionController` anpassen
- [ ] i18n anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by daniel-illi** [comment]
abgelöst durch #2664
