### ISSUE TITLE
PEOPLE: Anpassungen SelfInscription

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2641]
Das "Self-Inscription" feature soll erweitert werden, so dass es möglich ist, die Funktionalität abhängig von der Gruppe anzupassen.  
Im Core implementieren wir dazu den generischen Teil.

# Tech-Spec

### ActiveModel `SelfInscription` implementieren  
Als Vorlage dient https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/self_inscription.rb, aber nur minimaler Code der für Core relevant ist:
- include `ActiveModel::Model`, `ActiveModel::Attributes`
- Attribute `:person`, `:group`
- Validierungen
  - person und group present
  - Validieren, dass `group.self_registration_active?`, sonst error msg `"Für diese Gruppe ist die Selbstregistrierung deaktiviert."`
- ```ruby
  def group_for_title = @group
  ```
- ```ruby
  def role 
    @role ||= group.self_registration_role_type.constantize.new(
      group: group,
      person: person
    )
  ```
- ```ruby
  def save = role.save! if valid?
  ```

### `Groups::SelfInscriptionController` anpassen
- möglichst `dry_crud` Konventionen verwenden
- ```ruby
  def self.model_class
    @model_class ||= SelfInscription
  end
  ```
- `build_role` ersetzen durch `build_entry`:  
  Zuerst versuchen, eine spezifische Klasse zu finden entsprechend der Gruppe, ansonsten auf die default implementation zurückfallen (dies wird im SAC wagon verwendet)
  ```ruby
  def build_entry
    self_inscription_class = 
      "SelfInscriptions::#{@group.class.name}".safe_constantize ||
      SelfInscription
    self_inscription_class.new(person: person, group: group)
  end
  ```
- Notification mail Aufruf in callback verschieben:
  ```ruby
  after_create :send_notification_mail
  ```
- ```ruby
  def return_path = group_person_path(person.default_group_id, person)
- `def create` entfernen damit Implementation der Superklasse verwendet wird

### Helper method `self_inscrption_form_partial` implementieren

Falls es ein spezifisches partial gibt für die Klasse der aktuellen Gruppe, dann soll dieses verwendet werden.
Fallback auf das default form partial.

```ruby
default_partial = "groups/self_inscription/_form"
specialized_partial = "groups/self_inscription/#{group.class.model_name.i18n_key}/_form"
lookup_context.find_all(view_to_render, formats: [:html, :haml]).any? ? specialized_partial : default_partial
```
    
### View anpassen
`app/views/groups/self_inscription/new.html.haml`:  
  * `entry.group_for_title` verwenden für den call von `render_self_registration_title`
  * `render self_inscription_form_partial`

### i18n

Für die success message wird im überarbeiteten Controller die Implementierung von `dry_crud` verwendet. Der i18n key muss entsprechend angepasst werden:

* `groups.self_inscription.create.role_saved` verschieben nach `self_inscription.create.flash.success`

# ToDo

- [ ] `SelfInscription` active model erstellen
- [ ] `Groups::SelfInscriptionController` anpassen
- [ ] View helper implementieren
- [ ] View anpassen
- [ ] i18n anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by daniel-illi** [comment]
abgelöst von #2665
