### ISSUE TITLE
EVENTS: Use new structured fields in participation_contact_data validations

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#2660]
### Aktuelles Verhalten

`event_participation_contact_data[housenumber]` can/should be validated by now. This leads to errors or a state in which sending the form is not possible anymore.

### Gewünschtes Verhalten

Validations of Participation Contact Data should work "like before", just with the new fields. The previous field `address` should not be part the validations anymore.

### Schritte zu reproduzieren

- have an event with participation-contact-data configured
- apply

### Wann ist der Fehler aufgetreten?

2024-06-06

### hitobito version

2.1.5-integration

### Organisation

Jubla, but most likely everyone

### Screenshots, weiterer Kontext

![image](https://github.com/hitobito/hitobito/assets/95908537/980185d0-8360-4099-ae6f-802f4c9cb249)

```
contact_data:1 - Failed to load resource: the server responded with a status of 422 (Unprocessable Content)

turbo.es2017-esm.js:941 
Error: POST https://***/groups/296/events/699/participations/contact_data?event_role%5Btype%5D=Event%3A%3ARole%3A%3AParticipant 422
```

_Originally posted by @richardjubla in https://github.com/hitobito/hitobito/issues/2595#issuecomment-2152203950_

### ToDos

- [x] Check validations
- [x] Verify/adapt existing config of events
- [x] write a migration to change requirement of `address` to `street`
- [x] Adapt specs if needed

**Comment by richardjubla** [comment]
Vielen Dank! Ich mache hier einen auf "Panik": Im nächsten Release sind die Youth-Verbände voll in den Lageranmeldungen drin. Es wäre sehr ungünstig, wenn die Events dann nicht korrekt funktionieren sollten.
