### ISSUE TITLE
PEOPLE: Selfinscription migrieren auf Wizard

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2665]
In #2654 wurden die Basisklassen für wizards implementiert und in #2662 wurde die "self-registration" auf das neue Wizard Konstrukt migriert. Die "self-inscription" soll nach dem selben schema funktionieren.

Die Selfinscription wird im SAC Wagon nicht mehr verwendet, es sollen alle customizations entfernt werden.

# Tech-Spec

Ein POC existiert auf dem branch poc/wizard-registration und ein dazugehöriger Draft PR https://github.com/hitobito/hitobito/pull/2653/files?w=1  
Dieser soll als Vorlage für die Implementation verwendet werden.

Im Core:
- `Wizards::InscribeInGroupWizard`
  * einzelner step `Wizards::Steps::ConfirmInscription`  
    * Sicherstellen, dass der user in der Gruppe noch keine Rolle vom gleichen Typ besitzt. Der wizard sollte in diesem Fall gar nicht gestartet werden, also schon im Controller prüfen. Falls der wizard doch gestartet wird, raisen  
    * erstellt neue Rolle für user in der Gruppe
  * view partial migrieren `app/views/groups/self_inscription/_form.html.haml` -> `app/views/wizards/steps/_confirm_inscription.html.haml`
- `Groups::SelfInscriptionController` anpassen, dass der neue Wizard verwendet wird  
  → `#entry`, `#model_class` etc siehe POC
    
Im SAC Wagon:
- `SacCas::Groups::SelfInscriptionController` entfernen
- `app/views/groups/self_inscription` entfernen
- dazugehörige specs entfernen

# Dev Notes

Testen

 * Im generic als admin http://localhost:3000/en/groups/23/edit "Externe Registrierung "role type" setzen.
 * Als member unter http://localhost:3000/de/groups/23 "Externe Registrierung" link verwenden -> redirected zu http://localhost:3000/de/groups/10/self_inscription

# ToDo

- [x] Domainklasse erstellen oder anpassen
- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
