### ISSUE TITLE
GROUPS: Sortierung Groups mit static_name

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito#2673]
mit https://github.com/hitobito/hitobito/pull/2219 haben wir Gruppen mit statischen/übersetzbare Gruppen-Namen eingeführt.

Diese Gruppen werden noch nicht alphabetisch sortiert was wir hier mit diesem Ticket anpassen wollen.

![image](https://github.com/hitobito/hitobito/assets/655627/a3504037-c0d3-4e45-9ffe-3dcf13707842)

Als Beispiel sollen beim SAC die Untergruppen einer Sektion alphabetisch sortiert werden. Die Sortierung ist dadurch bei diesen Gruppen abhängig von der gewählten UI Sprache.

Herausforderung ist hier das es Gruppen mit Namen aus der table groups (Spalte name, short_name) sowie diese Gruppen mit den übersetzbaren Namen gibt (static_name). Theoretisch können diese unter dem gleichen Parent gemischt sein, also solche mit static_name und names aus der group table.

Bei Gruppen mit static_name = true sind die table attribute name, short_name leer bzw. werden nicht berücksichtigt. Diese können also nicht mit SQL sondern nur im Ruby-land sortiert werden. 

# Tech-Spec

- https://github.com/hitobito/hitobito/blob/master/app/helpers/sheet/group/nav_left.rb
- https://github.com/hitobito/hitobito/blob/master/spec/helpers/sheet/group/nav_left_spec.rb

Bei Gruppen mit static_name=true wird der Name aus der Locale bezogen: https://github.com/hitobito/hitobito_sac_cas/blob/master/config/locales/wagon.de.yml#L408

# ToDo

- [X] Verstehen wie Groups mit static_name funktionieren
    * Wenn auf einer Group:: Klasse `static_name = true` gesetzt ist, dann wird der Gruppenname nicht von der DB sondern von den Übersetzungen geholt.
    * `name` und `short_name` sind dann immer gleich
- [X] Verstehen wie Gruppen mit Namen aus table groups (name, short_name) sortiert werden
    * `awesome_nested_set` setzt das `lft` Feld so, dass die Gruppen einfach als sortierte Liste heraus geholt werden können.
- [x] Bestimmen wo die Gruppen in der Navigation effektiv sortiert werden (nav_left.rb) ?
- [x] Neue Sortierung inkl. Tests implementieren (i18n Übersetzung berücksichtigen)
- ~~[ ] Feature im Core kurz und knackig dokumentieren (auf Englisch) @mtnstar kurz fragen wo (doc wird bald überarbeitet/gemerged)~~
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by rnestler** [comment]
> Verstehen wie Gruppen mit Namen aus table groups (name, short_name) sortiert werden

Ich sehe nicht wo momentan Gruppen alphabetisch sortiert werden. Es scheint mir nur nach dem `lft` feld sortiert zu werden: `entry.groups_in_same_layer.without_deleted.order(:lft).to_a`

**Comment by kronn** [comment]
> > Verstehen wie Gruppen mit Namen aus table groups (name, short_name) sortiert werden
> 
> Ich sehe nicht wo momentan Gruppen alphabetisch sortiert werden. Es scheint mir nur nach dem `lft` feld sortiert zu werden:
> 
> ```ruby
> entry.groups_in_same_layer.without_deleted.order(:lft).to_a
> ```

Siehe https://github.com/hitobito/hitobito/blob/d41dfdfbba2be236fe1c6624ee6276aef2c3e594/app/models/group/nested_set.rb#L100-L109
