### ISSUE TITLE
API: Personen nach Gruppenzugehörigkeit filtern

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito#2700]
Als Autor\*in einer Drittapplikation welche via API mit hitobito kommuniziert
möchte ich alle Personen mit aktiven Rollen in einer Gruppe via API auflisten können,
um nicht jedes Mal die gesamte Liste von allen mir zugänglichen Personen abzurufen und selber filtern zu müssen.

Neu soll es auf der API Filtermöglichkeiten nach Gruppenzugehörigkeit geben.

# Mockup

<details>
<summary>Beispiel-Response auf Request /groups/9?include=roles.person (Gruppe mit ID 9 hat genau 2 aktive Rollen)</summary>

```json
{
  "data": {
    "id": "9",
    "type": "groups",
    "attributes": {
      "name": "2 Externe Kontakte",
      "short_name": null,
      "display_name": "2 Externe Kontakte",
      "description": null,
      "layer": false,
      "type": "Group::ExterneKontakte",
      "email": null,
      "address": null,
      "zip_code": null,
      "town": null,
      "country": null,
      "require_person_add_requests": false,
      "self_registration_url": null,
      "archived_at": null,
      "created_at": "2024-06-21T11:30:30+02:00",
      "updated_at": "2024-06-21T11:30:30+02:00",
      "deleted_at": null,
      "navision_id": null
    },
    "relationships": {
      "contact": {
        "meta": {
          "included": false
        }
      },
      "creator": {
        "meta": {
          "included": false
        }
      },
      "updater": {
        "meta": {
          "included": false
        }
      },
      "deleter": {
        "meta": {
          "included": false
        }
      },
      "parent": {
        "meta": {
          "included": false
        }
      },
      "layer_group": {
        "meta": {
          "included": false
        }
      },
      "phone_numbers": {
        "meta": {
          "included": false
        }
      },
      "social_accounts": {
        "meta": {
          "included": false
        }
      },
      "additional_emails": {
        "meta": {
          "included": false
        }
      },
      "roles": {
        "data": [
          {
            "type": "roles",
            "id": "825"
          },
          {
            "type": "roles",
            "id": "1"
          }
        ]
      }
    }
  },
  "included": [
    {
      "id": "825",
      "type": "roles",
      "attributes": {
        "person_id": 600000,
        "group_id": 9,
        "label": "",
        "type": "Group::ExterneKontakte::Kontakt",
        "created_at": "2024-06-25T14:52:53+02:00",
        "updated_at": "2024-06-25T14:52:53+02:00",
        "deleted_at": null
      },
      "relationships": {
        "person": {
          "data": {
            "type": "people",
            "id": "600000"
          }
        },
        "group": {
          "meta": {
            "included": false
          }
        },
        "layer_group": {
          "meta": {
            "included": false
          }
        }
      }
    },
    {
      "id": "1",
      "type": "roles",
      "attributes": {
        "person_id": 600001,
        "group_id": 9,
        "label": null,
        "type": "Group::ExterneKontakte::Kontakt",
        "created_at": "2024-06-21T11:30:31+02:00",
        "updated_at": "2024-06-21T11:30:31+02:00",
        "deleted_at": null
      },
      "relationships": {
        "person": {
          "data": {
            "type": "people",
            "id": "600001"
          }
        },
        "group": {
          "meta": {
            "included": false
          }
        },
        "layer_group": {
          "meta": {
            "included": false
          }
        }
      }
    },
    {
      "id": "600000",
      "type": "people",
      "attributes": {
        "first_name": "Puzzle",
        "last_name": "ITC",
        "nickname": null,
        "company_name": "Puzzle ITC",
        "company": true,
        "email": "hitobito-sac-cas@puzzle.ch",
        "address": null,
        "zip_code": null,
        "town": null,
        "country": null,
        "primary_group_id": 9,
        "gender": null,
        "birthday": "1999-09-09",
        "language": "de",
        "family_id": null,
        "membership_number": null
      },
      "relationships": {
        "primary_group": {
          "meta": {
            "included": false
          }
        },
        "layer_group": {
          "meta": {
            "included": false
          }
        },
        "roles": {
          "meta": {
            "included": false
          }
        },
        "phone_numbers": {
          "meta": {
            "included": false
          }
        },
        "social_accounts": {
          "meta": {
            "included": false
          }
        },
        "additional_emails": {
          "meta": {
            "included": false
          }
        }
      }
    },
    {
      "id": "600001",
      "type": "people",
      "attributes": {
        "first_name": "Yvonne",
        "last_name": "Kemper",
        "nickname": null,
        "company_name": null,
        "company": false,
        "email": "yvonne_kemper@hitobito.example.com",
        "address": null,
        "zip_code": "0815",
        "town": "Neu Annburg",
        "country": null,
        "primary_group_id": 9,
        "gender": "m",
        "birthday": "2007-06-21",
        "language": "de",
        "family_id": null,
        "membership_number": null
      },
      "relationships": {
        "primary_group": {
          "meta": {
            "included": false
          }
        },
        "layer_group": {
          "meta": {
            "included": false
          }
        },
        "roles": {
          "meta": {
            "included": false
          }
        },
        "phone_numbers": {
          "meta": {
            "included": false
          }
        },
        "social_accounts": {
          "meta": {
            "included": false
          }
        },
        "additional_emails": {
          "meta": {
            "included": false
          }
        }
      }
    }
  ],
  "meta": {}
}
```

</details>

# Tech-Spec

- Graphiti bietet verschiedene Wege, um die Daten zu filtern, eigene custom Filter anzulegen etc.
- Eine Lösung für genau unser Problem (eine Liste von Ressourcen nach einem Feld einer related Ressource zu filtern) hat Graphiti aber von Haus aus nicht. Am relevantesten ist wohl https://github.com/graphiti-api/graphiti/issues/430
- Es wurden verschiedene Optionen in Betracht gezogen, sowohl vom /people Endpunkt aus mit Includes und Filtern (bis hin zu Support für hitobito-Personenfilter die man im UI zusammenklicken kann), wie auch vom /groups Endpunkt aus mit Includes
- Wichtig war, dass wir hier bald eine Lösung bieten können, welche in Zukunft auch skaliert bzw. uns den Weg zu zukünftigen Erweiterungen nicht verbaut
- ~~Aufgrund dieser Überlegungen ist als Lösung angedacht, einfach auf dem /groups Endpunkt die Relation zu `roles` neu includebar zu machen. Die Abfrage nach allen Personen (und Rollen) in der Gruppe 123 sieht dann so aus: `/groups/123?include=roles.person`. Dies nutzt Graphiti Core Funktionalität, vermeidet die Erstellung von zu vielen custom Filtern und erlaubt es uns trotzdem in Zukunft, bei weiteren Anforderungen rückwärtskompatibel zu erweitern.~~
- ~~Die Personen und Rollen in der abgerufenen Gruppe kommen dann alle durchmischt im `included` Array der Response daher, und die Drittapplikation muss filtern nach dem Type. Falls das nicht reicht, wäre der nächste naheliegenede Ansatz, einen dedizierten /roles Endpoint zu machen, auf dem man folgendermassen filtert: `/roles?filter[group_id]=123&include=person`. Dann kommen nur noch die Personen im `included` Array der Response.~~
- Da wir in #2699 sowieso einen /roles Endpoint implementieren mussten, und dieser die Anforderungen bereits erfüllt, wird dieser hier weiterverwendet

# ToDo

- [x] ~~Auf GroupResource neu die Association `has_many :roles, writable: false` definieren~~
- [x] Roles Endpoint verwenden, um alle Personen in einer Gruppe zu finden
- [x] Bestehende Specs anpassen wo nötig
- [x] ~~Neue Specs schreiben~~
- [x] Graphiti schema.json in allen Wagons aktualisieren
- [x] Mit angemessener Rolle "durchklicken"
- [ ] Nach Merge und Deployment: In https://saccas.atlassian.net/browse/HIT-407 kommentieren mit Anleitung, wie man alle Personen einer Gruppe abrufen kann.
