### ISSUE TITLE
Export: Strukturierte Adresse auch im Export

### ISSUE THREAD

**Issue by nchiapol** [hitobito/hitobito#2705]
Mit https://github.com/hitobito/hitobito/issues/2226 erhalten wir strukturierte Adressen. In den Exporten scheint die Adresse aber immer noch überall in einem Feld ausgegeben zu werden. (Exporte und bisherige `json`-API)

Neu sollten auch die Exporte die Adressen strukturiert aus geben. Insbesondere bei der API scheint mir das dringend. Die Chance dass die Daten dort für Rechnungen genutzt werden ist hoch.

**Comment by betsim** [comment]
Im Export Excel > Spaltenauswahl bleibt das Feld "Adresse" gar komplett leer ⚠️
Im Export Excel > Adressliste ist die Adresse – allerdings in einem Feld – vorhanden

**Comment by nchiapol** [comment]
@ThomasEllenberger Habe das im Rahmen der Releasetests für https://github.com/hitobito/hitobito/issues/2226 eben getestet, funktioniert noch immer nicht. (Kommentar aus https://github.com/hitobito/hitobito/issues/2704 hier her verschoben, die Issues sind sehr ähnlich und wir konzentrieren uns wohl besser auf dieses hier.) 

Exporte der Gruppe https://cevi.puzzle.ch/groups/5/people
  * CSV-Export "Spaltenauswahl"  enthält eine leere Address-Spalte.
  * XLSX-Export "Spaltenauswahl"  enthält eine leere Address-Spalte.
  * CSV-Export "Haushalte" enthält eine Spalte Address mit Strasse + Nummer in einem Feld
  * CSV-Export "Adressliste" enthält eine Spalte Address mit Strasse + Nummer in einem Feld
  * json-Endpunkt (https://cevi.puzzle.ch/groups/5/people.json): Address mit Strasse + Nummer in einem Feld

**Comment by ThomasEllenberger** [comment]
Erneut getestet:

-  CSV-Export "Spaltenauswahl" enthält eine leere Address-Spalte. -> Gibt nun korrekte Adressfelder aus.
-  XLSX-Export "Spaltenauswahl" enthält eine leere Address-Spalte. -> Gibt nun korrekte Adressfelder aus.
-  CSV-Export "Haushalte" enthält eine Spalte Address mit Strasse + Nummer in einem Feld -> Verhalten besteht nach wie vor
-  CSV-Export "Adressliste" enthält eine Spalte Address mit Strasse + Nummer in einem Feld  -> Gibt nun korrekte Adressfelder aus.
-  json-Endpunkt (https://cevi.puzzle.ch/groups/5/people.json): Address mit Strasse + Nummer in einem Feld -> Verhalten besteht nach wie vor


### ToDo:

- [ ] Im CSV-Export "Haushaltsliste" soll die Strasse und Hausnummer in getrennten Feldern ausgegeben werden analog den anderen Exporten.
- [ ]  Im CSV-Export "Haushaltsliste" sollen die neuen Felder "Zusätzliche Addresszeile" und "Postfach" enthalten sein. 
- [ ] Im json Endpunkt sollen neu **zusätzlich** auch die Felder Strasse, Hausnummer, zusätzliche Addresszeile und Postfach enthalten sein.

**Comment by ThomasEllenberger** [comment]
Anpassung der jsonAPI aus dem ToDo entfernt.
Da die Schnittstelle deprecated ist, braucht es hier einen Grundsatzentscheid, wass damit geschehen soll.
-> wird in https://github.com/hitobito/hitobito/issues/3624 weiter verfolgt.

@nchiapol
