### ISSUE TITLE
Anpassung Anmeldefenster "Musikfest"-Dialog

### ISSUE THREAD

**Issue by ODI-Navil** [hitobito/hitobito#2731]
Bisher ...

Der Dialog zur Anmeldung an ein Musikfest ursprünglich derart hart codiert, dass diverse Fragen nicht konfigurierbar sind. Daher die Bitte an euch: bitte entfernt die Fragen zum Wunschspieltag und zum Reglement komplett aus der Anmeldemaske (siehe Screenshot unten).

<img width="713" alt="SBV" src="https://github.com/hitobito/hitobito/assets/115537177/52bc07dc-2bdc-46ef-b326-9fabb7f4a178">

# ToDo

- [x] Issue für Umsetzung ~~erstellen~~ _nutzen_
- [x] Workflow des Features beschreiben
- [x] ggf. Mockup erstellen
- [x] Tech-Spec ergänzen
- [x] ToDo für Umsetzung definieren
- [x] Fragebereich "Wunschspieltag" entfernen
- [x] Fragebereich "Reglement" entfernen
- [x] Specs anpassen
- [x] Validierungen anpassen
- [x] Übergänge prüfen, ggf. anpassen
