### ISSUE TITLE
ROLES: explizites Start- und Enddatum

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito#2775]
Rollen können eine beschränkte Gültigkeitsdauer haben.
Bisher wurden `created_at` und `deleted_at` dafür missbraucht, die Gültigkeit einer Rolle abzubilden.
Neu soll auf der Rolle ein optionales Startdatum `start_on` und Enddatum `end_on` hinterlegt sein.
Dies vereinfacht das Handling von zukünftigen Rollen sowie von Rollen mit vordefiniertem Ablaufdatum.

Um möglichst Kompatibel mit bestehendem Code zu bleiben, soll ein neuer `default_scope` definiert werden, welche analog dem bisherigen default scope von `paranoia` nur die aktuell gültigen Rollen enthält.

Die alten timestamps `deleted_at`, `delete_on` sowie `convert_on` werden nicht mehr benötigt und die entsprechenden Spalten sollen entfernt werden. Ebenso wird die Rollenklasse `FutureRole` nicht mehr benötigt und wird gelöscht.

Auf `Role` gibt es `after_create` und `after_destroy` callbacks, welche die Attribute `Person#primary_group_id` und `Person#contact_data_visible` setzen. Diese Mutationen sollen nur durch die Callbacks durchgeführt werden, wenn die bearbeitete Rolle aktuell aktiv ist.  
Die Mutationen müssen ebenfalls durchgeführt werden, nachdem eine Rolle aktiv wird (`start_on` erreicht) und wenn sie abläuft (`end_on` überschritten). Dazu wird ein Hintergrundjob implementiert, welcher für die Personen aller aktiv gewordenen und abgelaufenen Rollen seit dem letzten Job run die Mutationen durchführt.

# Tech-Spec

Siehe auch Draft PRs https://github.com/hitobito/hitobito/pull/2763 , https://github.com/hitobito/hitobito_sac_cas/pull/850

- Migrationen erstellen: 
  - [x] Spalten hinzufügen:
    ```ruby
    change_table :roles, bulk: true do |t|
      t.date :start_on
      t.date :end_on
    end
    ```
  - [x] Timestamps migrieren: (separate Migration verwenden, mysql unterstützt keine Transaktionen bei Schemaänderungen!)
    ```ruby
    execute <<~SQL
      UPDATE roles
      SET
        start_on = created_at,
        end_on = COALESCE(deleted_at, delete_on)
    SQL
    ```
  - [x] alte Spalten löschen:
    ```ruby
    change_table :roles, bulk: true do |t|
      t.remove :deleted_at, type: :datetime
      t.remove :delete_on, type: :date
      t.remove :convert_on, type: :date
      t.remove :convert_to, type: :string
    end
    ```
- `Role` anpassen
  - [x] `acts_as_paranoid` entfernen
  - [x] Validierungen von `created_at`, `delete_on` entfernen
  - [x] Valideren dass `end_on` >= `start_on` ist falls beide gesetzt sind
  - [x] Scopes implementieren:
    - [x] `active`:  
      ```ruby
      scope :active, ->(date = Date.current) {
        where("start_on <= :date OR start_on IS NULL AND end_on >= :date OR end_on IS NULL", date:)
      }
      ```
    - [x] default scope:   
      ```ruby
      default_scope` { active }
      ```
    - [x] `with_inactive`: da der default scope mit `start_on`/`end_on` filtert, müssen diese attrs unscoped werden:
      ```ruby
      scope :with_inactive, -> { unscope(where: [:start_on, :end_on]) }
      ```
    - [x] `inactive`: anpassen dass statt dem `deleted_at` von paranoia die neuen attrs verwendet werden:
      ```ruby
      scope :inactive, -> {
        with_inactive.where(
          "archived_at <= :now OR start_on > :today OR end_on < :today",
          now: Time.current.utc,
          today: Date.current
        )
      }
      ```
    - [x] `ended`, `future`: 
      ```ruby
      scope :ended, -> { with_inactive.where("end_on < :today", today: Date.current) }
      scope :future, -> { with_inactive.where("start_on > :today", today: Date.current) }
      ```
  - [x] `#destroy`: bisheriges Verhalten anpassen:
    - wo vorher "soft-destroy" verwendet wurde, soll neu das `end_on` auf gestern gesetzt werden, ausser `end_on` ist bereits auf ein vergangenes Datum gesetzt
    - wo vorher `#really_destroy!` zum Zuge kam, soll neu ein reguläres active record `#destroy` verwendet werden (da Role nicht mehr "paranoid" ist)
    - `destroy` callbacks sollen auch ausgeführt werden, wenn `end_on` gesetzt wird statt löschen
  - [x] `#really_destroy!(**)` implementieren: `#destroy` auf `super` aufrufen.  
        (diese Methode wird aufgerufen, wenn `Group#really_destroy` aufgerufen wird wegen der Option `dependent: :destroy` auf der Relation)
  - [x] accessors entfernen
    - `#start_on`
    - `#end_on`
    - `#outdated?`
    - `#paranoia_destroy_attributes`
  - [x] `def ended? = end_on? && end_on < Date.current`
  - [x] `#archive!`
- SAC Wagon  
  Siehe auch Draft PR https://github.com/hitobito/hitobito_sac_cas/pull/850
  - [x] auf `Group::SektionsMitglieder::Mitglied` und `MitgliedZusatzsektion` Validierung von `delete_on` entfernen
  - [x] SacCas::Role::MitgliedCommon
    - Validierung von `created_at` entfernen
    - Presence Validierung für `start_on`, `end_on`
  - [x] `SacCas::Role::ClassMethods#select_with_membership_years` anpassen
  - [x] weitere Referenzen an angepasste scopes/Attribute/Methoden anpassen

- SBV Wagon: 
  - [x] `hitobito_sbv/lib/tasks/reactivate.rake`: wird diese Funktion noch benötigt? Anpassen oder löschen

- Andere Wagons anpassen  
  - [x] Alle anderen Wagons kontrollieren und calls auf die angepassten Role Methoden kontrollieren, anpassen.     
  z.B. auf Github die Organisation hitobito durchsuchen nach `delete_on`, `convert_on`, `convert_to`, `FutureRole`

- [x] #2788

# ToDo

- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by richardjubla** [comment]
Wir haben in unserem Wagon noch https://github.com/hitobito/hitobito_jubla/pull/60 offen.

**Comment by richardjubla** [comment]
> @richardjubla merci für den Hinweis. Ich habs im PR entsprechend kommentiert 👍

Danke, bin froh habe ich hier den Zusammenhang korrekt gesehen.
