### ISSUE TITLE
PDF: Downgrade ttfunk wegen fehlerhaften Fonts

### ISSUE THREAD

**Issue by TheWalkingLeek** [hitobito/hitobito#2915]
## Aktuelles Verhalten

Manche Fonts werden inkorrekt in PDFs embedded aufgrund eines Bugs in (wahrscheinlich) prawn/ttfunk
Help Tickets dazu:
https://help.puzzle.ch/#ticket/zoom/8324
https://help.puzzle.ch/#ticket/zoom/8132
Issue bei prawn:
https://github.com/prawnpdf/prawn/issues/1346

## Lösungsvorschlag

Das Issue wird mehr oder weniger aktiv bei prawn getracked, als temporäre Lösung sollten wir in der Lage sein ttfunk auf `< 1.8.0` zu locken: https://github.com/prawnpdf/prawn/issues/1346#issuecomment-2409975117

## ToDo

- [ ] `prawn/ttfunk` im Gemfile downgraden
- [ ] Gemfile.lock updaten und im git einchecken
- [ ] Evtl. selbst via Adobe Acrobat Reader testen
- [ ] Tests auf allen Wagons sicherstellen/durchlaufen lassen
- [ ] SWW auf Integration testen lassen

**Comment by Largo** [comment]
Hier wird sicher dann auch die Schriftanpassung von #2372 mitgetestet.

**Comment by kronn** [comment]
Dies sollte auf der Integration getestet werden, was aber erst nach dem Ende des Mergefreeze gut möglich ist.

**Comment by richardjubla** [comment]
Wir sehen, dass Sonderzeichen das generieren von allen PDFs (Anmeldung, Etiketten, Exporte, Rechnungen) verunmöglicht. Siehe: https://github.com/hitobito/hitobito/issues/2294 

Wird hier das Problem gelöst?
