### ISSUE TITLE
BOOTSTRAP: StandardFormBuilder erweitern

### ISSUE THREAD

**Issue by njaeggi** [hitobito/hitobito#2916]
Der StandardFormBuilder setzt bei vielen Feldern wie Input Feldern oder Checkboxen Bootstrap Klassen, damit diese immer gleich gestyled sind und in allen Forms konsistent sind. Bei Dropdown selects oder auch File Upload Buttons werden nur die Standard Methoden von `ActionView::Helpers::FormBuilder` verwendet.

Daher haben wir überlegt, diese auch im `StandardFormBuilder` zu überschreiben, damit die gewünschten Bootstrap Klassen immer gesetzt werden.

Aktuell wird grundsätzlich bei jedem Dropdown Select oder FileUpload die Klasse von Hand gesetzt, was zu doppelten Klassen führt, sobald diese im `StandardFormBuilder` per default gesetzt werden.

# ToDo

- [ ] Herausfinden welche Inputfelder es gibt und noch nicht im `StandardFormBuilder` existieren
- [ ] `StandardFormBuilder` erweitern und Input Felder mit Bootstrap Klassen stylen
- [ ] Alle Wagons durchgehen und doppelt gesetzte Klassen entfernen
