### ISSUE TITLE
PEOPLE: Neue Filtermöglichkeiten nach Alter und Geschlecht

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#295]
Als administrierende Person von der Mitte möchte ich zusätzliche Möglichkeiten wie die Personenlisten gefiltert werden können und die gesuchten Personen oder Gruppen schneller zu finden.

# Mockup
Filter für Alter und Geschlecht
![image](https://user-images.githubusercontent.com/69250571/183082685-f548842e-40d3-4d87-813b-ff8bb1715c86.png)

Option Enthält nicht
![image](https://user-images.githubusercontent.com/69250571/183082368-90b4e96e-12b2-44be-980b-2c8054da8b47.png)

# Tech-Spec
- Umsetzung im Core
- Neuer Filter für Alter (`years`)
- Neuer Filter für Geschlecht (`gender`)
- «Enthält nicht» als Option neben «Enthält» und «ist genau»

# ToDo
- [x] Neue Filter-Felder `years` und `gender` in https://github.com/hitobito/hitobito/blob/master/app/models/person.rb#L84 ergänzen
- [x] Ggf. Filter-Implementation in https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/attributes.rb ergänzen, müsste aber eigentlich einfach so funktionieren
- [x] Option «Enthält nicht»: In https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/attributes.rb#L39 und https://github.com/hitobito/hitobito/blob/master/app/domain/person/filter/attributes.rb#L63 analog zu `match` ein Vergleich `not_match` implementieren, mit `NOT LIKE` statt `LIKE`
- [x] In https://github.com/hitobito/hitobito/blob/master/app/helpers/people_filter_helper.rb#L33 eine neue Option `not_match` einfügen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
