### ISSUE TITLE
EVENT: Mehrere Attachments gleichzeitig hochladen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito#3017]
Als Kursadmin will ich auf den Kursen mehrere Anhänge gleichzeitig hochladen können, damit ich schneller bin und weniger Fehler dabei mache.

Neu soll es möglich sein, dass im Upload-Dialog mehrere Dateien ausgewählt werden können und dann mehrere Dateien hochgeladen werden können.

# ToDo

- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
