### ISSUE TITLE
MESSAGES: Bounces nachvollziehbar machen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#3053]
Als Verantwortlicher eines Abos
möchte ich nachvollziehen können, welche Mails nicht ankommen
damit ich ungültige Adressen entfernen oder aktualisieren kann.

Neu soll die Mail-Adresse, die "bounces" ausgelöst hat, also die, an die nicht mehr zugestellt werden konnte, gespeichert werden. Damit kann der Verantwortliche eines Abos vergebliche Zustellversuche und ungewolltes Spamming vermeiden.

# Tech-Spec

- bounces sollte nachvollziehbar sein
- Siehe auch: https://github.com/hitobito/hitobito/issues/1847
- Bounced Mails merken
- nach 5 bounces keine Mails mehr an die Adresse schicken
- Mailversuche weiter tracken

## Bonus
- nächtlicher Job, der Bounced Mails (über subscriptions) vorhandenen Abos zuordnet
- bounces im Postfach wegsortieren
- blockierte e-mails in Abos anzeigen

# ToDo

- [x] Migration erstellen
	- `add_column :messages, :bounce_sender, :string`
	- ```create_table :bounces do |t|
	    t.string :email
	    t.integer :count
	    t.datetime :blocked_at
	    t.integer :mailing_lists, array: true

	    t.timestamps
	    t.unique :email
	  end
- [x] Model Bounces in Einstellungen / Mails als weitere Karteikarte sichtbar machen
	- [x] CRUD-Table
	- [x] Link zu Person
	- [x] Sheet-Title und Karteireiter besser benennen
- [x] Domainklasse anpassen, dass der Sender getrackt wird: `MailingLists::BulkMail::BounceHandler`
- [x] Domainklassen anpassen, dass der Versand an blockierte E-Mails nicht mehr erfolgt
	- [x] MailingLists::BulkMail
	- [x] Systemmails
	- [x] weitere?
- [x] View anpassen
	- [x] Liste der unzustellbaren Mails in den Abos anzeigen
	- [x] Warnung auf Benutzer anzeigen, wenn eigene Mail auf der Bounce-Liste ist
- [x] Specs schreiben
	- [x] Bounces
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] Dokumentation erweitern
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

## Follow-Up Ideen
- [ ] Besserer Helper/Wrapper für Bounce.blocked?
	- könnte auch nil handlen
	- besserer Name
- [ ] Background-Job anlegen, die alle Mailinglisten auf Bounce-Member prüft?
- [ ] Tags auf Personen, die bounces haben?
- [ ] Mails in Ordner "bounces" verschieben
- [ ] Einstellungen / Mails / Postfach erweitern, dass "bounces"-Ordner angezeigt wird

**Comment by ThomasEllenberger** [comment]
Hier wäre es sicherlich interessant wenn man diese Bounces auch im UI irgendwie dem Benutzer zugänglich macht, so dass Admins dies auslesen können, welche Adressen bei welchem Versand einen Bounce ausgelöst haben.

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Unser produktives System:
![Image](https://github.com/user-attachments/assets/6d4cbe26-9794-4bdc-afde-9c1f041f6f4c)
Verbindung zum Mailserver nicht möglich, bitte versuche es später erneut.
Temporary authentication failure. [mailstore02.cloud.puzzle.ch:2025-07-01 15:54:10]
