### ISSUE TITLE
UI auf Bootstrap 4 heben

### ISSUE THREAD

**Issue by RolandStuder** [hitobito/hitobito#354]
Wir setzen aktuell in hitobito noch das veraltetet Bootstrap 2.3 ein. Jetzt könnten wir den Sprung nach Bootstrap 4 machen. Bootstrap 4 ist nun in Beta und damit genug stabil, dass wir es einsetzen können.

Das ist vor allem Fleissarbeit. Wäre cool, dies als Community Projekt zu machen. Wer wäre dabei?

# ToDos

* [ ] Boostrap neues Gem einbauen
* [ ] Nur Komponenten einbinden welche gebraucht werden
* [ ] Glyphicons durch FontAwesome ersetzen
* [ ] Check what extensions we actually need (brauchen wir Compass überhaupt?)

# Javascript Komponenten ersetzen

* [ ] #= require bootstrap-alert
* [ ] #= require bootstrap-button
* [ ] #= require bootstrap-dropdown
* [ ] #= require bootstrap-tooltip
* [ ] #= require bootstrap-popover
* [ ] #= require bootstrap-typeahead
* [ ] #= require bootstrap-tab
* [ ] #= require bootstrap-modal
* [ ] #= require bootstrap-wysihtml5
* [ ] #= require bootstrap-wysihtml5/locales/de-DE
* [ ] #= require bootstrap-wysihtml5/locales/fr-FR
* [ ] #= require bootstrap-wysihtml5/locales/it-IT

# Check stuff

* [ ] Chosen Bootstrap

# Alle Wagons überarbeiten

* [ ] Hier alle Wagons aufführen, die angepasst werden müssen.

**Comment by RolandStuder** [comment]
Ich habe einen Branch angelegt und mir angeschaut, was es zu tun gäbe. Die paar Sachen die ich umgestellt habe, habe am Ende gleich ausgesehen. Visuell wird Bootstrap-4 nur minimale Unterschiede geben.

Mir scheint ingesamt, dass der Umstellungsaufwand doch recht gross wäre, aber kaum Vorteile bringt, ausser dass wir sagen können, es ist moderner. Es lohnt sich eher diese Ressourcen in konkrete Verbesserungen zu stecken.

Was sich sicher lohnen würde, wäre die Umstellung des Grid-Systems, da dieses in Bootstrap 2.3 sehr unflexibel ist. Aber dieses lässt sich unabhängig vom Rest einfach einbauen.

**Comment by RolandStuder** [comment]
Lohnt sicht nicht, da viele Helpers umgeschrieben werden müssen, ohne Nutzen daraus zu ziehen, der Hauptpainpoint ist damit adressiert, dass das Grid von Bootsrap 4 zur Verfügung steht.
