### ISSUE TITLE
Erweiterungen DSJ 2019

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#703]
Soll so umgesetzt werden:
* [ ] «Politische Partei» als Textfeld bei Personen hinzufügen
* [ ] «Aktuelle Nebenämter» bei Personen hinzufügen
* [ ] Sprache nicht als Tag sondern als Pflichtfeld (als Dropdown mit Auswahlmöglichkeiten De, Fr, It, Ro, En); bestehende Tags "umwandeln" und löschen

"Kann": 
* [ ] Spezifikation von «weitere Email» mit Dropdown; Auswahlmöglichkeiten noch zu definieren
* [ ] Fixes Format für Telefonnummer (Relevant ist hier die Suche: Sonderzeichen und Leerschläge sollten da nicht berücksichtigt) Matthias versucht den Weg über ein zusätzliches Feld für die Suche (Sphinx) und schaut sonst noch einmal mit Jochanan

-> Matthias gibt Feedback an Jochanan, die Kann-Anforderungen sollen so einfach wie möglich umgesetzt werden.

* [ ] Die neuen Felder sollen  auch exportiert werden.

**Comment by KunoKunz** [comment]
Für Gruppentyp Jugendparlamente:
    • Politische Kompetenzen: Einzelne Checkboxen für 
        ◦ "Vorstossrecht"
        ◦ "Beratung"
        ◦ "Teilnahme an Ratssitzungen"
        ◦ "andere Rechte"
        ◦ "Keine speziellen Rechte"
        ◦ "Keine Angabe"
    • Bei «Begleitung» zusätzlich Dropdown-Feld: Jugendarbeit, Gemeindeverwaltung/Politik, lose Begleitung, keine Begleitung, keine Angaben

**Comment by KunoKunz** [comment]
Weiteres
    • Gruppenstruktur von Jupa Stati so ändern, dass es noch eine Oberebene gibt. So müssten die Berechtigungen nicht immer 12x verteilt werden.
