### ISSUE TITLE
Erweiterungen Eidg Musikfest 2021 für SBV

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#810]
Für das eidg. Musikfest EMF (aka grösstes Blasmusikfestival der Welt) soll die heutige Lösung ergänzt werden. Für die Umsetzung werden die einzelnen Tasks dann einzelne Issues erstellt. Die Anforderungen hier sollen für eine grobe Schätzung des Aufwands dienen.

Für das EMF braucht es im Vergleich zu den heutigen Anlässen (https://sbv.puzzle.ch/de/groups/1/events/13) weitere Auswahlfelder für die Anmeldung:

**Anmeldung Musikvereine**
- SUISA-Liste: Ergänzung der Stücke mit der entsprechenden Spielklasse. 
- Einzelanmeldung oder Spielgemeinschaft (Auswahl eines Vereins aus der DB)
- Auswahl auf Anlass Entweder Konzert- oder Unterhaltungsmusik, Parademusik ist zusätzlich möglich. Pro Gesamtauswahl ist EINE Auswahl möglich.
- Spielplan/Festtage: Wunschtage gemäss Auswahl anzeigen. Flexibilität bei Spieltagen (an einem anderen Tag, zusätzliche Tage) erwünscht. Erste und zweite Prio angeben können.
- Zusätzliches Feld «Bestätigung der Vereine» (Bestätigung der Vereine, dass das Fest-Reglement vom SBV akzeptiert wird.)
- Literaturangabe: Liste mit den Stücken
- Checkboxen/Felder: Anzahl Begleitpersonen, Verpflegungsart, Zusatzverpflegung, Anreise-Art, Übernachtung (Hotel oder Massen-ukf) 
- Vereinsfoto

**Schnittstelle hitobito-JWE**
(Jungfrau World Event) - Info zu Festkarten (Verpflegungen, Begleitpersonen), Anreise-Art, Massenunterkünfte
- Export (Excelliste) mit Informationen zu oben aufgeführten Attributen 
- oder als mögliche Variante: JWE erhält eine Info (per Mail) und erfragt danach selber die Informationen.
Tbd: Information automatisch bei Buchung, gesammelt

**Schnittstelle hitobito-TOI**
(Information, dass Hotelbuchung gewünscht wird)
Entweder eine Info an TOI (automatische E-Mail) 
oder als Variante einen Link auf die Zielseite bei TOI

Offene Fragen:
* [ ] Wo sind die Informationen respektive die Zuordnung der Stücke zur Spielklasse hinterlegt? (SUISA/SBV) 
* [ ]  Anmeldefristen und Stichtage
* [ ]  Beispiel für Bühnenplan
* [ ]  Soll bei den Stücken/Spielklassen noch Logik reingepackt werden (bei Auswahl X kommen nur die entsprechenden Stücke zur Auswahl)?

Ziel: Ende Jahr fertig, ab Mitte Januar bereit, Probelauf Anfang Dezember. Bis Ende August (26./27. ist OK-Meeting) Grobofferte, danach weiteres Treffen, welches Reto organisiert.

**Comment by KunoKunz** [comment]
Bühnenplan zum separat schätzen, da Frontend-Implementierung.
[Bühnenplan Oberwil 2017 Version 2.1-1.pdf](https://github.com/hitobito/hitobito/files/3546719/Buhnenplan.Oberwil.2017.Version.2.1-1.pdf)
Die Idee ist, dass wir in hitobito diese Elemente darstellen und danach die Instrumente mittels Drag & Drop auf den Bühnenplan gezogen werden können

**Comment by hupf** [comment]
@KunoKunz Ein paar Fragen auf den ersten Blick zum Bühnenplan:
* Was ist das Ziel dieses Bühnenplans, wird der nur im Browser dargestellt? Gibt es eine read-only Ansicht? Muss er gedruckt werden können?
* Geht es um eine rein grafische Platzierung der Instrumente (x,y) oder hat dies auch sematischen Charakter (à la, das «Xylofon gestuft» steht auf Position «Zentrum links oben» oder ähnlich)?
* In diesem Zusammenhang: gibt es ein fixes Raster resp. fixe Stellen wohin die Instrumente plaziert werden können? Oder können sie frei (und ev. auch überlappend) positioniert werden?
* Gibt es Bereiche wo die Instrumente nicht platziert werden können oder sie nicht überlappen sollen?
* Layout Hochformat: dies müsste wohl für den Bildschirm angepasst werden, wahrscheinlich wäre eine Toolbar oder eine Sidebar, von wo aus die Instrumente gezogen werden können, sinnvoll. Wird dafür noch ein Mockup gemacht?
* Ist das Set der Instrumente fix, oder können die dynamisch erfasst werden, inkl. Symbol?
* Sind die Rechtecke Textfelder? Was kann dort erfasst werden?
* Wie/wo wird dies Ansicht konkret in die Applikation integriert? Wie funktioniert der Bearbeiten/Speichern Workflow?
* Was sind die Browseranforderungen?

**Comment by KunoKunz** [comment]
@hupf Wir bräuchten fürs Erste eine Grobschätzung. Da würde es reichen, wenn ihr einzelne Annahmen treffen würdet und allenfalls die Alternative als Option aufführen würdet. Ich kann die Fragen gerne einmal weiterleiten, falls die einzelnen Fragen einen zu grossen Spielraum haben.
