### ISSUE TITLE
Zusammenfassung Arbeiten Rechnungsstellung

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito#911]
Damit klar ist, welche Arbeiten die Puzzle-interne Weiterentwicklung für die Rechnungsstellung umfassen soll, werden die einzelnen Tickets hier zusammengefasst.

Ausgangslage und Ziele:
Zum Rechnungsmodul von hitobito gibt es einige Testfeedbacks und Wünsche für (individuelle) Weiterentwicklungen. 

[edit ak, 17.4.2020: Bestehende Tickets zur besseren Übersicht in neue Issues übernommen]

Im Rahmen des Puzzle-internen Vorhabens sollen folgende Tickets abgearbeitet werden:

* [x] #942  - Auswahl und Anzeige Rechnungsartikel
* [x] #944 - Standardtexte für Mahnungen 
* [x] #611 - Wichtigste Einstellungen für andere Länder/Währungen
* [x] #943 - Rechnungseinstellung allgemein  

Weiter sollen die Auswirkungen respektive die nötigen Arbeiten für die Umstellung des ESR-Standards geschätzt werden: #589 

Falls noch Zeit dafür vorhanden ist, könnte #939 auch umgesetzt werden.
