### ISSUE TITLE
Frontend Zukunft

### ISSUE THREAD

**Issue by hupf** [hitobito/hitobito#996]
### Stand heute

* CoffeeScript mit jQuery
* SCSS
* Letzte Bootstrap 2 Version von 2013
* Noch immer auf Asset Pipeline (Sprockets)
* Performance von CSS Build schlecht
* Veraltete Dependencies (z.B. Bootstrap2 von 2013)

### Zukunft

* Migration auf Webpacker -> verwenden von JavaScript Modules
* Einsatz von [Stimulus](https://stimulusjs.org/) für "sprinkles of JavaScript"
* Beobachten, was die [NEW MAGIC on the frontend](https://twitter.com/dhh/status/1275901955995385856) welche aus hey.com heraus veröffentlicht wird, bringt...
* Für Features mit sehr interaktiven und aufwändigen UIs wäre es immer noch möglich auf einzelnen Seiten (keine SPA) ein JavaScript Framework wie Vue.js einzusetzen, sollte dies eines Tages eine Anforderung sein.

### Migrationsansätze

Kurzfristig ist das Ziel Stimulus einsetzen zu können. Grundsätzlich soll komplett auf Webpacker gewechselt werden (keine Asset Pipeline mehr).

https://makandracards.com/makandra/69135-migration-from-the-asset-pipeline-to-webpacker

### TODOs

- [x] Webpacker installieren
- [x] Konfigurieren für old-school Libs (jQuery mit Plugins) via expose-loader und ProvidePlugin
- [x] Dependencies per Yarn installieren und in Bundle includen
  - [x] Custom Modernizr Build -> nur an einer Stelle verwendet, Feature Detection mit `@supports` in plain CSS implementiert.
  - [ ] WYSIWYG Editor (bootstrap3-wysihtml5) -> hoffnungslos veraltet, gar nicht auf NPM? In eigenes Bundle, da nur bei Custom Contents und Help Texts verwendet. Nach Möglichkeit auf ActionText/Trix wechseln.
- [x] Core Scripts in Bundle includen
- [x] Wagon Scripts in Bundle includen -> habe jetzt mal den Ansatz über ein `wagons.js.erb` gewählt, wo über die Wagons gelooped wird und die existierenden `wagon.js.coffee` Scripts importiert werden. Eine Alternative wäre in den Wagens eine eigene Webpacker Instanz zu installieren (und konfigurieren!) was das Ganze wohl unötig aufblasen würde.
- [x] Webpack Dev Server in Docker Compose Setup einbauen
- [x] ~s2i Script anpassen: `yarn install` und Webpack Bundle bauen~ -> ist mit `rake assets:precompile` bereits gelöst
- [x] System Specs laufen durch -> laufen lokal durch, siehe https://github.com/hitobito/development/issues/7
- [x] Core Styles (und Fonts) in Bundle includen -> Imports in SCSS Files werde nicht durch die Webpack Loaders prozessiert, Importieren eines ERB Files ist also nicht möglich; Alternative: Das Hauptfile zu einem ERB File machen und die Ruby Logik dort platzieren.
- [x] Wagon Styles in Bundle includen
- [x] Bilder im Bundle includen -> `image_pack_tag`
  - Wie ist es mit Bilder von Wagons? Kommen wir hier nicht um eine eigene Webpacker Instanz herum?
- [x] Alte Polyfills/Shims (z.B. für IE < 11) rausnehmen
- [x] Compass entfernen/ersetzen

### Findings

- Momentan ist keine Möglichkeit vorhanden, die Feature Specs lokal mit sichtbarem Browser laufen zu lassen (mit dem Docker Compose Setup). Dies ist zwingend nötig um Tests zu fixen oder neue zu schreiben. Offenbar wird das vom Team gar nicht gemacht – viele Feature Specs wurden auch ignoriert, da sie nicht mehr durchliefen.
- Bootstrap2 wird seit 2013 (!) nicht mehr weiterentwickelt und sollte ersetzt werden.

**Comment by hupf** [comment]
### Dependencies/Versions

* jquery 1.12.4 (2016)
* js-cookie 2.2.0 (latest, 2019)
* jquery-ujs 1.2.2 (latest, 2016)
* jquery-ui/widgets/datepicker 1.12.1 (latest, 2016)
* jquery-ui-datepicker-i18n 1.12.1 (latest, 2016)
* jquery-ui/effects/effect-highlight 1.12.1 (latest, 2016)
* bootstrap-sass 2.3.2.2 (latest 2.x, 2013)
  * bootstrap-transition
  * bootstrap-alert
  * bootstrap-button
  * bootstrap-collapse
  * bootstrap-dropdown
  * bootstrap-tooltip
  * bootstrap-popover
  * bootstrap-typeahead
  * bootstrap-tab
  * bootstrap-modal
* bootstrap-wysihtml5 0.3.3 (bootstrap3-wysihtml5-bower, latest, 2014) -> https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg – installierte Gem Version ist 0.3.3.8 (latest NPM Version 0.3.3), gemäss README wäre letzte Version mit Bootstrap2 Support eigentlich 0.3.1.24 (NPM Version 0.3.0)
* jquery_nested_form -> https://github.com/ryanb/nested_form/ letzte Version von 2013, kein NPM Package?
* chosen 1.8.7 (latest, 2018) -> https://github.com/harvesthq/chosen deprecated, sollte z.B. mit Selectize ersetzt werden
* jquery.remotipart -> https://github.com/JangoSteve/remotipart/ kein NPM Package?
* modernizr.custom.min 2.7.1 (2014)
* moment.min 2.9.0 (2015)
* tree ./modules -> eigene scripts
* wysiwyg -> eigenes script
* wagon -> scripts von wagons
* turbolinks (latest, 2014) -> https://github.com/kossnocorp/jquery.turbolinks deprecated, sollte eigentlich gar nicht mit Turbolinks 5 funktionieren und muss ersetzt werden (https://github.com/kossnocorp/jquery.turbolinks#warning-deprecated-warning)

**Comment by hupf** [comment]
Container für Webpack Dev Server im Development Setup hinzugefügt: https://github.com/hitobito/development/pull/6

Dieser unterstützt nun also Live Reload.

**Comment by hupf** [comment]
Feature Specs lokal laufen lassen, ohne Headless:

Mit Docker Compose DB/Server starten.

Dann ausserhalb von Docker:
```
RAILS_HOST_NAME=localhost:3000 RAILS_DB_ADAPTER=mysql2 RAILS_DB_HOST=127.0.0.1 RAILS_DB_PORT=33066 RAILS_DB_USERNAME=root RAILS_DB_PASSWORD=hitobito RAILS_DB_NAME=hitobito_development HEADLESS=false bundle exec rspec --tag type:feature spec/features/
```

**Comment by hupf** [comment]
Aktueller Stand, bin am Migrieren der SCSS Files nach Webpacker:
- Imports über `@import` in SCSS Files werden nicht mit den Webpack Loadern prozessiert. Es ist also nicht möglich ERB Files einzubinden. Alternativer Ansatz: das Hauptfile zu einem ERB File machen (`application.scss.erb`) und alle die Ruby Logik für AppSettings-Variablen und einbinden der Wagon Files dort implementieren. Dies ist soweit implementiert aber noch nicht gross getestet.
- Es werden Compass Mixins verwendet, ich versuche diese kurzfristig über https://www.npmjs.com/package/compass-mixins einzubinden.
- Weiter bin ich dran die Styles der Dependencies von den `node_modules/` einzubinden.
